Repository apache/hudi, pull requests merged in 2020-12, with the labels that each got.

#2192 [HUDI-1343] Add standard schema postprocessor which would rewrite the schema using spark-avro conversion
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SparkAvroPostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/SparkAvroSchemaProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
Labels: data-types

#2371 [HUDI-1490] Incremental Query should work even when there are partitions that have no incremental changes
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
Labels: release-blockers

#2360 [HUDI-1481] add streaming and delta streamer inline clustering unit test
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: release-blockers

#2275 [HUDI-1354] Block updates and replace on file groups in clustering
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/exception/HoodieClusteringUpdateException.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/UpdateStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/update/strategy/SparkRejectUpdateStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientOnCopyOnWriteStorage.java
Labels: release-blockers

#2342 [RFC-15][HUDI-1325] Merge updates of unsynced instants to metadata table
  hudi-client/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/src/test/java/org/apache/hudi/client/TestCompactionAdminClient.java
  hudi-client/src/test/java/org/apache/hudi/metadata/TestHoodieBackedMetadata.java
  hudi-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/metadata/AbstractHoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMergedInstantRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: release-blockers

#2254 [HUDI-1350] Support Partition level delete API in HUDI
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkDeletePartitionCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwriteCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwriteTableCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
Labels: release-blockers

#2363 [HUDI-1484] Escape the partition value in HiveSyncTool
  docker/demo/sparksql-incremental.commands
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
Labels: release-blockers

#2349 [HUDI-1474] Add additional unit tests to TestHBaseIndex
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestHBaseIndex.java
Labels: release-blockers

#2366 [HUDI-1312] [RFC-15] Support for metadata listing for snapshot queries through Hive/SparkSQL
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHFileInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java
Labels: release-blockers

#2045 [HUDI-1147] Modify GenericRecordFullPayloadGenerator to generate vali…
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/DeltaGenerator.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/FlexibleSchemaRecordGenerationIterator.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/generator/GenericRecordFullPayloadGenerator.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/generator/TestGenericRecordPayloadGenerator.java
Labels: release-blockers

#2350 [HUDI-1493] Fixed schema compatibility check for fields.
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
Labels: data-types, release-blockers

#2300 [HUDI-1434] fix incorrect log file path in HoodieWriteStat
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/CopyOnWriteInsertHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTimelineArchiveLog.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/AbstractMarkerBasedRollbackStrategy.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/AbstractSparkDeltaCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackHelper.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestUpdateSchemaEvolution.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieDeltaWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieLogFile.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AppendResult.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormatAppendFailure.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieDeltaWriteStat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
Labels: release-blockers
