Repository apache/hudi, pull requests merged in 2021-06, with the labels that each got.

#2964 [HUDI-1914] Add fetching latest schema to table command in hudi-cli
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/testutils/HoodieTestCommitMetadataGenerator.java
Labels: sev:critical

#2747 [HUDI-1743] Added support for SqlFileBasedTransformer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/SqlFileBasedTransformer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlFileBasedTransformer.java
  hudi-utilities/src/test/resources/delta-streamer-config/sql-file-transformer-empty.sql
  hudi-utilities/src/test/resources/delta-streamer-config/sql-file-transformer-invalid.sql
  hudi-utilities/src/test/resources/delta-streamer-config/sql-file-transformer.sql
Labels: sev:normal

#2896 [HUDI-1790] Added SqlSource to fetch data from any partitions for backfill use case
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SqlSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlSource.java
Labels: sev:normal

#2984 [HUDI-1950] Fix Azure CI failure in TestParquetUtils
  README.md
  azure-pipelines.yml
  hudi-common/src/test/java/org/apache/hudi/common/util/TestParquetUtils.java
  pom.xml
Labels: pr:wip

#2925 [HUDI-1879] Fix RO Tables Returning Snapshot Result
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/ConfigUtils.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
Labels: sev:high

#2915 [HUDI-251] Adds JDBC source support for DeltaStreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/SqlQueryBuilder.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JdbcSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSqlQueryBuilder.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJdbcSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/JdbcTestUtils.java
Labels: sev:normal

#3092 [HUDI-1910] Commit Offset to Kafka after successful Hudi commit
  hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/SourceCommitCallback.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/SourceFormatAdapter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestKafkaSource.java
Labels: release-blockers

#3178 [HUDI-2094] Supports hive style partitioning for flink writer
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink/src/main/java/org/apache/hudi/table/format/FilePathUtils.java
  hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java
Labels: flink

#3169 [HUDI-2085] Support specify compaction paralleism and compaction targ…
  hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java
  hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
Labels: flink

#3147 [HUDI-1983] [DOC]Add key gen type config to Configurations page in hudi we…
  docs/_docs/2_4_configurations.cn.md
  docs/_docs/2_4_configurations.md
Labels: docs

#3176 [HUDI-2092] Fix NPE caused by FlinkStreamerConfig#writePartitionUrlEn…
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
Labels: flink

#3165 [MINOR] Add caveat for multiwriter usage
  docs/_docs/2_9_concurrency_control.md
Labels: docs

#3175 [HUDI-1944] Support Hudi to read from committed offset
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Labels: deltastreamer
