Repository apache/hudi, pull requests merged in 2021-03, with the labels that each got.

#2562 [HUDI-1540] Fixing commons codec depedency in bundle jars
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
Labels: sev:critical

#2595 [HUDI-1634] Re-bootstrap metadata table when un-synced instants have been archived.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/metadata/TestHoodieBackedMetadata.java
Labels: sev:critical

#2539 [HUDI-1584] Modify maker file path, which should start with the target base path.
  hudi-flink/src/main/java/org/apache/hudi/operator/InstantGenerateOperator.java
Labels: sev:normal

#2495 [HUDI-1553] Configuration and metrics for the TimelineService.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineServerHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
Labels: sev:high

#2541 [HUDI-1587] Add latency and freshness support
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestWriteStatus.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePayloadProps.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/common/util/DateTimeUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestDefaultHoodieRecordPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestDateTimeUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala
Labels: sev:normal

#2611 [HUDI-1646] Provide mechanism to read uncommitted data through InputFormat
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieHiveUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
Labels: sev:normal

#2596 [HUDI-1636] Support Builder Pattern To Build Table Properties For HoodieTableConfig
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestMultiFS.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-examples/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java
  hudi-examples/src/main/java/org/apache/hudi/examples/spark/HoodieWriteClientExample.java
  hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BootstrapExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotExporter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Labels: sev:normal

#2577 [HUDI-1618] Fixing NPE with Parquet src in multi table delta streamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieMultiTableDeltaStreamer.java
Labels: sev:high

#2640 [HUDI-1663] Streaming read for Flink MOR table
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-flink/src/main/java/org/apache/hudi/operator/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/operator/StreamReadMonitoringFunction.java
  hudi-flink/src/main/java/org/apache/hudi/operator/StreamReadOperator.java
  hudi-flink/src/main/java/org/apache/hudi/sink/HoodieTableSink.java
  hudi-flink/src/main/java/org/apache/hudi/source/HoodieTableSource.java
  hudi-flink/src/main/java/org/apache/hudi/source/format/FilePathUtils.java
  hudi-flink/src/main/java/org/apache/hudi/source/format/mor/InstantRange.java
  hudi-flink/src/main/java/org/apache/hudi/source/format/mor/MergeOnReadInputFormat.java
  hudi-flink/src/main/java/org/apache/hudi/source/format/mor/MergeOnReadInputSplit.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamerV2.java
  hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink/src/test/java/org/apache/hudi/operator/utils/TestConfigurations.java
  hudi-flink/src/test/java/org/apache/hudi/operator/utils/TestData.java
  hudi-flink/src/test/java/org/apache/hudi/source/HoodieDataSourceITCase.java
  hudi-flink/src/test/java/org/apache/hudi/source/TestHoodieTableSource.java
  hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadMonitoringFunction.java
  hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadOperator.java
  hudi-flink/src/test/java/org/apache/hudi/source/format/TestInputFormat.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java
  hudi-flink/src/test/java/org/apache/hudi/utils/factory/CollectSinkTableFactory.java
  hudi-flink/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
  hudi-flink/src/test/resources/test_source2.data
Labels: release-blockers

#2500 [HUDI-1496] Fixing detection of GCS FileSystem
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/SchemeAwareFSDataInputStream.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
Labels: sev:critical

#2612 [HUDI-1563] Adding hudi file sizing/ small file management blog
  docs/_posts/2021-03-01-hudi-file-sizing.md
  docs/assets/images/blog/hudi-file-sizing/adding_new_files.png
  docs/assets/images/blog/hudi-file-sizing/bin_packing_existing_data_files.png
  docs/assets/images/blog/hudi-file-sizing/initial_layout.png
Labels: sev:normal

#2494 [HUDI-1552] Improve performance of key lookups from base file in Metadata Table.
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/metadata/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
Labels: release-blockers, sev:critical

#2653 [HUDI 1615] Fixing null schema in bulk_insert row writer path
  hudi-common/src/main/avro/HoodieCommitMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
Labels: sev:critical

#2673 [HUDI-1688] Uncache Rdd once write operation is complete
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: release-blockers, sev:critical

#2693 [MINOR] Remove unused var in AbstractHoodieWriteClient
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
Labels: code-clean

#2625 [1568] Fixing spark3 bundles
  docker/hoodie/hadoop/hive_base/pom.xml
  docker/hoodie/hadoop/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  pom.xml
  scripts/release/deploy_staging_jars.sh
Labels: release-blockers, sev:critical

#2691 [HUDI-1703] Fixing kafka auto.reset.offsets config param key
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestKafkaSource.java
Labels: release-blockers, sev:critical

#2619 [HUDI-1650] Custom avro kafka deserializer.
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deser/KafkaAvroSchemaDeserializer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deser/TestKafkaAvroSchemaDeserializer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/SchemaTestProvider.java
Labels: release-blockers, schema-and-data-types, sev:critical

#2636 [HUDI-1667]: Fix bug when HoodieMergeOnReadRDD read record from base …
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
Labels: release-blockers, sev:critical

#2698 [HUDI-1679] Concurrency Control in Hudi
  docs/_data/navigation.yml
  docs/_docs/2_4_configurations.md
  docs/_docs/2_9_concurrency_control.md
Labels: release-blockers

#2699 [HUDI-1709] Improving lock config names and adding hive metastore uri config
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/LockConfiguration.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveMetastoreBasedLockProvider.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveMetastoreBasedLockProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: release-blockers

#2702 [HUDI-1710] Read optimized query type for Flink batch reader
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java
  hudi-flink/src/test/java/org/apache/hudi/utils/source/ContinuousFileSource.java
Labels: release-blockers

#2708 [HUDI-1712] Rename & standardize config to match other configs
  hudi-common/src/main/java/org/apache/hudi/common/config/LockConfiguration.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: release-blockers

#2711 [hotfix] Log the error message for creating table source first
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
Labels: release-blockers

#2734 [HUDI-1731] Rename UpsertPartitioner in both hudi-java-client and hud…
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java
Labels: code-clean, sev:normal
