Repository apache/hudi, pull requests merged in 2021-07, with the labels that each got.

#3171 [HUDI-2088] Missing Partition Fields And PreCombineField In Hoodie Properties For Table Written By Flink
  hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: flink

#3216 [HUDI-2124] A Grafana dashboard for HUDI.
  scripts/grafana-dashboard.json
Labels: pr:wip

#3170 [HUDI-1930] Bootstrap support configure KeyGenerator by type
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieBootstrapConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorType.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/factory/HoodieAvroKeyGeneratorFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/factory/HoodieSparkKeyGeneratorFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
Labels: bootstrap

#3223 [HUDI-2132] Make coordinator events as POJO for efficient serialization
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/event/CommitAckEvent.java
  hudi-flink/src/main/java/org/apache/hudi/sink/event/WriteMetadataEvent.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: flink

#3182 [HUDI-2089] Fix the bug that metatable cannot support non_partition table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala
Labels: release-blockers

#3200 [HUDI-2111] [DOC] Update docs about bootstrap support configure KeyGenerato…
  content/docs/configurations.html
  docs/_docs/2_4_configurations.md
Labels: release-blockers

#3097 [HUDI-1996] Adding functionality to allow the providing of basic auth creds for confluent cloud schema registry
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestKeyRangeLookupTree.java
  hudi-utilities/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deser/TestKafkaAvroSchemaDeserializer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: release-blockers

#3177 [HUDI-2093] Fix empty avro schema path caused by duplicate parameters
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/schema/FilebasedSchemaProvider.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
  hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
Labels: flink

#3083 [HUDI-2016] Fixed bootstrap of Metadata Table when some actions are in progress.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/metadata/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMetrics.java
Labels: release-blockers

#3149 [HUDI-1104] Adding support for UserDefinedPartitioners and SortModes to BulkInsert with Rows
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieInternalConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertInternalPartitionerWithRowsFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/GlobalSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/NonSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitionerForRows.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/BulkInsertDataInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/internal/HoodieBulkInsertInternalWriterTestBase.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala
  hudi-spark-datasource/hudi-spark2/pom.xml
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieBulkInsertDataInternalWriterFactory.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieDataSourceInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/test/java/org/apache/hudi/internal/TestHoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/test/java/org/apache/hudi/internal/TestHoodieDataSourceInternalWriter.java
  hudi-spark-datasource/hudi-spark3/pom.xml
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieBulkInsertDataInternalWriterFactory.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalBatchWrite.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalBatchWriteBuilder.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalTable.java
  hudi-spark-datasource/hudi-spark3/src/test/java/org/apache/hudi/spark3/internal/TestHoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark3/src/test/java/org/apache/hudi/spark3/internal/TestHoodieDataSourceInternalBatchWrite.java
Labels: release-blockers, sev:critical

#3172 [HUDI-2069] Refactored String constants
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deser/KafkaAvroSchemaDeserializer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deser/TestKafkaAvroSchemaDeserializer.java
Labels: spark

#2206 [HUDI-1105] Adding dedup support for Bulk Insert w/ Rows
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkHoodieIndex.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/SparkRowWriteHelper.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala
Labels: release-blockers, sev:critical

#3075 [HUDI-2009] Fixing extra commit metadata in row writer path
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieDataSourceInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieWriterCommitMessage.java
  hudi-spark-datasource/hudi-spark2/src/test/java/org/apache/hudi/internal/TestHoodieDataSourceInternalWriter.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalBatchWrite.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalBatchWriteBuilder.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalTable.java
  hudi-spark-datasource/hudi-spark3/src/test/java/org/apache/hudi/spark3/internal/TestHoodieDataSourceInternalBatchWrite.java
Labels: release-blockers, sev:critical

#3186 [HUDI-2099] Hive lock which state is WATING should be released, otherw…
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveMetastoreBasedLockProvider.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/functional/TestHiveMetastoreBasedLockProvider.java
Labels: release-blockers

#3174 [HUDI-2087] Support Append only in Flink stream
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BucketType.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkAppendHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Labels: flink

#3243 [HUDI-2147] Remove unused class AvroConvertor in hudi-flink
  hudi-flink/src/main/java/org/apache/hudi/util/AvroConvertor.java
Labels: code-clean

#3142 [HUDI-1483] Support async clustering for deltastreamer and Spark streaming
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncClusteringService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncCompactService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractClusteringClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/async/SparkAsyncClusteringService.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/HoodieSparkClusteringClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/cluster/SparkClusteringPlanActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/async/SparkStreamingAsyncClusteringService.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaApp.java
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: release-blockers

#3033 [HUDI-1969] Support reading logs for MOR Hive rt table
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
Labels: release-blockers

#3268 [HUDI-2171] Add parallelism conf for bootstrap operator
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
Labels: flink

#3274 [HUDI-2180] Fix Compile Error For Spark3
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestParquet2SparkSchemaUtils.java
Labels: release-blockers

#3272 [HUDI-2149] Ensure and Audit docs for every configuration class in th…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieBootstrapConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieHBaseIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieInternalConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMemoryConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMetricsDatadogConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMetricsPrometheusConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteCommitCallbackConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/factory/HoodieAvroKeyGeneratorFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/ConsistencyGuardConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/NoOpConsistencyGuard.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/TimelineLayoutVersion.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/kafka/HoodieWriteCommitKafkaCallbackConfig.java
Labels: release-blockers

#3128 [HUDI-2029] Implement compression for DiskBasedMap in Spillable Map
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/LazyFileIterable.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestBitCaskDiskMap.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestExternalSpillableMap.java
Labels: release-blockers

#3287 Revert "[HUDI-2087] Support Append only in Flink stream (#3252)"
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BucketType.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkAppendHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Labels: flink

#2438 [HUDI-1447] DeltaStreamer kafka source supports consuming from specified timestamp
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Labels: sev:normal

#3154 [HUDI-1884] MergeInto Support Partial Update For COW
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/adapter/Spark3Adapter.scala
Labels: spark

#3296 [HUDI-2193] Remove state in BootstrapFunction
  hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapFunction.java
  hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
Labels: flink

#3247 [HUDI-2161] Adding support to disable meta columns with bulk insert operation
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieInternalWriteStatus.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieInternalRowFileWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieInternalRowFileWriterFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieInternalRowParquetWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandleWithoutMetaFields.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowParquetConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowParquetWriteSupport.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/BuiltinKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/ComplexKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/CustomKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/GlobalDeleteKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/NonpartitionedKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/RowKeyGeneratorHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/SimpleKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/TimestampBasedKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkAdapterSupport.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/storage/row/TestHoodieInternalRowParquetWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/storage/row/TestHoodieRowCreateHandle.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/keygen/TestComplexKeyGenerator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/keygen/TestCustomKeyGenerator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/keygen/TestSimpleKeyGenerator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/keygen/TestTimestampBasedKeyGenerator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/KeyGeneratorTestUtilities.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkDatasetTestUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/BulkInsertDataInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/internal/HoodieBulkInsertInternalWriterTestBase.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieSparkSqlWriterSuite.scala
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieBulkInsertDataInternalWriterFactory.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieDataSourceInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/test/java/org/apache/hudi/internal/TestHoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/test/java/org/apache/hudi/internal/TestHoodieDataSourceInternalWriter.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieBulkInsertDataInternalWriterFactory.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalBatchWrite.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalBatchWriteBuilder.java
  hudi-spark-datasource/hudi-spark3/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalTable.java
  hudi-spark-datasource/hudi-spark3/src/test/java/org/apache/hudi/spark3/internal/TestHoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark3/src/test/java/org/apache/hudi/spark3/internal/TestHoodieDataSourceInternalBatchWrite.java
Labels: release-blockers

#3184 [HUDI-1860] Add INSERT_OVERWRITE and INSERT_OVERWRITE_TABLE support to DeltaStreamer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/InsertOverwriteNode.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/InsertOverwriteTableNode.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: deltastreamer, release-blockers

#3258 [HUDI-2145] Create new bucket when NewFileAssignState filled
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
  hudi-flink/src/test/java/org/apache/hudi/sink/partitioner/TestBucketAssigner.java
Labels: flink

#3304 [HUDI-2198] Clean and reset the bootstrap events for coordinator when…
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
Labels: flink

#3257 [HUDI-1548] Add documentation for schema evolution
  docs/_docs/2_2_writing_data.md
Labels: release-blockers

#3316 [HUDI-2204] Add marker files for flink writer
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/clean/FlinkCleanActionExecutor.java
Labels: flink

#3299 [HUDI-2195] Sync Hive Failed When Execute CTAS In Spark2 And Spark3
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlUtils.scala
  packaging/hudi-spark-bundle/pom.xml
  pom.xml
Labels: release-blockers

#3230 [HUDI-2139] MergeInto MOR Table May Result InCorrect Result
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePayloadProps.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMereIntoLogOnlyTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
Labels: release-blockers

#2879 [HUDI-1848] Adding support for HMS for running DDL queries in hive-sy…
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-common/src/test/resources/complex.schema.avsc
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/DDLExecutor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HMSDDLExecutor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveQueryDDLExecutor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/JDBCExecutor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/QueryBasedDDLExecutor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/HiveSchemaUtil.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveSyncFunctionalTestHarness.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Labels: sev:critical

#3334 [HUDI-2209] Bulk insert for flink writer
  hudi-client/hudi-flink-client/pom.xml
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieRowData.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataFileWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataFileWriterFactory.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataParquetConfig.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataParquetWriteSupport.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataParquetWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/RowDataParquetWriteSupport.java
  hudi-flink/pom.xml
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorFactory.java
  hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteOperator.java
  hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
  hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/TimeWait.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
  hudi-flink/src/main/java/org/apache/hudi/util/RowDataProjection.java
  hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java
  hudi-flink/src/test/java/org/apache/hudi/table/HoodieDataSourceITCase.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestSQL.java
  hudi-flink/src/test/resources/test_source_5.data
Labels: flink

#3342 [HUDI-2219] Fix NPE of HoodieConfig
  hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java
Labels: release-blockers

#3340 [HUDI-2217] Fix no value present in incremental query on MOR
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Labels: release-blockers

#3351 [HUDI-2227] Only sync hive meta on successful commit for flink batch …
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/CoordinatorExecutor.java
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/NonThrownExecutor.java
Labels: flink

#3362 [HUDI-2245] BucketAssigner generates the fileId evenly to avoid data …
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigners.java
  hudi-flink/src/test/java/org/apache/hudi/sink/partitioner/TestBucketAssigner.java
Labels: flink

#3357 [HUDI-2241] Explicit parallelism for flink bulk insert
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
Labels: flink

#2296 [HUDI-1425] Performance loss with the additional hoodieRecords.isEmpty() in HoodieSparkSqlWriter#write
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: perf, release-blockers, sev:normal

#3207 [HUDI-2117] Unpersist the input rdd after the commit is completed to …
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: release-blockers

#3284 [HUDI-2184] Support setting hive sync partition extractor class based on flink co…
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: flink

#3341 [HUDI-2218] Fix missing HoodieWriteStat in HoodieCreateHandle
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java
Labels: release-blockers
