Repository apache/hudi, pull requests merged in 2022-06, with the labels that each got.

#5674 [HUDI-4011] Add hudi-aws-bundle
  packaging/hudi-aws-bundle/pom.xml
  packaging/hudi-aws-bundle/src/main/java/org/apache/hudi/aws/bundle/Main.java
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
  pom.xml
Labels: dependencies, priority:blocker, on-call-triaged

#5731 [HUDI-4187] Fix partition order in aws glue sync
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: meta-sync, priority:major, on-call-triaged

#5750 [HUDI-4190] Include hbase-protocol for shading in the bundles
  packaging/hudi-aws-bundle/pom.xml
  packaging/hudi-datahub-sync-bundle/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-gcp-bundle/pom.xml
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-hive-sync-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-timeline-server-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
Labels: dependencies, priority:critical, on-call-triaged

#5763 [HUDI-4101] When BucketIndexPartitioner take partition path for dispe…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
Labels: flink, index

#5733 [HUDI-4176] Fixing `TableSchemaResolver` to avoid repeated `HoodieCommitMetadata` parsing
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-common/src/main/java/org/apache/hudi/util/Lazy.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestTableSchemaResolverWithSparkSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:blocker

#5766 [HUDI-4197] Fix Async indexer to support building FILES partition
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: priority:blocker

#5747 [HUDI-4171] Fixing Non partitioned with virtual keys in read path
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieVirtualKeyInfo.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeSplit.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
Labels: priority:blocker

#5775 [MINOR] Mark AWSGlueCatalogSyncClient experimental
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: priority:minor, on-call-triaged

#5773 [HUDI-4200] Fixing sorting of keys fetched from metadata table
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Labels: priority:blocker

#5737 [HUDI-4178] Addressing performance regressions in Spark DataSourceV2 Integration
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/JFunction.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSparkSessionExtension.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_1Adapter.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/hudi/ResolveHudiAlterTableCommand312.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/hudi/Spark3DefaultSource.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/adapter/Spark3_2Adapter.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/ResolveHudiAlterTableCommandSpark32.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark3Analysis.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieInternalV2Table.scala
Labels: priority:blocker

#5744 [HUDI-4139]improvement for flink write operator name to identify tables easily
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Labels: priority:minor, on-call-triaged

#5647 Update the docs for Distributed File System (DFS) section on Hudi Delta Streamer page
  website/docs/hoodie_deltastreamer.md
  website/versioned_docs/version-0.10.0/hoodie_deltastreamer.md
  website/versioned_docs/version-0.10.1/hoodie_deltastreamer.md
  website/versioned_docs/version-0.11.0/hoodie_deltastreamer.md
Labels: docs, on-call-triaged

#5619 [HUDI-3889] Do not validate table config if save mode is set to Overwrite
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Labels: priority:major, on-call-triaged

#5829 [HUDI-4221] Fixing getAllPartitionPaths perf hit w/ FileSystemBackedMetadata
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
Labels: priority:blocker

#5840 [HUDI-4223] Fix NullPointerException from getLogRecordScanner when reading metadata table
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataTableWithSparkDataSource.scala
Labels: priority:blocker, spark, metadata

#5841 [HUDI-4205] Fix NullPointerException in HFile reader creation
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
Labels: priority:blocker, spark, metadata

#5813 [MINOR] fix AvroSchemaConverter duplicate branch in 'switch'
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroSchemaConverter.java
Labels: on-call-triaged

#5790 [HUDI-3682] testReaderFilterRowKeys fails in TestHoodieOrcReaderWriter
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieOrcReaderWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieReaderWriterBase.java
Labels: priority:minor

#5727 [HUDI-3863] Add UT for drop partition column in deltastreamer testsuite
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: priority:minor

#5788 [HUDI-4207] HoodieFlinkWriteClient.getOrCreateWriteHandle throws an e…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
Labels: priority:minor

#5761 [HUDI-4165] Support Create/Drop/Show/Refresh Index Syntax for Spark SQL
  hudi-common/src/main/java/org/apache/hudi/common/index/HoodieIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/index/HoodieIndexType.java
  hudi-spark-datasource/hudi-spark/src/main/antlr4/org/apache/hudi/spark/sql/parser/HoodieSqlCommon.g4
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Index.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/parser/HoodieSqlCommonAstBuilder.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestIndexSyntax.scala
Labels: priority:critical, spark-sql

#5897 [HUDI-4277] supoort flink table source with computed column
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
Labels: flink

#5878 [HUDI-4259] Flink create avro schema not conformance to standards
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroSchemaConverter.java
Labels: spark, flink, engine-interoperability

#5723 [HUDI-4173] Fix wrong results if the user read no base files hudi table by glob paths
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/execution/datasources/HoodieInMemoryFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
Labels: priority:critical, reader-core

#5734 [HUDI-4177] Fix hudi-cli rollback with rollbackUsingMarkers method call
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCommitsCommand.java
Labels: priority:minor

#5910 [HUDI-4286] Add release notes for 0.11.1
  website/releases/download.md
  website/releases/older-releases.md
  website/releases/release-0.10.0.md
  website/releases/release-0.10.1.md
  website/releases/release-0.11.0.md
  website/releases/release-0.11.1.md
  website/releases/release-0.7.0.md
  website/releases/release-0.8.0.md
  website/releases/release-0.9.0.md
Labels: docs

#5941 [HUDI-4290] Fix fetchLatestBaseFiles to filter replaced filegroups
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFSViewWithClustering.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
Labels: priority:blocker, query-engine, reader-core

#5944 [DOCS] Fix trino jar bundle in query engine setup page
  website/docs/query_engine_setup.md
  website/versioned_docs/version-0.10.0/query_engine_setup.md
  website/versioned_docs/version-0.10.1/query_engine_setup.md
  website/versioned_docs/version-0.11.0/query_engine_setup.md
  website/versioned_docs/version-0.11.1/query_engine_setup.md
  website/versioned_docs/version-0.9.0/query_engine_setup.md
Labels: docs, query-engine

#5895 Update procedures.md
  website/versioned_docs/version-0.11.0/procedures.md
Labels: docs

#5778 [DOCS] Add externalized confilg file doc in latest versions
  website/docs/configurations.md
  website/docs/quick-start-guide.md
  website/versioned_docs/version-0.10.1/configurations.md
  website/versioned_docs/version-0.11.0/configurations.md
Labels: docs

#5890 [HUDI-4273] Support inline schedule clustering for Flink stream
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/ClusteringPlanStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/FlinkRecentDaysClusteringPlanStrategy.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/FlinkSelectedPartitionsClusteringPlanStrategy.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitEvent.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanSourceFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/FlinkClusteringConfig.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ClusteringUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/ClusteringFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java
Labels: flink

#5877 [HUDI-4260] Change KEYGEN_CLASS_NAME without default value
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: flink

#5851 [HUDI-5246] Bumping mysql connector version due to security vulnerability
  hudi-sync/hudi-adb-sync/pom.xml
Labels: priority:critical, on-call-triaged

#5950 [HUDI-4311] Fix Flink lose data on some rollback scene
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
Labels: flink

#5472 [HUDI-4000][DOCS] Added a new blog on Hudi+dbt integration
  website/blog/2022-04-28-build-open-lakehouse-using-apache-hudi-and-dbt.md
  website/static/assets/images/blog/hudi_dbt_lakehouse.png
Labels: docs

#5366 [HUDI-1176] Upgrade hudi to log4j2
  hudi-aws/pom.xml
  hudi-cli/pom.xml
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/client/http/HoodieWriteCommitHttpCallbackClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogHttpClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogReporter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/callback/http/TestCallbackHttpClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/datadog/TestDatadogHttpClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/datadog/TestDatadogReporter.java
  hudi-gcp/pom.xml
  hudi-integ-test/pom.xml
  hudi-kafka-connect/pom.xml
  hudi-spark-datasource/hudi-spark/pom.xml
  hudi-sync/hudi-adb-sync/pom.xml
  hudi-sync/hudi-datahub-sync/pom.xml
  hudi-sync/hudi-hive-sync/pom.xml
  hudi-timeline-service/pom.xml
  hudi-utilities/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-timeline-server-bundle/pom.xml
  pom.xml
Labels: big-needle-movers

#5174 [MINOR] Make CLI 'commit rollback' using rollbackUsingMarkers false as default
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/CommitsCommand.java
Labels: priority:critical

#6006 [DOCS] Add blog on Apache Hudi vs Delta Lake TPC-DS benchmarks
  website/blog/2022-06-29-Apache-Hudi-vs-Delta-Lake-transparent-tpc-ds-lakehouse-performance-benchmarks.mdx
  website/static/assets/images/blog/2022-06-29-apache_hudi_vs_delta_lake_tpc_ds_benchmarks.png
Labels: docs

#5998 [DOCS] Remove duplicate faq page
  website/docs/faq.md
  website/docusaurus.config.js
  website/learn/faq.md
Labels: docs

#5987 [HUDI-4331] Allow loading external config file from class loader
  hudi-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
Labels: on-call-triaged, configs

#5999 [HUDI-4346] Fix the params of bulkInsertAsRow not update BULKINSERT_ARE_PARTITIONER_RECORDS_SORTED
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:major, spark-sql

#5907 [HUDI-4285] add ByteBuffer#rewind after ByteBuffer#get in AvroDeseria…
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroConversionUtils.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
Labels: priority:critical

#5458 [HUDI-3984] Remove mandatory check of partiton path for cli command
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java
Labels: priority:major, cli

#5048 [HUDI-3634] Could read empty or partial HoodieCommitMetaData in downstream if using HDFS
  hudi-common/src/main/java/org/apache/hudi/common/fs/HoodieWrapperFileSystem.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Labels: priority:critical

#6008 [DOCS] Fix typos in query types
  content/assets/js/43d31177.43d23fab.js
  content/cn/docs/0.5.0/concepts/index.html
  content/cn/docs/0.5.1/concepts/index.html
  content/cn/docs/0.5.2/concepts/index.html
  content/cn/docs/0.5.3/concepts/index.html
  content/cn/docs/0.6.0/concepts/index.html
  content/cn/docs/0.7.0/overview/index.html
  content/cn/docs/0.8.0/overview/index.html
  content/cn/docs/0.9.0/concepts/index.html
  content/cn/docs/0.9.0/overview/index.html
  content/cn/docs/next/concepts/index.html
  content/cn/docs/next/overview/index.html
  content/docs/0.5.0/concepts/index.html
  website/i18n/cn/docusaurus-plugin-content-docs/current/concepts.md
  website/i18n/cn/docusaurus-plugin-content-docs/current/overview.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.0/concepts.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.1/concepts.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.2/concepts.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.5.3/concepts.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.6.0/concepts.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.7.0/overview.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.8.0/overview.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.9.0/concepts.md
  website/i18n/cn/docusaurus-plugin-content-docs/version-0.9.0/overview.md
  website/versioned_docs/version-0.5.0/concepts.md
Labels: docs
