Repository apache/hudi, pull requests merged in 2022-10, with the labels that each got.

#6834 [DOCS] Add 1.0.0 release entry to Roadmap
  website/src/pages/roadmap.md
Labels: docs

#6851 [HUDI-4966] Add a partition extractor to handle partition values with slashes
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/SinglePartPartitionValueExtractor.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestPartitionValueExtractor.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncConfig.java
Labels: meta-sync, priority:critical

#6864 [HUDI-4980] Calculate avg record size using commit only
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
Labels: priority:major

#6751 [HUDI-4972] Fixes to make unit tests work on m1
  hudi-examples/hudi-examples-java/pom.xml
  hudi-timeline-service/pom.xml
  pom.xml
Labels: priority:minor

#6896 [HUDI-4975] Fix datahub bundle dependency
  packaging/hudi-datahub-sync-bundle/pom.xml
Labels: dependencies, priority:critical

#6575 [HUDI-4754] Add compliance check in github actions
  .github/README.md
  .github/workflows/pr_compliance.yml
  .github/workflows/update_pr_compliance.yml
  scripts/pr_compliance.py
Labels: priority:minor

#5933 [HUDI-4293] Implement Create/Drop/Show/Refresh Index Command for Secondary Index
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieSecondaryIndexException.java
  hudi-common/src/main/java/org/apache/hudi/secondary/index/HoodieSecondaryIndex.java
  hudi-common/src/main/java/org/apache/hudi/secondary/index/SecondaryIndexManager.java
  hudi-common/src/main/java/org/apache/hudi/secondary/index/SecondaryIndexType.java
  hudi-common/src/main/java/org/apache/hudi/secondary/index/SecondaryIndexUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Index.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestIndexSyntax.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
Labels: priority:major, spark, index

#6836 [HUDI-4952] Fixing reading from metadata table when there are no inflight commits
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
Labels: priority:blocker, metadata

#6003 [HUDI-1575][RFC-56] Early Conflict Detection For Multi-writer
  rfc/rfc-56/figure1.png
  rfc/rfc-56/figure2.png
  rfc/rfc-56/figure3.png
  rfc/rfc-56/figure4.png
  rfc/rfc-56/flow1.png
  rfc/rfc-56/rfc-56.md
Labels: priority:blocker, writer-core, big-needle-movers, rfc, multi-writer

#6912 [HUDI-3900] Fixing hdfs setup and tear down in tests to avoid flakiness
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java
Labels: priority:blocker, on-call-triaged

#6911 [HUDI-4816] [DOCS] Update docs for GlobalDeleteKeyGenerator
  website/docs/key_generation.md
  website/versioned_docs/version-0.10.0/key_generation.md
  website/versioned_docs/version-0.10.1/key_generation.md
  website/versioned_docs/version-0.11.0/key_generation.md
  website/versioned_docs/version-0.11.1/key_generation.md
  website/versioned_docs/version-0.12.0/key_generation.md
Labels: docs

#6913 [DOCS] Fix hoodie.index.type default value description in docs
  website/docs/configurations.md
  website/versioned_docs/version-0.11.0/configurations.md
  website/versioned_docs/version-0.11.1/configurations.md
  website/versioned_docs/version-0.12.0/configurations.md
Labels: docs

#6923 [HUDI-5010] Fix flink hive catalog external config not work
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogFactory.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/HoodieCatalogTestUtils.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalogFactory.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: flink, catalog

#6818 [HUDI-4948] Improve CDC Write
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandleWithChangeLog.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandleWithChangeLog.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCFileSplit.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieCDCLogRecordIterator.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/JsonUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/HoodieCDCTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
Labels: priority:minor, writer-core

#6892 [HUDI-4996] Update hoodie_cleaner.md
  website/docs/hoodie_cleaner.md
  website/versioned_docs/version-0.12.0/hoodie_cleaner.md
Labels: docs

#6948 [HUDI-5030]fix ut `TestPartialUpdateAvroPayload`.`testUseLatestRecordMetaValue`
  hudi-common/src/test/java/org/apache/hudi/common/model/TestPartialUpdateAvroPayload.java
Labels: priority:minor, writer-core

#6951 [HUDI-5033] Fix Broken Link In MultipleSparkJobExecutionStrategy
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Labels: priority:minor

#6941 [HUDI-5037] Upgrade org.apache.thrift:libthrift to 0.14.0
  packaging/hudi-integ-test-bundle/pom.xml
Labels: dependencies, priority:major

#6944 [MINOR] Fixing verbosity of docker set up
  docker/setup_demo.sh
Labels: priority:minor

#6934 [HUDI-5022] made better error messages for pr compliance
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr_compliance.yml
  scripts/pr_compliance.py
Labels: priority:minor

#6916 [HUDI-5003] Fix the type of InLineFileSystem`startOffset to long
  hudi-common/src/main/java/org/apache/hudi/common/fs/inline/InLineFSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/inline/InLineFsDataInputStream.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/InLineFSUtilsTest.java
Labels: priority:critical, writer-core

#6694 [HUDI-4855] Add missing table configs for bootstrap in Deltastreamer
  docker/demo/sparksql-bootstrap-prep-source.commands
  hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BootstrapExecutor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: priority:critical, deltastreamer, writer-core

#6876 [MINOR] Handling null event time
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
Labels: priority:minor

#6972 [HUDI-4977][DOCS] Fix broken links in Flink quick start guide
  website/docs/flink-quick-start-guide.md
  website/static/assets/images/blog/2022-09-28_Data_processing_with_Spark_time_traveling.png
  website/static/assets/images/blog/2022-10-06_Ingest_streaming_data_to_Apache_Hudi_tables_using_AWS_Glue_and_DeltaStreamer.png
  website/versioned_docs/version-0.10.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.10.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.11.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.11.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.12.0/flink-quick-start-guide.md
Labels: docs

#6973 [DOCS] Add more blogs to Hudi website
  website/blog/2022-09-20-Building-Streaming-Data-Lakes-with-Hudi-and-MinIO.mdx
  website/blog/2022-09-28-Data-processing-with-Spark-time-traveling.mdx
  website/blog/2022-10-06-Ingest-streaming-data-to-Apache-Hudi-using-AWS-Glue-and-DeltaStreamer.mdx
Labels: docs

#6995 [HUDI-3900] Closing resources in TestHoodieLogRecord
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Labels: priority:blocker

#6954 [HUDI-4982] Add validation job for spark bundles in GitHub Actions
  .github/workflows/bot.yml
  packaging/bundle-validation/spark-write-hive-sync/Dockerfile
  packaging/bundle-validation/spark-write-hive-sync/ci_run.sh
  packaging/bundle-validation/spark-write-hive-sync/hive-site.xml
  packaging/bundle-validation/spark-write-hive-sync/spark-defaults.conf
  packaging/bundle-validation/spark-write-hive-sync/validate.scala
  packaging/bundle-validation/spark-write-hive-sync/validate.sh
Labels: priority:major

#6899 [HUDI-4998] Inference of META_SYNC_PARTITION_EXTRACTOR_CLASS does not work with META_SYNC_PARTITION_FIELDS
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
Labels: meta-sync, priority:minor

#6471 [HUDI-4781] Allow omit metadata fields for hive sync
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfigHolder.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Labels: meta-sync, priority:minor

#6893 [HUDI-4997] use jackson-v2 replace jackson-v1 import.
  dependencies/hudi-flink-bundle_2.11.txt
  dependencies/hudi-flink-bundle_2.12.txt
  dependencies/hudi-hadoop-mr-bundle.txt
  dependencies/hudi-hive-sync-bundle.txt
  dependencies/hudi-integ-test-bundle.txt
  dependencies/hudi-kafka-connect-bundle.txt
  dependencies/hudi-presto-bundle.txt
  dependencies/hudi-spark-bundle_2.11.txt
  dependencies/hudi-spark-bundle_2.12.txt
  dependencies/hudi-spark3-bundle_2.12.txt
  dependencies/hudi-timeline-server-bundle.txt
  dependencies/hudi-utilities-bundle_2.11.txt
  dependencies/hudi-utilities-bundle_2.12.txt
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/util/HoodieWriteCommitCallbackUtil.java
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-timeline-server-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
  pom.xml
Labels: dependencies, priority:major

#6981 [HUDI-3900] Fix tempDir usage in TestHoodieLogFormat
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Labels: priority:major, on-call-triaged

#6906 [HUDI-4995] Relocate httpcomponents in all bundles
  packaging/hudi-datahub-sync-bundle/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-timeline-server-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
  pom.xml
Labels: dependencies, priority:major

#6844 [HUDI-4960] Upgrade jetty version for timeline server
  hudi-timeline-service/pom.xml
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerCreationFuture.java
  pom.xml
Labels: dependencies, priority:critical

#7016 [MINOR] fix cdc flake ut
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
Labels: priority:critical

#7022 [MINOR] Remove redundant space in PR compliance check
  scripts/pr_compliance.py
Labels: priority:critical

#7006 [HUDI-5063] Enabling run time stats to be serialized with commit metadata
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieCommitMetadata.java
Labels: priority:critical

#7023 [HUDI-5070] Adding lock provider to testCleaner tests since async cleaning is invoked
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
Labels: priority:blocker, on-call-triaged

#7034 [HUDI-5070] Move flaky cleaner tests to separate class
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/clean/TestCleanerInsertAndCleanByCommits.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
Labels: priority:blocker

#7014 [HUDI-4971] Remove direct use of kryo from `SerDeUtils`
  hudi-common/src/main/java/org/apache/hudi/common/util/AvroOrcUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/BinaryUtil.java
  hudi-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/SerDeUtils.scala
Labels: priority:blocker, spark-sql

#7033 [HUDI-5081] Tests clean up in hudi-utilities
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deser/TestKafkaAvroSchemaDeserializer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsSource.java
Labels: priority:major

#6946 [HUDI-5027] Replace hardcoded hbase config keys with constant variables
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java
Labels: priority:minor, index

#7012 [minor]add commit_action output in show_commits
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitsProcedure.scala
Labels: priority:minor

#7001 [HUDI-5061] bulk insert operation don't throw other exception except IOE Exception
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
Labels: priority:minor

#6660 [MINOR] Skip loading last completed txn for single writer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/TransactionManager.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
Labels: priority:major, writer-core, multi-writer

#5903 [HUDI-4281] Using hudi to build a large number of tables in spark on hive causes OOM
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hive/HiveClientUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
Labels: priority:major, hive

#6632 [HUDI-4753] more accurate record size estimation for log writing and spillable map
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
Labels: priority:major, writer-core

#6867 [HUDI-4201] Cli tool to get warned about empty non-completed instants from timeline
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java
Labels: priority:minor

#6955 [HUDI-5038] Increase default num_instants to fetch for incremental source
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: priority:critical, on-call-triaged, incremental-query

#6991 [HUDI-5049] HoodieCatalog supports the implementation of dropPartition
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkDeletePartitionCommitActionExecutor.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
Labels: priority:major

#7007 [HUDI-4809] Glue support drop partitions
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: meta-sync, priority:major

#6999 [HUDI-5057] Fix msck repair hudi table
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystPlansUtils.scala
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/RepairHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestRepairTable.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystPlanUtils.scala
Labels: priority:major, spark

#7024 [HUDI-4959] Fixing Avro's `Utf8` serialization in Kryo
  hudi-common/src/main/java/org/apache/hudi/common/util/SerializationUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestSerializationUtils.java
Labels: priority:critical

#6990 [HUDI-5048] add CopyToTempView support
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CopyToTempView.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCopyToTempViewProcedure.scala
Labels: priority:major, reader-core

#7005 [HUDI-4982] Add Utilities and Utilities Slim + Spark Bundle testing to GH Actions
  .github/workflows/bot.yml
  packaging/bundle-validation/Dockerfile
  packaging/bundle-validation/Dockerfile-base
  packaging/bundle-validation/ci_run.sh
  packaging/bundle-validation/conf/hive-site.xml
  packaging/bundle-validation/conf/hudi-defaults.conf
  packaging/bundle-validation/conf/spark-defaults.conf
  packaging/bundle-validation/spark-write-hive-sync/validate.sh
  packaging/bundle-validation/spark/validate.scala
  packaging/bundle-validation/utilities/hoodieapp.properties
  packaging/bundle-validation/utilities/validate.scala
  packaging/bundle-validation/validate.sh
Labels: priority:critical, utilities

#7009 [HUDI-5058]Fix flink catalog read spark table error : primary key col can not be nullable
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/DataTypeUtils.java
Labels: priority:major, reader-core

#7053 [HUDI-5087] Fix incorrect merging sequence for Column Stats Record in `HoodieMetadataPayload`
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataPayload.java
Labels: priority:critical

#6824 [HUDI-4946] fix merge into with no preCombineField has dup row by onl…
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
Labels: priority:major, spark-sql

#7030 [HUDI-5072] Extract transform duplicate code.
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/ExecutionStrategyUtil.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobExecutionStrategy.java
Labels: priority:minor

#7072 [HUDI-1570] Added average record size in a commit to the faq's
  website/docs/faq.md
  website/versioned_docs/version-0.12.1/faq.md
Labels: docs, priority:minor

#6079 [HUDI-3287] Remove hudi-spark dependencies from hudi-kafka-connect-bundle
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/factory/HoodieAvroKeyGeneratorFactory.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/utils/KafkaConnectUtils.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectTransactionServices.java
  packaging/hudi-kafka-connect-bundle/pom.xml
Labels: dependencies, priority:critical

#6989 [HUDI-5000] Support schema evolution for Hive/presto
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/SchemaEvolutionContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-presto-bundle/pom.xml
Labels: schema-and-data-types, priority:major, hive, reader-core

#6930 [HUDI-4716] Avoid parquet-hadoop-bundle in hudi-hadoop-mr
  packaging/hudi-hadoop-mr-bundle/pom.xml
  pom.xml
Labels: dependencies, priority:critical, on-call-triaged

#6952 [HUDI-5035] Remove usage of deprecated HoodieTimer constructor
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLookupHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/CopyOnWriteRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MergeOnReadRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/DirectWriteMarkers.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/validator/SparkPreCommitValidator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkDeletePartitionCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/HoodieWrapperFileSystem.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDBDAO.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CreateMetadataTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/InitMetadataTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCompactionProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataTableFilesProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataTablePartitionsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ValidateMetadataTableFilesProcedure.scala
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HiveQueryDDLExecutor.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/BatchedMarkerCreationRunnable.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerCreationFuture.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerDirState.java
Labels: priority:minor

#6796 [HUDI-4741] hotfix to avoid partial failover cause restored subtask f…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: priority:major, flink

#7090 Revert "[HUDI-4741] hotfix to avoid partial failover cause restored s…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: priority:critical, flink

#7048 [MINOR] Fix doc of org.apache.hudi.sink.meta.CkpMetadata#bootstrap
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
Labels: docs, flink

#6625 [HUDI-4799] improve analyzer exception tip when can not resolve expre…
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
Labels: priority:major, spark-sql

#7068 [HUDI-5096] boolean param is broken in HiveSyncTool
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncToolArgs.java
  pom.xml
Labels: meta-sync, priority:critical

#7091 [HUDI-5105] Add Call show_commit_extra_metadata for spark sql
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitExtraMetadataProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCommitsProcedure.scala
Labels: priority:major, spark-sql
