Repository apache/hudi, pull requests merged in 2022-11, with the labels that each got.

#7094 [HUDI-5107] Fix hadoop config in DirectWriteMarkers, HoodieFlinkEngineContext and StreamerUtil are not consistent issue
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/DirectWriteMarkers.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
Labels: priority:major, writer-core

#7096 [MINOR] Fix OverwriteWithLatestAvroPayload full class name
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
Labels: priority:major

#6959 [MINOR] fix(sec): upgrade commons-codec:commons-codec to 1.13
  packaging/hudi-integ-test-bundle/pom.xml
Labels: dependencies, priority:critical

#7120 [DOCS] Edit quickstart
  website/docs/quick-start-guide.md
Labels: docs

#7101 [HUDI-5065] Call close on SparkRDDWriteClient in HoodieCleaner
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCleaner.java
Labels: on-call-triaged

#6982 [HUDI-5045] Adding support to configure index type with integ tests
  docker/demo/config/test-suite/spark-immutable-to-mutable.yaml
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java
  hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertNode.scala
Labels: priority:critical

#7036 [HUDI-5076] Fixing non serializable path used in engineContext with metadata table intialization
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Labels: priority:critical, metadata

#6733 [HUDI-4880] Fix corrupted parquet file issue left by a leaked thread in CompactFunction
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactFunction.java
Labels: priority:critical, table-service

#7123 [MINOR] Fixing broken test
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java
Labels: priority:blocker

#6862 [HUDI-4989] Fixing deltastreamer init failures
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: priority:critical, deltastreamer

#7134 [MINOR] Fix flaky test in ITTestHoodieDataSource
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: priority:major, flink

#6681 [HUDI-4071] Remove default value for mandatory record key field
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/clustering/plan/strategy/TestSparkConsistentBucketClusteringPlanStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/TestHoodieIndexConfigs.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bucket/TestHoodieSimpleBucketIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigProperty.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
  hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java
  hudi-examples/hudi-examples-spark/src/test/java/org/apache/hudi/examples/quickstart/TestHoodieSparkQuickstart.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceWithBucketIndex.scala
Labels: priority:critical, writer-core

#7108 [DOCS] add FAQ on how to reduce table versions created in metastore by hudi
  website/docs/faq.md
  website/versioned_docs/version-0.12.1/faq.md
Labels: docs

#7112 [MINOR] Removing spark2 scala12 combinations from readme
  README.md
Labels: docs

#7111 [DOCS][MINOR] Adding useful maven commands to website
  website/contribute/developer-setup.md
Labels: docs, priority:critical

#7128 [HUDI-5153] Fix the write token name resolution of cdc log file
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
Labels: priority:major, writer-core

#7017 [HUDI-5066] Support flink hoodie source metaclient cache
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
Labels: flink

#7157 [HUDI-5132] Add hadoop-mr bundle validation
  packaging/bundle-validation/ci_run.sh
  packaging/bundle-validation/spark_hadoop_mr/write.scala
  packaging/bundle-validation/validate.sh
Labels: priority:blocker

#7131 [HUDI-2673] Add kafka connect bundle to validation test
  hudi-kafka-connect/demo/setupKafka.sh
  packaging/bundle-validation/Dockerfile-base
  packaging/bundle-validation/ci_run.sh
  packaging/bundle-validation/kafka/config-sink.json
  packaging/bundle-validation/kafka/consume.sh
  packaging/bundle-validation/kafka/produce.sh
  packaging/bundle-validation/validate.sh
Labels: priority:blocker

#7042 [HUDI-5082] Improve the cdc log file name format
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/HoodieCDCTestBase.scala
Labels: priority:major

#7127 [HUDI-5154] Improve hudi-spark-client Lambada writing
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/update/strategy/SparkAllowUpdateStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkValidatorUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDConsistentBucketPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metrics/DistributedRegistry.java
Labels: priority:minor

#7018 [HUDI-5067] Merge the columns stats of multiple log blocks from the s…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/WriteStatMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieDeltaWriteStat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: flink

#6939 [HUDI-5025] Rollback failed with log file not found when rollOver in rollback process
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java
Labels: priority:critical, writer-core

#6284 [HUDI-4526] Improve spillableMapBasePath disk directory is full
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMemoryConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
Labels: priority:major, writer-core, reader-core

#7092 [HUDI-5111] Improve integration test coverage
  docker/demo/config/test-suite/deltastreamer-immutable-dataset.yaml
  docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-hive.yaml
  docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml
  docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml
  docker/demo/config/test-suite/deltastreamer-medium-clustering.yaml
  docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml
  docker/demo/config/test-suite/deltastreamer-non-partitioned.yaml
  docker/demo/config/test-suite/detlastreamer-long-running-example.yaml
  docker/demo/config/test-suite/simple-clustering.yaml
  docker/demo/config/test-suite/simple-deltastreamer.yaml
  docker/demo/config/test-suite/spark-immutable-dataset.yaml
  docker/demo/config/test-suite/spark-long-running-non-partitioned.yaml
  docker/demo/config/test-suite/spark-long-running.yaml
  docker/demo/config/test-suite/spark-medium-clustering.yaml
  docker/demo/config/test-suite/spark-simple.yaml
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteJob.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/PrestoQueryNode.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/ValidateDatasetNode.java
  hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertNode.scala
Labels: priority:critical, on-call-triaged

#7171 [HUDI-5145] Avoid starting HDFS in hudi-utilities tests
  hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestDFSHoodieTestSuiteWriterAdapter.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestFileDeltaInputWriter.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSAvroDeltaInputReader.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSHoodieDatasetInputReader.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestCsvDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestParquetDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestAbstractDebeziumSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractCloudObjectsSourceTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractDFSSourceTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlFileBasedTransformer.java
Labels: priority:major

#7151 [MINOR] Performance improvement of flink ITs with reused miniCluster
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/FlinkMiniCluster.java
Labels: priority:critical

#7142 [HUDI-5056] Allow wildcards in partition paths for DELETE_PARTITIONS
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Labels: priority:major

#7160 [HUDI-5176] Fix incremental source to consider inflight commits before completed commits
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/QueryInfo.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: priority:blocker, incremental-query

#6838 [MINOR] Balance CI jobs
  azure-pipelines.yml
Labels: priority:major

#7168 [HUDI-5185] Fix CLI run compaction failing with --hoodieConfigs
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCompactionCommand.java
Labels: priority:minor, cli

#7180 [HUDI-5198] add in minor perf wins in hudi-utilities and locking related tests
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestTransactionManager.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJdbcSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestAbstractDebeziumSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractDFSSourceTestBase.java
Labels: priority:major

#7175 [HUDI-5191] Fix compatibility with avro 1.10
  .github/workflows/bot.yml
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/AbstractDebeziumAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestOverwriteNonDefaultsWithLatestAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestPartialUpdateAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestObjectSizeCalculator.java
Labels: priority:critical, spark

#6227 [HUDI-4496] Fixing Orc support broken for Spark 3.x and more
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieOrcWriter.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCFileSplit.java
  hudi-common/src/main/java/org/apache/hudi/common/util/AvroOrcUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CustomizedThreadFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/util/OrcReaderIterator.java
  hudi-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestOrcReaderIterator.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotExporter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
  packaging/hudi-flink-bundle/pom.xml
  pom.xml
Labels: priority:major, writer-core

#7181 [HUDI-5201] add totalRecordsDeleted metric
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
Labels: priority:minor, metrics

#7052 [MINOR] Make sure Dictionary Encoding in Parquet enabled by default
  hudi-cli/src/main/scala/org/apache/hudi/cli/SparkHelpers.scala
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroParquetWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataFileWriterFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieParquetConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/SparkHelpers.scala
Labels: priority:critical

#7211 [HUDI-5227] Bump Javalin to 4.6.7 and Jetty to 9.4.48
  hudi-timeline-service/pom.xml
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  packaging/hudi-timeline-server-bundle/pom.xml
  pom.xml
Labels: dependencies, priority:blocker

#7210 [DOCS] Add faq, talk and edit community sync page
  website/community/syncs.md
  website/docs/faq.md
  website/src/pages/talks.md
  website/static/assets/images/blog/2022-10-17-Get_started_with_apache_hudi_using_glue.jpeg
  website/static/assets/images/blog/2022-11-10_How_to_build_a_cost_optimized_glue_pipeline_with_apache_hudi.png
Labels: docs

#7188 [HUDI-5209] Fixing `QueueBasedExecutor` in Spark bundles (missing Disruptor as dep)
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/QueueBasedExecutorFactory.java
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
Labels: priority:critical

#7193 [HUDI-5203] Handle null fields in debezium avro payloads
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/MySqlDebeziumAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/PostgresDebeziumAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieDebeziumAvroPayloadException.java
  hudi-common/src/test/java/org/apache/hudi/common/model/debezium/TestMySqlDebeziumAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/debezium/TestPostgresDebeziumAvroPayload.java
Labels: priority:critical, deltastreamer

#6680 [HUDI-4812] Lazy fetching partition path & file slice for HoodieFileIndex
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/BuiltinKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/ComplexKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/PartitionPathFormatterBase.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/SimpleKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/StringPartitionPathFormatter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/UTF8StringPartitionPathFormatter.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/JFunction.scala
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-common/src/main/java/org/apache/hudi/hadoop/CachingPath.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieTableFileIndex.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestSimpleKeyGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/ScalaAssertionSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31HoodieParquetFileFormat.scala
Labels: performance, priority:critical, spark

#5113 [HUDI-3625] [RFC-60] Optimized storage layout for Cloud Object Stores
  rfc/rfc-60/rfc-60.md
Labels: priority:critical, rfc

#7138 [HUDI-5162] Allow user specified start offset for streaming query
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieMetadataLog.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieOffsetRangeLimit.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
Labels: priority:major, reader-core, spark-streaming

#7251 [HUDI-5070] Move flaky cleaner tests to separate class
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/clean/TestCleanerInsertAndCleanByCommits.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/clean/TestCleanerInsertAndCleanByVersions.java
Labels: priority:minor

#7250 [HUDI-5247] Clean up java client tests
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestHoodieJavaWriteClientInsert.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestJavaBulkInsertInternalPartitioner.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestBase.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
Labels: priority:minor

#7257 [DOCS] Change upcoming Community sync image
  website/static/assets/images/upcoming-community-calls.png
Labels: docs

#7258 [DOCS] Add more blogs and talks
  website/blog/2021-10-14-How-Amazon-Transportation-Service-enabled-near-real-time-event-analytics-at-petabyte-scale-using-AWS-Glue-with-Apache-Hudi.mdx
  website/blog/2022-10-17-Get-started-with-Apache-Hudi-using-AWS.mdx
  website/blog/2022-11-10-How-Hudl-built-a-cost-optimized-AWS-Glue-pipeline-with-Apache-Hudi-datasets.mdx
  website/src/pages/talks.md
Labels: docs

#7267 [HUDI-712] Improve exporter file listing and copy perf
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
Labels: performance, priority:minor, utilities

#7132 [HUDI-5157] Adding capability to remove all meta fields from source hudi table with Hudi incr source
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
Labels: priority:critical, deltastreamer

#7268 [MINOR] Fix typos in HoodieTimelineArchiver
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
Labels: priority:minor

#7263 [HUDI-5252] ClusteringCommitSink supports to rollback clustering
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ClusteringUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestClusteringUtil.java
Labels: flink, table-service

#7269 [HUDI-5260] fix insert into sql command with strict sql insert mode and no preCombine…
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:critical, spark-sql

#7308 [HUDI-5283] Replace deprecated method Schema.parse With Schema.Parser.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/bootstrap/HoodieBootstrapSchemaProvider.java
Labels: priority:minor, code-refactor

#7305 [HUDI-4209] Avoid using HDFS in HoodieClientTestHarness
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/index/bloom/TestFlinkHoodieBloomIndex.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkClientTestHarness.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkWriteableTestTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestFileBasedLockProvider.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieReadClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestMultiFS.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestUpdateSchemaEvolution.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestDataValidationCheckForLogCompactionActions.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestDirectWriteMarkers.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtilsWithRetryWrapperEnable.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormatAppendFailure.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/HdfsTestService.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/minicluster/MiniClusterUtil.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/hive/TestHoodieCombineHiveInputFormat.java
Labels: priority:major

#7021 [Minor] fix multi deser avro payload
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/commmon/model/HoodieSparkRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/BaseAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/EventTimeAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/PartialUpdateAvroPayload.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/PayloadCreation.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/QuickstartUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/model/TestHoodieRecordSerialization.scala
Labels: priority:major, writer-core, reader-core

#7243 [HUDI-5242] Do not fail Meta sync in Deltastreamer when inline table service fails
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: priority:critical, deltastreamer

#6920 [HUDI-5007] Prevent Hudi from reading the entire timeline's when perf…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
Labels: flink, reader-core

#7310 [HUDI-5285] Exclude *-site.xml files from jar packaging
  hudi-utilities/pom.xml
Labels: dependencies, priority:major, on-call-triaged

#7264 [HUDI-5253] HoodieMergeOnReadTableInputFormat could have duplicate records issue if it contains delta files while still splittable
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieRealtimePath.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieMergeOnReadTableInputFormat.java
Labels: priority:critical, hive, reader-core

#6855 [DOC] [HUDI-4968] Update old config keys
  website/docs/flink-quick-start-guide.md
  website/docs/querying_data.md
  website/versioned_docs/version-0.11.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.11.0/querying_data.md
  website/versioned_docs/version-0.11.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.11.1/querying_data.md
  website/versioned_docs/version-0.12.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.12.0/querying_data.md
Labels: docs, priority:minor

#7124 [HUDI-5151] Fix bug with broken flink data skipping caused by ClassNotFoundException of InLineFileSystem
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
Labels: priority:critical, metadata

#7304 [HUDI-5278] Support more conf to cluster procedure
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: priority:major, spark-sql

#7287 [MINOR] Reuse empty InternalSchema instance
  hudi-common/src/main/java/org/apache/hudi/internal/schema/InternalSchema.java
Labels: schema-and-data-types, priority:minor

#7003 [minor] add more test for rfc46
  azure-pipelines.yml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/bootstrap/BootstrapRecordConsumer.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkMergeHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaMergeHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/model/HoodieInternalRow.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/commmon/model/HoodieSparkRecord.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDSpatialCurveSortPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileWriterFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkParquetReader.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/ParquetBootstrapMetadataHandler.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/util/HoodieSparkRecordUtils.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystExpressionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieInternalRowUtils.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieEmptyRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/IdentityIterator.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroParquetReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/LogFileIterator.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/HoodieSparkValidateDuplicateKeyRecordMerger.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieInternalRowUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestStructTypeSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/model/TestHoodieRecordSerialization.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCompactionTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteFromTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoLogOnlyTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: priority:blocker

#5830 [HUDI-3981] Flink engine support for comprehensive schema evolution
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/CastMap.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/HoodieParquetEvolvedSplitReader.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/HoodieParquetReader.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/HoodieParquetSplitReader.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/InternalSchemaManager.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataCastProjection.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataProjection.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestCastMap.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
Labels: schema-and-data-types, priority:major, flink, big-needle-movers
