Repository apache/hudi, pull requests merged in 2022-01, with the labels that each got.

#4118 [HUDI-2774] Handle duplicate instants while fetching pending clustering plans
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
Labels: sev:critical

#4505 [HUDI-3141] Metadata merged log record reader - avoiding NullPointerException when reading records by keys
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMergedLogRecordReader.java
Labels: sev:critical

#4500 [HUDI-3147] Add endpoint_url to dynamodb lock provider
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
  hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
Labels: sev:critical

#4478 [HUDI-2966] Closing LogRecordScanner in compactor
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
Labels: sev:critical

#4512 [HUDI-3170] Do not preserve filename when preserveCommitMetadata enabled
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: sev:critical

#4513 [HUDI-3168] Fixing null schema with empty commit in incremental relation
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
Labels: sev:critical

#4431 Update HiveIncrementalPuller.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HiveIncrementalPuller.java
Labels: sev:critical

#4428 [HUDI-44] Adding support to preserve commit metadata for compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
Labels: sev:critical

#4507 [HUDI-52] Enabling savepoint and restore for MOR table
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/savepoint/SavepointActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
Labels: sev:critical

#4427 [HUDI-3165] Enabling InProcessLockProvider for all multi-writer tests instead of FileSystemBasedLockProviderTestClass
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/InProcessLockProvider.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: sev:critical

#4408 [MINOR] unused method in HoodieColumnProjectionUtils removed
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieColumnProjectionUtils.java
Labels: sev:critical

#4460 [HUDI-3118] Add default HUDI_DIR in setupKafka.sh
  hudi-kafka-connect/demo/setupKafka.sh
Labels: sev:critical

#4521 [HUDI-3183] Wrong result of HoodieArchivedTimeline loadInstants with TimeRangeFilter
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
Labels: sev:critical

#4440 [HUDI-3100] Add config for hive conditional sync
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
Labels: sev:critical

#4527 [HUDI-3188] Update quick start guide for Kafka Connect Sink for Hudi
  hudi-kafka-connect/README.md
Labels: sev:critical

#4485 [HUDI-2947] Fixing checkpoint fetch in detlastreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: sev:critical

#4536 [HUDI-3185] HoodieConfig#getBoolean should return false when default …
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/config/TestConfigProperty.java
Labels: sev:critical

#4533 [HUDI-2682] Spark schema not updated with new columns on hive sync
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
Labels: sev:critical

#4203 [HUDI-2909] Handle logical type in TimestampBasedKeyGenerator
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/ComplexAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/GlobalAvroDeleteKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/NonpartitionedAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/SimpleAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/TimestampBasedAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataKeyGenerator.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/execution/bulkinsert/JavaCustomColumnsSortPartitioner.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestJavaBulkInsertInternalPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDCustomColumnsSortPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bucket/TestBucketIdentifier.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/keygen/TestTimestampBasedKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/keygen/BaseKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-common/src/test/resources/timestamp-logical-type.avsc
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/PayloadCreation.java
  hudi-flink/src/test/java/org/apache/hudi/utils/TestStringToRowDataConverter.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/bootstrap/SparkFullBootstrapDataProviderBase.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/SqlKeyGenerator.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestGenericRecordAndRowConsistency.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: sev:critical

#4530 [HUDI-3178] Fixing metadata table compaction so as to not include uncommitted data
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiveLog.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkCopyOnWriteTableArchiveWithReplace.java
Labels: sev:critical

#4451 [HUDI-3104] Kafka-connect support hadoop config environments and properties
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/utils/KafkaConnectUtils.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectConfigs.java
  hudi-kafka-connect/src/test/java/org/apache/hudi/connect/TestHdfsConfiguration.java
  hudi-kafka-connect/src/test/resources/hadoop_conf/core-site.xml
  hudi-kafka-connect/src/test/resources/hadoop_conf/hdfs-site.xml
  hudi-kafka-connect/src/test/resources/hadoop_home/etc/hadoop/core-site.xml
  hudi-kafka-connect/src/test/resources/hadoop_home/etc/hadoop/hdfs-site.xml
Labels: sev:critical

#4471 [HUDI-3125] spark-sql write timestamp directly
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/RowKeyGeneratorHelper.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionHelper.scala
  hudi-client/hudi-spark-client/src/test/scala/org/apache/hudi/keygen/TestRowGeneratorHelper.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: sev:critical

#4458 [HUDI-3112] Fix KafkaConnect can not sync to Hive Problem
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/utils/KafkaConnectUtils.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectConfigs.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectTransactionServices.java
Labels: sev:critical

#4518 [HUDI-2477] Removing rollbacks instants from timeline for restore operation
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: sev:critical

#4406 [HUDI-3030] InProcessLockPovider as default when any async servcies enabled with no lock provider override
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/AbstractHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
Labels: sev:critical

#4544 [HUDI-2735] Allow empty commits in Kafka Connect Sink for Hudi
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/transaction/ConnectTransactionCoordinator.java
  hudi-kafka-connect/src/test/java/org/apache/hudi/connect/TestConnectTransactionCoordinator.java
Labels: sev:critical

#4519 [HUDI-3180] Include files from completed commits while bootstrapping metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBootstrap.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
Labels: sev:critical

#4497 [HUDI-3148] Create pushgateway client based on port
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PushGatewayMetricsReporter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PushGatewayReporter.java
Labels: sev:critical

#4553 [HUDI-3158] Removing extraneous warn logs in ClusteringUtils
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
Labels: sev:critical

#2768 [HUDI-485]: corrected the check for incremental sql
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-utilities/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HiveIncrementalPuller.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
Labels: sev:high

#4551 [HUDI-3010] Unbundle parquet-avro and shade hbase in presto-bundle
  packaging/hudi-presto-bundle/pom.xml
Labels: sev:critical

#4540 [HUDI-3194] fix MOR snapshot query (HIVE) during compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLayoutConfig.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java
Labels: priority:major

#4602 [HUDI-3245] Convert uppercase letters to lowercase in storage configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
Labels: priority:critical

#4078 [HUDI-2833][Design] Merge small archive files instead of expanding indefinitely.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTimelineArchiveLog.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiveLog.java
  hudi-common/src/main/avro/HoodieMergeArchiveFilePlan.avsc
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
Labels: priority:critical, core-writer-flow

#2903 [HUDI-1850][HUDI-3234] Fixing read of a empty table but with failed write
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/EmptyRelation.scala
Labels: priority:major, pr:author-action

#4280 [HUDI-1822] Rewriting rfc-27 for data skipping index
  rfc/rfc-27/col_stats.png
  rfc/rfc-27/rfc-27.md
Labels: rfc

#4565 [HUDI-3215] Solve UT for Spark 3.2
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
Labels: priority:critical, writer-core

#3957 [HUDI-2688][RFC-40] A new Hudi connector for Trino
  rfc/README.md
  rfc/rfc-40/Hudi_Connector.png
  rfc/rfc-40/rfc-40.md
Labels: rfc
