Repository apache/hudi, pull requests merged in 2022-02, with the labels that each got.

#3946 [HUDI-2711] Fallback to fulltable scan for IncrementalRelation if underlying files have been cleared or moved by cleaner
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: priority:major

#3989 [HUDI-2589] RFC-37: Metadata table based bloom index
  rfc/README.md
  rfc/rfc-37/metadata_index_1.png
  rfc/rfc-37/metadata_index_bloom_partition.png
  rfc/rfc-37/metadata_index_col_stats.png
  rfc/rfc-37/rfc-37.md
Labels: rfc

#4716 [HUDI-3322][HUDI-3343] Fixing Metadata Table Records Duplication Issues
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackRequest.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestMetadataConversionUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java
  hudi-common/src/main/avro/HoodieRollbackMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/common/HoodieRollbackStat.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: priority:critical

#4721 [HUDI-3320] Hoodie metadata table validator
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
Labels: priority:critical

#4762 [HUDI-3367] Adding support for custom scheduler configs with streaming sink
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/SchedulerConfGenerator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSchedulerConfGenerator.java
Labels: priority:critical

#4755 [HUDI-3361] Fixing missing begin checkpoint in HoodieIncremental pull
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: priority:critical

#4420 [HUDI-1847] Adding inline scheduling support for spark datasource path for compaction and clustering
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableClustering.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableIncrementalRead.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
Labels: priority:critical

#4783 [HUDI-3333] fix that getNestedFieldVal breaks with Spark 3.2
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  pom.xml
Labels: priority:critical

#4749 [HUDI-3402] Set hoodie.parquet.outputtimestamptype to TIMESTAMP_MICROS by default
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieStorageConfig.java
Labels: priority:critical

#4772 [HUDI-3362] Fix restore to rollback pending clustering operations followed by other rolling back other commits
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RestorePlanActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
Labels: priority:critical

#3648 [HUDI-2413] fix Sql source's checkpoint issue
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SqlSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlSource.java
Labels: priority:critical

#4753 [HUDI-3370] The files recorded in the commit may not match the actual ones for MOR Compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/HoodieSparkCompactor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-examples/src/main/java/org/apache/hudi/examples/spark/HoodieWriteClientExample.java
  hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CompactionHoodiePathCommand.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
Labels: priority:blocker

#4611 [HUDI-3254] Introduce HoodieCatalog to manage tables for Spark Datasource V2
  .github/workflows/bot.yml
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddColumnsCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieSqlBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3SqlUtils.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/Spark3Adapter.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/hudi/Spark3DefaultSource.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/connector/catalog/HoodieIdentifier.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark3Analysis.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/BasicStagedTable.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieInternalV2Table.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieStagedTable.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/hudi/catalog/TableCreationMode.java
  style/scalastyle.xml
Labels: priority:blocker, big-needle-movers

#4801 [MINOR] Prevent async service from starting twice
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java
Labels: priority:major

#4617 HUDI-1657: build failed on AArch64, Fedora 33
  hudi-kafka-connect/pom.xml
  pom.xml
Labels: priority:critical

#4795 [HUDI-1576] Make archiving an async service
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestArchivedCommitsCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCommitsCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCompactionCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncArchiveService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/AsyncCleanerService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/async/HoodieAsyncService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/async/TestAsyncArchiveService.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Labels: priority:blocker

#4714 [HUDI-3204] fix problem that spark on TimestampKeyGenerator has no re…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/TimestampBasedAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/parser/BaseHoodieDateTimeParser.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/parser/HoodieDateTimeParser.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/keygen/TestTimestampBasedKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSourceStorage.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Labels: priority:critical

#4832 [HUDI-3442]Duplicate code calls for 'FlinkOptions.flatOptions'
  hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunction.java
Labels: priority:minor

#4712 [HUDI-2809] Introduce a checksum mechanism for validating hoodie.properties
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRepairsCommand.java
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToThreeDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToFourUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
  hudi-client/hudi-spark-client/pom.xml
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
  hudi-common/src/main/java/org/apache/hudi/common/util/BinaryUtil.java
  hudi-common/src/main/java/org/apache/hudi/common/util/SpillableMapUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java
  hudi-common/src/test/java/org/apache/hudi/common/properties/TestTypedProperties.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-integ-test/pom.xml
  pom.xml
Labels: priority:blocker

#4823 [HUDI-3438] Avoid getSmallFiles if hoodie.parquet.small.file.limit is 0
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkUpsertDeltaCommitPartitioner.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/WriteProfile.java
Labels: priority:major

#4854 [HUDI-3458] Fix BulkInsertPartitioner generic type
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseBulkInsertHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaBulkInsertHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaBulkInsertPreppedCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBulkInsertCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBulkInsertHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBulkInsertPreppedCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkBulkInsertDeltaCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkBulkInsertPreppedDeltaCommitActionExecutor.java
Labels: priority:critical

#4715 [HUDI-1273] Adding savepoint and restore docs to website
  website/docs/disaster_recovery.md
  website/sidebars.js
Labels: priority:critical

#3964 [HUDI-2732][RFC-38] Spark Datasource V2 Integration
  rfc/README.md
  rfc/rfc-38/1.png
  rfc/rfc-38/rfc-38.md
Labels: rfc

#3646 [HUDI-349]: Added new cleaning policy based on number of hours
  hudi-cli/src/main/java/org/apache/hudi/cli/utils/CommitUtil.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCleaningPolicy.java
Labels: priority:critical

#4815 [HUDI-3423] upgrade spark to 3.2.1
  README.md
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieSqlBase.scala
  pom.xml
Labels: priority:critical

#4212 [HUDI-2925] Fix duplicate cleaning of same files when unfinished clean operations are present.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
Labels: priority:critical, priority:major

#4535 [HUDI-3161] Add Call Produce Command for Spark SQL
  hudi-spark-datasource/hudi-spark/src/main/antlr4/org/apache/hudi/spark/sql/parser/HoodieSqlCommon.g4
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Call.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CallProcedureHoodieCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/Procedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ProcedureArgs.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ProcedureBuilder.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ProcedureParameter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ProcedureParameterImpl.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RollbackToInstantTimeProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowCommitsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/parser/HoodieSqlCommonAstBuilder.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCallCommandParser.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCallProcedure.scala
  hudi-spark-datasource/hudi-spark3-common/pom.xml
Labels: priority:blocker

#4810 [HUDI-3421]Pending clustering may break AbstractTableFileSystemView#getxxBaseFile()
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: priority:critical

#4919 [HUDI-3521] Fixing kafka key and value serializer value type from class to string
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java
Labels: priority:critical

#4840 [HUDI-2917] rollback insert data appended to log file when using Hbase Index
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/WorkloadProfile.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/WorkloadStat.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
Labels: priority:critical

#4920 [HUDI-3528] Fix String convert issue and overwrite putAll method in Typed…
  hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java
  hudi-common/src/test/java/org/apache/hudi/common/properties/TestTypedProperties.java
Labels: priority:critical, on-call-triaged

#4844 [HUDI-3450] Avoid passing empty string spark master to hudi cli
  hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java
  hudi-cli/src/test/java/org/apache/hudi/cli/testutils/SparkUtilTest.java
Labels: priority:minor
