Repository apache/hudi, pull requests merged in 2022-03, with the labels that each got.

#4902 [HUDI-3497] Adding Datatable validator tool
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDataTableUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDataTableValidator.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieRepairTool.java
Labels: priority:critical

#4922 [HUDI-3441] Add support for "marker delete" in hudi-cli
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/MarkersCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestMarkersCommand.java
Labels: priority:blocker

#4679 [HUDI-3315] RFC-35 Part-1 Support bucket index in Flink writer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink/src/main/java/org/apache/hudi/sink/BucketStreamWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/BucketStreamWriteOperator.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
  hudi-flink/src/test/java/org/apache/hudi/sink/StreamWriteITCase.java
  hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: rfc

#4779 [HUDI-3264]: made schema registry urls configurable with MTDS
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/resources/delta-streamer-config/short_trip_uber_config.properties
  hudi-utilities/src/test/resources/delta-streamer-config/uber_config.properties
Labels: priority:major

#4728 [HUDI-2973] RFC-27: Data skipping index to improve query performance
  rfc/rfc-27/rfc-27.md
Labels: rfc

#4941 [HUDI-3544] Fixing "populate meta fields" update to metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Labels: priority:blocker

#4905 [HUDI-3548] Fix if user specify key "hoodie.datasource.clustering.async.enable" directly, async clustering not work
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java
Labels: clustering, on-call-triaged

#4607 [HUDI-3161][RFC-47] Add Call Produce Command for Spark SQL
  rfc/README.md
  rfc/rfc-46/rfc-46.md
  rfc/rfc-47/process.png
  rfc/rfc-47/rfc-47.md
Labels: rfc

#4911 [HUDI-3460] Add reader merge memory option for flink
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
  hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
  hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
  hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
Labels: flink

#4812 [HUDI-2761] Fixing timeline server for repeated refreshes
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
Labels: priority:critical

#4468 [HUDI-3130] Fixing Hive getSchema for RT tables addressing different partitions having different schemas
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-common/src/test/resources/simple-test-evolved-compatible.avsc
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/functional/TestHoodieCombineHiveInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
Labels: priority:critical, on-call-triaged

#4921 [HUDI-3520] Introduce DeleteSupportSchemaPostProcessor to support adding _hoodie_is_deleted column to schema
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/DeleteSupportSchemaPostProcessor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SparkAvroPostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/DummySchemaProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/SparkAvroSchemaProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
Labels: priority:major

#4930 [HUDI-3525] Introduce JsonkafkaSourcePostProcessor to support data post process before it is transformed to DataSet
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieSourcePostProcessException.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/processor/JsonKafkaSourcePostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSourcePostProcessor.java
Labels: priority:minor

#4932 [HUDI-3069] Improve HoodieMergedLogRecordScanner avoid putting unnecessary hoodie records
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
Labels: priority:minor

#4811 [HUDI-3213] Making commit preserve metadata to true for compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java
  hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/DefaultSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: priority:critical, writer-core, compaction

#4739 [HUDI-3365] Make sure Metadata Table records are updated appropriately on HDFS
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/upgrade/JavaUpgradeDowngradeHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/SparkRDDWriteClientOverride.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
Labels: priority:blocker

#4973 [HUDI-3576] Configuring timeline refreshes based on latest commit
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
Labels: on-call-triaged

#4961 [HUDI-2677] Add DFS based message queue for flink writer[part3]
  hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
  hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
  hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMessage.java
  hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
  hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
  hudi-flink/src/test/java/org/apache/hudi/sink/meta/TestCkpMetadata.java
Labels: flink

#4970 [HUDI-3574] Improve maven module configs for different spark profiles
  .github/workflows/bot.yml
  hudi-spark-datasource/pom.xml
  pom.xml
Labels: priority:major, on-call-triaged

#4986 [HUDI-3584] Skip integ test modules by default
  pom.xml
Labels: priority:major, on-call-triaged

#4848 [HUDI-3258] HoodieData for metadata index records, bloom and colstats init
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLookupHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkWriteableTestTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/HoodieMetadataBloomIndexCheckFunction.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieGlobalBloomIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkWriteableTestTable.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieDeltaWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataRecordsGenerationParams.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: big-needle-movers

#4991 [HUDI-3587] Making SupportsUpgradeDowngrade serializable
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SupportsUpgradeDowngrade.java
Labels: priority:critical, on-call-triaged

#4968 [HUDI-3568] Introduce ChainedSchemaPostProcessor to support setting multi processors at once
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/exception/HoodieSchemaPostProcessException.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/ChainedSchemaPostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/DummySchemaPostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
Labels: priority:minor

#5002 [HUDI-3595] Fixing NULL schema provider for empty batch
  hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestParquetDFSSourceEmptyBatch.java
Labels: priority:critical

#4972 [HUDI-3522] Introduce DropColumnSchemaPostProcessor to support drop columns from schema
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/DropColumnSchemaPostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestSchemaPostProcessor.java
Labels: priority:minor

#4326 [HUDI-2999] [RFC-42] RFC for consistent hashing index
  rfc/rfc-42/basic_bucket_hashing.png
  rfc/rfc-42/bucket_resizing.png
  rfc/rfc-42/bucket_resizing_virtual_log_file.png
  rfc/rfc-42/consistent_hashing.png
  rfc/rfc-42/rfc-42.md
Labels: rfc

#4926 [HUDI-3566]add thread factory in BoundedInMemoryExecutor
  hudi-common/src/main/java/org/apache/hudi/common/util/CustomizedThreadFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryExecutor.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestCustomizedThreadFactory.java
Labels: priority:major

#5015 [HUDI-3513] Make sure Column Stats does not fail in case it fails to load previous Index Table state
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/columnstats/ColumnStatsIndexHelper.java
Labels: priority:critical, on-call-triaged

#4999 [HUDI-3592] Fix NPE of DefaultHoodieRecordPayload if Property is empty
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestDefaultHoodieRecordPayload.java
Labels: priority:critical

#4969 [HUDI-3569] Introduce ChainedJsonKafkaSourePostProcessor to support setting multi processors at one time
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/processor/ChainedJsonKafkaSourcePostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSourcePostProcessor.java
Labels: priority:minor

#4971 [HUDI-3556] Re-use rollback instant for rolling back of clustering and compaction if rollback failed mid-way
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
Labels: priority:blocker, on-call-triaged

#5013 [HUDI-3593] Restore TypedProperties and flush checksum in table config
  hudi-common/src/main/java/org/apache/hudi/common/config/OrderedProperties.java
  hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/properties/TestOrderedProperties.java
  hudi-common/src/test/java/org/apache/hudi/common/properties/TestTypedProperties.java
Labels: priority:critical

#5039 [HUDI-3621] Fixing NullPointerException in DeltaStreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: priority:critical, on-call-triaged

#5040 [HUDI-3623] Removing hive sync node from non hive yamls
  docker/demo/config/test-suite/cow-spark-long-running.yaml
  docker/demo/config/test-suite/cow-spark-simple.yaml
  docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions-metadata.yaml
  docker/demo/config/test-suite/deltastreamer-long-running-multi-partitions.yaml
  docker/demo/config/test-suite/deltastreamer-medium-full-dataset-validation.yaml
  docker/demo/config/test-suite/detlastreamer-long-running-example.yaml
  docker/demo/config/test-suite/insert-overwrite-table.yaml
  docker/demo/config/test-suite/insert-overwrite.yaml
  docker/demo/config/test-suite/simple-clustering.yaml
  docker/demo/config/test-suite/simple-deltastreamer.yaml
  docker/demo/config/test-suite/spark-clustering.yaml
Labels: priority:minor, on-call-triaged

#5038 [HUDI-3620] Adding spark3.2.0 profile
  pom.xml
Labels: priority:critical, on-call-triaged

#5045 [HUDI-3633] Allow non-string values to be set in TypedProperties
  hudi-common/src/main/java/org/apache/hudi/common/config/TypedProperties.java
  hudi-common/src/test/java/org/apache/hudi/common/properties/TestTypedProperties.java
Labels: priority:major

#4995 [HUDI-3589] flink sync hive metadata supports table properties and serde properties
  hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/HiveSyncContext.java
Labels: priority:major, flink

#4997 [HUDI-3588] Remove hudi-common and hudi-hadoop-mr jars in Presto Docker image
  docker/compose/docker-compose_hadoop284_hive233_spark244.yml
  docker/hoodie/hadoop/pom.xml
  docker/hoodie/hadoop/prestobase/Dockerfile
Labels: priority:blocker

#5032 [HUDI-3607] Support backend switch in HoodieFlinkStreamer
  hudi-flink/pom.xml
  hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
  hudi-flink/src/main/java/org/apache/hudi/util/FlinkStateBackendConverter.java
Labels: priority:major, flink

#5006 [DOCS] Redesigned the blog page with grid layout
  website/blog/2021-08-18-improving-marker-mechanism.md
  website/blog/2021-08-23-s3-events-source.md
  website/blog/2021-09-01-building-eb-level-data-lake-using-hudi-at-bytedance.md
  website/blog/2021-12-16-lakehouse-concurrency-control-are-we-too-optimistic.md
  website/blog/2022-01-06-apache-hudi-2021-a-year-in-review.md
  website/blog/2022-01-14-change-data-capture-with-debezium-and-apache-hudi.md
  website/docusaurus.config.js
  website/src/css/custom.css
  website/src/theme/BlogLayout/index.js
  website/src/theme/BlogPostItem/index.js
  website/src/theme/BlogPostItem/styles.module.css
Labels: docs, priority:major

#4994 [Hudi-3376] Add an option to skip under deletion files for HoodieMetadataTableValidator
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: priority:major

#4975 [HUDI-3404] Automatically adjust write configs based on metadata table and write concurrency mode
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
Labels: priority:blocker

#4974 [HUDI-3494] Consider triggering condition of MOR compaction during archival
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CompactionUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java
Labels: priority:blocker

#5028 [HUDI-3645] fix NPE caused by multiple threads accessing non-thread-safe HashMap
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java
Labels: priority:critical

#5049 [HUDI-3598] Row Data to Hoodie Record Operator parallelism needs to always be consistent with input operator for chaining purpose
  hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Labels: flink

#4877 [HUDI-3457] Refactored Spark DataSource Relations to avoid code duplication
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieConversionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeInputFormatUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyViewRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieDataSourceHelper.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileScanRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/HoodieHadoopFSUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/execution/datasources/HoodieInMemoryFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/TestHoodieInMemoryFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Labels: priority:blocker

#5079 [MINOR] Fixing sparkUpdateNode for record generation
  hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkInsertNode.scala
  hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/dag/nodes/SparkUpsertNode.scala
Labels: on-call-triaged

#4385 [HUDI-1436]: provided option to trigger clean every nth commit
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleaningTriggerStrategy.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestHoodieConcatHandle.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: priority:critical, on-call-triaged

#5075 [HUDI-3640] Set SimpleKeyGenerator as default in 2to3 table upgrade for Spark engine
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/TwoToThreeUpgradeHandler.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestTwoToThreeUpgradeHandler.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaSortAndSizeExecutionStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
Labels: priority:blocker

#4175 [HUDI-2883] Refactor hive sync tool / config to use reflection and standardize configs
  docker/demo/sparksql-incremental.commands
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/HiveQueryNode.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/dag/nodes/HiveSyncNode.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/helpers/HiveServiceProvider.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/utils/KafkaConnectUtils.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectTransactionServices.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableDropPartitionCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaApp.java
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaGenerateApp.java
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/DLASyncTool.java
  hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/util/Utils.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/GlobalHiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/GlobalHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-sync/hudi-sync-common/pom.xml
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/AbstractSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestSyncUtilHelpers.java
  hudi-sync/hudi-sync-common/src/test/resources/log4j-surefire-quiet.properties
  hudi-sync/hudi-sync-common/src/test/resources/log4j-surefire.properties
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BootstrapExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java
Labels: priority:blocker

#5108 [HUDI-3697] Fixing non partitioned all files record in MDT
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
Labels: priority:blocker

#5098 [HUDI-3624] Check all instants before starting a commit in metadata table
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
Labels: priority:blocker

#5112 [HUDI-3638] Make ZookeeperBasedLockProvider serializable
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
Labels: priority:blocker

#5004 [HUDI-1180] Upgrade HBase to 2.4.9
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriterFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieOrcReaderWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieReaderWriterBase.java
  hudi-client/hudi-client-common/src/test/resources/hudi_0_10_hbase_1_2_3_bootstrap_index_partitions.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_10_hbase_1_2_3_complex.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_10_hbase_1_2_3_simple.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_11_hbase_2_4_9_bootstrap_index_partitions.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_11_hbase_2_4_9_complex.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_11_hbase_2_4_9_simple.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_9_hbase_1_2_3_bootstrap_index_partitions.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_9_hbase_1_2_3_complex.hfile
  hudi-client/hudi-client-common/src/test/resources/hudi_0_9_hbase_1_2_3_simple.hfile
  hudi-client/hudi-spark-client/pom.xml
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHBaseKVComparator.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileReader.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileUtils.java
  hudi-common/src/main/resources/hbase-site.xml
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemHFileInLining.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-timeline-server-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: priority:blocker

#5088 [HUDI-3678] Fix record rewrite of create handle when 'preserveMetadat…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestUpdateSchemaEvolution.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
Labels: priority:blocker

#4888 [HUDI-3396] Refactoring `MergeOnReadRDD` to avoid duplication, fetch only projected columns
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieDataSourceHelper.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileScanRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieUnsafeRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/HoodieUnsafeRDDUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Labels: priority:blocker

#4821 [HUDI-3435] Do not throw exception when instant to rollback does not …
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: priority:critical

#5027 [HUDI-3612] Should create new TypedProperties when modifying it
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaSortAndSizeExecutionStrategy.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaBulkInsertHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSingleFileSortExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSortAndSizeExecutionStrategy.java
Labels: priority:critical

#5114 [HUDI-3604] Adjust the order of timeline changes in rollbacks
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRollbacksCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/CopyOnWriteRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MergeOnReadRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestCopyOnWriteRollbackActionExecutor.java
Labels: priority:blocker

#5137 [HUDI-3719] High performance costs of AvroSerizlizer in DataSource wr…
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/hudi/benchmark/HoodieBenchmark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/hudi/benchmark/HoodieBenchmarkBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/hudi/benchmark/HoodieBenchmarks.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/AvroSerDerBenchmark.scala
Labels: priority:critical

#5076 [HUDI-2757] Implement Hudi AWS Glue sync
  hudi-aws/pom.xml
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AwsGlueCatalogSyncTool.java
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/HoodieGlueSyncException.java
  hudi-aws/src/main/java/org/apache/hudi/aws/utils/S3Utils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/MapUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestCollectionUtils.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectTransactionServices.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/DLASyncTool.java
  hudi-sync/hudi-dla-sync/src/main/java/org/apache/hudi/dla/HoodieDLAClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/AbstractHiveSyncHoodieClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncException.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/DDLExecutor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/GlobalHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/AbstractSyncHoodieClient.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/model/Partition.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/TableUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Labels: aws-support, priority:blocker

#4967 [HUDI-3736] Fix default dynamodblock url default value
  hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
Labels: priority:critical

#4955 [HUDI-3549] Removing dependency on "spark-avro"
  README.md
  docker/demo/config/test-suite/templates/spark_command.txt.template
  hudi-cli/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-spark-client/pom.xml
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/avro/HoodieAvroSchemaConverters.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-examples/bin/hudi-delta-streamer
  hudi-examples/hudi-examples-spark/pom.xml
  hudi-integ-test/README.md
  hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestBase.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/command/ITTestHoodieSyncCommand.java
  hudi-spark-datasource/hudi-spark-common/pom.xml
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/avro/HoodieSparkAvroSchemaConverters.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/avro/SchemaConverters.scala
  hudi-spark-datasource/hudi-spark/pom.xml
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionCodeGen.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/index/bucket/TestBucketIdentifier.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/KeyGeneratorTestUtilities.java
  hudi-spark-datasource/hudi-spark2/pom.xml
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/HoodieSpark2_4AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/HoodieSpark2_4AvroSerializer.scala
  hudi-spark-datasource/hudi-spark3-common/pom.xml
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_1Adapter.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroUtils.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/HoodieSpark3_1AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/HoodieSpark3_1AvroSerializer.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/adapter/Spark3_2Adapter.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/avro/AvroUtils.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/avro/HoodieSpark3_2AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3/src/main/scala/org/apache/spark/sql/avro/HoodieSpark3_2AvroSerializer.scala
  hudi-utilities/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieDataTableValidator.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieRepairTool.java
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: priority:blocker

#5155 [HUDI-3536] Add hudi-datahub-sync implementation
  hudi-sync/hudi-datahub-sync/pom.xml
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/HoodieDataHubSyncException.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubEmitterSupplier.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestDataHubSyncConfig.java
  hudi-sync/hudi-datahub-sync/src/test/resources/log4j-surefire-quiet.properties
  hudi-sync/hudi-datahub-sync/src/test/resources/log4j-surefire.properties
  hudi-sync/pom.xml
  packaging/hudi-datahub-sync-bundle/pom.xml
  packaging/hudi-datahub-sync-bundle/src/main/java/org/apache/hudi/datahub/bundle/Main.java
  pom.xml
Labels: priority:blocker

#5167 [HUDI-3736] Fix null pointer when key not specified
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
Labels: priority:blocker

#4962 [HUDI-3355] Issue with out of order commits in the timeline when ingestion writers using SparkAllowUpdateStrategy
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: priority:blocker, on-call-triaged

#5171 [HUDI-3681] Provision additional hudi-spark-bundle with different versions
  .github/workflows/bot.yml
  README.md
  pom.xml
Labels: priority:blocker

#5183 [MINOR] Fixing flakiness in TestHoodieSparkMergeOnReadTableRollback.testRollbackWithDeltaAndCompactionCommit
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
Labels: priority:blocker

#5134 [HUDI-3750] Fix NPE when build HoodieFileIndex
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
Labels: priority:blocker

#5173 [HUDI-3721] Delete MDT if necessary when trigger rollback to savepoint
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestSavepointsCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
Labels: priority:blocker

#5138 [HUDI-3713] Guarding archival for multi-writer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Labels: priority:blocker

#5110 [HUDI-3692] Fix lost log writes during async compaction when using metadata table
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
Labels: priority:blocker

#5158 [HUDI-3733] Adding HoodieFailedWritesCleaningPolicy for restore with hudi-cli
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SavepointsCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
Labels: priority:blocker

#5157 [HUDI-3732] Fixing rollback validation
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Labels: priority:blocker

#5168 [HUDI-3729][SPARK] fixed the per regression by enable vectorizeReader for parquet file
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/hudi/benchmark/HoodieBenchmarkBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/CowTableReadBenchmark.scala
Labels: priority:blocker

#4693 [HUDI-2488][HUDI-3175] Implement async metadata indexing
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToThreeDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToFourUpgradeHandler.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-common/pom.xml
  hudi-common/src/main/avro/HoodieArchivedMetaEntry.avsc
  hudi-common/src/main/avro/HoodieIndexCommitMetadata.avsc
  hudi-common/src/main/avro/HoodieIndexPartitionInfo.avsc
  hudi-common/src/main/avro/HoodieIndexPlan.avsc
  hudi-common/src/main/java/org/apache/hudi/common/bloom/SimpleBloomFilter.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataRecordsGenerationParams.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/resources/delta-streamer-config/indexer.properties
Labels: priority:blocker
