Repository apache/hudi, pull requests merged in 2022-12, with the labels that each got.

#7346 [HUDI-5304] Disabling spark-sql core flow tests to unblock CI
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
Labels: priority:blocker

#7293 Update query_engine_setup.md
  website/versioned_docs/version-0.12.1/query_engine_setup.md
Labels: docs

#7326 [HUDI-5294] Support type change for schema on read + reconcile schema
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
Labels: schema-and-data-types, priority:blocker, release-0.12.2

#7238 [HUDI-5023] Cleaning up `QueueBasedExecutor` impls
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/CopyOnWriteInsertHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/bootstrap/BootstrapRecordConsumer.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseMergeHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/QueueBasedExecutorFactory.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/execution/ExplicitWriteHandler.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/execution/FlinkLazyInsertIterable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/execution/JavaLazyInsertIterable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/SparkLazyInsertIterable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestBoundedInMemoryExecutorInSpark.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestBoundedInMemoryQueue.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorExecutionInSpark.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ParquetReaderIterator.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/BaseHoodieQueueBasedExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryQueue.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/DisruptorExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/DisruptorMessageQueue.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/FunctionBasedQueueProducer.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/HoodieConsumer.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/HoodieExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/HoodieExecutorBase.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/HoodieIterableMessageQueue.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/HoodieMessageQueue.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/HoodieProducer.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/IteratorBasedQueueConsumer.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/IteratorBasedQueueProducer.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeUnmergedRecordReader.java
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
Labels: priority:critical, writer-core

#7215 [MINOR] Fix locale specific NumberFormatException in testutils …
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
Labels: priority:major, release-0.12.2

#7389 [HUDI-5334] Fix checkpoint reading for structured streaming
  hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
Labels: priority:major, release-0.12.2

#7320 [HUDI-5290] remove the lock in #writeTableMetadata
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: priority:critical, flink, metadata, release-0.12.2

#6505 [HUDI-4764] AWS GlueSync turn partition already exist error into warning
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: meta-sync, aws-support, priority:major, release-0.12.2

#6077 [DOCS] sql-client.execution.result-mode = tableau
  website/docs/flink-quick-start-guide.md
Labels: docs, flink

#7140 [HUDI-5163] Fixing failure handling with spark datasource write
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableDropPartitionCommand.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/TruncateHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
Labels: priority:blocker, spark, writer-core, release-0.12.2

#6960 fix(sec): upgrade com.google.protobuf:protobuf-java to 3.16.1
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
Labels: dependencies, priority:minor, release-0.12.2

#7395 [HUDI-5347] FIxing performance traps in Spark SQL `MERGE INTO` implementation
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/sql/IExpressionEvaluator.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/payload/SqlTypedRecord.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionCodeGen.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
Labels: priority:blocker, release-0.12.2

#7349 [HUDI-5291] Fixing NPE in MOR column stats accounting
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/cow-updated2-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/mor-updated2-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/update-input-table-json/part-00000-7e680484-e7e1-48b6-8289-1a7c483b530b-c000.json
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Labels: priority:critical, index, metadata, release-0.12.2

#7370 [HUDI-5346][HUDI-5320] Fixing Create Table as Select (CTAS) performance gaps
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieUnsafeUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala
Labels: priority:blocker, release-0.12.2

#7408 [HUDI-5350] Fix oom cause compaction event lost problem
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/NonThrownExecutor.java
Labels: priority:blocker, flink, table-service

#6725 [HUDI-4881] Push down filters if possible when syncing partitions to Hive
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/expression/AttributeReferenceExpression.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/expression/BinaryOperator.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/expression/Expression.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/expression/ExpressionVisitor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/expression/LeafExpression.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/expression/Literal.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/FilterGenVisitor.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/HiveSchemaUtil.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/PartitionFilterGenerator.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/util/TestPartitionFilterGenerator.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
Labels: performance, meta-sync, priority:major

#7402 [HUDI-5342] Add new bulk insert sort modes repartitioning data by partition path
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertSortMode.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertInternalPartitionerFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertInternalPartitionerWithRowsFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRDDPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionAndSortPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionAndSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitionerForRows.java
  hudi-common/src/main/java/org/apache/hudi/common/function/SerializableFunctionUnchecked.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:blocker, writer-core, release-0.12.2

#7396 [HUDI-5338] Adjust coalesce behavior within NONE sort mode for bulk insert
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BulkInsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertInternalPartitionerFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertInternalPartitionerWithRowsFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/NonSortPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/NonSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitionerForRows.java
Labels: priority:blocker, writer-core, release-0.12.2

#7424 [HUDI-5347] Cleaned up transient state from `ExpressionPayload` making it non-serializable
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/catalyst/expressions/SafeProjection.scala
Labels: priority:blocker, release-0.12.2

#7236 [HUDI-5372] Fix the npe caused by alter table add column.
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddColumnsCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTable.scala
Labels: priority:blocker, release-0.12.2

#7360 [MINOR] Fix Out of Bounds Exception for DayBasedCompactionStrategy
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/DayBasedCompactionStrategy.java
Labels: priority:blocker, release-0.12.2

#7412 [HUDI-5353] Close file readers
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseMergeHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobExecutionStrategy.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/InputSplitUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeRecordReaderUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: priority:blocker, release-0.12.2

#7037 [HUDI-5078] Fixing determination of table service for metadata calls
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkMergeOnReadTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Labels: priority:critical, metadata, release-0.12.2

#7421 [HUDI-5296] Allow disable schema on read after enabling
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
Labels: priority:blocker, release-0.12.2

#7436 [HUDI-5348] Cache file slices in HoodieBackedTableMetadata
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: priority:blocker, metadata, release-0.12.2

#6793 [HUDI-4917] Optimized the way to get HoodieBaseFile of loadColumnRangesFromFiles of Bloom Index
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieRangeInfoHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieReadHandle.java
Labels: performance, priority:critical, index, release-0.12.2

#7411 [HUDI-5351] Handle populateMetaFields when repartitioning in sort partitioner
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertInternalPartitionerFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BulkInsertInternalPartitionerWithRowsFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/GlobalSortPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/GlobalSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionAndSortPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionAndSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionPathRepartitionPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/PartitionSortPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDPartitionSortPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestBulkInsertInternalPartitionerForRows.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:blocker, writer-core, release-0.12.2

#7442 [DOCS] Update community sync schedule and fix broken links
  website/docusaurus.config.js
  website/static/assets/images/upcoming-community-calls.png
Labels: docs

#5610 [HUDI-4113] Fix cannot parse <null> schema when use spark delete sql
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
Labels: priority:major, writer-core, release-0.12.2

#7437 [HUDI-5366] Closing metadata writer from within writeClient
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
Labels: priority:blocker, release-0.12.2

#7366 [HUDI-5318] Fix partition pruning for clustering scheduling
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestPartitionAwareClusteringPlanStrategy.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: priority:critical, release-0.12.2

#7450 [HUDI-5375] Fixing reusing file readers with Metadata reader within FileIndex
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
Labels: priority:blocker

#7265 [HUDI-5251] Split GitHub actions CI by spark and flink
  .github/workflows/bot.yml
  hudi-examples/hudi-examples-flink/pom.xml
  hudi-flink-datasource/hudi-flink/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  pom.xml
Labels: dependencies, priority:blocker, flink

#7174 [HUDI-5023] Consuming records from Iterator directly instead of using inner message queue
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/ExecutorFactory.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/execution/FlinkLazyInsertIterable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/execution/JavaLazyInsertIterable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/SparkLazyInsertIterable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestSimpleExecutionInSpark.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/BaseHoodieQueueBasedExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/ExecutorType.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/HoodieExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/SimpleHoodieExecutor.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/BoundInMemoryExecutorBenchmark.scala
Labels: priority:critical, release-0.12.2

#7458 [HUDI-5390] Docker Demo only works on master for m1 macs but site does not mention this
  website/docs/docker_demo.md
  website/versioned_docs/version-0.12.0/docker_demo.md
  website/versioned_docs/version-0.12.1/docker_demo.md
Labels: docs

#7069 [HUDI-5097] Fix partition reading without partition fields table config
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
Labels: priority:blocker, release-0.12.2

#7088 [HUDI-5104] Add feature flag to disable HoodieFileIndex and fall back to HoodieROTablePathFilter
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkConfUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Labels: priority:major, spark, release-0.12.2

#7419 [HUDI-5357] Optimize deployment of release artifacts
  scripts/release/deploy_staging_jars.sh
Labels: pr:wip, dependencies, priority:blocker, release-0.12.2

#7488 [HUDI-5403] Turn off metadata-table-based file listing in BaseHoodieTableFileIndex
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieSanity.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkConfUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
Labels: aws-support, priority:blocker, query-engine, release-0.12.2

#7493 [HUDI-5409] Avoid file index and use fs view cache in COW input format
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
Labels: priority:blocker, release-0.12.2

#7497 [HUDI-5412] Send the boostrap event if the JM also rebooted
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
Labels: priority:blocker, flink-sql

#7501 [HUDI-5357] Fix release build commands
  scripts/release/deploy_staging_jars.sh
  scripts/release/validate_staged_bundles.sh
Labels: priority:blocker, release-0.12.2

#7504 [HUDI-5399] Flink mor table streaming read throws NPE
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
Labels: flink

#7500 [HUDI-5404] Add flink bundle validation
  .github/workflows/bot.yml
  packaging/bundle-validation/Dockerfile
  packaging/bundle-validation/Dockerfile-base
  packaging/bundle-validation/ci_run.sh
  packaging/bundle-validation/flink/compact.sh
  packaging/bundle-validation/flink/insert.sql
  packaging/bundle-validation/validate.sh
Labels: priority:major, flink

#7224 [HUDI-5182] Create Hudi CLI Bundle
  packaging/hudi-cli-bundle/conf/hudi-env.sh
  packaging/hudi-cli-bundle/conf/log4j2.properties
  packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh
  packaging/hudi-cli-bundle/pom.xml
  packaging/hudi-cli-bundle/src/main/java/org/apache/hudi/cli/bundle/Main.java
  pom.xml
Labels: priority:blocker, cli

#7516 New blog 12 19
  website/blog/2022-12-19-Build-Your-First-Hudi-Lakehouse-with-AWS-Glue-and-AWS-S3.md
  website/static/assets/images/blog/DataCouncil.jpg
  website/static/assets/images/blog/build-your-first-hudi-lakehouse-12-19-diagram.jpg
Labels: docs

#7534 [DOCS] Add videos page for tracking all guides, tutorials and hands o…
  website/blog/2022-11-22-Build-your-Apache-Hudi-data-lake-on-AWS-using-Amazon-EMR-Part-1.mdx
  website/docusaurus.config.js
  website/src/pages/videos.md
  website/static/assets/images/2022-11-22-aws_hudi_best_practices_part1.jpeg
  website/static/assets/images/blog/2022-11-22-aws_hudi_best_practices_part1.png
Labels: docs

#7540 [HUDI-5456] Flink streaming read skips uncommitted instants
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
Labels: flink

#7526 Revert "[HUDI-5409] Avoid file index and use fs view cache in COW input format (#7493)"
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
Labels: priority:blocker, query-engine

#7480 [HUDI-5400] Fix read issues when Hudi-FULL schema evolution is not enabled
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieParquetFileFormatHelper.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/spark/sql/execution/datasources/parquet/Spark24HoodieVectorizedParquetRecordReader.java
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark24HoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31HoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32PlusHoodieParquetFileFormat.scala
Labels: schema-and-data-types, priority:critical, writer-core

#7527 [HUDI-5411] Avoid virtual key info for COW table in the input format
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
Labels: priority:blocker, query-engine

#7521 [HUDI-4827] Rebase Azure Image on Ubuntu 22.04 - scalatest-maven-plugin version update
  azure-pipelines.yml
  pom.xml
Labels: priority:blocker

#7560 [HUDI-5476] Fix utilities test failure with zookeeper
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestZookeeperBasedLockProvider.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestDFSHoodieTestSuiteWriterAdapter.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/TestFileDeltaInputWriter.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/job/TestHoodieTestSuiteJob.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSAvroDeltaInputReader.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/testsuite/reader/TestDFSHoodieDatasetInputReader.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-utilities/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/multisync/TestMultipleMetaSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestAbstractDebeziumSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractCloudObjectsSourceTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlFileBasedTransformer.java
  hudi-utilities/src/test/resources/delta-streamer-config/short_trip_uber_config.properties
Labels: priority:blocker

#7569 [DOCS] Add aws module dependency for config generation and update new configs
  hudi-utils/pom.xml
  website/docs/configurations.md
Labels: docs

#7578 [HUDI-5486][DOCS] Update 0.12.x release notes with Long Term Support
  website/releases/download.md
  website/releases/release-0.12.0.md
  website/releases/release-0.12.1.md
  website/releases/release-0.12.2.md
Labels: docs

#7517 [HUDI-5420] Fix metadata table validator to exclude uncommitted log files due to retry
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: priority:critical, metadata
