Repository apache/hudi, pull requests merged in 2022-08, with the labels that each got.

#6272 [HUDI-4518] Free lock if allocated but not acquired
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
Labels: priority:critical, multi-writer

#6239 [HUDI-4501] Throwing exception when restore is attempted with hoodie.arhive.beyond.savepoint is enabled
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: priority:blocker

#6265 [HUDI-4516] fix Task not serializable error when run HoodieCleaner after one failure
  hudi-common/src/main/java/org/apache/hudi/common/util/DefaultSizeEstimator.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordSizeEstimator.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDBBasedMap.java
Labels: priority:blocker

#6286 [HUDI-4298] Mor table reading for base and log files lost sequence of events
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
Labels: priority:blocker

#6279 [HUDI-4525] Fixing Spark 3.3 `AvroSerializer` implementation
  .github/workflows/bot.yml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestConvertFilterToCatalystExpression.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroSerializer.scala
Labels: priority:blocker

#6292 [HUDI-4531] Wrong partition path for flink hive catalog when the part…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HiveSchemaUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/TableOptionProperties.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: priority:blocker

#6306 [HUDI-4545] Do not modify the current record directly for OverwriteNo…
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteNonDefaultsWithLatestAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestOverwriteNonDefaultsWithLatestAvroPayload.java
Labels: priority:blocker

#6280 [HUDI-4470] Remove spark dataPrefetch disabled prop in DefaultSource
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Labels: priority:blocker, spark

#6317 [HUDI-4540] Cover different table types in functional tests of Spark structured streaming
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
Labels: priority:blocker

#6310 [HUDI-4474] Fix inferring props for meta sync
  docker/demo/config/hoodie-incr.properties
  hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: priority:blocker

#6313 [HUDI-4550] Fallback to listing based rollback for completed instant
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/CopyOnWriteRestoreActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/MergeOnReadRestoreActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/CopyOnWriteRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MergeOnReadRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestClientRollback.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
Labels: priority:blocker, on-call-triaged

#6248 [HUDI-4303] Adding 4 to 5 upgrade handler to check for old deprecated "default" partition value
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FiveToFourDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToFiveUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
  hudi-common/src/main/java/org/apache/hudi/common/util/PartitionPathEncodeUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
Labels: priority:blocker

#6296 [HUDI-4534] Fixing upgrade to reload Metaclient for deltastreamer writes
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Labels: priority:blocker

#6266 [HUDI-4517] If no marker type file, fallback to timeline based marker
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/MarkerBasedRollbackUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/util/MarkerUtils.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerDirState.java
Labels: priority:blocker, on-call-triaged

#5884 [HUDI-3669] Add a remote request retry mechanism for 'Remotehoodietablefiles…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/RetryHelper.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
Labels: priority:blocker, writer-core

#6254 [HUDI-4508] Repair the exception when reading optimized query for mor in hive and presto/trino
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
Labels: priority:blocker

#6311 [HUDI-4548] Unpack the column max/min to string instead of Utf8 for M…
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: priority:blocker, writer-core, metadata

#6327 [HUDI-4568] Shade dropwizard metrics-core in hudi-aws-bundle
  packaging/hudi-aws-bundle/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
Labels: dependencies, priority:blocker

#6331 [HUDI-4572] fix 'Not a valid schema field: ts' error in HoodieFlinkCompactor, if …
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
Labels: priority:blocker

#6329 [HUDI-4570] Fix hive sync path error due to reuse of storage descript…
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/HMSDDLExecutor.java
Labels: priority:blocker, hive

#6333 [HUDI-4571] Fix partition extractor infer function when partition field mismatch
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/replication/TestHiveSyncGlobalCommitTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/TestHoodieSyncConfig.java
Labels: priority:blocker, configs

#6339 [MINOR] Fix wrong key to determine sync sql cascade
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/QueryBasedDDLExecutor.java
Labels: priority:blocker

#6318 [HUDI-4577] Adding test coverage for `DELETE FROM`, Spark Quickstart guide
  hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/quickstart/HoodieSparkQuickstart.java
  hudi-examples/hudi-examples-spark/src/test/java/org/apache/hudi/examples/quickstart/TestHoodieSparkQuickstart.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteFromTable.scala
  hudi-utilities/src/test/resources/hive-site.xml
Labels: spark-sql

#6319 [HUDI-4556] Improve functional test coverage of column stats index
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/cow-updated2-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/mor-updated2-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/update-input-table-json/part-00000-7e680484-e7e1-48b6-8289-1a7c483b530b-c000.json
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Labels: priority:blocker, metadata

#6320 [HUDI-4558] lost 'hoodie.table.keygenerator.class' in hoodie.properties
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java
Labels: priority:blocker

#6246 [HUDI-4543] Support natural order when table schema contains a field named 'ts'
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: flink

#6356 [HUDI-4590] Add hudi-aws dependency to hudi-flink-bundle.
  packaging/hudi-flink-bundle/pom.xml
Labels: priority:blocker

#6334 [HUDI-4576][DOCS] Fix schema evolution docs
  website/docs/schema_evolution.md
  website/versioned_docs/version-0.11.0/schema_evolution.md
  website/versioned_docs/version-0.11.1/schema_evolution.md
Labels: docs

#6228 [HUDI-4488] Improve S3EventsHoodieIncrSource efficiency
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
Labels: priority:blocker

#6369 [HUDI-4611] optimized code in the class of HoodieFlinkStreamer
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
Labels: priority:minor

#6359 [HUDI-4564] Update docs for Spark 3.3 support
  website/docs/quick-start-guide.md
Labels: docs

#6394 [DOCS] Update slack invite link due to rate limit on prev invite link
  website/blog/2021-12-16-lakehouse-concurrency-control-are-we-too-optimistic.md
  website/blog/2022-01-06-apache-hudi-2021-a-year-in-review.md
  website/blog/2022-01-14-change-data-capture-with-debezium-and-apache-hudi.md
  website/community/get-involved.md
  website/docs/overview.md
  website/docusaurus.config.js
  website/i18n/cn/docusaurus-plugin-content-pages/get-involved.md
  website/i18n/cn/docusaurus-theme-classic/footer.json
  website/sidebars.js
  website/sidebarsCommunity.js
  website/sidebarsContribute.js
  website/src/pages/powered-by.md
  website/versioned_docs/version-0.10.0/overview.md
  website/versioned_docs/version-0.10.1/overview.md
  website/versioned_docs/version-0.11.0/overview.md
  website/versioned_docs/version-0.11.1/overview.md
  website/versioned_sidebars/version-0.10.0-sidebars.json
  website/versioned_sidebars/version-0.10.1-sidebars.json
  website/versioned_sidebars/version-0.11.0-sidebars.json
  website/versioned_sidebars/version-0.11.1-sidebars.json
  website/versioned_sidebars/version-0.9.0-sidebars.json
Labels: pr:wip

#6376 [HUDI-4579] Add docs on upgrading and downgrading table through CLI
  website/docs/cli.md
Labels: docs

#6374 [HUDI-4608] Fix upgrade command in Hudi CLI
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUpgradeDowngradeCommand.java
Labels: priority:critical, cli

#6402 [HUDI-4580][DOCS] Update docs of Spark SQL create table statement
  website/docs/quick-start-guide.md
  website/docs/table_management.md
  website/versioned_docs/version-0.11.0/quick-start-guide.md
  website/versioned_docs/version-0.11.0/table_management.md
  website/versioned_docs/version-0.11.1/quick-start-guide.md
  website/versioned_docs/version-0.11.1/table_management.md
Labels: docs

#6370 [HUDI-4565][HUDI-4307][HUDI-3013] Updated docs for presto-hudi integration
  website/docs/query_engine_setup.md
Labels: docs

#6381 [HUDI-4566] Document configuration updates
  hudi-utils/README.md
  hudi-utils/generate_config.sh
  hudi-utils/pom.xml
  website/docs/basic_configurations.md
  website/docs/configurations.md
  website/docs/writing_data.md
Labels: docs

#6362 [MINOR][DOCS] add tip to schema evolution
  website/docs/schema_evolution.md
  website/versioned_docs/version-0.11.0/schema_evolution.md
  website/versioned_docs/version-0.11.1/schema_evolution.md
Labels: docs

#6027 [HUDI-4354] add --force-empty-sync flag to deltastreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieDeltaStreamer.java
Labels: priority:minor, deltastreamer

#6399 [HUDI-4583][DOCS] Optimal write configs for bulk insert
  website/docs/performance.md
Labels: docs

#6365 [HUDI-4601] Read error from MOR table after compaction with timestamp partitioning
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: flink, reader-core

#6415 [HUDI-4632] Remove the force active property for flink1.14 profile
  pom.xml
Labels: flink

#5139 [HUDI-3579] Add timeline commands in hudi-cli
  hudi-cli/src/main/java/org/apache/hudi/cli/HoodiePrintHelper.java
  hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
  hudi-cli/src/main/java/org/apache/hudi/cli/Table.java
  hudi-cli/src/main/java/org/apache/hudi/cli/TableHeader.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/TimelineCommand.java
Labels: pr:wip, cli

#6457 [MINOR] Add filesystem based lock provider to release note
  website/releases/release-0.12.0.md
Labels: docs

#6351 [HUDI-4584] Cleaning up Spark utilities
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/BuiltinKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/upgrade/SparkUpgradeDowngradeHelper.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/PathUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystExpressionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystPlansUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSource.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestConvertFilterToCatalystExpression.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/util/TestPathUtils.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystExpressionUtils.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: spark

#6352 [HUDI-4584] Fixing `SQLConf` not being propagated to executor
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/SQLConfInjectingRDD.scala
Labels: priority:blocker, spark, spark-sql

#6450 [HUDI-4665] Flipping default for "ignore failed batch" config in streaming sink to false
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java
Labels: priority:critical, spark-streaming

#6501 [HUDI-4721] Revert "[HUDI-3669] Add a remote request retry mechanism for 'RemoteHoodietablefiles… (#5884)"
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/RetryHelper.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
Labels: priority:blocker

#6416 [Stacked on 6386] Fixing `DebeziumSource` to properly commit consumed offsets
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
Labels: priority:critical

#6111 [HUDI-4399][RFC-57] Protobuf support in DeltaStreamer
  rfc/rfc-57/rfc-57.md
Labels: rfc

#6000 [HUDI-4340] fix not parsable text DateTimeParseException in HoodieInstantTimeGenerator.parseDateFromInstantTime
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Labels: priority:major, writer-core

#6521 [DOCS] Update Hudi support versions for Redshift Spectrum in the current doc.
  website/docs/query_engine_setup.md
Labels: docs

#6538 [DOCS][MINOR] Improve spark quick start doc
  website/docs/quick-start-guide.md
  website/versioned_docs/version-0.10.0/quick-start-guide.md
  website/versioned_docs/version-0.10.1/quick-start-guide.md
  website/versioned_docs/version-0.11.0/quick-start-guide.md
  website/versioned_docs/version-0.11.1/quick-start-guide.md
  website/versioned_docs/version-0.12.0/quick-start-guide.md
Labels: docs

#6492 [DOCS] Fix typo in compaction.md
  website/docs/compaction.md
Labels: docs

#6326 [HUDI-4339] Add example configuration for HoodieCleaner in docs
  website/docs/hoodie_cleaner.md
  website/versioned_docs/version-0.11.1/hoodie_cleaner.md
  website/versioned_docs/version-0.12.0/hoodie_cleaner.md
Labels: docs

#6302 [DOCS] Clarification to Docker quickstart demo
  website/docs/docker_demo.md
Labels: docs

#6083 [DOCS] Fix link rendering error in Docker Demo and some other typos
  website/docs/docker_demo.md
  website/docs/quick-start-guide.md
Labels: docs

#6255 [DOCS] Add doc about javax.security.auth.login.LoginException in Hudi KC Sink
  hudi-kafka-connect/README.md
Labels: docs, kafka-connect

#6515 [HUDI-4730] Fix batch job cannot clean old commits files
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java
Labels: priority:major, writer-core, flink

#6541 [HUDI-4740] Add metadata fields for hive catalog #createTable
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HiveSchemaUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: schema-and-data-types, priority:critical, hive

#6534 [HUDI-4695] Fix flaky TestInlineCompaction#testCompactionRetryOnFailureBasedOnTime
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestInlineCompaction.java
Labels: priority:minor

#6535 [HUDI-4193] change protoc version so it compiles on m1 mac
  pom.xml
Labels: dependencies, priority:critical, kafka-connect

#6547 [HUDI-4748][DOCS] Add examples of soft deletes in docs
  website/docs/quick-start-guide.md
  website/docs/writing_data.md
  website/versioned_docs/version-0.10.0/quick-start-guide.md
  website/versioned_docs/version-0.10.0/writing_data.md
  website/versioned_docs/version-0.10.1/quick-start-guide.md
  website/versioned_docs/version-0.10.1/writing_data.md
  website/versioned_docs/version-0.11.0/quick-start-guide.md
  website/versioned_docs/version-0.11.0/writing_data.md
  website/versioned_docs/version-0.11.1/quick-start-guide.md
  website/versioned_docs/version-0.11.1/writing_data.md
  website/versioned_docs/version-0.12.0/quick-start-guide.md
  website/versioned_docs/version-0.12.0/writing_data.md
Labels: docs

#6546 [HUDI-4438] Fix flaky TestCopyOnWriteActionExecutor#testPartitionMetafileFormat
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
Labels: priority:critical

#6542 [MINOR] Fix typo in HoodieArchivalConfig
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieArchivalConfig.java
Labels: docs
