Repository apache/hudi, pull requests merged in 2023-12, with the labels that each got.

#10221 [HUDI-7165] Flink multi writer not close the failed instant heartbeat
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
Labels: priority:critical, release-0.14.1

#10205 [HUDI-7153] Fixing range overflow with kakfa source and spark partition management
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
Labels: priority:critical, release-0.14.1

#10050 [HUDI-7071] Throw exceptions when clustering/index job fail
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
Labels: priority:critical, release-0.14.1

#10198 [HUDI-7154] Fix NPE from empty batch with row writer enabled in Hudi Streamer
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:critical, release-0.14.1

#9630 [HUDI-6822] Fix deletes handling in hbase index when partition path is updated
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordDelegate.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/model/TestHoodieRecordSerialization.scala
Labels: priority:blocker, release-0.14.1, bug-fix

#10226 [HUDI-7166] Provide a Procedure to Calculate Column Stats Overlap Degree
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowColumnStatsOverlapProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
Labels: spark-sql, cli

#10222 [HUDI-7100] Fixing insert overwrite operations with drop dups config
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: priority:critical, release-0.14.1

#10224 [HUDI-6980] Fixing closing of write client on failure scenarios
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
Labels: priority:critical, release-0.14.1

#10240 [MINOR] Fixing view manager reuse with Embedded timeline server
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
Labels: priority:critical, release-0.14.1

#10244 [HUDI-7172] Fix the timeline archiver to support concurrent writer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/ActiveActionWithDetails.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/DummyActiveAction.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/ActiveAction.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
Labels: writer-core

#10144 [HUDI-7125] Fix bugs for CDC queries
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCDCFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodiePartitionCDCFileGroupMapping.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
Labels: release-1.0.0

#9667 [HUDI-6836] Shutting down deltastreamer in tests and shutting down metrics for write client
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, release-0.14.1

#10080 [DOCS] Added video resources to Concepts and Services Sections
  package-lock.json
  website/docs/clustering.md
  website/docs/concurrency_control.md
  website/docs/disaster_recovery.md
  website/docs/file_sizing.md
  website/docs/hoodie_cleaner.md
  website/docs/indexing.md
  website/docs/key_generation.md
  website/docs/markers.md
  website/docs/metadata.md
  website/docs/metadata_indexing.md
  website/docs/migration_guide.md
  website/docs/precommit_validator.md
  website/docs/record_payload.md
  website/docs/rollbacks.md
  website/docs/schema_evolution.md
  website/docs/table_types.md
  website/docs/transforms.md
  website/docs/write_operations.md
  website/videoBlog/2022-11-20-Different_table_types_in_Apache_Hudi_MOR_and_COW_Deep_Dive_By_Sivabalan_Narayanan.md
  website/videoBlog/2022-12-14-Build_Slowly_Changing_Dimensions_Type_2_SCD2_with_Apache_Spark_and_Apache_Hudi_Hands_on_Labs.md
  website/videoBlog/2022-12-28-Comparing_Apache_Hudi_s_MOR_and_COW_Tables_Use_Cases_from_Uber.md
  website/videoBlog/2023-01-12-Build_Real_Time_Streaming_Pipeline_with_Apache_Hudi_Kinesis_and_Flink_Hands_on_Lab.md
  website/videoBlog/2023-01-13-Build_Real_Time_Low_Latency_Streaming_pipeline_from_DynamoDB_to_Apache_Hudi_using_Kinesis_FlinkLab.md
  website/videoBlog/2023-03-18-Push_Hudi_Commit_Notification_TO_HTTP_URI_with_Callback.md
  website/videoBlog/2023-05-07-Maximizing_Efficiency_DataLake_Hudi_Glue_ETL_Jobs_with_Templated_Approach_Serverless_Architecture.md
Labels: docs

#10243 [MINOR] Fixing integ test writer for commit time generation
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieTestSuiteWriter.java
Labels: priority:critical, release-0.14.1

#10260 [MINOR] Fixing streamer props in integ tests
  docker/demo/config/test-suite/test-metadata-aggressive-clean-archival-inline-compact.properties
Labels: priority:critical, release-0.14.1

#10247 [HUDI-7173] Fix hudi-on-flink read issues involving schema evolution …
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
  hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapDecimalVector.java
  hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapDecimalVector.java
  hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapDecimalVector.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapDecimalVector.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapDecimalVector.java
Labels: schema-and-data-types, flink, reader-core

#10162 [HUDI-7136] in the dfs catalog scenario, solve the problem of Primary key definit…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
Labels: priority:critical, release-0.14.1

#10137 [HUDI-7137] Implement Bootstrap for new FG reader
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/common/table/log/CachingIterator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/common/table/log/LogFileIterator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieInternalRowUtils.scala
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieLogFile.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/CachingIterator.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieMergeHandleWithSparkMerger.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestNewHoodieParquetFileFormat.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestQueryMergeOnReadOptimizedTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestHoodieLogFileProcedure.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/HoodieSpark30CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/HoodieSpark34CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/HoodieSpark35CatalystPlanUtils.scala
Labels: release-1.0.0

#8062 [HUDI-5823][RFC-65] RFC for Partition Lifecycle Management
  rfc/rfc-65/rfc-65.md
Labels: rfc

#10157 [HUDI-7135] Spark reads hudi table error when flink creates the table without pre…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: priority:critical, flink, release-0.14.1

#10259 [MINOR] Relaxing required props with defaults
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
Labels: priority:critical, release-0.14.1

#10209 [HUDI-7159]Check the table type between hoodie.properies and table options
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: priority:critical, release-0.14.1

#10292 [HUDI-7206] Fixing auto deletion of mdt
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
Labels: priority:critical, release-0.14.1

#10288 [HUDI-7201] Schema Evolution: use target schema if source is empty
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
Labels: priority:critical, release-0.14.1

#10284 [HUDI-7199] Optimize contains impl with HoodieDefaultTimeline
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
Labels: release-0.14.1

#10153 [HUDI-7023] Support querying without syncing partition metadata to catalog
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/index/TestHoodieIndexUtils.java
  hudi-spark-datasource/hudi-spark/pom.xml
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHiveIncrementalPuller.java
Labels: meta-sync, index, release-1.0.0

#10298 [HUDI-7210] In CleanFunction#open, triggers the cleaning under option 'clean.async.enabled'
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/CleanFunction.java
Labels: usability, release-0.14.1

#10312 [HUDI-7132] Data may be lost for flink task failure
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: priority:blocker, flink, release-0.14.1

#10304 [HUDI-7215] Delete NewHoodieParquetFileFormat
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkFileFormatUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieMergeHandleWithSparkMerger.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapRead.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestNewHoodieParquetFileFormat.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartialUpdateAvroPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
Labels: spark, reader-core, release-1.0.0

#10332 [HUDI-7232] [DOCS] Split FAQ into multiple pages
  website/docs/faq.md
  website/docs/faq_design_and_concepts.md
  website/docs/faq_general.md
  website/docs/faq_integrations.md
  website/docs/faq_querying_tables.md
  website/docs/faq_storage.md
  website/docs/faq_table_services.md
  website/docs/faq_writing_tables.md
  website/docs/quick-start-guide.md
  website/docs/record_payload.md
  website/docs/writing_data.md
  website/sidebars.js
Labels: docs

#10254 [HUDI-7183] Fix static insert overwrite partitions issue
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwriteCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertOverwriteCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: spark-sql

#10307 [HUDI-7223] Cleaner KEEP_LATEST_BY_HOURS should retain latest commit before earliest commit to retain
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/model/CleanFileInfo.java
Labels: priority:blocker, release-0.14.1

#10365 [HUDI-4699] RFC for auto record key generation
  rfc/rfc-76/rfc-76.md
Labels: rfc

#10379 [HUDI-7138] Fix scala typed properties conversion for schema evol
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieConversionUtils.scala
Labels: priority:blocker, release-0.14.1

#10425 [HUDI-7263][BLOG] Hudi 2023 a year in review
  website/blog/2023-12-28-apache-hudi-2023-a-year-in-review.md
  website/static/assets/images/blog/2023-12-28-a-year-in-review-2023/00.cover.png
  website/static/assets/images/blog/2023-12-28-a-year-in-review-2023/01.PR_histogram.png
  website/static/assets/images/blog/2023-12-28-a-year-in-review-2023/02.contentspotlight.png
  website/static/assets/images/blog/2023-12-28-a-year-in-review-2023/03.events.png
Labels: articles
