Repository apache/hudi, pull requests merged in 2023-06, with the labels that each got.

#8850 [HUDI-6290] Fix Flink MDT compaction strategy
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: priority:blocker, metadata

#8795 [HUDI-6258] support olap engine query mor table in table name without ro/rt suffix
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
Labels: meta-sync

#8792 [HUDI-6256] Fix the data table archiving and MDT cleaning config conf…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java
Labels: metadata, table-service, configs

#8867 [HUDI-6307] Sync TIMESTAMP_MILLIS to hive
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/HiveSchemaUtil.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/util/TestHiveSchemaUtil.java
Labels: meta-sync, schema-and-data-types, hive

#8888 [MINOR] Reformat HoodieAvroParquetReader
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/avro/HoodieAvroParquetReader.java
Labels: hive, version-compatibility

#8840 [HUDI-5352] Fix `LocalDate` serialization in colstats
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/util/JsonUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-hive-sync-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-timeline-server-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: priority:critical, metadata

#8910 [HUDI-6342] Fixing flaky Continuous mode multi writer tests
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: priority:critical, release-0.14.0

#8745 [HUDI-6182] Hive sync use state transient time to avoid losing partit…
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-sync/hudi-adb-sync/src/main/java/org/apache/hudi/sync/adb/AdbSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Labels: meta-sync, hive, multi-writer

#8900 [HUDI-6334] Integrate logcompaction table service to metadata table and provides various bugfixes to metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/CompactHelpers.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/HoodieLogCompactionPlanGenerator.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestDataValidationCheckForLogCompactionActions.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieLogCompactException.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: priority:critical, release-0.14.0

#8924 [DOCS]Add new blogs in Hudi website
  website/blog/2022-10-08-what-why-and-how-apache-hudis-bloom-index.mdx
  website/blog/2023-02-12-table-service-deployment-models-in-apache-hudi.mdx
  website/blog/2023-02-19-bulk-insert-sort-modes-with-apache-hudi.mdx
  website/blog/2023-05-12-ingesting-data-to-apache-hudi-using-spark-sql.mdx
  website/blog/2023-05-16-how-zoom-implemented-streaming-log-ingestion-and-efficient-gdpr-deletes-using-apache-hudi-on-amazon-emr.mdx
  website/blog/2023-05-19-hudi-metafields-demystified.mdx
  website/blog/2023-05-29-different-query-types-with-apache-hudi.mdx
  website/blog/2023-06-03-text-based-search-from-elastic-search-to-vector-search.mdx
  website/static/assets/images/blog/2022-10-08-what-why-and-how-apache-hudis-bloom-index.png
  website/static/assets/images/blog/2023-05-16-how-zoom-implemented-streaming-log-ingestion-and-efficient-gdpr-deletes-using-apache-hudi-on-amazon-emr.png
  website/static/assets/images/blog/2023-05-19-Hudi-Metafields-demystified.png
  website/static/assets/images/blog/2023-06-03-text-based-search-from-elastic-search-to-vector-search.png
Labels: docs

#8917 [HUDI-6182] Fix the hive sync compatibility and improve timeline check
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Labels: meta-sync

#8590 [HUDI-3545] [UBER] Make HoodieAvroWriteSupport class configurable
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroParquetWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroWriteSupport.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroFileWriterFactory.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestParquetUtils.java
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieBaseParquetWriter.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/SparkHelpers.scala
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestCluster.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
Labels: priority:blocker, writer-core, release-0.14.0

#8927 [DOCS] Add new videos to hudi website
  website/src/pages/videos.md
Labels: docs

#8897 [MINOR][DOCS] Unify the sql format in the procedures.md file
  website/docs/procedures.md
Labels: docs

#8868 [HUDI-6278] Fix the use of DynamoDBLockConfig class
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
  hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
Labels: aws-support, priority:major, configs

#8354 [MINOR] Exclude pentaho deps from hive-exec
  hudi-client/hudi-flink-client/pom.xml
  hudi-client/hudi-java-client/pom.xml
  hudi-client/hudi-spark-client/pom.xml
  hudi-examples/hudi-examples-flink/pom.xml
  hudi-examples/hudi-examples-spark/pom.xml
  hudi-flink-datasource/hudi-flink/pom.xml
  hudi-hadoop-mr/pom.xml
  hudi-integ-test/pom.xml
  hudi-spark-datasource/hudi-spark/pom.xml
  hudi-sync/hudi-adb-sync/pom.xml
  hudi-utilities/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
Labels: dependencies, hive

#8530 [HUDI-6121] Log the exception in the hudi commit kafka callback
  hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/kafka/HoodieWriteCommitKafkaCallback.java
Labels: writer-core

#8928 [HUDI-6348] Flink MDT log compaction
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkMergeOnReadTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/compact/HoodieFlinkMergeOnReadTableCompactor.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: flink, metadata

#8860 [HUDI-6314] Fix spark sql core flow
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
Labels: priority:critical

#8930 [HUDI-6355] Avoid merge records for global index when non-partitioned
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieGlobalBloomIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieGlobalSimpleIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: priority:critical

#8858 [HUDI-6301][UBER] Support SqlFileBasedSource for DeltaStreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SqlFileBasedSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlFileBasedSource.java
  hudi-utilities/src/test/resources/delta-streamer-config/sql-file-based-source-invalid-table.sql
  hudi-utilities/src/test/resources/delta-streamer-config/sql-file-based-source.sql
Labels: priority:major, release-0.14.0

#8921 [HUDI-6349] Do not consider nullability as a criteria for schema evolution in merger
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieInternalRowUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: spark, writer-core

#8914 [HUDI-6344] Flink MDT bulk_insert for initial commit
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/ExplicitWriteHandleTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkBulkInsertPreppedCommitActionExecutor.java
Labels: flink, metadata

#8783 [HUDI-5569] Maintain commit timeline even in case of long standing inflights
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
Labels: performance, priority:critical, metadata, table-service

#8832 [HUDI-6288] Create IngestionPrimaryWriterBasedConflictResolutionStrategy to prioritize ingestion writers over other writers
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/ConcurrentOperation.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/ConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/IngestionPrimaryWriterBasedConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SimpleConcurrentFileWritesConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestBucketIndexConcurrentFileWritesConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestConflictResolutionStrategyUtil.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestIngestionPrimaryWriterBasedConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestMultiwriterWithIngestionAsPrimaryWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: priority:critical, release-0.14.0

#8740 [HUDI-6231] Handle glue comments
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: aws-support, priority:major

#8957 [HUDI-6341] Update README with Spark 3.4 support
  README.md
Labels: docs

#8953 [HUDI-6368] Strength avro record merger
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseWriteHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkWriteHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaWriteHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/ParquetBootstrapMetadataHandler.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePreCombineAvroRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OperationModeAwareness.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroParquetReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestHoodieRecordUtils.java
  hudi-examples/hudi-examples-flink/src/test/java/org/apache/hudi/examples/quickstart/TestQuickstartData.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeUnmergedRecordReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/HoodieSparkValidateDuplicateKeyRecordMerger.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileRecordsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieOptionConfig.scala
Labels: writer-core

#8849 [HUDI-6304] Handle cases when inflight files are removed and job failed leaving pending rollback files
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestConsistentBucketIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestSparkConsistentBucketClustering.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieKeyLocationFetchHandle.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/ClusteringTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestCopyOnWriteRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/ClusteringTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: priority:critical, release-0.14.0

#8876 [HUDI-6312] Guard incremental query for multi-writer scenario
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadByStateTransitionTime.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamSourceReadByStateTransitionTime.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/QueryInfo.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: priority:critical

#8936 [MINOR] Remove imports and methods in HoodieWriteConfig and HoodieSparkSqlWriter
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: configs

#8972 [HUDI-6370] Automatically decide archival boundary based on cleaning configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
Labels: table-service

#8945 [HUDI-6360] spark-memory paramater should not be required in compactor or clustering job
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
Labels: spark, table-service

#8955 [HUDI-6367] Fix NPE in HoodieAvroParquetReader and support complex schema with timestamp
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieColumnProjectionUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/avro/HoodieAvroParquetReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieColumnProjectionUtils.java
Labels: schema-and-data-types, hive, stability

#8950 [HUDI-6366] Prevent flink offline table service rerun completed instant
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanSourceFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanSourceFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ClusteringCommitTestSink.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/CompactionCommitTestSink.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
Labels: priority:minor, flink, table-service, usability

#8961 [MINOR] Add database name to flink operator uid and operator name
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: flink

#8990 [HUDI-6387] Fix Spark CDC when delete all records from a filegroup
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCDCForSparkSQL.scala
Labels: change-data-capture

#8991 [HUDI-6389] Fix instant time check against the active timeline in meta sync
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
Labels: meta-sync, priority:critical

#9001 [HUDI-6402] Hudi Spark3.3 and upper version need close JavaTimeModule For JsonUtils
  hudi-common/src/main/java/org/apache/hudi/common/util/JsonUtils.java
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
Labels: dependencies, spark

#8985 [HUDI-6383] Hudi bucket index bulk insert into need partition sort to improve speed
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BucketBulkInsertPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BucketIndexBulkInsertPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/BucketPartitionUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: spark, writer-core

#9011 [HUDI-6407] Rename USE_LOG_RECORD_READER_SCAN_V2 in HoodieRealtimeConfig
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/GenericRecordValidationTestUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/config/HoodieRealtimeConfig.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
Labels: configs

#9010 [HUDI-6403] Ensure `hoodie.properties` updated after deleting MDT
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/TruncateHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteMetadataTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
Labels: priority:critical, release-0.14.0

#8993 [HUDI-6391] Fix pre-commit validators based on Spark SQL
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkValidatorUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/validator/SparkPreCommitValidator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/validator/SqlQueryEqualityPreCommitValidator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/validator/SqlQueryInequalityPreCommitValidator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/validator/SqlQuerySingleResultPreCommitValidator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSourceStorage.scala
Labels: spark

#8729 [HUDI-6223] Support Incremental read via Spark SQL table valued function
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logcal/HoodieTableChanges.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark32PlusAnalysis.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/TableValuedFunctions.scala
Labels: priority:major, spark-sql, incremental-etl, release-0.14.0

#8875 [HUDI-6311] Spark SQL Insert Into should use bulk insert by default for out of the box experience
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestInsertIntoOperation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCDCForSparkSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDeleteFromTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoLogOnlyTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestHoodiePruneFileSourcePartitions.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCleanProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCommitsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCompactionProcedure.scala
Labels: priority:blocker, release-0.14.0

#8487 [HUDI-6093] Use the correct partitionToReplacedFileIds during commit.
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:critical, release-0.14.0

#8956 [HUDI-6315] Optimize UPSERT codepath to use meta fields instead of key generation and index lookup
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCreateRecordUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/bootstrap/SparkFullBootstrapDataProviderBase.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala
Labels: release-0.14.0

#9021 [HUDI-6412] Pass WriteStatus to metadata writer to run table service with record index
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitSink.java
Labels: priority:blocker, release-0.14.0

#8994 [HUDI-6390] Fixes partition specs generation
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FilePathUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
Labels: flink, reader-core

#8898 [HUDI-6333] allow using manifest file directly to create a bigquery external table
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncConfig.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncToolArgs.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestManifestFileWriter.java
Labels: query-engine

#9025 [HUDI-6413] Fix build on Spark 2.4 and Scala 2.12
  .github/workflows/bot.yml
  pom.xml
Labels: dependencies, spark

#9028 [HUDI-6419] Change partition key to lower case when drop partition
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/HivePartitionUtil.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
Labels: spark-sql

#9040 [HUDI-6421] Claim RFC-70 for Hudi Reverse Streamer
  rfc/README.md
Labels: rfc

#7336 [HUDI-5297] Deprecate InternalWriteStatus and re-use WriteStatus
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/FailOnFirstErrorWriteStatus.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieInternalWriteStatus.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/inmemory/HoodieInMemoryHashIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BulkInsertDataInternalWriterHelper.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieInternalWriteStatus.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieReadClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestWriteStatus.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieMergeHandle.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/storage/row/TestHoodieRowCreateHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordDelegate.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/BaseWriterCommitMessage.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/internal/HoodieBulkInsertInternalWriterTestBase.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieDataSourceInternalWriter.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieWriterCommitMessage.java
  hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/HoodieDataSourceInternalBatchWrite.java
  hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/HoodieWriterCommitMessage.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/TableSizeStats.java
Labels: priority:critical, release-0.14.0

#9036 [HUDI-6412] Handle record index payload update
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataRecordIndex.scala
Labels: priority:critical, release-0.14.0

#8552 [DOCS] Update data quality docs
  website/docs/precommit_validator.md
  website/versioned_docs/version-0.13.0/precommit_validator.md
  website/versioned_docs/version-0.13.1/precommit_validator.md
Labels: docs

#7087 [MINOR] Fix creation of timeline instants in cleaner test cases
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
Labels: priority:minor, test-coverage

#9008 [HUDI-6406] Pass in Spark Engine Context Wrapper for DeltaSync instead of spark engine context
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/HoodieJavaEngineContext.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/EngineProperty.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieEngineContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieLocalEngineContext.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/BaseErrorTableWriter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/ErrorTableUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
Labels: deltastreamer, spark

#9043 [HUDI-6385] Fixing archival tests after RLI base patch
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Labels: priority:critical, release-0.14.0

#9046 [HUDI-6433] Make the meta sync of streaming sink thread safe
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java
Labels: meta-sync, concurrency-control

#8716 [HUDI-6226] Support parquet native bloom filters
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieBaseParquetWriter.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieParquetBloom.scala
Labels: priority:minor, writer-core

#9048 [HUDI-6434] Fix illegalArgumentException when do read_optimized read in Flink
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: flink-sql, usability

#7343 [HUDI-5303] Allow users to control the concurrency to submit jobs in clustering
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Labels: priority:critical, release-0.14.0

#9020 [HUDI-6411] Make spark SQL options case insensitive
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Labels: priority:critical, spark-sql, configs, release-0.14.0

#9037 [HUDI-6420] Fixing Hfile on-demand and prefix based reads to use optimized apis
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroHFileReader.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieSeekingFileReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
Labels: priority:blocker, release-0.14.0

#9044 [HUDI-6332] Fixing async indexer tests
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:critical, release-0.14.0

#9061 [HUDI-6440] Fallback to default Marker Type if the content of marker file is empty
  hudi-common/src/main/java/org/apache/hudi/common/util/MarkerUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestMarkerUtils.java
Labels: writer-core

#9072 [HUDI-6445] Flaky ds test multi writer
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: priority:critical, release-0.14.0

#9065 [HUDI-6451] Randomly obtain a path in HoodieMemoryConfig#getDefaultSpillableMapBasePath
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMemoryConfig.java
Labels: writer-core, stability

#8548 [HUDI-6126] Fix test `testInsertDatasetWithTimelineTimezoneUTC`
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Labels: test-coverage, release-0.14.0

#9069 [MINOR] Fixing commit time parsing w/ archival
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Labels: priority:critical, release-0.14.0

#9077 [HUDI-6454] Remove redundant indexing testcases
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieGlobalBloomIndex.java
Labels: priority:critical, release-0.14.0

#8076 [HUDI-5884] Support bulk_insert for insert_overwrite and insert_overwrite_table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieInternalConfig.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSingleFileSortExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSortAndSizeExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertOverwriteCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertOverwriteTableCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieInternalV2Table.scala
Labels: priority:critical, big-needle-movers, release-0.14.0

#8604 [HUDI-6151] Rollback previously applied commits to MDT when operations are retried.
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Labels: priority:critical, metadata, release-0.14.0

#9088 [MINOR] Improve CollectionUtils helper methods
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestSchemaEvolutionClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestRollbackUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: priority:major

#9017 [HUDI-6393] Enable MOR support for Record index with functional test cases
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/util/JavaConversions.scala
Labels: priority:critical, release-0.14.0

#8609 [HUDI-6154] Introduced retry while reading hoodie.properties to deal with parallel updates.
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:critical, writer-core, release-0.14.0

#9063 [HUDI-6448] Improve upgrade/downgrade for table ver. 6
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FiveToFourDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FiveToSixUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToFiveUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/OneToZeroDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/TwoToOneDowngradeHandler.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
Labels: priority:critical, release-0.14.0

#9058 [HUDI-6376] Support for deletes in HUDI Indexes including metadata table record index.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
Labels: priority:blocker, writer-core, release-0.14.0
