Repository apache/hudi, pull requests merged in 2023-08, with the labels that each got.

#9315 [HUDI-5760] Use Avro as serde for delete log blocks
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
  hudi-common/src/main/avro/HoodieDeleteRecordList.avsc
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieDeleteBlock.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-common/src/test/resources/format/delete-block-v2-content-10-records.data
Labels: priority:blocker, release-0.14.0, format-change

#9113 [HUDI-6466] Fix spark insert overwrite partitioned table with dynamic partition
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:blocker, data-consistency, release-0.14.0

#9237 [HUDI-6569] Fix write failure for Avro Enum type
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java
  hudi-client/hudi-java-client/src/test/resources/testDataGeneratorSchema.txt
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/GenericRecordValidationTestUtils.java
  hudi-client/hudi-spark-client/src/test/resources/testDataGeneratorSchema.txt
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestAvroOrcUtils.java
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/avro/AvroDeserializer.scala
  hudi-utilities/src/test/resources/streamer-config/source-flattened.avsc
  hudi-utilities/src/test/resources/streamer-config/source.avsc
  hudi-utilities/src/test/resources/streamer-config/source_evolved.avsc
  hudi-utilities/src/test/resources/streamer-config/source_evolved_post_processed.avsc
  hudi-utilities/src/test/resources/streamer-config/sql-transformer.properties
  hudi-utilities/src/test/resources/streamer-config/target-flattened.avsc
  hudi-utilities/src/test/resources/streamer-config/target.avsc
Labels: schema-and-data-types, priority:blocker, release-0.14.0

#9343 Revert "[HUDI-6476] Improve the performance of getAllPartitionPaths (#9121)"
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
Labels: performance

#9312 [HUDI-6609] Reverting multi writer checkpointing with HoodieStreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/HoodieStreamerConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltastreamerMultiWriterCkptUpdateFunc.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamerMultiWriterCkptUpdateFunc.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, release-0.14.0

#9338 [DOCS] Update bootstrap page
  website/docs/migration_guide.md
  website/src/theme/DocPage/index.js
Labels: docs

#8697 [HUDI-5514] Improving usability/performance with out of box default for append only use-cases
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestAutoGenerationOfRecordKeys.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:blocker, release-0.14.0

#9357 [HUDI-6588] Fix duplicate fileId on TM failover and recovery
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
Labels: flink, streaming, data-consistency, stability

#9308 [HUDI-6606] Use record level index with SQL equality queries
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Labels: priority:blocker, index, release-0.14.0

#9347 [HUDI-6638] Upgrade AWS Java SDK to V2
  hudi-aws/pom.xml
  hudi-aws/src/main/java/org/apache/hudi/aws/cloudwatch/CloudWatchReporter.java
  hudi-aws/src/main/java/org/apache/hudi/aws/credentials/HoodieAWSCredentialsProviderFactory.java
  hudi-aws/src/main/java/org/apache/hudi/aws/credentials/HoodieConfigAWSCredentialsProvider.java
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
  hudi-aws/src/main/java/org/apache/hudi/aws/utils/DynamoTableUtils.java
  hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
  hudi-aws/src/test/java/org/apache/hudi/aws/TestHoodieAWSCredentialsProviderFactory.java
  hudi-aws/src/test/java/org/apache/hudi/aws/cloudwatch/TestCloudWatchReporter.java
  hudi-aws/src/test/java/org/apache/hudi/aws/transaction/integ/ITTestDynamoDBBasedLockProvider.java
  hudi-utilities/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelector.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/S3EventsMetaSelector.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelector.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestS3EventsMetaSelector.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/CloudObjectTestUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractCloudObjectsSourceTestBase.java
  packaging/hudi-aws-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: priority:blocker, release-0.14.0

#9311 [HUDI-6607] Fixing RLI schema to support different fileID formats
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/avro/HoodieMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectWriterProvider.java
Labels: priority:blocker, release-0.14.0

#9337 [HUDI-6628] Rely on methods in HoodieBaseFile and HoodieLogFile instead of FSUtils when possible
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/CompactionAdminClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaUpsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/HoodieFileProbingFunction.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/HoodieMetadataBloomFilterProbingFunction.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/deltacommit/SparkUpsertDeltaCommitPartitioner.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/BaseFile.java
  hudi-common/src/main/java/org/apache/hudi/common/model/CompactionOperation.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieBaseFile.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieLogFile.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieBaseFile.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieLogFile.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/WriteProfile.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeSplit.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeFileSplit.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: priority:blocker, release-0.14.0

#9324 [HUDI-6619] Fix hudi-integ-test-bundle dependency on jackson jsk310 package
  packaging/hudi-hive-sync-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: priority:blocker, release-0.14.0

#9248 [HUDI-6324] Fixing deletion of MDT index
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Labels: priority:blocker, release-0.14.0

#9208 [DOCS] Improve Developer Setup page
  website/contribute/developer-setup.md
Labels: docs

#9206 [DOCS][HUDI-6536] Add docs on table version change in 0.11.0
  website/releases/release-0.11.0.md
Labels: docs

#9359 [HUDI-6639] Rename hoodie.sql.write.operation to hoodie.spark.sql.insert.into.operation
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCDCForSparkSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
Labels: priority:blocker, release-0.14.0

#9327 [HUDI-6617] make HoodieRecordDelegate implement KryoSerializable
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordDelegate.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieCommonKryoRegistrar.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieRecordDelegate.java
Labels: performance

#9261 [HUDI-6579] Adding support for upsert and deletes with spark datasource for pk less table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCreateRecordUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestAutoGenerationOfRecordKeys.scala
Labels: priority:blocker, release-0.14.0

#9365 [HUDI-6646] Add default lock provider for spark offline compaction an…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/FileSystemBasedLockProvider.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCLIUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunCompactionProcedure.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestUtilHelpers.java
Labels: priority:critical, release-0.14.0

#9374 [HUDI-6652] Implement basePath-level synchronization in runHoodieMetaSync
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestSyncUtilHelpers.java
Labels: meta-sync, priority:blocker, release-0.14.0

#9345 [HUDI-6649] Fix column stat based data filtering for MOR
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: priority:blocker, index, release-0.14.0

#9276 [HUDI-6635] Hudi Spark Integration Redesign MOR and Bootstrap reading
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystPlansUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieDataSourceHelper.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/NewHoodieParquetFileFormatUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionFileSliceMapping.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/LegacyHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapRead.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestNewHoodieParquetFileFormat.java
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark24LegacyHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/HoodieSpark30CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_0Adapter.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30LegacyHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_1Adapter.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31LegacyHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_2Adapter.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32LegacyHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_3Adapter.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33LegacyHoodieParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/HoodieSpark34CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_4Adapter.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34LegacyHoodieParquetFileFormat.scala
  rfc/README.md
Labels: priority:blocker, spark, reader-core, release-0.14.0

#9373 [HUDI-6651] Support IN SQL query with Record Index
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Labels: priority:blocker, index, release-0.14.0

#8998 [HUDI-6400] Fail when merger class not found
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestHoodieRecordUtils.java
Labels: priority:blocker, release-0.14.0

#9278 [HUDI-6312] Rename enum values of `HollowCommitHandling`
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkConfUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadByStateTransitionTime.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamSourceReadByStateTransitionTime.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
Labels: priority:blocker, release-0.14.0

#9367 [HUDI-6648] Support building table views from existing files
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieBaseFile.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/dto/BaseFileDTO.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/dto/FilePathDTO.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ExternalFilePathUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieBaseFile.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataPayload.java
Labels: priority:blocker, release-0.14.0

#9382 [HUDI-6660] For merge into use primary key constraint when optimized writes are enabled
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTableWithNonRecordKeyField.scala
Labels: priority:blocker, release-0.14.0

#9336 [HUDI-6629] - Changes for s3/gcs IncrSource job to taken into sourceLimit during ingestion
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudDataFetcher.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectIncrCheckpoint.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryInfo.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/QueryInfo.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestIncrSourceHelper.java
Labels: priority:blocker, release-0.14.0

#9387 [HUDI-6666] Disabling a flaky or long running tests
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
Labels: priority:blocker, release-0.14.0

#9385 [HUDI-6665] Fixing metadata writer close
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
Labels: priority:blocker, release-0.14.0

#9386 [HUDI-6662] Relax matching condition to allow non pk columns to match on
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTableWithNonRecordKeyField.scala
Labels: priority:blocker, release-0.14.0

#9199 [HUDI-6534]Support consistent hashing row writer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIdentifier.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/ConsistentHashingBucketInsertPartitioner.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/index/bucket/TestConsistentBucketIdIdentifier.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkConsistentBucketClusteringExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/ConsistentBucketIndexBulkInsertPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDConsistentBucketBulkInsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RowRecordKeyExtractor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/factory/HoodieSparkKeyGeneratorFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BulkInsertDataInternalWriterHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/ConsistentBucketBulkInsertDataInternalWriterHelper.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/hudi/spark3/internal/HoodieBulkInsertDataInternalWriter.java
Labels: spark

#9392 [DOCS]Update slack links due to upcoming expiry of old link
  website/blog/2021-12-16-lakehouse-concurrency-control-are-we-too-optimistic.md
  website/blog/2022-01-06-apache-hudi-2021-a-year-in-review.md
  website/blog/2022-01-14-change-data-capture-with-debezium-and-apache-hudi.md
  website/blog/2022-12-29-Apache-Hudi-2022-A-Year-In-Review.md
  website/community/get-involved.md
  website/docs/overview.md
  website/docusaurus.config.js
  website/i18n/cn/docusaurus-plugin-content-pages/get-involved.md
  website/i18n/cn/docusaurus-theme-classic/footer.json
  website/sidebars.js
  website/sidebarsCommunity.js
  website/sidebarsContribute.js
  website/src/components/JoinCommunity/index.js
  website/src/pages/powered-by.md
  website/versioned_docs/version-0.10.0/overview.md
  website/versioned_docs/version-0.10.1/overview.md
  website/versioned_docs/version-0.11.0/overview.md
  website/versioned_docs/version-0.11.1/overview.md
  website/versioned_docs/version-0.12.0/overview.md
  website/versioned_docs/version-0.12.1/overview.md
  website/versioned_docs/version-0.12.2/overview.md
  website/versioned_docs/version-0.12.3/overview.md
  website/versioned_docs/version-0.13.0/overview.md
  website/versioned_docs/version-0.13.1/overview.md
  website/versioned_sidebars/version-0.10.0-sidebars.json
  website/versioned_sidebars/version-0.10.1-sidebars.json
  website/versioned_sidebars/version-0.11.0-sidebars.json
  website/versioned_sidebars/version-0.11.1-sidebars.json
  website/versioned_sidebars/version-0.12.0-sidebars.json
  website/versioned_sidebars/version-0.12.1-sidebars.json
  website/versioned_sidebars/version-0.12.2-sidebars.json
  website/versioned_sidebars/version-0.12.3-sidebars.json
  website/versioned_sidebars/version-0.13.0-sidebars.json
  website/versioned_sidebars/version-0.13.1-sidebars.json
  website/versioned_sidebars/version-0.9.0-sidebars.json
Labels: docs

#9280 [HUDI-6587] Check incomplete commit for time travel query
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieTimeTravelException.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestTimeTravelQuery.scala
Labels: priority:blocker, release-0.14.0

#8327 [HUDI-5361] Propagate all hoodie configs from spark sqlconf, but don't overwrite values already set
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Labels: priority:blocker, release-0.14.0

#9419 [HUDI-6679] Fix initialization of metadata table partitions upon failure
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Labels: priority:blocker, metadata, release-0.14.0

#9409 [HUDI-6663] New Parquet File Format remove broadcast to fix performance issue for complex file slices
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/NewHoodieParquetFileFormatUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionFileSliceMapping.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
Labels: priority:blocker, spark, release-0.14.0

#9223 [HUDI-6553] Speedup column stats and bloom index creation on large datasets.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: priority:blocker, release-0.14.0

#9428 [DOCS] Update compaction page
  website/docs/compaction.md
  website/src/theme/DocPage/index.js
  website/static/assets/images/hudi_mor_file_layout.jpg
  website/static/assets/images/hudi_mor_file_layout_post_compaction.jpg
Labels: docs

#9429 [DOCS] Update clustering page with inline configs
  website/docs/clustering.md
  website/src/theme/DocPage/index.js
Labels: docs

#9346 [DOCS] Update Indexing page with all index types and file layout page
  website/docs/file_layouts.md
  website/docs/indexing.md
  website/src/theme/DocPage/index.js
Labels: docs

#9411 [HUDI-6674] Add rollback info from metadata table in timeline commands
  hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/TimelineCommand.java
Labels: priority:blocker, release-0.14.0

#9413 [HUDI-6675] Fix Clean action will delete the whole table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
Labels: priority:blocker, release-0.14.0

#9447 [MINOR] Infer the preCombine field only if the value is not null
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
Labels: priority:blocker, release-0.14.0

#9437 [HUDI-6689] Add record index validation in MDT validator
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: priority:blocker, release-0.14.0

#9433 [HUDI-6686] - Handling empty commits after s3 applyFilter api
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestIncrSourceHelper.java
Labels: priority:blocker, release-0.14.0

#9436 [HUDI-6688] Fix partition validation to only consider commits in metadata table validator
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: priority:blocker, release-0.14.0

#9449 [HUDI-6553][FOLLOW-UP] Introduces Tuple3 for HoodieTableMetadataUtil
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/Tuple3.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ColumnStatsIndices.java
Labels: priority:blocker, release-0.14.0

#8944 [HUDI-6359] Spark offline compaction/clustering will never rollback when both requested and inflight states exist
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
Labels: priority:blocker, table-service, release-0.14.0

#9366 [HUDI-6476][FOLLOW-UP] Path filter by FileStatus to avoid additional fs request
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
Labels: performance

#9483 [HUDI-6156] Prevent leaving tmp file in timeline, delete tmp file whe…
  hudi-common/src/main/java/org/apache/hudi/common/fs/HoodieWrapperFileSystem.java
Labels: priority:blocker, release-0.14.0

#9488 [HUDI-6731] BigQuerySyncTool: add flag to allow for read optimized sync for MoR tables
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
Labels: meta-sync, query-engine

#9484 [HUDI-6729] Fix get partition values from path for non-string type partition column
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestGetPartitionValuesFromPath.scala
Labels: schema-and-data-types, spark

#9444 [HUDI-6692] Don't default to bulk insert on nonpkless table if recordkey is omitted
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: priority:blocker, release-0.14.0

#9467 [HUDI-6621] Fix downgrade handler for 0.14.0
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SupportsUpgradeDowngrade.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/upgrade/FlinkUpgradeDowngradeHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/upgrade/JavaUpgradeDowngradeHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/upgrade/SparkUpgradeDowngradeHelper.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSixToFiveDowngradeHandler.scala
Labels: priority:blocker, release-0.14.0

#9468 [HUDI-6718] Check Timeline Before Transitioning Inflight Clean in Multiwriter Scenario
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanActionExecutor.java
Labels: priority:blocker, release-0.14.0

#9535 [HUDI-6754] Fix record reader tests in hudi-hadoop-mr
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/hive/TestHoodieCombineHiveInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieMergeOnReadSnapshotReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
Labels: priority:blocker, release-0.14.0

#9422 [HUDI-6681] Ensure MOR Column Stats Index skips reading filegroups correctly
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestDataSkippingWithMORColstats.java
Labels: priority:blocker, release-0.14.0

#9408 [HUDI-6671] Support 'alter table add partition' sql
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddPartitionCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableAddPartition.scala
Labels: spark-sql

#9406 [DOCS] Update Metadata table and metadata indexing related pages
  website/docs/metadata.md
  website/docs/metadata_indexing.md
  website/src/theme/DocPage/index.js
Labels: docs

#6854 [HUDI-4631] Adding retries to spark datasource writes on conflict failures:
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: priority:major, multi-writer, release-1.0.0

#9539 [HUDI-6726] Fix connection leaks related to file reader and iterator close
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/SimpleExecutor.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroHFileReader.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieHFileUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHFileRecordReader.java
Labels: priority:blocker, release-0.14.0

#9562 [DOCS] Update Record payload page
  website/docs/record_payload.md
  website/src/theme/DocPage/index.js
Labels: docs

#9516 [DOCS] Update file sizing page
  website/docs/file_sizing.md
  website/src/theme/DocPage/index.js
Labels: docs

#9545 [HUDI-6758] Detecting and skipping Spurious log blocks with MOR reads
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Labels: priority:blocker, release-0.14.0

#9547 [MINOR] Fixing warn log with auto key gen
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
Labels: priority:blocker, release-0.14.0

#9559 [HUDI-3727] Add metrics for async indexer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMetrics.java
Labels: index, metadata, release-1.0.0

#9543 [HUDI-6445] Fixing metrics to use IN-MEMORY type in tests
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/TestHoodieMetadataBase.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java
Labels: priority:blocker, release-0.14.0

#9561 [HUDI-6763] Optimize collect calls
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
Labels: priority:blocker, release-0.14.0
