Repository apache/hudi, pull requests merged in 2023-02, with the labels that each got.

#7706 [HUDI-5585][flink]Fix flink creates and writes the table, the spark alter table reports an error
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HiveSchemaUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/TableOptionProperties.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: priority:major, flink-sql, engine-interop

#7793 [HUDI-5317] Fix insert overwrite table for partitioned table
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:major, spark-sql

#7787 [HUDI-5646] Guard dropping columns by a config, do not allow by default
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableChangeColumnCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBasicSchemaEvolution.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSourceStorage.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Labels: priority:blocker

#7810 [MINOR] Restoring existing behavior for `DeltaStreamer` Incremental Source
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
Labels: priority:blocker

#7821 [HUDI-5681] Fixing Kryo being instantiated w/ invalid `SparkConf`
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/SerDeUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
Labels: priority:blocker

#7816 [HUDI-5676] Fix BigQuerySyncTool standalone mode
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncToolArgs.java
  packaging/hudi-gcp-bundle/pom.xml
Labels: priority:blocker

#7796 [HUDI-5647] Automate savepoint and restore tests
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestSavepointRestoreCopyOnWrite.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestSavepointRestoreMergeOnRead.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
Labels: priority:major, spark, utilities, test-coverage

#7813 [HUDI-5684] Fix CTAS and Insert Into to avoid combine-on-insert by default
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
Labels: priority:blocker

#7818 [HUDI-5678] Fix `deduceShuffleParallelism` in row-writing Bulk Insert helper
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieUnsafeUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:blocker

#7802 [0.13.0 Only] Disable default Avro schema validation
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:blocker

#7833 [HUDI-5691] Fixing `HoodiePruneFileSourcePartitions` to properly handle non-partitioned tables
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodiePruneFileSourcePartitions.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestHoodiePruneFileSourcePartitions.scala
Labels: priority:blocker

#7815 [HUDI-5671] BucketIndexPartitioner partition algorithm skew
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java
Labels: flink, index

#7664 [HUDI-5551] support seconds unit on event_time
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestWriteStatus.java
Labels: priority:minor, metrics

#7838 [HUDI-5682] Bucket index does not work correctly for multi-writer sce…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/BucketIndexConcurrentFileWritesConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestBucketIndexConcurrentFileWritesConflictResolutionStrategy.java
Labels: priority:critical, writer-core, index, multi-writer

#7831 [HUDI-5653] Add @AfterEach in TestHoodieDeltaStreamerWithMultiWriter to reset the datasource between tests
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: priority:blocker

#7841 [HUDI-5496] Avoid unnecessary file system parsing to initialize metadata table for a new data table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/HoodieDataSourceInternalWriter.java
Labels: priority:blocker

#7830 [HUDI-5689] Make CDC config working for DeltaStreamer path
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: priority:blocker

#7848 [MINOR] Validate configs for OCC early conflict detection
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
Labels: priority:blocker

#7850 [MINOR] Make most of the Spark SQL DML operations configs overridable
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
Labels: priority:blocker

#7853 [HUDI-5700] Annotate config classes for docs generation
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/replication/GlobalHiveSyncConfig.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
Labels: priority:blocker

#7852 [HUDI-5701] Remove meta fields from cdc new record in CDCLogger
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCDCForSparkSQL.scala
Labels: priority:blocker

#7849 [HUDI-5702] Avoid to write useless change-data when compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java
Labels: priority:blocker

#7854 [HUDI-5703] Improve ConfigProperty APIs for docs generation
  hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieHBaseIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteCommitCallbackConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigClassProperty.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigProperty.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/kafka/HoodieWriteCommitKafkaCallbackConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/pulsar/HoodieWriteCommitPulsarCallbackConfig.java
Labels: docs, priority:blocker

#7855 [MINOR] Improve configuration docs
  hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
Labels: docs, priority:blocker

#7858 [HUDI-5638] Activate platform service profile when deploy
  .github/workflows/bot.yml
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_binary.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_docker.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_mac_m1.sh
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
Labels: priority:blocker

#7856 [HUDI-5704] De-coupling column drop flag and schema validation flag (0.13.0)
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
Labels: priority:blocker

#7857 [HUDI-5704] De-coupling column drop flag and schema validation flag
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
Labels: priority:critical

#7795 [HUDI-5651] sort the inputs by record keys for bulk insert tasks
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: performance, priority:major, flink, index

#7378 [HUDI-5329] spark reads hudi table error when flink creates the table without preCombine fields
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
Labels: priority:critical

#7873 [MINOR] Added safety-net check to catch any potential issue to deduce parallelism from the incoming `Dataset` appropriately
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
Labels: priority:blocker

#7801 [HUDI-5657] Fix NPE if filters condition contains null literal when using column stats data skipping for flink
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ExpressionEvaluator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/stats/TestExpressionEvaluator.java
  hudi-flink-datasource/hudi-flink1.13.x/src/test/java/org/apache/hudi/adapter/TestCallExpressions.java
  hudi-flink-datasource/hudi-flink1.14.x/src/test/java/org/apache/hudi/adapter/TestCallExpressions.java
  hudi-flink-datasource/hudi-flink1.15.x/src/test/java/org/apache/hudi/adapter/TestCallExpressions.java
  hudi-flink-datasource/hudi-flink1.16.x/src/test/java/org/apache/hudi/adapter/TestCallExpressions.java
Labels: flink, metadata, reader-core

#7883 [HUDI-5721] Add Github actions on source validation
  .github/workflows/bot.yml
  scripts/release/create_source_directory.sh
  scripts/release/create_source_release.sh
  scripts/release/validate_source_binary_files.sh
  scripts/release/validate_source_copyright.sh
  scripts/release/validate_source_rat.sh
  scripts/release/validate_staged_release.sh
Labels: priority:major

#7756 [MINOR] remove useless code.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/CompactionAdminClient.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaCompatibility.java
  hudi-common/src/main/java/org/apache/hudi/common/HoodieJsonPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DeleteRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/parquet/io/ByteBufferBackedInputFile.java
Labels: priority:minor, code-refactor

#7281 [HUDI-5270] Duplicate key error when insert_overwrite same partition …
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
Labels: priority:critical, multi-writer, release-0.12.2

#6856 [HUDI-4968] Update misleading read.streaming.skip_compaction/skip_clustering config
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
Labels: docs, priority:minor

#7876 [MINOR] Improve RunClusteringProcedure with partition selected
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/PartitionAwareClusteringPlanStrategy.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: priority:major

#7900 [HUDI-5731] Cleaning up unnecessary relocation for com.google.common packages
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
Labels: dependencies, priority:critical

#7903 [HUDI-5734]Fix flink batch read skip clustering data lost
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: priority:major, flink, table-service, incremental-query

#7916 [MINOR] Fix wrong assertion in TestHoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: priority:major

#7917 [HUDI-5758] Restoring state of `HoodieKey` to make sure it's binary compatible w/ its state in 0.12
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
  hudi-common/src/main/java/org/apache/hudi/common/model/DeleteRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieKey.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
Labels: priority:blocker

#7924 [HUDI-5768] Fix Spark Datasource read of metadata table
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
Labels: priority:blocker

#7921 [HUDI-5764] Rollback delta commits from `HoodieIndexer` lazily in metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: priority:blocker, metadata

#7927 [HUDI-5771] Improve deploy script of release artifacts
  scripts/release/deploy_staging_jars.sh
Labels: priority:blocker

#5041 [HUDI-3580] [RFC-48] Create RFC for LogCompaction support to Hudi
  rfc/rfc-48/async_logcompaction_issues.jpeg
  rfc/rfc-48/base_case.jpeg
  rfc/rfc-48/huge_data_after_logcompaction_written_to_multiple_blocks.jpeg
  rfc/rfc-48/rfc-48.md
  rfc/rfc-48/rollback_block_scenario.jpeg
Labels: big-needle-movers, rfc

#6121 [HUDI-4406] Support Flink compaction/clustering write error resolvement to avoid data loss
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionCommitSink.java
Labels: priority:major, flink, table-service

#7633 [HUDI-5737] Fix Deletes issued without any prior commits
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: priority:minor, spark-sql

#7931 [HUDI-5773] Support archive command for spark sql
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/ArchiveExecutorUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ArchiveCommitsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestArchiveCommitsProcedure.scala
Labels: spark-sql

#7860 [HUDI-5673] Support multi writer for bucket index with guarded lock
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/storage/HoodieConsistentBucketLayout.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/storage/HoodieSimpleBucketLayout.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/index/FlinkHoodieIndexFactory.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/common/AbstractStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ViewStorageProperties.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/meta/TestCkpMetadata.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestViewStorageProperties.java
Labels: priority:major, multi-writer

#7918 [MINOR] Fix spark sql run clean do not exit
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java
Labels: spark-sql

#7792 [MINOR] Improving logging and tracking of failures for metadata validator
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: priority:minor, metadata

#7868 [HUDI-1593] Add support for "show restores" and "show restore" commands in hudi-cli
  hudi-cli/src/main/java/org/apache/hudi/cli/HoodieTableHeaderFields.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/RestoresCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRestoresCommand.java
Labels: priority:major, cli

#7972 [HUDI-5809][RFC-56] Keep RFC-56 early conflict detection update to date
  rfc/rfc-56/rfc-56.md
Labels: docs

#7809 [HUDI-5664] Improve SqlQueryPreCommitValidator#queries Parallelism.
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/validator/SqlQueryPreCommitValidator.java
Labels: priority:minor, writer-core

#7977 [HUDI-5811] Specify the artifact of protoc to solve the problem that cannot be compiled on m1 mac
  pom.xml
Labels: priority:major, project-build

#7672 [HUDI-5557]Avoid converting columns that are not indexed in CSI
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/ColumnStatsIndexHelper.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Labels: priority:critical, spark, writer-core, metadata, release-0.12.3, release-0.13.1

#7941 [HUDI-5786] Add a new config to specific spark write rdd storage level
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
Labels: spark, configs

#7981 [HUDI-5058] HoodieCatalog#getTable sets primary key with hoodie.datasource.write.recordkey.field for table initialized via Spark
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
Labels: schema-and-data-types, flink, engine-interop

#7894 [HUDI-5729] Fix RowDataKeyGen method getRecordKey
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java
Labels: writer-core, flink

#7995 [HUDI-5821] Improve the resource release for HoodieTableFileSystemView
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
Labels: writer-core

#7840 [MINOR] Close InflaterInputStream in finally when calling decompressBytes in BitCaskDiskMap
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java
Labels: priority:minor, writer-core, code-refactor

#8001 [HUDI-5817] Fix async indexer metadata writer to avoid eager rollback and failed write cleaning
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:critical, metadata

#7970 [DOCS] Change Config generator to generate subgroups
  hudi-utils/generate_config.sh
  hudi-utils/pom.xml
  hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
Labels: docs

#7601 [MINOR]: Fix usage of SchemaRegistryProvider with Row source
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/SourceFormatAdapter.java
Labels: priority:major

#7159 [HUDI-5173] Skip if there is only one file in clusteringGroup
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/FlinkSizeBasedClusteringPlanStrategy.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestFlinkSizeBasedClusteringPlanStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/SparkSizeBasedClusteringPlanStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestSparkBuildClusteringGroupsForPartition.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
Labels: priority:major, spark, flink, table-service

#7804 [HUDI-915][HUDI-5656] Rebased `HoodieBootstrapRelation` onto `HoodieBaseRelation`
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:critical, spark, reader-core, release-0.13.1, bootstrap

#8022 [HUDI-5833] Add 0.13.0 release notes
  website/docusaurus.config.js
  website/releases/download.md
  website/releases/older-releases.md
  website/releases/release-0.10.0.md
  website/releases/release-0.10.1.md
  website/releases/release-0.11.0.md
  website/releases/release-0.11.1.md
  website/releases/release-0.12.0.md
  website/releases/release-0.12.1.md
  website/releases/release-0.12.2.md
  website/releases/release-0.13.0.md
  website/releases/release-0.7.0.md
  website/releases/release-0.8.0.md
  website/releases/release-0.9.0.md
  website/src/components/HomepageHeader/index.js
Labels: docs, priority:blocker

#7536 [HUDI-5455] Add commons-configuration2 in hudi cli bundle
  packaging/hudi-cli-bundle/pom.xml
Labels: priority:critical, cli

#7948 [HUDI-5794] Failing new commits on any pending restore commits
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: priority:critical

#7965 [DOCS] Merge query engine setup and querying data docs
  website/docs/query_engine_setup.md
  website/docs/querying_data.md
  website/sidebars.js
  website/versioned_docs/version-0.12.2/querying_data.md
Labels: docs, query-engine

#7967 [DOCS] Update metadata indexing doc
  website/docs/metadata.md
  website/docs/metadata_indexing.md
Labels: docs

#6269 [MINOR] Reduce verbosity of the most noisy log messages
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
Labels: priority:minor

#8052 [HUDI-5850] Fix timestamp(6) field long overflow
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataToAvroConverters.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: writer-core, flink

#8050 [HUDI-5855] Release resource actively for Flink hive meta sync
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AwsGlueCatalogSyncTool.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
Labels: meta-sync, flink

#8026 [HUDI-5835] After performing the update operation, the hoodie table cannot be read normally by spark
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBootstrapRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala
Labels: schema-and-data-types, priority:blocker, spark, flink, release-0.12.3, release-0.13.1

#7914 [HUDI-5080] Unpersist only relevant RDDs instead of all
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/compact/HoodieFlinkMergeOnReadTableCompactor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/HoodieJavaEngineContext.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/compact/HoodieJavaMergeOnReadTableCompactor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaRDD.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/compact/HoodieSparkMergeOnReadTableCompactor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/common/TestHoodieSparkEngineContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieEngineContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieLocalEngineContext.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: priority:critical
