Repository apache/hudi, pull requests merged in 2023-09, with the labels that each got.

#8437 [HUDI-6066] HoodieTableSource supports parquet predicate push down
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/ExpressionPredicates.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/RecordIterators.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cow/CopyOnWriteInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestExpressionPredicates.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
  hudi-flink-datasource/hudi-flink1.13.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.13.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
  hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
  hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
  hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
Labels: big-needle-movers

#9589 [HUDI-6579] Fix streaming write when meta cols dropped
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCreateRecordUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:blocker, release-0.14.0

#9491 [HUDI-6732] Allow wildcards from Spark-SQL entrypoints for drop parti…
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
Labels: spark-sql

#9600 [HUDI-6813] Support table name for meta sync in bootstrap
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
Labels: priority:blocker, release-0.14.0

#9595 [MINOR] Catch EntityNotFoundException correctly
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: priority:blocker, release-0.14.0

#9584 [HUDI-6808] SkipCompaction Config should not affect the stream read of the cow table
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
Labels: priority:blocker, release-0.14.0

#9560 [DOCS] Update cleaning page
  website/docs/hoodie_cleaner.md
  website/src/theme/DocPage/index.js
Labels: docs

#9565 [HUDI-6725] Support efficient completion time queries on the timeline
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/CompletionTimeQueryView.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
Labels: release-1.0.0, concurrency-control

#9573 [HUDI-6804] Fix hive read schema evolution MOR table
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/SchemaEvolutionContext.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
Labels: schema-and-data-types, hive, schema-evolution

#9475 [HUDI-6766] Fixing mysql debezium data loss
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/MySqlDebeziumAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/debezium/TestMySqlDebeziumAvroPayload.java
Labels: deltastreamer, data-loss

#9372 [DOCS]Update Concurrency page
  website/docs/concurrency_control.md
  website/docs/table_types.md
  website/src/theme/DocPage/index.js
Labels: docs

#9537 [HUDI-6711] [RFC-73] Multi-table transactions
  rfc/README.md
  rfc/rfc-73/rfc-73.md
Labels: rfc, release-1.0.0

#9616 [HUDI-6819] Fix logic for throwing exception in getRecordIndexUpdates.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Labels: priority:blocker, release-0.14.0

#9546 [HUDI-6397][HUDI-6759] Fixing misc bugs w/ metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: priority:blocker, release-0.14.0

#9594 [HUDI-6742] Remove the log file appending for multiple instants
  hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestStorageSchemes.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Labels: writer-core, release-1.0.0, format-change

#9521 [HUDI-6736] Fixing rollback completion and commit timeline files removal
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestCopyOnWriteRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, release-0.14.0

#9653 [HUDI-6833] Add field for tracking log files from failed commit in rollback metadata
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java
  hudi-common/src/main/avro/HoodieRollbackMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/common/HoodieRollbackStat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
Labels: priority:blocker, release-0.14.0

#9642 [HUDI-6820] Close write clients in tests
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRestoresCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestClusteringCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCompactionCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/callback/TestHoodieClientInitCallback.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestDataValidationCheckForLogCompactionActions.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestFlinkConsistentHashingClustering.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestClusteringUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestViewStorageProperties.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamSourceReadByStateTransitionTime.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotExporter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/HoodieOfflineJobTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
Labels: priority:blocker, release-0.14.0

#9661 [HUDI-6820] Fixing CI stability issues
  .github/workflows/bot.yml
  azure-pipelines-20230430.yml
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, release-0.14.0

#9611 [HUDI-6758] Fixing deducing spurious log blocks due to spark retries
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/DummyTaskContextSupplier.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/FlinkTaskContextSupplier.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkAppendHandle.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/JavaTaskContextSupplier.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkTaskContextSupplier.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/LocalTaskContextSupplier.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/TaskContextSupplier.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Labels: priority:blocker, release-0.14.0

#9670 [HUDI-6845] Upgrade org.apache.pulsar:pulsar-client to 2.10.2
  pom.xml
Labels: version-upgrade

#9664 [HUDI-6835] Adjust spark sql core flow test scenarios
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
Labels: priority:major, test-coverage

#9482 [HUDI-6728] Update BigQuery manifest sync to support schema evolution
  hudi-gcp/pom.xml
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySchemaResolver.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySchemaResolver.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncTool.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
  hudi-sync/hudi-adb-sync/src/main/java/org/apache/hudi/sync/adb/AdbSyncConfig.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/util/TestManifestFileWriter.java
Labels: priority:blocker, release-0.14.0

#9538 [HUDI-6738] - Apply object filter before checkpoint batching in GcsEventsHoodieIncrSource
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/GcsObjectMetadataFetcher.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
Labels: priority:blocker, release-0.14.0

#9618 [HUDI-6753] Fix parquet inline reading flaky test
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerDAGExecution.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestTransformer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Labels: priority:blocker, release-0.14.0

#9684 [MINOR] Fixing failing tests with BQ sync tests
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
Labels: priority:blocker, release-0.14.0

#9675 [MINOR] Avoiding to ingest update records to RLI
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Labels: priority:blocker, release-0.14.0

#9666 [HUDI-6834] Fixing time travel queries when overlaps with cleaner and archival time window
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestTimeTravelQuery.scala
Labels: priority:blocker, release-0.14.0

#9686 [MINOR] Avoiding warn log for succeeding in first attempt
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:blocker, release-0.14.0

#9671 [HUDI-6842] Fixing flaky tests for async clustering test
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, release-0.14.0

#9665 [HUDI-6478] Deduce op as upsert for INSERT INTO
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AutoRecordKeyGenerationUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala
Labels: priority:blocker, spark-sql, release-0.14.0

#9473 [HUDI-6724] - Defaulting previous Instant time to init time to enable full read of initial commit
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestIncrSourceHelper.java
Labels: priority:blocker, release-0.14.0

#9619 [DOCS] Update write operations page
  website/docs/write_operations.md
  website/src/theme/DocPage/index.js
Labels: docs

#9486 [DOCS] Update Key generation page
  website/docs/key_generation.md
  website/src/theme/DocPage/index.js
Labels: docs

#9221 [HUDI-6550] Add Hadoop conf to HiveConf for HiveSyncConfig
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
Labels: priority:blocker, release-0.14.1

#9711 [HUDI-6858] Fix checkpoint reading in Spark structured streaming
  hudi-common/src/main/java/org/apache/hudi/common/util/CommitUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestCommitUtils.java
Labels: priority:blocker, spark-streaming, release-0.14.0

#9590 [HUDI-6780] Introduce enums instead of classnames in table properties
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieBootstrapConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/BootstrapIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/model/BootstrapIndexType.java
  hudi-common/src/main/java/org/apache/hudi/common/model/RecordPayloadType.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorType.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/resources/streamer-config/short_trip_uber_config.properties
Labels: configs, release-1.0.0

#9582 [MINOR] Fix hbase index config improper use
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
Labels: configs

#9710 [HUDI-6857] Update BigQuerySyncTool docs
  website/docs/gcp_bigquery.md
Labels: docs, release-0.14.0

#9680 [HUDI-6848] Fix non-unique uid for hudi operators
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Labels: flink, reader-core

#9722 [HUDI-6863] Revert auto-tuning of dedup parallelism
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: priority:blocker, release-0.14.0

#9729 [HUDI-6869] Fixing schema evolution docs
  website/docs/schema_evolution.md
Labels: docs, release-0.14.0

#9699 [HUDI-6861] update sql pages for 0.14.0
  website/docs/procedures.md
  website/docs/table_management.md
Labels: docs, priority:blocker, release-0.14.0

#9701 [HUDI-6852] Added spark streaming to streaming ingestion page
  website/docs/hoodie_streaming_ingestion.md
  website/docs/overview.md
  website/sidebars.js
  website/versioned_docs/version-0.10.0/overview.md
  website/versioned_docs/version-0.10.1/overview.md
  website/versioned_docs/version-0.11.0/overview.md
  website/versioned_docs/version-0.11.1/overview.md
  website/versioned_docs/version-0.12.0/overview.md
  website/versioned_docs/version-0.12.1/overview.md
  website/versioned_docs/version-0.12.2/overview.md
  website/versioned_docs/version-0.12.3/overview.md
  website/versioned_docs/version-0.13.0/overview.md
  website/versioned_docs/version-0.13.1/overview.md
Labels: docs, priority:blocker, release-0.14.0

#8958 [HUDI-6341][DOCS] Add Spark 3.4 support in quick start
  website/docs/quick-start-guide.md
Labels: docs, priority:blocker, release-0.14.0

#9360 [HUDI-6867] Upgrade thrift's version to 0.13.0
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_docker.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_mac_m1.sh
  pom.xml
Labels: dependencies

#9416 [HUDI-6678] Fix the acquisition of clean&rollback instants to archive
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CompactionUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java
Labels: table-service

#9734 [DOCS][MINOR] Update roadmap page for 0.14.0 timeline
  website/src/pages/roadmap.md
Labels: docs

#9724 [HUDI-6865] Fix InternalSchema schemaId when column is dropped
  hudi-common/src/main/java/org/apache/hudi/internal/schema/InternalSchema.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/action/InternalSchemaMerger.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/InternalSchemaUtils.java
  hudi-common/src/test/java/org/apache/hudi/internal/schema/action/TestMergeSchema.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterTableCommand.scala
Labels: schema-evolution, release-0.14.1

#9275 [HUDI-6584] Abstract commit in CommitActionExecutor
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
Labels: code-refactor

#9517 [HUDI-6708] Support record level indexing with async indexer
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieMemoryConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/AbstractIndexingCatchupTask.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/IndexingCatchupTask.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/IndexingCatchupTaskFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RecordBasedIndexingCatchupTask.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/WriteStatBasedIndexingCatchupTask.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/index/TestIndexingCatchupTask.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieCleanerTestBase.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestFileIOUtils.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/reader/DFSHoodieDatasetInputReader.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileRecordsProcedure.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/resources/streamer-config/indexer-record-index.properties
Labels: index, metadata, release-1.0.0

#9709 [HUDI-6856] Adding a page for partially failed commits
  website/docs/rollbacks.md
  website/sidebars.js
  website/static/assets/images/blog/rollbacks/multi_writer_rollback.png
  website/static/assets/images/blog/rollbacks/single_write_rollback.png
Labels: docs, priority:blocker, release-0.14.0

#9705 [DOCS] Add Record Index Metadata partition documentation and other schema details
  website/src/pages/tech-specs.md
Labels: docs, priority:blocker, release-0.14.0

#9746 [HUDI-6874] Move configs for reading a file group to hudi-common module
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/IOUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/GenericRecordValidationTestUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestSparkIOUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMemoryConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestConfigUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/FlinkCompactionConfig.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestFormatUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/config/HoodieRealtimeConfig.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadSnapshotReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeUnmergedRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeRecordReaderUtils.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieMergeOnReadSnapshotReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/reader/DFSHoodieDatasetInputReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileRecordsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Labels: release-1.0.0

#9756 [DOCS] Update configurations page for 0.14.0
  hudi-utils/generate_config.sh
  hudi-utils/pom.xml
  hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
  website/docs/basic_configurations.md
  website/docs/configurations.md
Labels: docs, pr:wip

#9754 [HUDI-6881] Hudi configured spark.scheduler.allocation.file should include scheme since Spark3.2
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SchedulerConfGenerator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSchedulerConfGenerator.java
Labels: spark, utilities

#8169 [HUDI-5924] Fixing cli clean command to trim down a subset based on start and end
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/CleansCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/DiffCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/utils/CLIUtils.java
Labels: priority:major, cli

#7968 [DOCS] Update hive metastore sync docs
  website/docs/syncing_metastore.md
Labels: docs, meta-sync

#8297 [MINOR] Replace 'obj == null' with Optional.ofNullable() in HoodieTableSource, make the code more standardized
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
Labels: priority:minor, flink, code-refactor
