Repository apache/hudi, pull requests merged in 2023-11, with the labels that each got.

#9886 [HUDI-6946] Data Duplicates with range pruning while using hoodie.bloom.index.use.metadata
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestBloomIndexTagWithColStats.java
Labels: priority:blocker, spark, metadata, release-0.14.1

#9933 [HUDI-6997] A new WriteConcurrencyMode type for non-blocking concurrency control
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/WriteMarkers.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteConcurrencyMode.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsInference.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:critical, writer-core, configs, concurrency-control

#9948 [DOCS] Add tags and thumbnails for video pages
  website/static/assets/images/video_blogs/2023-01-15-Real_Time_Streaming_Data_Pipeline_From_Aurora_Postgres_to_Hudi_with_DMS_Kinesis_and_Flink_DEMO.png
  website/static/assets/images/video_blogs/2023-01-17-Cleaner_Service_Save_up_to_40_on_data_lake_storage_costs_Hudi_Labs.png
  website/static/assets/images/video_blogs/2023-01-17-Global_Bloom_Index_Remove_duplicates_guarantee_uniquness_Hudi_Labs.png
  website/static/assets/images/video_blogs/2023-01-17-Leverage_Apache_Hudi_incremental_query_to_process_new_updated_data_Hudi_Labs.png
  website/static/assets/images/video_blogs/2023-01-17-Leverage_Apache_Hudi_upsert_to_remove_duplicates_on_a_data_lake_Hudi_Labs.png
  website/static/assets/images/video_blogs/2023-01-17-Precomb_Key_Overview_Avoid_dedupes_Hudi_Labs.png
  website/static/assets/images/video_blogs/2023-01-17-Use_Apache_Hudi_for_hard_deletes_on_your_data_lake_for_data_governance_Hudi_Labs.png
  website/static/assets/images/video_blogs/2023-02-21-Apache_Hudi_Bulk_Insert_Sort_Modes_a_summary_of_two_incredible_blogs.png
  website/static/assets/images/video_blogs/2023-02-22-Use_Glue_40_to_take_regular_save_points_for_your_Hudi_tables_for_backup_or_disaster_Recovery.png
  website/static/assets/images/video_blogs/2023-02-25-RFC51_Change_Data_Capture_in_Apache_Hudi_like_Debezium_and_AWS_DMS_Hands_on_Labs.png
  website/static/assets/images/video_blogs/2023-03-04-Develop_Incremental_Pipeline_with_CDC_from_Hudi_to_Aurora_Postgres_Demo_Video.png
  website/static/assets/images/video_blogs/2023-03-06-Power_your_Down_Stream_ElasticSearch_Stack_From_Apache_Hudi_Transaction_Datalake_with_CDCDemo_Video.png
  website/static/assets/images/video_blogs/2023-03-11-How_do_I_read_data_from_Cross_Account_S3_Buckets_and_Build_Hudi_Datalake_in_Datateam_Account.png
  website/static/assets/images/video_blogs/2023-03-11-Query_crossaccount_Hudi_Glue_Data_Catalogs_using_Amazon_Athena.png
  website/static/assets/images/video_blogs/2023-03-15-Learn_About_Bucket_Index_SIMPLE_In_Apache_Hudi_with_lab.png
  website/videoBlog/2023-01-15-Real_Time_Streaming_Data_Pipeline_From_Aurora_Postgres_to_Hudi_with_DMS_Kinesis_and_Flink_DEMO.md
  website/videoBlog/2023-01-16-Real_Time_Streaming_Pipeline_From_Aurora_Postgres_to_Hudi_with_DMS_Kinesis_and_Flink_Hands_on_Lab.md
  website/videoBlog/2023-01-17-Cleaner_Service_Save_up_to_40_on_data_lake_storage_costs_Hudi_Labs.md
  website/videoBlog/2023-01-17-Global_Bloom_Index_Remove_duplicates_guarantee_uniquness_Hudi_Labs.md
  website/videoBlog/2023-01-17-How_businesses_use_Hudi_Soft_delete_features_to_do_soft_delete_instead_of_hard_delete_on_Datalake.md
  website/videoBlog/2023-01-17-Leverage_Apache_Hudi_incremental_query_to_process_new_updated_data_Hudi_Labs.md
  website/videoBlog/2023-01-17-Leverage_Apache_Hudi_upsert_to_remove_duplicates_on_a_data_lake_Hudi_Labs.md
  website/videoBlog/2023-01-17-Precomb_Key_Overview_Avoid_dedupes_Hudi_Labs.md
  website/videoBlog/2023-01-17-Use_Apache_Hudi_for_hard_deletes_on_your_data_lake_for_data_governance_Hudi_Labs.md
  website/videoBlog/2023-01-20-How_do_I_identify_Schema_Changes_in_Hudi_Tables_and_Send_Email_Alert_when_New_Column_addedremoved.md
  website/videoBlog/2023-01-21-How_to_detect_and_Mask_PII_data_in_Apache_Hudi_Data_Lake_Hands_on_Lab.md
  website/videoBlog/2023-01-23-Writing_data_quality_and_validation_scripts_for_a_Hudi_data_lake_with_AWS_Glue_and_pydeequ_Hands_on_Lab.md
  website/videoBlog/2023-01-28-Learn_How_to_restrict_Intern_from_accessing_Certain_Column_in_Hudi_Datalake_with_lake_Formation.md
  website/videoBlog/2023-02-07-How_do_I_Ingest_Extremely_Small_Files_into_Hudi_Data_lake_with_Glue_Incremental_data_processing.md
  website/videoBlog/2023-02-11-Create_Your_Hudi_Transaction_Datalake_on_S3_with_EMR_Serverless_for_Beginners_in_fun_and_easy_way.md
  website/videoBlog/2023-02-18-Streaming_Ingestion_from_MongoDB_into_Hudi_with_Glue_kinesis_Event_bridge_MongoStream_Hands_on_labs.md
  website/videoBlog/2023-02-21-Apache_Hudi_Bulk_Insert_Sort_Modes_a_summary_of_two_incredible_blogs.md
  website/videoBlog/2023-02-22-Use_Glue_40_to_take_regular_save_points_for_your_Hudi_tables_for_backup_or_disaster_Recovery.md
  website/videoBlog/2023-02-25-RFC51_Change_Data_Capture_in_Apache_Hudi_like_Debezium_and_AWS_DMS_Hands_on_Labs.md
  website/videoBlog/2023-02-26-Python_helper_class_which_makes_querying_incremental_data_from_Hudi_Data_lakes_easy.md
  website/videoBlog/2023-03-04-Develop_Incremental_Pipeline_with_CDC_from_Hudi_to_Aurora_Postgres_Demo_Video.md
  website/videoBlog/2023-03-06-Power_your_Down_Stream_ElasticSearch_Stack_From_Apache_Hudi_Transaction_Datalake_with_CDCDemo_Video.md
  website/videoBlog/2023-03-06-Power_your_Down_Stream_Elastic_Search_Stack_From_Apache_Hudi_Transaction_Datalake_with_CDCDeepDive.md
  website/videoBlog/2023-03-07-How_to_Rollback_to_Previous_Checkpoint_during_Disaster_in_Apache_Hudi_using_Glue_40_Demo.md
  website/videoBlog/2023-03-11-How_do_I_read_data_from_Cross_Account_S3_Buckets_and_Build_Hudi_Datalake_in_Datateam_Account.md
  website/videoBlog/2023-03-11-Query_crossaccount_Hudi_Glue_Data_Catalogs_using_Amazon_Athena.md
  website/videoBlog/2023-03-15-Learn_About_Bucket_Index_SIMPLE_In_Apache_Hudi_with_lab.md
  website/videoBlog/2023-03-17-Setting_Uber_s_Transactional_Data_Lake_in_Motion_with_Incremental_ETL_Using_Apache_Hudi.md
  website/videoBlog/2023-03-18-Push_Hudi_Commit_Notification_TO_HTTP_URI_with_Callback.md
  website/videoBlog/2023-03-19-RFC_18_Insert_Overwrite_in_Apache_Hudi_with_Example.md
Labels: docs

#9872 [HUDI-5210] Implement functional indexes
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieFunctionalIndexClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/functional/HoodieSparkFunctionalIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/functional/TestHoodieSparkFunctionalIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/avro/HoodieIndexPartitionInfo.avsc
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieFunctionalIndexConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieFunctionalIndexDefinition.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieFunctionalIndexMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieFunctionalIndexException.java
  hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieFunctionalIndex.java
  hudi-common/src/main/java/org/apache/hudi/index/secondary/HoodieSecondaryIndex.java
  hudi-common/src/main/java/org/apache/hudi/index/secondary/SecondaryIndexManager.java
  hudi-common/src/main/java/org/apache/hudi/index/secondary/SecondaryIndexType.java
  hudi-common/src/main/java/org/apache/hudi/index/secondary/SecondaryIndexUtils.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieFileWriterFactory.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/TestWaitBasedTimeGenerator.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndexClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/main/antlr4/org/apache/hudi/spark/sql/parser/HoodieSqlCommon.g4
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: index, release-1.0.0

#9975 [HUDI-7022] RunClusteringProcedure support limit parameter
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedureUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: spark, table-service, usability

#9959 [HUDI-7012] The BootstrapOperator reduces the memory.
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
Labels: flink, stability

#9970 [HUDI-7021] Add blog to introduce record level index
  website/blog/2023-11-01-record-level-index.md
  website/static/assets/images/blog/record-level-index/01.metadatatable_layout.png
  website/static/assets/images/blog/record-level-index/02.RLI_init_flow.png
  website/static/assets/images/blog/record-level-index/03.RLI_bulkinsert.png
  website/static/assets/images/blog/record-level-index/04.RLI_tagging.png
  website/static/assets/images/blog/record-level-index/index-latency.png
  website/static/assets/images/blog/record-level-index/write-latency.png
Labels: docs

#9925 [HUDI-6990] Configurable clustering task parallelism
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Labels: table-service, stability

#9937 [HUDI-6382] support hoodie-table-type changing in hudi-cli
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestTableCommand.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
Labels: priority:major, spark, cli, table-service

#9871 [HUDI-2461] Support out of order commits in MDT with completion time view
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/CompletionTimeQueryView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CompactionUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestCompactionUtils.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
Labels: metadata, release-1.0.0, concurrency-control

#9996 [MINOR] Fix build failure caused by bad tag name `index`
  website/blog/2023-11-01-record-level-index.md
Labels: docs

#9993 [MINOR] Hotfix in HdfsParquetImportProcedure for format parameter is not need to add
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HdfsParquetImportProcedure.scala
Labels: spark-sql

#9953 [Docs] Update videos tags+thumbnails page 4
  content/assets/images/video_blogs/2023-05-03-Build_deploy_and_run_Spark_jobs_on_Amazon_EMR_with_the_opensource_EMR_CLI_tool.png
  content/assets/images/video_blogs/2023-05-03-Mastering_Slowly_Changing_Dimension_with_Hudi_A_StepbyStep_Guide_to_Efficient_Data_Management.png
  content/assets/images/video_blogs/2023-05-06-How_to_Build_Your_Own_Version_of_AWS_Glue_Bookmark_to_get_Only_New_Incremental_Files.png
  content/assets/images/video_blogs/2023-05-07-Maximizing_Efficiency_DataLake_Hudi_Glue_ETL_Jobs_with_Templated_Approach_Serverless_Architecture.png
  content/assets/images/video_blogs/2023-05-11-EMR_Serverless_for_Beginners_Ingest_Data_incrementally_Submit_Spark_Job_with_EMRCLI_Data_lake.png
  content/assets/images/video_blogs/2023-05-13-EMR-Serverless-Made-Easy_-Submitting-Hive-SQL-Queries-for-Beginners-with-NYC-Taxi-Dataset.png
  content/assets/images/video_blogs/2023-05-16-Unify-Your-Event-Data_Guide-to-Mapping-Events-to-Standardized-Format-with-Incremental-ETL-using-Hudi.png
  content/assets/images/video_blogs/2023-05-19-Hands-On-Lab_-Unleashing-Efficiency-and-Flexibility-with-Partial-Updates-in-Apache-Hudi.png
  content/assets/images/video_blogs/2023-05-20-Mastering_File_Sizing_in_Hudi_Boosting_Performance_and_Efficiency.png
  content/assets/images/video_blogs/2023-05-21-How_to_Set_Up_AWS_Glue_Locally.png
  website/videoBlog/.2022-11-17-Insert_Update_Delete_On_Datalake_S3_with_Apache_Hudi_and_glue_Pyspark.md.swp
  website/videoBlog/2022-11-17-Insert_Update_Delete_On_Datalake_S3_with_Apache_Hudi_and_glue_Pyspark.md
  website/videoBlog/2023-05-03-Build_deploy_and_run_Spark_jobs_on_Amazon_EMR_with_the_opensource_EMR_CLI_tool.md
  website/videoBlog/2023-05-03-Mastering_Slowly_Changing_Dimension_with_Hudi_A_StepbyStep_Guide_to_Efficient_Data_Management.md
  website/videoBlog/2023-05-06-How_to_Build_Your_Own_Version_of_AWS_Glue_Bookmark_to_get_Only_New_Incremental_Files.md
  website/videoBlog/2023-05-07-Maximizing_Efficiency_DataLake_Hudi_Glue_ETL_Jobs_with_Templated_Approach_Serverless_Architecture.md
  website/videoBlog/2023-05-11-EMR_Serverless_for_Beginners_Ingest_Data_incrementally_Submit_Spark_Job_with_EMRCLI_Data_lake.md
  website/videoBlog/2023-05-13-EMR_Serverless_Made_Easy_Submitting_Hive_SQL_Queries_for_Beginners_with_NYC_Taxi_Dataset.md
  website/videoBlog/2023-05-16-Unify_Your_Event_Data_Guide_to_Mapping_Events_to_Standardized_Format_with_Incremental_ETL_using_Hudi.md
  website/videoBlog/2023-05-19-HandsOn_Lab_Unleashing_Efficiency_and_Flexibility_with_Partial_Updates_in_Apache_Hudi.md
  website/videoBlog/2023-05-20-Mastering_File_Sizing_in_Hudi_Boosting_Performance_and_Efficiency.md
  website/videoBlog/2023-05-21-How_to_Set_Up_AWS_Glue_Locally_with_Docker_Accessing_Glue_Database_Table_in_Your_LocalEnvironment.md
Labels: docs

#9936 [HUDI-7001] ComplexAvroKeyGenerator should represent single record key as the value string without composing the key field name
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/ComplexAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestComplexAvroKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/BuiltinKeyGenerator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestComplexKeyGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Labels: priority:critical, writer-core

#9888 [HUDI-6790] Support incremental/CDC queries using HadoopFsRelation
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCDCFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieIncrementalFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodiePartitionCDCFileGroupMapping.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodiePartitionFileSliceMapping.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodiePartitionValues.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkFileFormatUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionFileSliceMapping.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/HoodieMultipleBaseFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
Labels: release-1.0.0

#10001 [HUDI-7048] Fix checkpoint loss issue when changing MOR to COW in streamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: deltastreamer, spark

#7907 [HUDI-6495][RFC-66] Non-blocking Concurrency Control
  rfc/rfc-66/compaction.png
  rfc/rfc-66/log_file_sequence.png
  rfc/rfc-66/multi_writer.png
  rfc/rfc-66/non_serial_compaction.png
  rfc/rfc-66/rfc-66.md
Labels: writer-core, rfc, multi-writer, streaming, release-1.0.0

#9949 [HUDI-6993] Support Flink 1.18
  .github/workflows/bot.yml
  README.md
  azure-pipelines-20230430.yml
  hudi-flink-datasource/hudi-flink/pom.xml
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink1.13.x/src/main/java/org/apache/hudi/adapter/HiveCatalogConstants.java
  hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/adapter/HiveCatalogConstants.java
  hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/adapter/HiveCatalogConstants.java
  hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/adapter/HiveCatalogConstants.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/adapter/HiveCatalogConstants.java
  hudi-flink-datasource/hudi-flink1.18.x/pom.xml
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/AbstractStreamOperatorAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/AbstractStreamOperatorFactoryAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/DataStreamScanProviderAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/DataStreamSinkProviderAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/HiveCatalogConstants.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/MailboxExecutorAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/MaskingOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/OperatorCoordinatorAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/RateLimiterAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/SortCodeGeneratorAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelDeleteAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelUpdateAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/Utils.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapArrayVector.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapMapColumnVector.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapRowColumnVector.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/ParquetDecimalVector.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/AbstractColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ArrayColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/BaseVectorizedColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/EmptyColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/FixedLenBytesColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/Int64TimestampColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/MapColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetDataColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetDataColumnReaderFactory.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/RowColumnReader.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/RunLengthDecoder.java
  hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/OutputAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/StateInitializationContextAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/StreamingRuntimeContextAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
  hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/TestTableEnvs.java
  hudi-flink-datasource/pom.xml
  packaging/bundle-validation/base/build_flink1180hive313spark332.sh
  packaging/bundle-validation/base/build_flink1180hive313spark340.sh
  packaging/bundle-validation/ci_run.sh
  pom.xml
  scripts/release/deploy_staging_jars.sh
  scripts/release/validate_staged_bundles.sh
Labels: priority:major, flink, version-upgrade

#10020 [HUDI-7055] Support reading only log files in file group reader-based Spark parquet file format
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
Labels: priority:blocker, release-1.0.0

#10022 [HUDI-7056] Add config for merging using positions
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
Labels: priority:blocker, release-1.0.0

#10025 [HUDI-7057] Support CopyToTableProcedure with patitial column copy
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CopyToTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCopyToTableProcedure.scala
Labels: spark-sql, sql-procedure, table-maintenance

#10027 [HUDI-7058] Check if option is empty before get in HoodieBaseFileGroupRecordBuffer
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
Labels: priority:blocker, release-1.0.0

#10005 [HUDI-7044] Skip reading records for delete blocks for positional merging
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
Labels: priority:blocker, release-1.0.0

#10026 [HUDI-7047] Fix Stack Overflow Caused by partition pruning
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieIncrementalFileIndex.scala
Labels: priority:blocker, release-1.0.0

#10032 [HUDI-7060] Disable new file group reader or new parquet file format for CDC, time travel, and incremental query types
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
Labels: priority:blocker, release-1.0.0

#10018 [HUDI-7053] Fix the filter pushdown logic for file group reader
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
Labels: priority:blocker, release-1.0.0

#10037 [HUDI-7063] Use existing relation logic for queries reading base files only in Spark
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Labels: priority:blocker, release-1.0.0

#10036 [HUDI-7062] Implement Caching Iterator for new filegroup reader
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
Labels: priority:blocker, release-1.0.0

#10038 [HUDI-7064] Recheck should use batch when cached result is true
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/NewHoodieParquetFileFormat.scala
Labels: priority:blocker, release-1.0.0

#10045 [HUDI-7060] Handle time travel queries using snapshot relation
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
Labels: priority:blocker, release-1.0.0

#10046 [HUDI-7067] Add fallback to full update if all fields are updated in MERGE INTO statement
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
Labels: priority:blocker, release-1.0.0

#10043 [HUDI-7068] Disable vectorized reader for hoodie filegroup reader when schema isn't supported
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: priority:blocker, release-1.0.0

#10049 [HUDI-7070] Disable partial update for MERGE INTO statement without update action
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
Labels: priority:blocker, release-1.0.0

#10047 [HUDI-7073] Fix schema projection in file group reader-based parquet file format
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: priority:blocker, release-1.0.0

#10056 [MINOR] Fix the flag for bootstrap
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Labels: priority:blocker, release-1.0.0

#10058 [HUDI-7079] disable new file format for metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/CompactHelpers.java
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Labels: priority:blocker, release-1.0.0

#10059 [MINOR] disable reader in schema evo test
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
Labels: priority:blocker, release-1.0.0

#9998 [HUDI-7076] Turn on new features by default through configs for 1.0.0-beta1
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestNestedSchemaPruningOptimization.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestHoodiePruneFileSourcePartitions.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: priority:blocker, release-1.0.0

#10053 [HUDI-7074] Flink incremental query for non-blocking concurrency control
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergedReadHandle.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java
Labels: priority:blocker, flink, incremental-query, release-1.0.0

#10071 [HUDI-7035] Fix CDC Incremental Read When First Write Contains Delete And Upsert
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
Labels: streaming, incremental-etl, change-data-capture, correctness

#9984 [MINOR] Fix npe for get internal schema
  hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java
Labels: writer-core

#9260 [HUDI-6695] Use the AWS provider chain in Glue sync and add a new provider for STS assume role
  hudi-aws/pom.xml
  hudi-aws/src/main/java/org/apache/hudi/aws/credentials/HoodieAWSCredentialsProviderFactory.java
  hudi-aws/src/main/java/org/apache/hudi/aws/credentials/HoodieConfigAWSAssumedRoleCredentialsProvider.java
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/main/java/org/apache/hudi/config/HoodieAWSConfig.java
  hudi-aws/src/test/java/org/apache/hudi/aws/TestHoodieAWSCredentialsProviderFactory.java
Labels: meta-sync, aws-support

#10048 [HUDI-7069] Optimize metaclient construction and include table config…
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/ClusteringTask.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/CompactionTask.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/multitable/MultiTableServiceUtils.java
Labels: spark, table-service

#10103 [DOCS] Remove redundant blog entries
  website/blog/2023-09-19-A-Beginners-Guide-to-Apache-Hudi-with-PySpark—Part-1-of-2.mdx
  website/blog/2023-10-20-Its-Time-for-the-Universal-Data-Lakehouse‍.mdx
  website/static/assets/images/blog/2023-09-19-A-Beginners-Guide-to-Apache-Hudi-with-PySpark—Part-1-of-2.png
Labels: docs

#10065 [HUDI-5936] Fix serialization problem when FileStatus is not serializable
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/common/fs/NonSerializableFileSystem.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/common/fs/TestHoodieSerializableFileStatus.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/HoodieSerializableFileStatus.java
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
Labels: priority:blocker, spark, writer-core, metadata, release-0.14.1

#10004 [MINOR] Removing unnecessary guards to row writer with deltastreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: priority:critical, release-0.14.1

#10119 [HUDI-7109] Fix Flink may re-use a committed instant in append mode
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
Labels: priority:blocker, flink, release-0.14.1, bug-fix

#10123 [HUDI-7113] Update release scripts and docs for Spark 3.5 support
  README.md
  scripts/release/deploy_staging_jars.sh
  scripts/release/validate_staged_bundles.sh
Labels: release-1.0.0

#10133 [HUDI-7119]Don't write hoodie.table.precombine.field=ts to hoodie.properties when use Flink to create a insert hudi table and the `ts` field does not exist
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: flink

#10100 [HUDI-7098] Adding max bytes per partition with cloud stores source in DS
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudStoreIngestionConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
Labels: priority:critical, release-0.14.1

#10101 [HUDI-7099] Providing metrics for archive and defining some string constants
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Labels: priority:critical, release-0.14.1

#10118 [HUDI-7108] Fix schema refresh for KafkaAvroSchemaDeserializer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
Labels: priority:critical, release-0.14.1

#10130 [HUDI-7111] Fix performance regression of tag when written into simple bucket index table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIndexLocationMapper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieBucketIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieConsistentBucketIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieSimpleBucketIndex.java
Labels: priority:blocker, spark, release-0.14.1

#10146 [HUDI-7127] Fixing set up and tear down in tests
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieParquetBloom.scala
Labels: priority:blocker, release-0.14.1

#10067 [MINOR] Misc fixes in deltastreamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: priority:critical, release-0.14.1

#10068 [HUDI-7083] Adding support for multiple tables with Prometheus Reporter
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/prometheus/PrometheusReporter.java
Labels: priority:critical, release-0.14.1

#9567 [HUDI-6734] Add back HUDI-5409: Avoid file index and use fs view cache in COW input format
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
Labels: priority:critical, release-0.14.1

#9941 [HUDI-7003] Add option to fallback to full table scan if files are deleted due to…
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadWithFullTableScan.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:critical, release-0.14.1

#10117 [HUDI-7106] Fix sqs deletes, deltasync service close and error table default configs.
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelector.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/ErrorTableUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: priority:critical, release-0.14.1

#10125 [HUDI-7115] Add in new options for the bigquery sync
  hudi-gcp/pom.xml
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncConfig.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncTool.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncToolArgs.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
Labels: priority:critical, release-0.14.1

#10098 [HUDI-7096] Improving incremental query to fetch partitions based on commit metadata
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieTableFileIndex.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieMergeHandleWithSparkMerger.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
Labels: priority:critical, release-0.14.1

#10150 [HUDI-6961] Fixing DefaultHoodieRecordPayload to honor deletion based on meta field as well as custome delete marker
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestDefaultHoodieRecordPayload.java
Labels: priority:critical, release-0.14.1

#10136 [HUDI-7123] Improve CI scripts
  .github/workflows/bot.yml
  azure-pipelines-20230430.yml
  packaging/bundle-validation/base/build_flink1153hive313spark323.sh
  packaging/bundle-validation/base/build_flink1162hive313spark331.sh
  packaging/bundle-validation/ci_run.sh
Labels: priority:critical, release-0.14.1

#10120 [HUDI-7110] Add call procedure for show column stats information
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataTableColumnStatsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
Labels: spark, table-maintenance

#10014 [HUDI-7052] Fix partition key validation for custom key generators.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/AutoRecordGenWrapperAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/AutoRecordKeyGeneratorWrapper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/AutoRecordGenWrapperKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, release-0.14.1

#10122 [HUDI-7112] Reuse existing timeline server and performance improvements
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineServerHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/HttpRequestClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestHoodieJavaWriteClientInsert.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/dto/DTOUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/BaseFileHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerDirState.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  pom.xml
Labels: priority:critical, release-0.14.1

#10095 [MINOR] Making misc fixes to deltastreamer sources(S3 and GCS)
  hudi-common/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
Labels: priority:critical, release-0.14.1

#10135 [HUDI-7120] Performance improvements in deltastreamer executor code path
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLocationFetchHandle.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroConversionUtils.scala
Labels: priority:critical, release-0.14.1

#10151 [HUDI-7034] Refresh index fix - remove cached file slices within part…
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
Labels: priority:blocker, spark, release-0.14.1

#10099 [HUDI-7097] Fixing instantiation of Hms Uri with HiveSync tool
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
Labels: priority:critical, release-0.14.1

#10073 [HUDI-7086] Scaling gcs event source
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubMessagesFetcher.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubQueueClient.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/gcs/TestPubsubMessagesFetcher.java
Labels: priority:critical, release-0.14.1

#10097 [HUDI-7095] Making perf enhancements to JSON serde
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/HttpRequestClient.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  pom.xml
Labels: priority:critical, release-0.14.1

#10158 [HUDI-7006] Reduce unnecessary is_empty rdd calls in StreamSync
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SparkSampleWritesUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSparkSampleWritesUtils.java
Labels: priority:critical, release-0.14.1

#10002 [HUDI-7041] Optimize the memory usage of timeline server for table service
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/ClusteringPlanStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RocksDbBasedFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/RocksDBSchemaHelper.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
Labels: priority:blocker, writer-core, release-0.14.1

#10188 [HUDI-7148] Add an additional fix to the potential thread insecurity problem of heartbeat client.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java
Labels: priority:critical, release-0.14.1

#10102 [HUDI-7102] Fix a bug for time travel queries on MOR tables
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Labels: priority:critical, release-0.14.1

#10190 [minor] when metric prefix length is 0 ignore the metric prefix
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
Labels: release-0.14.1

#10192 [HUDI-7149] Add a dbt example project with CDC capability
  hudi-examples/hudi-examples-dbt/.gitignore
  hudi-examples/hudi-examples-dbt/README.md
  hudi-examples/hudi-examples-dbt/dbt_project.yml
  hudi-examples/hudi-examples-dbt/models/example_cdc/profile_changes.sql
  hudi-examples/hudi-examples-dbt/models/example_cdc/profiles.sql
  hudi-examples/hudi-examples-dbt/models/example_cdc/raw_updates.sql
  hudi-examples/hudi-examples-dbt/models/example_cdc/schema.yml
Labels: priority:major, dbt

#10171 [HUDI-7086] Fix the default for gcp pub sub max sync time to 1min for PR #10073
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/PubsubMessagesFetcher.java
Labels: priority:critical, release-0.14.1

#10109 [HUDI-7103] Support time travel queies for COW tables
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapRead.java
Labels: release-1.0.0

#10173 [HUDI-7138] Fix error table writer and schema registry provider
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieConversionUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
Labels: priority:critical, release-0.14.1

#10210 [HUDI-7128][FOLLOW-UP] Support metadatadelete with batch mode
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DeleteMetadataTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestMetadataProcedure.scala
Labels: spark-sql

#10213 [HUDI-7161] Add commit action type and extra metadata to write callback on commit message
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/common/HoodieWriteCommitCallbackMessage.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
Labels: release-0.14.1

#10212 [HUDI-7160] Copy over schema properties when adding Hudi Metadata fields
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
Labels: release-0.14.1
