Repository apache/hudi, pull requests merged in 2023-10, with the labels that each got.

#9624 [HUDI-6785] Introduce a new File Group Reader
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkRecordMerger.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/CloseableInternalRowIterator.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/CloseableScalaIterator.scala
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReverseReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderState.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/EmptyIterator.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
Labels: release-1.0.0

#7235 [HUDI-5148][RFC-63] RFC for Index Function
  rfc/README.md
  rfc/rfc-63/rfc-63.md
Labels: big-needle-movers, rfc, release-1.0.0

#9712 [HUDI-6851] Fixing Spark quick start guide
  website/docs/configurations.md
  website/docs/flink-quick-start-guide.md
  website/docs/flink_tuning.md
  website/docs/overview.md
  website/docs/querying_data.md
  website/docs/quick-start-guide.md
  website/docs/schema_evolution.md
  website/docs/sql_ddl.md
  website/docs/sql_dml.md
  website/docs/sql_queries.md
  website/docs/table_management.md
  website/sidebars.js
  website/versioned_docs/version-0.10.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.10.0/overview.md
  website/versioned_docs/version-0.10.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.10.1/overview.md
  website/versioned_docs/version-0.11.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.11.0/overview.md
  website/versioned_docs/version-0.11.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.11.1/overview.md
  website/versioned_docs/version-0.12.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.12.0/overview.md
  website/versioned_docs/version-0.12.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.12.1/overview.md
  website/versioned_docs/version-0.12.2/flink-quick-start-guide.md
  website/versioned_docs/version-0.12.2/overview.md
  website/versioned_docs/version-0.12.3/flink-quick-start-guide.md
  website/versioned_docs/version-0.12.3/overview.md
  website/versioned_docs/version-0.13.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.13.0/overview.md
  website/versioned_docs/version-0.13.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.13.1/overview.md
Labels: docs, priority:blocker, release-0.14.0

#9820 [DOCS] Add linkedin Hudi page in website
  website/docusaurus.config.js
  website/src/components/JoinCommunity/Icons/linkedin.svg
  website/src/components/JoinCommunity/index.js
  website/src/css/custom.css
  website/static/assets/images/linkedin.png
Labels: docs

#9811 [HUDI-6828] Fix wrong partitionToReplaceIds when insertOverwrite empty data into partitions
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieInternalConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkInsertOverwriteCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertOverwriteCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: bug-fix

#9581 [HUDI-6795] Implement writing record_positions to log blocks for updates and deletes
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/ListBasedHoodieBloomIndexHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLocationFetchHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLookupHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLookupResult.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/utils/TestLegacyArchivedMetaEntryReader.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/index/bloom/TestFlinkHoodieBloomIndex.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkWriteableTestTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/HoodieFileProbingFunction.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkParquetReader.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieKeyLocationFetchHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordGlobalLocation.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordLocation.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/LogReaderUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCDCDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/util/BaseFileUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroHFileReader.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroOrcReader.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroParquetReader.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieBootstrapFileReader.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormatAppendFailure.java
  hudi-common/src/test/java/org/apache/hudi/common/table/log/TestLogReaderUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieDeleteBlock.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestParquetUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestSerializationUtils.java
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieReaderWriterBase.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieSparkMergeOnReadTableClustering.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
Labels: release-1.0.0

#9816 [HUDI-6913] Set default database name correctly
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
Labels: bug-fix

#8143 [HUDI-5911] SimpleTransactionDirectMarkerBasedDetectionStrategy can't work with none-partitioned table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/DirectMarkerTransactionManager.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSimpleTransactionDirectMarkerBasedDetectionStrategyWithZKLockProvider.java
Labels: bug-fix

#9585 [HUDI-6809] Optimizing the judgment of generating clustering plans
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/clustering/plan/strategy/TestSparkConsistentBucketClusteringPlanStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
Labels: table-service

#9786 [HUDI-6894] ReflectionUtils is not thread safe
  hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java
Labels: thread-safety

#9863 [HUDI-6941] Fix partition pruning for multiple partition fields
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: performance, release-0.14.1

#9850 [HUDI-6480] Flink support non-blocking concurrency control
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Labels: flink, big-needle-movers, release-1.0.0, concurrency-control

#9867 [HUDI-6944] Fix Flink bootstrap concurrency issue causes job to keep rolling back
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
Labels: priority:critical, flink, bootstrap

#9118 [HUDI-2141] Support flink stream write metrics
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/metrics/FlinkStreamWriteMetrics.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/append/AppendWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
Labels: flink, metrics, release-1.0.0

#9836 [HUDI-6924] Fix hoodie table config not wok in table properties
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
Labels: spark-sql

#9875 [HUDI-6950] Query should process listed partitions to avoid driver oom due to large number files in table first partition
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
Labels: priority:critical, performance-regression, release-0.14.1

#9053 [HUDI-6369] Fix spacial curve with sample strategy fails when 0 or 1 rows only is incoming
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/execution/RangeSample.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/spark/sql/hudi/execution/TestRangeSampleSort.java
Labels: bug-fix

#6983 [HUDI-5031] Fix MERGE INTO creates empty partition files when source table has partitions but target table does not
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/CopyOnWriteInsertHandler.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/SparkLazyInsertIterable.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
Labels: priority:major, spark-sql, release-0.12.2, bug-fix

#7206 [HUDI-5220] fix hive snapshot query add non hoodie paths file status
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
  hudi-hadoop-mr/src/test/resources/emptyFile
  pom.xml
  scripts/release/validate_source_copyright.sh
Labels: priority:critical, release-0.12.2, bug-fix

#9879 [HUDI-6952] Skip reading the uncommitted log files for log reader
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestCompactionAdminClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/CompletionTimeQueryView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
Labels: performance, reader-core, release-1.0.0

#9897 [Docs] Flink Quickstart Restructuring
  website/docs/flink-quick-start-guide.md
Labels: docs, flink

#9749 [HUDI-6878] Fix Overwrite error when ingest multiple tables
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSourceDAGExecution.scala
Labels: spark, writer-core, bug-fix

#9908 [HUDI-6972][DOCS] Fix config link redirection
  website/src/theme/DocPage/index.js
Labels: docs

#9896 [HUDI-6962] Fix the conflicts resolution for bulk insert under NB-CC
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BulkInsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
  hudi-flink-datasource/hudi-flink1.13.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
  hudi-flink-datasource/hudi-flink1.14.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
  hudi-flink-datasource/hudi-flink1.15.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
  hudi-flink-datasource/hudi-flink1.16.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
  hudi-flink-datasource/hudi-flink1.17.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
Labels: release-1.0.0

#9887 [HUDI-6959] Bulk insert V2 do not rollback failed instant on abort
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:critical, spark-sql, data-consistency, stability

#9910 [HUDI-6973] Instantiate HoodieFileGroupRecordBuffer inside new file group reader
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: release-1.0.0

#9876 [HUDI-6800] Support writing partial updates to the data blocks in MOR tables
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
Labels: release-1.0.0

#9761 [HUDI-6821] Support multiple base file formats in Hudi table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/bootstrap/BootstrapUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/BaseConsistentHashingBucketClusteringPlanStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ZeroToOneUpgradeHandler.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestHoodieJavaWriteClientInsert.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/bootstrap/TestBootstrapUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieFileFormat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/util/BaseFileUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkFileFormatUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/HoodieMultipleBaseFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairMigratePartitionMetaProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestHoodieMultipleBaseFileFormat.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/Spark32NestedSchemaPruning.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
Labels: release-1.0.0, format-change

#9911 [HUDI-6975] Optimize the code of DayBasedCompactionStrategy
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/strategy/DayBasedCompactionStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java
Labels: priority:minor, table-service, code-refactor

#9789 [HUDI-6896] HoodieAvroHFileReader.RecordIterator iteration never terminates
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroHFileReader.java
Labels: bug-fix

#9950 [DOCS] Add tags and thumbnails to video guides
  website/static/assets/images/video_blogs/2023-03-21-RFC_42_Consistent_Hashing_in_Apache_Hudi_MOR_Tables.png
  website/static/assets/images/video_blogs/2023-03-25-Build_CDC_Pipeline_from_Microsoft_SQL_Server_into_Apache_Hudi_with_AWS_DMS_PART_1.png
  website/static/assets/images/video_blogs/2023-03-30-Project_Using_Apache_Hudi_Deltastreamer_and_AWS_DMS_Hands_on_Lab_Part_1.png
  website/static/assets/images/video_blogs/2023-04-06-Efficient_Data_Lake_Management_with_Apache_Hudi_Cleaner_Benefits_of_Scheduling_Data_Cleaning_1.png
  website/static/assets/images/video_blogs/2023-04-07-Advantages_of_Metadata_Indexing_and_Asynchronous_Indexing_in_Hudi_Hands_on_Lab.png
  website/static/assets/images/video_blogs/2023-04-12-Efficient_Data_Ingestion_with_Glue_Concurrency_and_Hudi_Data_Lake.png
  website/static/assets/images/video_blogs/2023-04-20-Effortlessly_Sync_Your_JDBC_Source_to_Hudi_Transactional_Datalake_No_DMS_or_Debezium_Required.png
  website/static/assets/images/video_blogs/2023-04-25-Joining_Hudi_Raw_Tables_for_Powerful_Data_Analysis_with_Spark_SQL.png
  website/static/assets/images/video_blogs/2023-04-26-From_Raw_Data_to_Insights_Building_a_Lake_House_with_Hudi_and_Star_Schema_Step_by_Step_Guide.png
  website/static/assets/images/video_blogs/2023-04-29-Efficiently_Managing_Ride_Late_Arriving_Tips_Data_with_Incremental_ETL_using_Apache_Hudi_Hands_On.png
  website/static/assets/images/video_blogs/2023-05-01-Building_a_Scalable_and_Resilient_Streaming_ETL_Pipeline_with_Hudi_s_Incremental_Processing_1.png
  website/videoBlog/2022-12-30-Step_by_Step_guide_how_to_setup_VPC_Subnet_Get_Started_with_HUDI_on_EMR_Installation_Guide.md
  website/videoBlog/2023-01-17-Cleaner_Service_Save_up_to_40_on_data_lake_storage_costs_Hudi_Labs.md
  website/videoBlog/2023-03-21-RFC_42_Consistent_Hashing_in_Apache_Hudi_MOR_Tables.md
  website/videoBlog/2023-03-25-Build_CDC_Pipeline_from_Microsoft_SQL_Server_into_Apache_Hudi_with_AWS_DMS_PART_1.md
  website/videoBlog/2023-03-25-Build_CDC_Pipeline_from_Microsoft_SQL_Server_into_Apache_Hudi_with_AWS_DMS_PART_2.md
  website/videoBlog/2023-03-25-Build_CDC_Pipeline_from_Microsoft_SQL_Server_into_Apache_Hudi_with_AWS_DMS_PART_3.md
  website/videoBlog/2023-03-25-Build_CDC_Pipeline_from_Microsoft_SQL_Server_into_Apache_Hudi_with_AWS_DMS_PART_4.md
  website/videoBlog/2023-03-25-Build_CDC_Pipeline_from_Microsoft_SQL_Server_into_Apache_Hudi_with_AWS_DMS_PART_5.md
  website/videoBlog/2023-03-25-Podcast_1_What_is_Apache_Hudi.md
  website/videoBlog/2023-03-25-Podcast_2_Why_Lake_house_architecture_is_being_adopted_by_businesses_and_how_hudi_can_assist_you.md
  website/videoBlog/2023-03-25-Podcast_3_Benefits_of_Using_a_Transactional_Data_Lake_and_How_Apache_Hudi_Can_Help.md
  website/videoBlog/2023-03-25-Podcast_Exploring_Copy_on_Write_Table_Type_in_Apache_Hudi_Benefits_and_Use_Cases.md
  website/videoBlog/2023-03-25-Podcast_Importance_of_Data_Governance_and_Apache_Hudi_in_Managing_a_Data_Lake_The_Case_of_Grofers.md
  website/videoBlog/2023-03-25-Podcast_Maximizing_Data_Management_Efficiency_with_Apache_Hudi_s_Clustering_Feature.md
  website/videoBlog/2023-03-25-Podcast_Maximizing_Efficiency_with_Merge_on_Read_Table_Type_in_Apache_Hudi_Benefits_and_Use_Cases.md
  website/videoBlog/2023-03-25-Podcast_Optimizing_Data_Lake_Performance_with_Apache_Hudi_Compaction_Strategies_and_Benefits.md
  website/videoBlog/2023-03-25-Weekend_Project_Build_CDC_Pipeline_from_Microsoft_SQL_Server_into_Apache_Hudi_1.md
  website/videoBlog/2023-03-26-How_to_use_Apache_Hudi_with_AWS_Glue_Studio_Visual_Editor_Hands_on_Lab.md
  website/videoBlog/2023-03-30-Podcast_Uber_s_GameChanging_Data_Management_with_Apache_Hudi_Delta_Streamer.md
  website/videoBlog/2023-03-30-Project_Using_Apache_Hudi_Deltastreamer_and_AWS_DMS_Hands_on_Lab_Part_1.md
  website/videoBlog/2023-03-30-Project_Using_Apache_Hudi_Deltastreamer_and_AWS_DMS_Hands_on_Lab_Part_2.md
  website/videoBlog/2023-03-30-Project_Using_Apache_Hudi_Deltastreamer_and_AWS_DMS_Hands_on_Lab_Part_3.md
  website/videoBlog/2023-03-30-Project_Using_Apache_Hudi_Deltastreamer_and_AWS_DMS_Hands_on_Lab_Part_4.md
  website/videoBlog/2023-03-31-Project_Using_Apache_Hudi_Deltastreamer_and_AWS_DMS_Hands_on_Lab_Part_5.md
  website/videoBlog/2023-04-02-Learn_How_to_Integrate_Apache_Hudi_with_Redshift_Spectrum_Hands_on_Labs_with_Code.md
  website/videoBlog/2023-04-04-Running_Apache_Hudi_Delta_Streamer_On_EMR_Serverless_Hands_on_Lab_step_by_step_guide.md
  website/videoBlog/2023-04-05-Getting_Alerts_when_hudi_Delta_Streamer_Fails_with_Event_Driven_Approach_using_Lambdas_Event_Bridge.md
  website/videoBlog/2023-04-06-Efficient_Data_Lake_Management_with_Apache_Hudi_Cleaner_Benefits_of_Scheduling_Data_Cleaning_1.md
  website/videoBlog/2023-04-06-Efficient_Data_Lake_Management_with_Apache_Hudi_Cleaner_Benefits_of_Scheduling_Data_Cleaning_2.md
  website/videoBlog/2023-04-07-Advantages_of_Metadata_Indexing_and_Asynchronous_Indexing_in_Hudi_Hands_on_Lab.md
  website/videoBlog/2023-04-08-Understanding_Clustering_in_Apache_Hudi_and_the_Benefits_of_Asynchronous_Clustering.md
  website/videoBlog/2023-04-09-Bootstrapping_in_Apache_Hudi_on_EMR_Serverless_with_Lab.md
  website/videoBlog/2023-04-11-Learn_about_Apache_Hudi_Transformers_with_Hands_on_Lab.md
  website/videoBlog/2023-04-11-Podcast_Unleashing_the_Power_of_Data_The_Epic_Story_Behind_Apache_Hudi_s_Creation_by_Uber.md
  website/videoBlog/2023-04-12-Efficient_Data_Ingestion_with_Glue_Concurrency_and_Hudi_Data_Lake.md
  website/videoBlog/2023-04-20-Effortlessly_Sync_Your_JDBC_Source_to_Hudi_Transactional_Datalake_No_DMS_or_Debezium_Required.md
  website/videoBlog/2023-04-25-Joining_Hudi_Raw_Tables_for_Powerful_Data_Analysis_with_Spark_SQL.md
  website/videoBlog/2023-04-26-From_Raw_Data_to_Insights_Building_a_Lake_House_with_Hudi_and_Star_Schema_Step_by_Step_Guide.md
  website/videoBlog/2023-04-29-Efficiently_Managing_Ride_Late_Arriving_Tips_Data_with_Incremental_ETL_using_Apache_Hudi_Hands_On.md
  website/videoBlog/2023-05-01-Building_a_Scalable_and_Resilient_Streaming_ETL_Pipeline_with_Hudi_s_Incremental_Processing_1.md
  website/videoBlog/2023-05-03-Build_deploy_and_run_Spark_jobs_on_Amazon_EMR_with_the_opensource_EMR_CLI_tool.md
Labels: docs

#9883 [HUDI-6801] Implement merging partial updates from log files for MOR tables
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkRecordMerger.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileReaderFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkParquetReader.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/merge/SparkRecordMergingUtils.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/CloseableInternalRowIterator.scala
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
Labels: release-1.0.0

#9939 [DOCS] Add tags for video blogs
  website/static/assets/images/video_blogs/2022-11-19-Build_a_Spark_pipeline_to_analyze_streaming_data_using_AWS_Glue_Apache_Hudi_S3_and_Athena.png
  website/static/assets/images/video_blogs/2022-11-20-Different_table_types_in_Apache_Hudi_MOR_and_COW_Deep_Dive_By_Sivabalan_Narayanan.png
  website/static/assets/images/video_blogs/2022-12-15-Build_production_Ready_Real_Time_Transaction_Hudi_Datalake_from_DynamoDB_Streams_using_Glue_kinesis.png
  website/static/assets/images/video_blogs/2022-12-17-Migrate_Certain_Tables_from_ONPREM_DB_using_DMS_into_Apache_Hudi_Transaction_Datalake_with_GlueDemo.png
  website/static/assets/images/video_blogs/2022-12-17-Step_by_Step_Guide_on_Migrate_Certain_Tables_from_DB_using_DMS_into_Apache_Hudi_Transaction_Datalake.png
  website/static/assets/images/video_blogs/2022-12-19-Build_Production_Ready_Alternative_Data_Pipeline_from_DynamoDB_to_Apache_Hudi_PROJECT_DEMO.png
  website/static/assets/images/video_blogs/2022-12-19-Build_Production_Ready_Alternative_Data_Pipeline_from_DynamoDB_to_Apache_Hudi_Step_by_Step_Guide.png
  website/static/assets/images/video_blogs/2022-12-20-Getting_started_with_Kafka_and_Glue_to_Build_Real_Time_Apache_Hudi_Transaction_Datalake.png
  website/static/assets/images/video_blogs/2022-12-23-Apache_Hudi_with_DBT_Hands_on_LabTransform_Raw_Hudi_tables_with_DBT_and_Glue_Interactive_Session.png
  website/static/assets/images/video_blogs/2022-12-27-Bring_Data_from_Source_using_Debezium_with_CDC_into_Kafka_S3Sink_Build_Hudi_Datalake_Hands_on_lab.png
  website/static/assets/images/video_blogs/2022-12-28-Comparing_Apache_Hudi_s_MOR_and_COW_Tables_Use_Cases_from_Uber.png
  website/static/assets/images/video_blogs/2022-12-30-Step_by_Step_guide_how_to_setup_VPC_Subnet_Get_Started_with_HUDI_on_EMR_Installation_Guide.png
  website/static/assets/images/video_blogs/2023-01-01-Streaming_ETL_using_Apache_Flink_joining_multiple_Kinesis_streams_Demo.png
  website/static/assets/images/video_blogs/2023-01-13-Build_Real_Time_Low_Latency_Streaming_pipeline_from_DynamoDB_to_Apache_Hudi_using_Kinesis_FlinkLab.png
  website/videoBlog/2022-11-17-Insert_Update_Delete_On_Datalake_S3_with_Apache_Hudi_and_glue_Pyspark.md
  website/videoBlog/2022-11-19-Build_a_Spark_pipeline_to_analyze_streaming_data_using_AWS_Glue_Apache_Hudi_S3_and_Athena.md
  website/videoBlog/2022-11-20-Different_table_types_in_Apache_Hudi_MOR_and_COW_Deep_Dive_By_Sivabalan_Narayanan.md
  website/videoBlog/2022-12-08-Simple_5_Steps_Guide_to_get_started_with_Apache_Hudi_and_Glue_40_and_query_the_data_using_Athena.md
  website/videoBlog/2022-12-11-Build_Datalakes_on_S3_with_Apache_HUDI_in_a_easy_way_for_Beginners_with_hands_on_labs_Glue.md
  website/videoBlog/2022-12-14-Build_Slowly_Changing_Dimensions_Type_2_SCD2_with_Apache_Spark_and_Apache_Hudi_Hands_on_Labs.md
  website/videoBlog/2022-12-14-Hands_on_Lab_with_using_DynamoDB_as_lock_table_for_Apache_Hudi_Data_Lakes.md
  website/videoBlog/2022-12-14-How_to_convert_Existing_data_in_S3_into_Apache_Hudi_Transaction_Datalake_with_Glue_Hands_on_Lab.md
  website/videoBlog/2022-12-15-Build_production_Ready_Real_Time_Transaction_Hudi_Datalake_from_DynamoDB_Streams_using_Glue_kinesis.md
  website/videoBlog/2022-12-17-Migrate_Certain_Tables_from_ONPREM_DB_using_DMS_into_Apache_Hudi_Transaction_Datalake_with_GlueDemo.md
  website/videoBlog/2022-12-17-Step_by_Step_Guide_on_Migrate_Certain_Tables_from_DB_using_DMS_into_Apache_Hudi_Transaction_Datalake.md
  website/videoBlog/2022-12-18-InsertUpdateReadWriteSnapShot_Time_Travel_incremental_Query_on_Apache_Hudi_datalake_S3.md
  website/videoBlog/2022-12-19-Build_Production_Ready_Alternative_Data_Pipeline_from_DynamoDB_to_Apache_Hudi_PROJECT_DEMO.md
  website/videoBlog/2022-12-19-Build_Production_Ready_Alternative_Data_Pipeline_from_DynamoDB_to_Apache_Hudi_Step_by_Step_Guide.md
  website/videoBlog/2022-12-20-Getting_started_with_Kafka_and_Glue_to_Build_Real_Time_Apache_Hudi_Transaction_Datalake.md
  website/videoBlog/2022-12-21-Learn_Schema_Evolution_in_Apache_Hudi_Transaction_Datalake_with_hands_on_labs.md
  website/videoBlog/2022-12-23-Apache_Hudi_with_DBT_Hands_on_LabTransform_Raw_Hudi_tables_with_DBT_and_Glue_Interactive_Session.md
  website/videoBlog/2022-12-24-Apache_Hudi_on_Windows_Machine_Spark_33_and_hadoop27_Step_by_Step_guide_and_Installation_Process.md
  website/videoBlog/2022-12-24-Lets_Build_Streaming_Solution_using_Kafka_PySpark_and_Apache_HUDI_Hands_on_Lab_with_code.md
  website/videoBlog/2022-12-27-Bring_Data_from_Source_using_Debezium_with_CDC_into_Kafka_S3Sink_Build_Hudi_Datalake_Hands_on_lab.md
  website/videoBlog/2022-12-28-Comparing_Apache_Hudi_s_MOR_and_COW_Tables_Use_Cases_from_Uber.md
  website/videoBlog/2022-12-30-Step_by_Step_guide_how_to_setup_VPC_Subnet_Get_Started_with_HUDI_on_EMR_Installation_Guide.md
  website/videoBlog/2023-01-01-Streaming_ETL_using_Apache_Flink_joining_multiple_Kinesis_streams_Demo.md
  website/videoBlog/2023-01-01-Transaction_Hudi_Data_Lake_with_Streaming_ETL_from_Multiple_Kinesis_Streams_Joining_using_Flink.md
  website/videoBlog/2023-01-11-Great_ArticleApache_Hudi_vs_Delta_Lake_vs_Apache_Iceberg_Lakehouse_Feature_Comparison_by_OneHouse.md
  website/videoBlog/2023-01-12-Build_Real_Time_Streaming_Pipeline_with_Apache_Hudi_Kinesis_and_Flink_Hands_on_Lab.md
  website/videoBlog/2023-01-13-Build_Real_Time_Low_Latency_Streaming_pipeline_from_DynamoDB_to_Apache_Hudi_using_Kinesis_FlinkLab.md
Labels: docs
