Repository apache/hudi, pull requests merged in 2023-01, with the labels that each got.

#4966 [HUDI-3572]support DAY_ROLLING strategy in ClusteringPlanPartitionFilterMode
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanPartitionFilter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanPartitionFilterMode.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestSparkClusteringPlanPartitionFilter.java
Labels: priority:major, table-service

#7588 [HUDI-5489] Flink offline compactor throws exception in service mode
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/HoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
Labels: priority:major, flink, table-service

#7561 [HUDI-5477] Optimize timeline loading in Hudi sync client
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Labels: meta-sync, priority:critical

#7448 [HUDI-5160] Fix data source write save as table
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieOptionConfig.scala
Labels: priority:minor, spark-sql

#7435 [MINOR] Fix parameter parsing in hudi utilities
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
Labels: utilities

#7568 [HUDI-5341] CleanPlanner retains earliest commits must not be later than earliest pending commit
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
Labels: priority:critical, table-service

#7624 [DOCS] Add new committers to Team page
  website/community/team.md
Labels: docs

#7609 [HUDI-5504]Fix concurrency conflict when asyncCompaction is enabled
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactOperator.java
Labels: priority:critical, flink, table-service

#7573 [HUDI-5484] Avoid using `GenericRecord` in `HoodieColumnStatMetadata`
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDataSourceUtils.java
Labels: priority:blocker

#7625 [HUDI-5515] Fix concurrency conflict in ClusteringOperator when process latency marker
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
Labels: priority:critical, flink, table-service

#7372 [HUDI-5326] Fix clustering group building in SparkSizeBasedClusteringPlanStrategy
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/SparkSizeBasedClusteringPlanStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSortAndSizeExecutionStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/clustering/plan/strategy/TestSparkSizeBasedClusteringPlanStrategy.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestLayoutOptimization.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: priority:critical, spark, release-0.12.2

#7605 [HUDI-5349] Clean up partially failed restore
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/BaseRestoreActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/CopyOnWriteRestoreActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/MergeOnReadRestoreActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/restore/RestoreUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RestorePlanActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestClientRollback.java
  hudi-common/src/main/avro/HoodieRestorePlan.avsc
Labels: priority:blocker, metadata

#7580 [HUDI-5434] Fix archival in metadata table to not rely on completed rollback or clean in data table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
Labels: priority:critical, metadata

#7631 [MINOR] Remove useless RollbackTimeline
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/RollbacksCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestRollbacksCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestCommitsCommand.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowRollbacksProcedure.scala
Labels: priority:minor, timeline-server

#7365 [HUDI-5317] Fix insert overwrite table for partitioned table
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieInternalV2Table.scala
Labels: priority:critical, spark-sql

#7641 [MINOR] Fix flaky tests in ITTestHoodieDataSource caused by unordered hashmap
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Labels: priority:minor, flink-sql, test-coverage

#7640 [HUDI-5514] Add in support for a keyless workflow
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeylessKeyGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeylessKeyGenerator.java
  hudi-client/hudi-client-common/src/test/resources/keyless_schema.avsc
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
Labels: priority:blocker, writer-core

#7639 Update docs
  website/blog/2023-01-11-Apache-Hudi-vs-Delta-Lake-vs-Apache-Iceberg-Lakehouse-Feature-Comparison.mdx
  website/docs/hoodie_deltastreamer.md
  website/versioned_docs/version-0.10.0/writing_data.md
  website/versioned_docs/version-0.10.1/writing_data.md
  website/versioned_docs/version-0.11.0/writing_data.md
  website/versioned_docs/version-0.11.1/writing_data.md
  website/versioned_docs/version-0.12.0/writing_data.md
  website/versioned_docs/version-0.12.1/writing_data.md
  website/versioned_docs/version-0.12.2/writing_data.md
  website/versioned_docs/version-0.5.3/writing_data.md
  website/versioned_docs/version-0.6.0/writing_data.md
  website/versioned_docs/version-0.7.0/writing_data.md
  website/versioned_docs/version-0.8.0/writing_data.md
  website/versioned_docs/version-0.9.0/writing_data.md
Labels: docs

#7618 [MINOR] Polish README and template.md in RFC.
  rfc/README.md
  rfc/template.md
Labels: docs, priority:minor

#7585 [HUDI-5545] Extending support to other special characters
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/S3EventsMetaSelector.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestS3EventsMetaSelector.java
Labels: priority:critical, deltastreamer

#7637 [HUDI-5538] Fix ContinuousFileSource and ITTestDataStreamWrite for flink 1.16 support
  azure-pipelines.yml
  hudi-examples/hudi-examples-flink/src/main/java/org/apache/hudi/examples/quickstart/source/ContinuousFileSource.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/JsonDeserializationFunction.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/source/ContinuousFileSource.java
Labels: priority:minor, flink

#7646 [HUDI-5542] Add javadocs for InternalSchemaManager
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/InternalSchemaManager.java
Labels: docs

#7518 [MINOR] Fix minor issues in HoodieMetadataTableValidator docs
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: docs

#7621 [HUDI-5512] fix spark call procedure run_bootstrap missing conf and c…
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunBootstrapProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestBootstrapProcedure.scala
Labels: priority:minor, spark-sql

#5064 [HUDI-3654] Add new module `hudi-metaserver`
  .github/workflows/bot.yml
  .gitignore
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetaserverConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ReflectionUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/RetryHelper.java
  hudi-platform-service/hudi-metaserver/README.md
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/pom.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/HoodieTableMetaserverClient.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/timeline/HoodieMetaserverBasedTimeline.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/view/HoodieMetaserverFileSystemView.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/client/HoodieMetaserverClient.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/client/HoodieMetaserverClientImp.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/client/HoodieMetaserverClientProxy.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/util/EntityConversions.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/test/java/org/apache/hudi/metaserver/client/TestHoodieMetaserverClient.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/bin/start_hudi_metaserver.sh
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/pom.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/HoodieMetaserver.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/HoodieMetaserverProxyHandler.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/HoodieMetaserverService.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/TableService.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/TimelineService.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/MetaserverStorage.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/RelationalDBBasedStorage.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/bean/InstantBean.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/bean/TableBean.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/BasicDao.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/BatchDaoOperation.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/HikariDataSourceFactory.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/SqlSessionFactoryUtils.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/WrapperDao.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/util/MetaserverTableUtils.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/util/TServerSocketWrapper.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/hikariPool.properties
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/mybatis-config.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/mybatis/DDLMapper.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/mybatis/TableMapper.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/mybatis/TimelineMapper.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/test/java/org/apache/hudi/metaserver/TestHoodieMetaserver.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/test/java/org/apache/hudi/metaserver/store/TestRelationalDBBasedStore.java
  hudi-platform-service/hudi-metaserver/pom.xml
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_binary.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_docker.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_mac_m1.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/hudi-metaserver.thrift
  hudi-platform-service/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-metaserver-server-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  pom.xml
Labels: priority:blocker, big-needle-movers

#7682 [MINOR] Add database config for flink
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
Labels: priority:minor, flink

#7571 [HUDI-4710]Fix flaky: TestKeyRangeLookupTree#testFileGroupLookUpManyEntriesWithSameStartValue
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestKeyRangeLookupTree.java
Labels: priority:major

#6732 [HUDI-4148] Add client for hudi table service manager
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieTableServiceManagerClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/RunsTableService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaTableServiceClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/HoodieSparkClusteringClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestClientRollback.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieTableServiceManagerConfig.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/HoodieFlinkClusteringJob.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ClusteringUtil.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/SparkRDDWriteClientOverride.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/DeltaSync.java
Labels: priority:blocker, big-needle-movers, table-service

#7544 [HUDI-5433] Fix the way we deduce the pending instants for MDT writes
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Labels: priority:blocker, metadata

#7582 [HUDI-5488] Make sure Disrupt queue start first, then insert records
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/BaseHoodieQueueBasedExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/DisruptorExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/DisruptorMessageQueue.java
Labels: priority:blocker, writer-core

#6782 [HUDI-4911][HUDI-3301] Fixing `HoodieMetadataLogRecordReader` to avoid flushing cache for every lookup
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestRepairsCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/common/table/log/HoodieFileSliceReader.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/HoodieLogCompactionPlanGenerator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMergedLogRecordReader.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieRecord.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestBitCaskDiskMap.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestExternalSpillableMap.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestRocksDbBasedMap.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestRocksDbDiskMap.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala
Labels: performance, priority:blocker, writer-core, metadata, reader-core

#7612 [HUDI-5336] Fixing log file pattern match to ignore extraneous files
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormatAppendFailure.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
Labels: priority:blocker, writer-core

#7677 [HUDI-5559] Support CDC for flink bounded source
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/factory/CollectSinkTableFactory.java
Labels: priority:critical, flink, incremental-etl

#7626 [HUDI-5516] Reduce memory footprint on workload with thousand active partitions
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkWriteHandleFactory.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactOperator.java
Labels: performance, priority:blocker, flink

#7423 [HUDI-5384] Adding optimization rule to appropriately push down filters into the `HoodieFileIndex`
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystExpressionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/util/TablePathUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/HoodieSparkSessionExtension.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodiePruneFileSourcePartitions.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestNestedSchemaPruningOptimization.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestHoodiePruneFileSourcePartitions.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystExpressionUtils.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystExpressionUtils.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystExpressionUtils.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystExpressionUtils.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystExpressionUtils.scala
Labels: priority:blocker, spark, spark-sql

#7607 [HUDI-5499] Fixing Spark SQL configs not being properly propagated for CTAS and other commands
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HiveSyncProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: priority:blocker, spark-sql

#7721 [MINOR] Disable async clean in testCleanerDeleteReplacedDataWithArchive
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker

#7490 [HUDI-5407][HUDI-5408] Fixing rollback in MDT to be eager
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, metadata

#7512 [HUDI-5417] support to read avro from non-legacy map/list in parquet log
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroParquetReader.java
  hudi-common/src/main/java/org/apache/parquet/avro/HoodieAvroParquetReaderBuilder.java
  hudi-common/src/main/java/org/apache/parquet/avro/HoodieAvroReadSupport.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Labels: priority:blocker

#7702 [HUDI-5579] Fixing Kryo registration to be properly wired into Spark sessions
  README.md
  docker/demo/config/spark-defaults.conf
  docker/demo/config/test-suite/templates/spark_command.txt.template
  hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkTempViewProvider.java
  hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java
  hudi-cli/src/test/java/org/apache/hudi/cli/functional/CLIFunctionalTestHarness.java
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-java-client/pom.xml
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/providers/SparkProvider.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/config/SerializableConfiguration.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieCommonKryoRegistrar.java
  hudi-common/src/main/java/org/apache/hudi/common/util/SerializationUtils.java
  hudi-examples/bin/hudi-delta-streamer
  hudi-examples/hudi-examples-common/pom.xml
  hudi-examples/hudi-examples-java/pom.xml
  hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/common/HoodieExampleSparkUtils.java
  hudi-examples/hudi-examples-spark/src/test/java/org/apache/hudi/examples/quickstart/TestHoodieSparkQuickstart.java
  hudi-examples/hudi-examples-spark/src/test/python/HoodiePySparkQuickstart.py
  hudi-flink-datasource/hudi-flink/pom.xml
  hudi-hadoop-mr/pom.xml
  hudi-integ-test/README.md
  hudi-kafka-connect/pom.xml
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaApp.java
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaGenerateApp.java
  hudi-spark-datasource/hudi-spark/src/test/java/HoodieJavaStreamingApp.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestTableSchemaResolverWithSparkSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/BoundInMemoryExecutorBenchmark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/CowTableReadBenchmark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/ReadAndWriteWithoutAvroBenchmark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestBootstrapProcedure.scala
  hudi-sync/hudi-sync-common/pom.xml
  hudi-timeline-service/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotCopier.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieRepairTool.java
  packaging/bundle-validation/conf/spark-defaults.conf
  packaging/hudi-cli-bundle/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/README.md
  pom.xml
Labels: priority:blocker, spark

#7728 [HUDI-5596] Fix hudi-cli-bundle startup issue with gson
  hudi-cli/src/main/java/org/apache/hudi/cli/Main.java
  packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh
Labels: priority:blocker, cli

#7731 [MINOR] Fix flink 1.15 build profile
  pom.xml
Labels: priority:blocker, flink

#7670 [HUDI-5555] set class-loader in parquet data block
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
Labels: priority:blocker

#7232 [HUDI-5235] clustering target size should larger than small file limit
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
Labels: priority:major, flink

#7741 [MINOR] Fixing FS `InputStream` leaks
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
Labels: priority:minor, writer-core

#7739 [HUDI-5593] Fixing deadlocks due to async cleaner interplay w/ main thread
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker

#7371 [HUDI-3673] Clean up hbase shading dependencies
  packaging/hudi-aws-bundle/pom.xml
  packaging/hudi-datahub-sync-bundle/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-gcp-bundle/pom.xml
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-hive-sync-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-timeline-server-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
  pom.xml
Labels: dependencies, priority:major

#7726 [HUDI-5575] Adding/Fixing auto generation of record keys w/ hudi
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/ComplexAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/CustomAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/GlobalAvroDeleteKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/NonpartitionedAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/SimpleAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestAutoRecordKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/ComplexKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/CustomKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/GlobalDeleteKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/NonpartitionedKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/SimpleKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/TimestampBasedKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
  hudi-common/src/main/java/org/apache/hudi/keygen/AutoRecordKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/keygen/BaseKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestComplexKeyGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestSimpleKeyGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAutoRecordKeyGeneration.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker, writer-core

#7543 [HUDI-5401] Ensure user-provided hive metastore uri is set in HiveConf if not already set
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  packaging/bundle-validation/spark_hadoop_mr/write.scala
Labels: meta-sync, priority:blocker

#7461 [HUDI-5392] Fixing Bootstrapping flow handling of arrays
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/MergingIterator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala
Labels: priority:blocker

#7727 [HUDI-2608] Support json schema in SchemaRegistryProvider
  hudi-common/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/converter/JsonToAvroSchemaConverter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/converter/TestJsonToAvroSchemaConverter.java
  hudi-utilities/src/test/resources/schema-provider/json/enum-properties/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/enum-properties/input.json
  hudi-utilities/src/test/resources/schema-provider/json/example-address/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/example-address/input.json
  hudi-utilities/src/test/resources/schema-provider/json/example-calendar/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/example-calendar/input.json
  hudi-utilities/src/test/resources/schema-provider/json/example-card/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/example-card/input.json
  hudi-utilities/src/test/resources/schema-provider/json/example-geographical-location/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/example-geographical-location/input.json
  hudi-utilities/src/test/resources/schema-provider/json/multiple-properties/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/multiple-properties/input.json
  hudi-utilities/src/test/resources/schema-provider/json/nested-properties/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/nested-properties/input.json
  hudi-utilities/src/test/resources/schema-provider/json/single-properties/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/single-properties/input.json
Labels: priority:blocker

#7528 [HUDI-5443] Fixing exception trying to read MOR table after `NestedSchemaPruning` rule has been applied
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystExpressionUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/AvroProjection.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BaseFileOnlyRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SafeAvroProjection.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSource.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestNestedSchemaPruningOptimization.scala
Labels: priority:blocker, spark, spark-sql

#7709 [HUDI-5582] Do not let users override internal metadata configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
Labels: priority:blocker, metadata

#6830 [HUDI-2118] Skip checking corrupt log blocks for transactional write file systems
  hudi-common/src/main/java/org/apache/hudi/common/fs/StorageSchemes.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Labels: performance, priority:blocker, reader-core

#7576 [HUDI-4991] Allow kafka-like configs to set truststore and keystore for the SchemaProvider
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
Labels: priority:blocker

#7747 Revert "[HUDI-5575] Adding/Fixing auto generation of record keys w/ hudi (#7726)"
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/ComplexAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/CustomAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/GlobalAvroDeleteKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/NonpartitionedAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/SimpleAvroKeyGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestAutoRecordKeyGenerator.java
  hudi-client/hudi-client-common/src/test/resources/keyless_schema.avsc
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/ComplexKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/CustomKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/GlobalDeleteKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/NonpartitionedKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/SimpleKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/TimestampBasedKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
  hudi-common/src/main/java/org/apache/hudi/keygen/AutoRecordKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/keygen/BaseKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestComplexKeyGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestSimpleKeyGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAutoRecordKeyGeneration.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:blocker

#7746 [HUDI-5610] Fix hudi-cli-bundle startup conflict for spark 3.2.x
  packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh
  packaging/hudi-cli-bundle/pom.xml
Labels: priority:blocker, cli

#7722 [HUDI-5594] Add metaserver bundle validation
  .github/workflows/bot.yml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetaserverConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/pom.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/HoodieTableMetaserverClient.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/common/table/timeline/HoodieMetaserverBasedTimeline.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/client/HoodieMetaserverClient.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/client/HoodieMetaserverClientImp.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/src/main/java/org/apache/hudi/metaserver/client/HoodieMetaserverClientProxy.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/pom.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/HoodieMetaserver.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/HoodieMetaserverPreparations.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/HoodieMetaserverGateway.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/HoodieMetaserverProxyHandler.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/TableService.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/service/TimelineService.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/MetaserverStorage.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/RelationalDBBasedStorage.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/bean/InstantBean.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/bean/TableBean.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/BatchDaoOperation.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/hikariPool.properties
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/mybatis/DDLMapper.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/mybatis/TableMapper.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/test/java/org/apache/hudi/metaserver/store/TestRelationalDBBasedStore.java
  hudi-platform-service/hudi-metaserver/pom.xml
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_docker.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/bin/thrift_in_mac_m1.sh
  hudi-platform-service/hudi-metaserver/src/main/thrift/hudi-metaserver.thrift
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  packaging/bundle-validation/ci_run.sh
  packaging/bundle-validation/service/read.scala
  packaging/bundle-validation/service/write.scala
  packaging/bundle-validation/validate.sh
  packaging/hudi-metaserver-server-bundle/pom.xml
Labels: priority:blocker

#7749 [HUDI-5620] Fix bundle validation early exiting issue
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetaserverConfig.java
  packaging/bundle-validation/service/read.scala
  packaging/bundle-validation/validate.sh
Labels: priority:blocker

#7750 [HUDI-5617] Rename configs for async conflict detector for clarity
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/conflict/detection/TimelineServerBasedDetectionStrategy.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/AsyncTimelineServerBasedDetectionStrategy.java
Labels: priority:blocker

#7751 [HUDI-5618] Add `since version` to new configs for 0.13.0 release
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetaserverConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieTableServiceManagerConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfigHolder.java
Labels: docs, priority:blocker

#7723 [HUDI-5363] Removing default value for shuffle parallelism configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseBulkInsertHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseDeleteHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseWriteHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieDeleteHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/ParallelismHelper.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkDeleteHelper.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/FlinkWriteHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaBulkInsertHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaDeleteHelper.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/JavaWriteHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBulkInsertHelper.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/JFunction.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieUnsafeUtils.scala
Labels: priority:blocker

#7445 [HUDI-5380] Fixing change table path but table location in metastore …
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ConfigUtils.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SparkDataSourceTableUtils.java
Labels: meta-sync, priority:critical, hive

#7690 [HUDI-5485] Add File System View API for batch listing and improve savepoint performance with metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/savepoint/SavepointActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSavepoint.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestBase.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataFileSystemView.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/BaseFileHandler.java
Labels: priority:blocker

#7720 [HUDI-5592] Fixing some of the flaky tests in CI
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
Labels: priority:critical

#7701 [DOCS] Add more video resources to the website
  website/src/pages/videos.md
Labels: docs

#7762 [HUDI-5627] Improve the usability of Hudi CLI bundle
  packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh
Labels: priority:blocker, cli

#7758 [HUDI-5623] Increase default time to wait between retries by lock provider client
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
Labels: priority:blocker

#7476 [HUDI-5023] Switching default Write Executor type to `SIMPLE`
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/HoodieLazyInsertIterable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/ExecutorFactory.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/execution/FlinkLazyInsertIterable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/execution/JavaLazyInsertIterable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/SparkLazyInsertIterable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestBoundedInMemoryExecutorInSpark.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestBoundedInMemoryQueue.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorExecutionInSpark.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestSimpleExecutionInSpark.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/BoundedInMemoryExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/DisruptorExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/DisruptorMessageQueue.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/ExecutorType.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/SimpleExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/util/queue/WaitStrategyFactory.java
Labels: performance, priority:blocker

#7768 [HUDI-5630] Fixing flaky parquet projection tests
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Labels: priority:blocker

#7774 [MINOR] Add `hudi-platform-service` and `hudi-metaserver-server-bundle` to root pom
  pom.xml
Labels: priority:blocker

#7775 [HUDI-5635] Fix release scripts
  scripts/release/cut_release_branch.sh
  scripts/release/deploy_staging_jars.sh
  scripts/release/validate_staged_bundles.sh
Labels: priority:blocker

#7779 [MINOR] Add missing Apache License in source files
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/resources/mybatis-config.xml
  hudi-utilities/src/test/resources/schema-provider/proto/oneof_schema.avsc
  hudi-utilities/src/test/resources/schema-provider/proto/parent_schema_recursive_default_limit.avsc
  hudi-utilities/src/test/resources/schema-provider/proto/parent_schema_recursive_depth_2.avsc
  hudi-utilities/src/test/resources/schema-provider/proto/sample_schema_defaults.avsc
  hudi-utilities/src/test/resources/schema-provider/proto/sample_schema_wrapped_and_timestamp_as_record.avsc
  packaging/hudi-metaserver-server-bundle/pom.xml
Labels: priority:blocker

#7780 [MINOR] Fix validate_staged_release.sh
  scripts/release/validate_staged_release.sh
Labels: priority:blocker

#7760 [HUDI-5626] Rename CDC logging mode options
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCInferCase.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCSupplementalLoggingMode.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/HoodieCDCTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCStreamingSuite.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCDCForSparkSQL.scala
Labels: priority:blocker

#7773 [MINOR] Skip docs generation for table service manager
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieTableServiceManagerConfig.java
Labels: priority:blocker

#7782 Revert "[MINOR] Add `hudi-platform-service` and `hudi-metaserver-server-bundle` to root pom"
  pom.xml
Labels: priority:blocker

#7770 [HUDI-5631] Improve defaults of early conflict detection configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
Labels: priority:blocker, writer-core, multi-writer

#7759 [HUDI-5624] Fix HoodieAvroRecordMerger to use new precombine API
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecordMerger.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartialUpdateAvroPayload.scala
Labels: priority:blocker

#7764 [HUDI-5628] Fixing log record reader scan V2 config name
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/CompactionExecutionHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/LogCompactionExecutionHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/HoodieLogCompactionPlanGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/reader/DFSHoodieDatasetInputReader.java
Labels: priority:blocker

#7785 [HUDI-5638] Fix metaserver test setup
  azure-pipelines.yml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-client/pom.xml
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/pom.xml
  hudi-platform-service/hudi-metaserver/pom.xml
  pom.xml
Labels: priority:blocker

#7784 [HUDI-5640] Add missing profiles in `deploy_staging_jars.sh`
  scripts/release/deploy_staging_jars.sh
Labels: priority:blocker

#7783 [HUDI-5639] Fixing stream identifier for single writer with spark streaming ingest
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
Labels: priority:blocker

#7777 [MINOR] Fix `HoodieCDCRDD` setting flag `usesVirtualKeys`
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
Labels: priority:blocker, spark-sql

#7608 [HUDI-5503] Optimize flink table factory option check
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableFactory.java
Labels: priority:critical, writer-core, flink

#7772 [MINOR] Cleaning up recently introduced configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/ExecutorFactory.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorExecutionInSpark.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/TestDisruptorMessageQueue.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/analysis/TestHoodiePruneFileSourcePartitions.scala
Labels: priority:blocker

#7781 [HUDI-5637] Add Kryo for hive sync
  packaging/hudi-hive-sync-bundle/pom.xml
Labels: meta-sync, priority:blocker

#7410 [HUDI-5634] Rename CDC related classes
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCFileSplit.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCInferenceCase.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
  rfc/rfc-51/rfc-51.md
Labels: priority:blocker

#7790 [HUDI-5632] Fix failure launching Spark jobs from `hudi-cli-bundle`
  hudi-cli/src/main/java/org/apache/hudi/cli/utils/SparkUtil.java
Labels: priority:blocker, cli

#7797 [MINOR] Make `data_before_after` the default cdc logging mode
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
Labels: priority:blocker

#7679 [HUDI-5563] Check table exist before drop table
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestDropTable.scala
Labels: priority:minor, spark-sql

#7685 [HUDI-5568] incorrect use of fileSystemView
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
Labels: priority:blocker, writer-core, flink

#7799 [HUDI-5655] Closing write client for spark ds writer in all cases
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: priority:blocker

#7798 [HUDI-5654] Fixing reading of empty rollback completed meta files from data table timeline
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
Labels: priority:blocker

#7761 [MINOR] Standardise schema concepts on Flink Engine
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/InternalSchemaUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/InternalSchemaManager.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/RecordIterators.java
Labels: schema-and-data-types, priority:minor, writer-core

#7769 [HUDI-5633] Fixing performance regression in `HoodieSparkRecord`
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/execution/HoodieLazyInsertIterable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieBootstrapHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/ExecutorFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/SparkLazyInsertIterable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkParquetReader.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkParquetWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/BuiltinKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/BaseBootstrapMetadataHandler.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/OrcBootstrapMetadataHandler.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/ParquetBootstrapMetadataHandler.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/util/HoodieSparkRecordUtils.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieInternalRowUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieUnsafeRowUtils.scala
  hudi-client/hudi-spark-client/src/test/scala/org/apache/spark/sql/TestHoodieUnsafeRowUtils.scala
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieEmptyRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/MetadataValues.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieInternalRowUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieInternalRowUtils.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: performance, priority:blocker
