Repository apache/hudi, pull requests merged in 2024-12, with the labels that each got.

#12381 [DOCS] add new committer to the Team page
  website/community/team.md
Labels: docs, size:XS

#12380 [HUDI-8609] always read partition column from file if it is the precombine
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestCreateTable.scala
Labels: size:M

#12386 [DOCS] Update storage layouts, write operations and table/query types
  site-image-source/hudi-table-query-type.excalidraw
  site-image-source/incr-vs-batch-write.excalidraw
  site-image-source/kafka-connect-txn.excalidraw
  website/docs/file_layouts.md
  website/docs/flink-quick-start-guide.md
  website/docs/hudi_stack.md
  website/docs/indexes.md
  website/docs/ingestion_kafka_connect.md
  website/docs/key_generation.md
  website/docs/metadata.md
  website/docs/metadata_indexing.md
  website/docs/overview.mdx
  website/docs/record_payload.md
  website/docs/storage_layouts.md
  website/docs/table_types.md
  website/docs/timeline.md
  website/docs/use_cases.md
  website/docs/write_operations.md
  website/docusaurus.config.js
  website/sidebars.js
  website/src/pages/tech-specs-1point0.md
  website/static/assets/images/hudi-table-query-type.png
  website/static/assets/images/incr-vs-batch-writes.png
  website/static/assets/images/kafka-connect-txn.png
  website/versioned_docs/version-0.14.1/flink-quick-start-guide.md
  website/versioned_docs/version-0.14.1/overview.mdx
  website/versioned_docs/version-0.14.1/use_cases.md
  website/versioned_docs/version-0.14.1/write_operations.md
  website/versioned_docs/version-0.15.0/flink-quick-start-guide.md
  website/versioned_docs/version-0.15.0/overview.mdx
  website/versioned_docs/version-0.15.0/use_cases.md
  website/versioned_docs/version-0.15.0/write_operations.md
Labels: docs, size:XL

#12376 [HUDI-8606] Use spark engineContext to parallelize secondary keys lookup
  azure-pipelines-20230430.yml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
Labels: size:S

#12377 [HUDI-8611] Improve metadata index config docs
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
Labels: size:S

#12385 [HUDI-8602] Fix a bug for incremental query
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/TestIncrementalQueryWithArchivedInstants.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadWithFullTableScan.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:M

#12391 [HUDI-7503] Not allowing start time earlier than active timeline with CDC queries
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
Labels: size:S

#12392 [HUDI-8619] Add checkpoint translation for Spark streaming source
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieStreamingSink.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieSourceOffset.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV1.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
Labels: size:L

#12272 [MINOR] Remove extra timeline reload during conflict resolution
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java
Labels: size:S

#12401 [HUDI-8619] Use new config for streaming source table version
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
Labels: size:S

#12411 [DOCS] Updating first pass of concurrency control, indexes, and metad…
  site-image-source/commit-time-ordering-merge-mode.excalidraw
  site-image-source/event-time-ordering-merge-mode.excalidraw
  website/docs/concurrency_control.md
  website/docs/indexes.md
  website/docs/metadata.md
  website/docs/record_merger.md
  website/docs/record_payload.md
  website/sidebars.js
  website/static/assets/images/commit-time-ordering-merge-mode.png
  website/static/assets/images/event-time-ordering-merge-mode.png
Labels: docs, size:XL

#12409 [DOCS] Add indexing examples and info for 1.0
  website/docs/metadata_indexing.md
  website/docs/quick-start-guide.md
  website/docs/sql_ddl.md
  website/docs/sql_queries.md
Labels: docs, size:M

#12415 [HUDI-8619] Fix stream source parameters
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
Labels: size:S

#12418 [HUDI-8619] fix a bug for checkpoint translation
  hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/CheckpointUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/checkpoint/TestCheckpointUtils.java
Labels: size:S

#12416 [HUDI-8643] Filter records for from_unixtime function with expression index
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
Labels: size:L

#12419 [HUDI-8633] Fix a flaky test for partition stats
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
Labels: size:XS

#12390 [HUDI-8552] Add a new merge handle based on file group reader for compaction in Spark
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/EngineBroadcastManager.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieCompactionHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileWriterFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/SparkBroadcastManager.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/compact/HoodieSparkMergeOnReadTableCompactor.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieEngineContext.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieReadStats.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/ObjectInspectorCache.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/pom.xml
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestMultiWriterWithPreferWriterIngestion.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestConsistentBucketIndex.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestDataValidationCheckForLogCompactionActions.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestSavepointRestoreMergeOnRead.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestInlineCompaction.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableIncrementalRead.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestSparkNonBlockingConcurrencyControl.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestSpark35RecordPositionMetadataColumn.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: size:L

#12410 [HUDI-8639] Support filter by partitions in ShowInvalidParquetProcedure
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowInvalidParquetProcedure.scala
Labels: size:M

#12425 [MINOR] fix the wrong class parameter type
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
Labels: size:XS

#12417 [MINOR] Pass in engine context from StreamSync to dedupe
  hudi-spark-datasource/hudi-spark-common/pom.xml
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:S

#12424 [HUDI-8653] Disable record position generation with NBCC or during pending compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
Labels: size:M

#12422 [HUDI-8652] Throw exception in unsupported scenarios with partial updates in MIT
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
Labels: size:S

#12426 [HUDI-8552] Adding support to read input for clustering based on new FG reader
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/SparkBroadcastManager.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/util/AvroSchemaCache.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReaderBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
Labels: size:L

#12427 [HUDI-8659] Remove ENUM type check and add other fixes for file group reader-based compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/GenericRecordValidationTestUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieReadStats.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
Labels: size:L

#12431 [MINOR] Fix README and CI fir min Spark 3.3 patch version support
  .github/workflows/bot.yml
  README.md
  release/release_guide.md
Labels: size:XS

#12437 [MINOR] Update README version description
  README.md
Labels: size:S

#12440 [HUDI-8671][DOCS] Improve record merger docs
  website/docs/record_merger.md
Labels: docs, size:S

#12439 [HUDI-8672][DOCS] Update configuration docs based on release-1.0.0 branch
  website/docs/basic_configurations.md
  website/docs/configurations.md
Labels: docs, size:XL

#12420 [DOCS] Refine quickstart docs further for 1.0
  website/docs/gcp_bigquery.md
  website/docs/indexes.md
  website/docs/metadata_indexing.md
  website/docs/performance.md
  website/docs/quick-start-guide.md
  website/docs/sql_ddl.md
  website/docs/sql_dml.md
  website/docs/sql_queries.md
  website/static/assets/images/bloom-filter-expression-index-with-pruning.png
  website/static/assets/images/bloom-filter-expression-index-without-pruning.png
  website/static/assets/images/column-stat-expression-index-with-pruning.png
  website/static/assets/images/column-stat-expression-index-without-pruning.png
  website/static/assets/images/partition-stat-index-with-pruning.png
  website/static/assets/images/partition-stat-index-without-pruning.png
  website/static/assets/images/secondary-index-with-pruning.png
  website/static/assets/images/secondary-index-without-pruning.png
Labels: docs, size:L

#12444 [MINOR] Improve config docs to avoid build errors
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/S3EventsHoodieIncrSourceConfig.java
Labels: size:S

#12446 [HUDI-8674] Fix Flink build in CI to be consistent with release script
  .github/workflows/bot.yml
Labels: size:S

#12066 [HUDI-8362] Fix DebeziumSource to always returning dataframe with schema
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestAbstractDebeziumSource.java
Labels: size:S

#12359 [MINOR] Only getCompletionTime for completedInstants
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
Labels: size:XS

#12225 [HUDI-8497]Check consistency between pk statement and option when create table using HoodieHiveCatalog
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: size:S

#12459 [Docs] Update hoodie_cleaner.md , Spelling correction and cli command example correction
  website/versioned_docs/version-0.15.0/hoodie_cleaner.md
Labels: docs, size:XS

#12450 [HUDI-8676] Improve ValidationUtils performance by lazy appending msg
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-io/src/main/java/org/apache/hudi/common/util/ValidationUtils.java
Labels: size:XS

#12462 [MINOR] Update DOAP with 1.0.0 Release
  doap_HUDI.rdf
Labels: size:XS

#12457 [DOCS] Update index related docs for Hudi 1.0
  website/docs/metadata_indexing.md
  website/docs/quick-start-guide.md
  website/docs/sql_ddl.md
  website/docs/sql_queries.md
Labels: docs, size:M

#12443 [HUDI-8670][DOCS] Blog post for non-blocking concurrency control
  website/blog/2024-12-06-non-blocking-concurrency-control.md
  website/static/assets/images/blog/non-blocking-concurrency-control/legacy_file_layout.png
  website/static/assets/images/blog/non-blocking-concurrency-control/lsm_archive_timeline.png
  website/static/assets/images/blog/non-blocking-concurrency-control/new_file_layout.png
Labels: docs, size:M

#12467 [DOCS] Update flink and spark versions for 1.0
  website/docs/flink-quick-start-guide.md
  website/docs/quick-start-guide.md
Labels: docs, size:S

#12469 [Site][Minor]Ignore warning on blog truncation and authors in build
  website/docusaurus.config.js
Labels: docs, size:XS

#12278 [MINOR] Log wheather there has data files to be read in stream read
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
Labels: size:XS

#12277 [HUDI-8537] Alter table operation no need to do rollback for failed writes
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddColumnsCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterTableCommand.scala
Labels: size:M

#12471 [HUDI-8706] Avoid reading partition path from records if not required
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieKeyLocationFetchHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-common/src/main/java/org/apache/hudi/common/util/FileFormatUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/HFileUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/TestParquetUtils.java
Labels: size:S

#12402 [HUDI-8630] Fix convert spark key generator issue
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:S

#12473 [MINOR] Update Maven and Java versions in README
  README.md
Labels: size:XS

#12396 [MINOR] Refactored `Pipelines::bulkInsert`
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Labels: size:S

#12394 [HUDI-8626] fix: using rename to create consistent-hash-metadata file
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bucket/HoodieSparkConsistentBucketIndex.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
Labels: size:S

#12279 [MINOR] Log details when the metadata files are not found.
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java
Labels: size:XS

#11514 [HUDI-7856] Adding RFC-78 for 1.0 migration from 0.x
  rfc/README.md
  rfc/rfc-78/rfc-78.md
Labels: size:L

#12476 [DOCS] Changing metadata, indexed page, adding image for row vs columnar files
  site-image-source/row-col-based-base-file-formats.excalidraw
  website/docs/concurrency_control.md
  website/docs/indexes.md
  website/docs/metadata.md
  website/docs/storage_layouts.md
  website/static/assets/images/metadata_table_anim.gif
  website/static/assets/images/row-col-based-base-file-formats.png
Labels: docs, size:XL

#10814 [HUDI-7146] [RFC-77] RFC for secondary index
  rfc/rfc-77/rfc-77.md
Labels: rfc, size:L

#12449 [DOCS]: Update Write Path diagram
  website/docs/write_operations.md
  website/static/assets/images/write_path_cluster.png
Labels: docs, size:XS

#12478 [HUDI-8296] Improve docs around Hudi Spark support and hudi-utilities-slim-bundle
  website/docs/cleaning.md
  website/docs/cli.md
  website/docs/clustering.md
  website/docs/compaction.md
  website/docs/concurrency_control.md
  website/docs/deployment.md
  website/docs/gcp_bigquery.md
  website/docs/hoodie_streaming_ingestion.md
  website/docs/metadata_indexing.md
  website/docs/migration_guide.md
  website/docs/querying_data.md
  website/docs/quick-start-guide.md
  website/docs/snapshot_exporter.md
  website/docs/syncing_datahub.md
Labels: docs, size:M

#12399 Update docker_demo.md to explicitily use Scala Version 2.11 for the demo build
  website/versioned_docs/version-0.15.0/docker_demo.md
Labels: docs, size:XS

#12475 [DOCS] Add release highlights for 1.0.0 release
  website/docs/concurrency_control.md
  website/docs/deployment.md
  website/docs/sql_ddl.md
  website/docs/sql_dml.md
  website/docs/sql_queries.md
  website/releases/release-1.0.0-beta2.md
  website/releases/release-1.0.0.md
Labels: docs, size:M

#12489 [DOCS] Update spark and flink versions in quickstart
  website/docs/flink-quick-start-guide.md
  website/docs/quick-start-guide.md
  website/versioned_docs/version-1.0.0/flink-quick-start-guide.md
  website/versioned_docs/version-1.0.0/quick-start-guide.md
Labels: docs, size:S

#12482 [MINOR] Avoid scanning raw timeline on archival if no instants to archive
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v2/TimelineArchiverV2.java
Labels: size:S

#12413 [HUDI-8085] Remove guards around Spark 3.3
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestConvertFilterToCatalystExpression.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithCustomKeyGenerator.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/BoundInMemoryExecutorBenchmark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/CowTableReadBenchmark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/ReadAndWriteWithoutAvroBenchmark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestIndexSyntax.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestNestedSchemaPruningOptimization.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTableDropPartition.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestCreateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTableWithNonRecordKeyField.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestRepairTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestTimeTravelTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallCommandParser.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SchedulerConfGenerator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSchedulerConfGenerator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotExporter.java
Labels: size:XL

#12389 [HUDI-8622] fix performance regression of tag when written into consistent bucket index table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieBucketIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieConsistentBucketIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieSimpleBucketIndex.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
Labels: size:M

#12455 [HUDI-8641] Ensure all binary expressions are correctly parsed for data skipping using expression index
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkExpressionIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/expression/ExpressionIndexSparkFunctions.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/expression/HoodieSparkExpressionIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/expression/TestHoodieSparkExpressionIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieIndexDefinition.java
  hudi-common/src/main/java/org/apache/hudi/index/expression/HoodieExpressionIndex.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
Labels: size:XL

#12496 [HUDI-8650] Add test for dropping partition stats
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
Labels: size:S

#12497 [HUDI-8772] Fix NPE when deserialize cleaner plan
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
Labels: meta-sync, spark, bug-fix, size:XS

#12502 [DOCS] Hudi 1.0 Announce blog
  site-image-source/backwards-compat-writing.excalidraw
  site-image-source/expression-index-date-partitioning.excalidraw
  website/blog/2024-12-16-announcing-hudi-1-0-0.md
  website/static/assets/images/backwards-compat-writing.png
  website/static/assets/images/expression-index-date-partitioning.png
  website/static/assets/images/nbcc_partial_updates.gif
Labels: docs, size:XL

#12481 [HUDI-8748] Fix check for whether legacy mode is enabled for file
  hudi-hadoop-common/src/main/java/org/apache/parquet/avro/HoodieAvroReadSupport.java
  hudi-hadoop-common/src/test/java/org/apache/parquet/avro/TestHoodieAvroReadSupport.java
Labels: size:M

#12403 [MINOR] Add test case validating meta-client reload in TransactionUtils
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/utils/TestTransactionUtils.java
Labels: size:S

#12506 [site][MINOR] Update event banner
  website/src/components/EventFeature/index.js
Labels: docs, size:XS

#12500 [MINOR] Reduce logs from marker creation
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
Labels: size:XS

#12344 [HUDI-8590] fix: wrong file path for consistent-bucket-commit-marker-file
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-io/src/main/java/org/apache/hudi/common/util/ValidationUtils.java
Labels: size:S

#12245 [HUDI-8394] Restrict multiple bulk inserts into COW with simple bucket and disabled Spark native row writer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BucketIndexBulkInsertPartitioner.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/keygen/TestKeyGenUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/execution/bulkinsert/TestRDDSimpleBucketBulkInsertPartitioner.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: spark-sql, size:M

#12456 [HUDI-8616] feat(hudi-datahub-sync): improvements
  hudi-sync/hudi-datahub-sync/pom.xml
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubResponseLogger.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubTableProperties.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/util/SchemaFieldsUtil.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestDataHubSyncConfig.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestHoodieDataHubDatasetIdentifier.java
  packaging/hudi-datahub-sync-bundle/pom.xml
Labels: size:XL

#12492 [DOCS] Fix overview banner latest version
  website/i18n/cn/code.json
Labels: docs, size:XS

#12495 [HUDI-8771] Fix Incorrect classification of input paths in InputPathHandler and HoodieInputFormatUtils
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/InputPathHandler.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestInputPathHandler.java
Labels: size:S

#12508 [DOCS] Update secondary index in tech specs
  website/src/pages/tech-specs-1point0.md
Labels: docs, size:S

#12474 [MINOR] refactor: extract the common logic for the bucket-type bulk insert partitioner
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BucketIndexBulkInsertPartitioner.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/BucketSortBulkInsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/ConsistentBucketIndexBulkInsertPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDBucketIndexPartitioner.java
Labels: size:M

#12513 [HUDI-8780] Claiming RFC-83 For Incremental Table Service
  rfc/README.md
Labels: size:XS

#12515 [HUDI-8781] Optimize executor memory usage during executing clustering
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/ConcatenatingIterator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LazyConcatenatingIterator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestLazyConcatenatingIterator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Labels: size:L

#12528 [MINOR] Fix incorrect configuration name "hoodie.metadata.enabled" --> "hoodie.metadata.enable"
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieCopyOnWriteTableInputFormat.java
  hudi-platform-service/hudi-metaserver/README.md
  packaging/bundle-validation/service/read.scala
  packaging/bundle-validation/service/write.scala
Labels: size:XS

#12527 [MINOR] Resolving dependabot warnings
  hudi-sync/hudi-datahub-sync/pom.xml
  packaging/hudi-cli-bundle/pom.xml
  pom.xml
Labels: size:S

#12532 [HUDI-8789] Dropping hbase deps from presto/trino bundle
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
Labels: size:S

#12516 [HUDI-8631] Support of `hoodie.populate.meta.fields` for Flink append mode
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: size:S

#12520 [HUDI-8784] Validate auto key gen for SQL
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAutoKeyGenForSQL.scala
Labels: size:S

#12533 [DOCS] Update current and future release versions in roadmap
  website/src/pages/roadmap.md
Labels: docs, size:S

#12517 [HUDI-8742] Add expression index test with auto keygen
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
Labels: size:S

#12430 [HUDI-8655] Add tests for Schema Cache and Spillable Map
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/hadoop/TestHoodieFileGroupReaderOnHive.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestAvroSchemaCache.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
Labels: size:L

#12534 [HUDI-8792] Fix bug with timeline server reuse overriding client properties
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineServerHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestHoodieJavaWriteClientInsert.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
Labels: size:S

#12543 [MINOR] Modify constants name and adjust getMetricsName function parameter po…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/metrics/HoodieMetaSyncMetrics.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/metrics/TestHoodieMetaSyncMetrics.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerMetrics.java
Labels: size:S

#12447 [HUDI-8648] Fix a bug for secondary index deletion
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexKeyUtils.java
Labels: size:M

#12556 [DOCS][Blog] add 2024 year-end review blog
  website/blog/2024-12-29-apache-hudi-2024-a-year-in-review.mdx
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/community-events.png
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/community-syncs.png
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/cover.jpg
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/hudi-tdg.jpg
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/hudi0to1.png
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/lakehouse-chronicles.png
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/newsletter.png
  website/static/assets/images/blog/2024-12-29-a-year-in-review-2024/pr-history.svg
Labels: docs, size:M
