Repository apache/hudi, pull requests merged in 2024-08, with the labels that each got.

#11703 [HUDI-8033] Claiming RFC-81 for Log Compaction with Merge Sort
  rfc/README.md
Labels: size:XS

#11711 [HUDI-8035] Fetching commit metadata from timeline fails during upgrade
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Labels: size:S

#11716 [DOCS] Added RLI issue fix guidance and known 0.15.0 regression
  website/releases/release-0.15.0.md
  website/versioned_docs/version-0.14.0/troubleshooting.md
  website/versioned_docs/version-0.14.1/troubleshooting.md
  website/versioned_docs/version-0.15.0/troubleshooting.md
Labels: docs, size:S

#11559 [HUDI-7948] RFC-80: Support column families for wide tables
  rfc/rfc-80/append-handle.png
  rfc/rfc-80/bucket.png
  rfc/rfc-80/family-compaction.png
  rfc/rfc-80/file-group.png
  rfc/rfc-80/grand-compaction.png
  rfc/rfc-80/process-read.png
  rfc/rfc-80/process-write.png
  rfc/rfc-80/rfc-80.md
  rfc/rfc-80/row-reader.png
  rfc/rfc-80/table.png
Labels: size:M

#11691 [HUDI-8040] Fix SimpleConcurrentFileWritesConflictResolutionStrategy get pending clustering wrong
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SimpleConcurrentFileWritesConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestConflictResolutionStrategyUtil.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleConcurrentFileWritesConflictResolutionStrategy.java
Labels: size:S

#11722 [HUDI-8041] Support projection push down for lookup join
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: flink, size:XS

#11638 [HUDI-7996] Store partition type with partition fields in table configs
  hudi-aws/src/main/java/org/apache/hudi/config/GlueCatalogSyncClientConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieTableConfigUtils.java
  hudi-common/src/main/java/org/apache/hudi/keygen/BaseKeyGenerator.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/utils/KafkaConnectUtils.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/KafkaConnectTransactionServices.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BootstrapExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:L

#11597 [HUDI-7692] Extract metadata record type to MetadataPartitionType enum
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
Labels: size:L

#11729 [MINOR] Reduce unnecessary code paths
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
Labels: size:XS

#11736 [MINOR] don't run scheduled workflow on forks
  .github/workflows/scheduled_workflow.yml
Labels: size:XS

#11679 [HUDI-7881] Compare bigquery table base path via source-uris if hive partitioning options are not available
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
Labels: size:S

#11728 [HUDI-8043] Fix DDB Lock provider bug
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProviderBase.java
  hudi-aws/src/test/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProviderBaseTest.java
Labels: size:S

#11677 [HUDI-8015] Fix Glue Meta Sync Failure with recreating the table
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
Labels: size:M

#11746 [HUDI-712] Revert back to overwrite=true in HoodieSnapshotExporter
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
Labels: size:XS

#11731 [HUDI-6948] Fix schema evolution for non row writer
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReader.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReaderIterator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
Labels: size:S

#11732 [HUDI-6948] Fix non row writer schema evolution
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReader.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReaderIterator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
Labels: size:S

#11748 [MINOR] improve performance of generateBucketKey
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
Labels: size:XS

#11747 [MINOR] HoodieAvroUtils performance optimization of createFullName method
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
Labels: size:S

#11751 [HUDI-8067] Use exec to run the IT
  docker/setup_demo.sh
  docker/stop_demo.sh
  hudi-integ-test/pom.xml
Labels: size:S

#11754 [Minor] Add Events banner for upcoming Linkedin Live event
  README.md
  website/src/components/EventFeature/index.js
  website/src/pages/index.js
Labels: docs, size:XS

#11759 [DOCS][HUDI-8012] Update docs on checkstyle configuration in IDE setup
  website/contribute/developer-setup.md
  website/static/assets/images/contributing/IDE_setup_checkstyle_1.png
  website/static/assets/images/contributing/IDE_setup_checkstyle_2.png
  website/static/assets/images/contributing/IDE_setup_checkstyle_3.png
  website/static/assets/images/contributing/IDE_setup_checkstyle_4.png
  website/static/assets/images/contributing/IDE_setup_code_style_java_after.png
  website/static/assets/images/contributing/IDE_setup_code_style_java_before.png
Labels: docs, size:S

#11755 [MINOR] avoid repeated write behavior in ut
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
Labels: size:S

#11762 update missing file for blog entry on hudi parquet and orc
  website/static/assets/images/blog/hudi-parquet-orc.png
Labels: docs, size:XS

#11756 [MINOR] Fixed checkstyle in HoodieJavaWriteClientExample
  hudi-examples/hudi-examples-java/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java
Labels: size:S

#11771 [MINOR] Update Azure CI links in README
  README.md
Labels: size:XS

#11757 [MINOR] improve comaction operator shuffle
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanEvent.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Labels: size:S

#11493 [HUDI-7920] Make Spark 3.5 the default build profile for Spark integration
  .github/workflows/bot.yml
  README.md
  azure-pipelines-20230430.yml
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSparkSampleWritesUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotExporter.java
  pom.xml
Labels: size:S

#11774 [HUDI-8079] Get rid of other count case for fg reader
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: size:S

#11786 [HUDI-8088] Fix documentation: filename of Externalized Config file
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
Labels: size:XS

#11787 [HUDI-8088][DOCS] Fix documentation: filename of Externalized Config file
  hudi-utils/src/main/java/org/apache/hudi/utils/HoodieConfigDocGenerator.java
  website/docs/configurations.md
  website/releases/release-0.10.0.md
  website/versioned_docs/version-0.10.0/configurations.md
  website/versioned_docs/version-0.10.1/configurations.md
  website/versioned_docs/version-0.11.0/configurations.md
  website/versioned_docs/version-0.12.0/configurations.md
  website/versioned_docs/version-0.12.0/quick-start-guide.md
  website/versioned_docs/version-0.12.1/configurations.md
  website/versioned_docs/version-0.12.1/quick-start-guide.md
  website/versioned_docs/version-0.12.2/configurations.md
  website/versioned_docs/version-0.12.2/quick-start-guide.md
  website/versioned_docs/version-0.12.3/configurations.md
  website/versioned_docs/version-0.12.3/quick-start-guide.md
  website/versioned_docs/version-0.13.0/configurations.md
  website/versioned_docs/version-0.13.0/quick-start-guide.md
  website/versioned_docs/version-0.13.1/configurations.md
  website/versioned_docs/version-0.13.1/quick-start-guide.md
  website/versioned_docs/version-0.14.0/configurations.md
  website/versioned_docs/version-0.14.1/configurations.md
  website/versioned_docs/version-0.15.0/configurations.md
Labels: docs, size:S

#11761 [HUDI-8073] Add hosts to storage path info and use it if present
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieBaseFile.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileGroupReaderBasedRecordReader.java
  hudi-io/src/main/java/org/apache/hudi/storage/StoragePathInfo.java
Labels: size:M

#11791 [DOCS] Change office hours to Wednesdays 9am
  website/community/office_hours.md
  website/community/syncs.md
  website/docs/overview.md
  website/versioned_docs/version-0.10.0/overview.md
  website/versioned_docs/version-0.10.1/overview.md
  website/versioned_docs/version-0.11.0/overview.md
  website/versioned_docs/version-0.11.1/overview.md
  website/versioned_docs/version-0.12.0/overview.md
  website/versioned_docs/version-0.12.1/overview.md
  website/versioned_docs/version-0.12.2/overview.md
  website/versioned_docs/version-0.12.3/overview.md
  website/versioned_docs/version-0.13.0/overview.md
  website/versioned_docs/version-0.13.1/overview.md
  website/versioned_docs/version-0.14.0/overview.md
  website/versioned_docs/version-0.14.1/overview.md
  website/versioned_docs/version-0.15.0/overview.md
Labels: docs, size:S

#11795 [HUDI-8096] Improve OverwriteNonDefaultsWithLatestAvroPayload Java Doc
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteNonDefaultsWithLatestAvroPayload.java
Labels: size:XS

#11796 [HUDI-8097] Fix getting Schema evolution setting from hudi-defaults.conf on altering columns
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/resources/external-config/hudi-defaults.conf
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestSqlConf.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/hudi/Spark33ResolveHudiAlterTableCommand.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/hudi/Spark34ResolveHudiAlterTableCommand.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/hudi/Spark35ResolveHudiAlterTableCommand.scala
Labels: size:S

#11792 [HUDI-8093] Replace Hadoop Configuration with StorageConfiguration in hudi-client-common module
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/bootstrap/BootstrapUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/DirectWriteMarkers.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/WriteMarkersFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToFiveUpgradeHandler.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/HoodieTestCommitGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/GenericRecordValidationTestUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieMergeOnReadTestUtils.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaTableServiceClient.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HadoopFSTestUtils.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/perf/TimelineServerPerf.java
Labels: size:L

#11799 [HUDI-8104] fix Hive on spark select mor rt table, org.apache.hudi.hadoop.hive.HoodieCombineRealtimeFileSplit cannot be cast to org.apache.hadoop.hive.shims.HadoopShimsSecure
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/hive/HoodieCombineHiveInputFormat.java
Labels: hive, size:XS

#11806 [MINOR] Fix the log offset for merged write stat
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/WriteStatMerger.java
Labels: size:XS

#11813 [MINOR][DOCS] Remove event banner
  website/blog/2024-07-31-hudi-file-formats.md
  website/src/pages/index.js
Labels: docs, size:XS

#11808 [HUDI-8108] Optimize HoodieTimeline#filterPendingExcludingMajorAndMinorCompaction function naming
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/OneToZeroDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/TwoToOneDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ZeroToOneUpgradeHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Labels: size:S

#11814 [HUDI-8112] Fix TestHoodieActiveTimeline#testTimelineGetOperations test logic error
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Labels: size:S

#11779 [HUDI-8070] Support Flink 1.19
  .github/workflows/bot.yml
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BulkInsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/ClusteringFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/CompactFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink1.14.x/src/main/java/org/apache/hudi/adapter/CollectOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.15.x/src/main/java/org/apache/hudi/adapter/CollectOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.16.x/src/main/java/org/apache/hudi/adapter/CollectOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/adapter/CollectOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/CollectOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/pom.xml
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/CollectOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/DataStreamScanProviderAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/DataStreamSinkProviderAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/HiveCatalogConstants.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/MaskingOutputAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/OperatorCoordinatorAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/SortCodeGeneratorAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelDeleteAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelUpdateAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/Utils.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/ParquetSplitReaderUtil.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapArrayVector.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapDecimalVector.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapMapColumnVector.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/HeapRowColumnVector.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/ParquetDecimalVector.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/AbstractColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ArrayColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/BaseVectorizedColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/EmptyColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/FixedLenBytesColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/Int64TimestampColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/MapColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetColumnarRowSplitReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetDataColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/ParquetDataColumnReaderFactory.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/RowColumnReader.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/RunLengthDecoder.java
  hudi-flink-datasource/hudi-flink1.19.x/src/test/java/org/apache/hudi/adapter/TestHoodieCatalogs.java
  hudi-flink-datasource/hudi-flink1.19.x/src/test/java/org/apache/hudi/adapter/TestStreamConfigs.java
  hudi-flink-datasource/pom.xml
  packaging/bundle-validation/base/build_flink1190hive313spark350.sh
  packaging/bundle-validation/base/build_flink1190hive313spark350scala213.sh
  packaging/bundle-validation/base/build_flink1190hive313spark351scala213.sh
  packaging/bundle-validation/ci_run.sh
  pom.xml
  scripts/release/deploy_staging_jars.sh
Labels: size:XL

#11601 [HUDI-7970] Move methods from HoodieTableConfigUtils to HoodieTableConfig
  hudi-aws/src/main/java/org/apache/hudi/config/GlueCatalogSyncClientConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/CustomAvroKeyGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/CustomKeyGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieTableConfigUtils.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncConfig.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
Labels: size:M

#11811 [HUDI-8078]Persisting writestatus to optimize the writes
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
Labels: performance, size:XS

#11800 [HUDI-8105] Refactor MercifulJsonConverter to be extendible for Json to Row conversion
  hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/DateLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/DecimalLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/DurationLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/EnumTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/FixedTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/JsonFieldProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/LocalTimestampMicroLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/LocalTimestampMilliLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/Parser.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/TimeLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/TimeMicroLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/TimeMilliLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/TimestampMicroLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/TimestampMilliLogicalTypeProcessor.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieJsonConversionException.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieJsonToAvroConversionException.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
Labels: size:XL

#11845 docs table horizontal scroll fix
  website/src/css/custom.css
  website/src/theme/DocRoot/Layout/Main/index.js
  website/src/theme/DocRoot/Layout/Main/styles.module.css
  website/src/theme/DocRoot/Layout/Sidebar/ExpandButton/index.js
  website/src/theme/DocRoot/Layout/Sidebar/ExpandButton/styles.module.css
  website/src/theme/DocRoot/Layout/Sidebar/index.js
  website/src/theme/DocRoot/Layout/Sidebar/styles.module.css
  website/src/theme/DocRoot/Layout/index.js
  website/src/theme/DocRoot/Layout/styles.module.css
  website/src/theme/DocRoot/index.js
  website/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.js
  website/src/theme/NavbarItem/LocaleDropdownNavbarItem/styles.module.css
Labels: docs, size:M

#11848 [HUDI-8133] allow the ability to add additional jars to execute the run_sync_tool
  hudi-sync/hudi-hive-sync/run_sync_tool.sh
Labels: size:XS

#11854 [HUDI-6791] Format some comments
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCInferenceCase.java
Labels: size:S

#11823 [HUDI-7696] Refactoring functions in HoodieTableMetadataUtil
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: size:S

#11867 [DOCS] Add Event banner
  website/src/components/EventFeature/index.js
  website/src/pages/index.js
Labels: docs, size:XS
