Repository apache/hudi, pull requests merged in 2024-03, with the labels that each got.

#10782 Revert "[HUDI-6438] Config parameter 'MAKE_NEW_COLUMNS_NULLABLE' to allow for marking a newly created column as nullable"
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: size:S

#10783 [DOCS] Revert [HUDI-6438] Remove config parameter 'hoodie.datasource.write.new.columns.nullable'
  website/docs/configurations.md
Labels: docs, size:XS

#10665 updated HoodieMultiTableStreamer to include mor table type; also did …
  website/docs/hoodie_streaming_ingestion.md
Labels: docs, size:XS

#10498 [DOCS] Add explanation for deduplicate command
  website/docs/procedures.md
  website/versioned_docs/version-0.13.1/procedures.md
  website/versioned_docs/version-0.14.0/procedures.md
  website/versioned_docs/version-0.14.1/procedures.md
Labels: docs, size:S

#10790 [HUDI-7459] Update hudi-gcp-bundle pom
  hudi-gcp/pom.xml
  packaging/hudi-gcp-bundle/pom.xml
  pom.xml
Labels: size:XS

#10787 [HUDI-7463] Bump Spark 3.5 version to Spark 3.5.1
  pom.xml
Labels: version-upgrade, size:XS

#8588 [MINOR] Release 0.12.3 script update
  scripts/release/deploy_staging_jars.sh
  scripts/release/validate_staged_bundles.sh
Labels: size:M

#10794 [HUDI-7462] Refactor checkTopicCheckpoint in KafkaOffsetGen for reusability
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
Labels: size:S

#10772 [HUDI-7464] Fix minor bugs in kafka post-processing related code
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/KafkaOffsetPostProcessor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestKafkaOffsetPostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
Labels: size:M

#10726 [DOCS] Initial commit for videos
  website/static/assets/images/video_blogs/2023-05-07-Maximizing_Efficiency_DataLake_Hudi_Glue_ETL_Jobs_with_Templated_Approach_Serverless_Architecture.png
  website/static/assets/images/video_blogs/2023-05-13-EMR-Serverless-Made-Easy_-Submitting-Hive-SQL-Queries-for-Beginners-with-NYC-Taxi-Dataset.png
  website/static/assets/images/video_blogs/2024-02-03-Apache-Hudi-Table-Services-Export-Services-HoodieSnapshotExporter-Hands-on-labs.png
  website/static/assets/images/video_blogs/2024-02-03-Apache-Hudi-Table-Services-Offline-Compaction-HoodieCompactor-Hands-on-labs.png
  website/static/assets/images/video_blogs/2024-02-07-Building-an-Open-Source-Data-Lake-House-with-Hudip-Postgres-Hive-Metastore-Minio-and-StarRocks.png
  website/static/assets/images/video_blogs/2024-02-10-Data-Ingestion-to-Visualization-Hudi-MinIO-StarRocks-HiveMetaStore-Apache-SuperSet-Hands-on-Guide.png
  website/static/assets/images/video_blogs/2024-02-17-Learn-How-to-Integerate-Hudi-Spark-job-with-Airflow-and-MinIO-Hands-on-Labs.png
  website/static/assets/images/video_blogs/2024-02-18-Build-Incremental-ETL-pipeline-with-Hudi-and-Airflow-and-MinIO.png
  website/videoBlog/2022-12-27-Bring_Data_from_Source_using_Debezium_with_CDC_into_Kafka_S3Sink_Build_Hudi_Datalake_Hands_on_lab.md
  website/videoBlog/2023-01-01-Streaming_ETL_using_Apache_Flink_joining_multiple_Kinesis_streams_Demo.md
  website/videoBlog/2023-01-01-Transaction_Hudi_Data_Lake_with_Streaming_ETL_from_Multiple_Kinesis_Streams_Joining_using_Flink.md
  website/videoBlog/2023-01-12-Build_Real_Time_Streaming_Pipeline_with_Apache_Hudi_Kinesis_and_Flink_Hands_on_Lab.md
  website/videoBlog/2023-01-13-Build_Real_Time_Low_Latency_Streaming_pipeline_from_DynamoDB_to_Apache_Hudi_using_Kinesis_FlinkLab.md
  website/videoBlog/2023-01-15-Real_Time_Streaming_Data_Pipeline_From_Aurora_Postgres_to_Hudi_with_DMS_Kinesis_and_Flink_DEMO.md
  website/videoBlog/2023-01-16-Real_Time_Streaming_Pipeline_From_Aurora_Postgres_to_Hudi_with_DMS_Kinesis_and_Flink_Hands_on_Lab.md
  website/videoBlog/2023-01-17-Leverage_Apache_Hudi_incremental_query_to_process_new_updated_data_Hudi_Labs.md
  website/videoBlog/2023-02-26-Python_helper_class_which_makes_querying_incremental_data_from_Hudi_Data_lakes_easy.md
  website/videoBlog/2023-03-04-Develop_Incremental_Pipeline_with_CDC_from_Hudi_to_Aurora_Postgres_Demo_Video.md
  website/videoBlog/2023-03-06-Power_your_Down_Stream_ElasticSearch_Stack_From_Apache_Hudi_Transaction_Datalake_with_CDCDemo_Video.md
  website/videoBlog/2023-03-06-Power_your_Down_Stream_Elastic_Search_Stack_From_Apache_Hudi_Transaction_Datalake_with_CDCDeepDive.md
  website/videoBlog/2023-03-17-Setting_Uber_s_Transactional_Data_Lake_in_Motion_with_Incremental_ETL_Using_Apache_Hudi.md
  website/videoBlog/2023-04-25-Joining_Hudi_Raw_Tables_for_Powerful_Data_Analysis_with_Spark_SQL.md
  website/videoBlog/2023-04-29-Efficiently_Managing_Ride_Late_Arriving_Tips_Data_with_Incremental_ETL_using_Apache_Hudi_Hands_On.md
  website/videoBlog/2023-05-01-Building_a_Scalable_and_Resilient_Streaming_ETL_Pipeline_with_Hudi_s_Incremental_Processing_1.md
  website/videoBlog/2023-05-07-Maximizing_Efficiency_DataLake_Hudi_Glue_ETL_Jobs_with_Templated_Approach_Serverless_Architecture.md
  website/videoBlog/2023-05-13-EMR_Serverless_Made_Easy_Submitting_Hive_SQL_Queries_for_Beginners_with_NYC_Taxi_Dataset.md
  website/videoBlog/2023-06-02-How_to_Query_Hudi_Tables_in_Incremental_Fashion_and_Get_only_New_data_on_AWS_Glue_Hands_on_Lab.md
  website/videoBlog/2023-06-05-How_to_JOIN_Hudi_Tables_in_Incremental_fashion_with_DynamoDB_in_AWS_GLue_Hands_on_Lab_for_Begineer.md
  website/videoBlog/2023-06-10-How_to_read_data_from_Multiple_Hudi_Tables_Join_them_and_insert_into_DynamoDB_with_AWS_Glue.md
  website/videoBlog/2023-09-23-Flink-with-POSTGRES-RealTime-Stream-Data-Processing-with-Python-Hands-on-Labs.md
  website/videoBlog/2023-09-26-How-to-Ingest-Data-from-PostgreSQL-into-Hudi-Tables-on-S3-with-Apache-Flink-CDC-Connector-Python.md
  website/videoBlog/2023-10-14-Accelerating-Data-Processing-Leveraging-Apache-Hudi-with-DynamoDB-for-Faster-Commit-Time-Retrieval.md
  website/videoBlog/2023-12-11-Simplifying-Big-Data-Setting-Up-SparkSQL-Hive-Thrift-Server-and-Hudi-with-Beeline-in-Minutes.md
  website/videoBlog/2023-12-16-Learn-How-to-Setup-Hudi-on-EMR-with-Hive-and-Query-Data-using-Hue-and-Presto-CLI-Hands-on-Labs.md
  website/videoBlog/2023-12-24-Apache-Hudi-Spark-DBT-Glue-Hive-MetaStore-Setup-Locally-in-Minutes-Hands-On-Exercise.mdx
  website/videoBlog/2023-12-25-Hudi-DBT-Spark-Glue-Hive-MetaStore-Join-two-hudi-tables-Labs-with-Exercise-Files.mdx
  website/videoBlog/2024-01-06-Dynamic-Delta-Streamer-Jobs-with-JDBC-Puller-for-Postgres-Bring-all-Tables-from-particular-Schema-full.mdx
  website/videoBlog/2024-01-06-Dynamic-Delta-Streamer-Jobs-with-JDBC-Puller-for-Postgres-Bring-all-Tables-from-particular-Schema.mdx
  website/videoBlog/2024-02-03-Apache-Hudi-Table-Services-Export-Services-HoodieSnapshotExporter-Hands-on-labs.mdx
  website/videoBlog/2024-02-03-Apache-Hudi-Table-Services-Offline-Compaction-HoodieCompactor-Hands-on-labs.mdx
  website/videoBlog/2024-02-07-Building-an-Open-Source-Data-Lake-House-with-Hudip-Postgres-Hive-Metastore-Minio-and-StarRocks.mdx
  website/videoBlog/2024-02-10-Data-Ingestion-to-Visualization-Hudi-MinIO-StarRocks-HiveMetaStore-Apache-SuperSet-Hands-on-Guide.mdx
  website/videoBlog/2024-02-17-Learn-How-to-Integerate-Hudi-Spark-job-with-Airflow-and-MinIO-Hands-on-Labs.mdx
  website/videoBlog/2024-02-18-Build-Incremental-ETL-pipeline-with-Hudi-and-Airflow-and-MinIO.mdx
Labels: docs, size:M

#10444 [MINOR] Fix violations of Sonarqube rule java:S2184
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestHBasePutBatchSizeCalculator.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/SizeAwareDataOutputStream.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieWithTimelineServer.java
Labels: code-refactor, size:S

#10767 [HUDI-7447] Fix not bootstrap when subTask restart when OPCoordinator handle CheckPointComplete not finished
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BulkInsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
Labels: priority:critical, flink-sql, stability, size:S

#10594 [HUDI-9424]Support using local timezone when writing flink TIMESTAMP data
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/RowDataToAvroConverters.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestRowDataToAvroConverters.java
Labels: flink-sql, size:M

#10632 [HUDI-7341] Support unmerged record read
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
Labels: size:M

#10795 [HUDI-7465] Split tests in CI further to reduce total CI elapsed time
  .github/workflows/bot.yml
  azure-pipelines-20230430.yml
Labels: test-stability, size:M

#10728 [HUDI-6089] Handle default insert behaviour to ingest duplicates
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:S

#10800 [HUDI-7469] Reduce redundant tests with Hudi record types
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestAlterTableDropPartition.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestCompactionTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTable2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestMergeIntoTableWithNonRecordKeyField.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestTimeTravelTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestUpdateTable.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: test-stability, size:L

#10214 [HUDI-6953] Adding test for composite keys with bulk insert row writer
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: size:S

#7481 [DOCS] Fix dataframe write option in schema_evolution docs
  website/docs/schema_evolution.md
  website/versioned_docs/version-0.10.0/schema_evolution.md
  website/versioned_docs/version-0.10.1/schema_evolution.md
  website/versioned_docs/version-0.11.0/schema_evolution.md
  website/versioned_docs/version-0.11.1/schema_evolution.md
  website/versioned_docs/version-0.12.0/schema_evolution.md
  website/versioned_docs/version-0.12.1/schema_evolution.md
  website/versioned_docs/version-0.12.2/schema_evolution.md
  website/versioned_docs/version-0.13.0/schema_evolution.md
  website/versioned_docs/version-0.13.1/schema_evolution.md
  website/versioned_docs/version-0.14.0/schema_evolution.md
  website/versioned_docs/version-0.14.1/schema_evolution.md
Labels: docs, size:M

#9462 [HUDI-3625] Update RFC-60
  rfc/rfc-60/read_flow.png
  rfc/rfc-60/rfc-60.md
  rfc/rfc-60/wrapper_fs.png
Labels: size:S

#10797 [MINOR] Clean code of FileSystemViewManager
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestPartialUpdateForMergeInto.scala
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
Labels: size:M

#10792 [HUDI-7458] Fix bug with functional index creation
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToFourUpgradeHandler.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndexClient.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: size:M

#10194 [HUDI-7150] ExternalSpillableMap support values method
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
Labels: size:XS

#10802 [HUDI-7471] Increase the number of Spark executors in tests
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/providers/SparkProvider.java
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/TestHoodieInMemoryFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSourceFormatAdapter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSanitizationUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlQueryBasedTransformer.java
Labels: test-stability, size:S

#10804 [HUDI-7472] prevent MDT partitions from getting dropped
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndexClient.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
Labels: size:S

#10799 [MINOR] Add PR description validation on documentation updates
  .github/PULL_REQUEST_TEMPLATE.md
  scripts/pr_compliance.py
Labels: size:S

#10786 [HUDI-7479] SQL confs don't propagate to spark row writer properly
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:S

#10811 [DOCS] remove key requirements part of streaming query and change tab…
  website/docs/flink-quick-start-guide.md
  website/versioned_docs/version-0.14.1/flink-quick-start-guide.md
Labels: docs, size:S

#10565 [HUDI-7337] Implement MetricsReporter that reports metrics to M3
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsM3Config.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/m3/M3MetricsReporter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/m3/M3ScopeReporterAdaptor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/m3/TestM3Metrics.java
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
  pom.xml
Labels: release-0.14.2, size:L

#10677 [HUDI-7413] Fix schema exception types and error messages thrown with schema exceptions
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaCompatibility.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieNullSchemaTypeException.java
  hudi-common/src/main/java/org/apache/hudi/exception/InvalidUnionTypeException.java
  hudi-common/src/main/java/org/apache/hudi/exception/MissingSchemaFieldException.java
  hudi-common/src/main/java/org/apache/hudi/exception/SchemaBackwardsCompatibilityException.java
  hudi-common/src/main/java/org/apache/hudi/exception/SchemaCompatibilityException.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/convert/AvroInternalSchemaConverter.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
  hudi-common/src/test/java/org/apache/hudi/internal/schema/utils/TestAvroSchemaEvolutionUtils.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestHoodieSchemaUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
Labels: size:L

#10821 [HUDI-7475] Disable ITs in hudi-aws module
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/ITTestGluePartitionPushdown.java
  hudi-aws/src/test/java/org/apache/hudi/aws/transaction/integ/ITTestDynamoDBBasedLockProvider.java
Labels: size:XS

#10724 [HUDI-7418] Create a common method for filtering in S3 and GCS sources and add tests for filtering out extensions
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/CloudSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/S3EventsHoodieIncrSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/gcs/GcsObjectMetadataFetcher.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
Labels: size:M

#10788 [HUDI-7463][branch-0.x] Bump Spark 3.5 version to Spark 3.5.1
  pom.xml
Labels: version-upgrade, size:XS

#10817 [MINOR] Fix Azure publishing of JUnit results
  azure-pipelines-20230430.yml
Labels: size:S

#10810 [HUDI-6947] Refactored HoodieSchemaUtils.deduceWriterSchema with many flags
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
Labels: size:M

#10698 [HUDI-7356] Passing configs to file reader constructor for flexibility
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileReaderFactory.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroFileReaderFactory.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieFileReaderFactory.java
Labels: priority:minor, code-refactor, size:S

#10679 [DOCS] Update GCP config doc
  website/docs/gcp_bigquery.md
Labels: docs, size:XS

#10605 [MINOR] Add UT org.apache.hudi.io.TestHoodieTimelineArchiver#testRetryArchivalAfterPreviousFailedDeletion
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
Labels: release-0.14.2, size:S

#7153 [HUDI-5167] Reducing total test run time: reducing tests for virtual keys
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: priority:major, test-coverage, test-stability, size:M

#10719 initial commit for hudi blogs
  website/blog/2024-01-11-In-House-Data-Lake-with-CDC-Processing-Hudi-Docker.mdx
  website/blog/2024-01-17-Enforce-fine-grained-access-control-on-Open-Table-Formats-via-Amazon-EMR-integrated-with-AWS-Lake-Formation.mdx
  website/blog/2024-01-18-Deleting-Items-from-Apache-Hudi-using-Delta-Streamer-in-UPSERT-Mode-with-Kafka-Avro-Messages.mdx
  website/blog/2024-01-20-Data-Engineering-Bootstrapping-Data-lake-with-Apache-Hudi.mdx
  website/blog/2024-01-20-Learn-How-to-Move-Data-From-MongoDB-to-Apache-Hudi-Using-PySpark.mdx
  website/blog/2024-01-30-Leverage-Partition-Paths-of-your-data-lake-tables-to-Optimize-Data-Retrieval-Costs-on-the-cloud.mdx
  website/blog/2024-02-04-Apache-Hudi-Managing-Partition-on-a-petabyte-scale-table.mdx
  website/blog/2024-02-12-How-a-POC-became-a-production-ready-Hudi-data-lakehouse-through-close-team-collaboration.mdx
  website/static/assets/images/blog/2024-01-11-In-House-Data-Lake-with-CDC-Processing-Hudi-Docker.png
  website/static/assets/images/blog/2024-01-17-Enforce-fine-grained-access-control-on-Open-Table-Formats-via-Amazon-EMR-integrated-with-AWS-Lake-Formation.png
  website/static/assets/images/blog/2024-01-18-Deleting-Items-from-Apache-Hudi-using-Delta-Streamer-in-UPSERT-Mode-with-Kafka-Avro-Messages.png
  website/static/assets/images/blog/2024-01-20-Data-Engineering-Bootstrapping-Data-lake-with-Apache-Hudi.png
  website/static/assets/images/blog/2024-01-20-Learn-How-to-Move-Data-From-MongoDB-to-Apache-Hudi-Using-PySpark.png
  website/static/assets/images/blog/2024-01-30-Leverage-Partition-Paths-of-your-data-lake-tables-to-Optimize-Data-Retrieval-Costs-on-the-cloud.png
  website/static/assets/images/blog/2024-02-04-Apache-Hudi-Managing-Partition-on-a-petabyte-scale-table.png
  website/static/assets/images/blog/2024-02-12-How-a-POC-became-a-production-ready-Hudi-data-lakehouse-through-close-team-collaboration.png
Labels: docs, size:M

#10830 [HUDI-7488] The BigQuerySyncTool can't work well when the hudi table schema changed #10829
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
Labels: meta-sync, gcp-support, size:S

#10833 [HUDI-7482] Update schema evolution docs to explicitly state allowed type promotions
  website/docs/schema_evolution.md
  website/versioned_docs/version-0.14.1/schema_evolution.md
Labels: docs, size:S

#10839 [DOCS] updated powered by logo
  website/assets/images/powers/hudi-logo-page.png
  website/src/pages/powered-by.md
Labels: docs, size:XS

#10837 [HUDI-7491] Fixing handling null values of extra metadata in clean commit metadata
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
Labels: size:XS

#10807 [HUDI-7476] Incremental loading for archived timeline
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/LSMTimelineWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieArchivedTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
Labels: size:M

#10676 [HUDI-7411] Meta sync should consider cleaner commit
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Labels: size:S

#10655 [HUDI-7402] Align MDT cleaner configs with the data table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataWriteUtils.java
Labels: size:S

#10842 [MINOR] Code clean for time generator
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGeneratorBase.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGenerators.java
Labels: size:S

#8393 [HUDI-6043] Metadata Table should use default values for Compaction preserveCommitMetadata field
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
Labels: size:XS

#10825 [DOCS] Initial commit for blogs
  website/blog/2024-02-06-Building-an-Open-Source-Data-Lake-House-with-Hudi-Postgres-Hive-Metastore-Minio-and-StarRocks.mdx
  website/blog/2024-02-27-Building-Data-Lakes-on-AWS-with-Kafka-Connect-Debezium-Apicurio-Registry-and-Apache-Hudi.mdx
  website/blog/2024-03-05-Apache-Hudi-From-Zero-To-One-blog-9.mdx
  website/static/assets/images/blog/2024-02-06-Building-an-Open-Source-Data-Lake-House-with-Hudi-Postgres-Hive-Metastore-Minio-and-StarRocks.png
  website/static/assets/images/blog/2024-02-27-Building-Data-Lakes-on-AWS-with-Kafka-Connect-Debezium-Apicurio-Registry-and-Apache-Hudi.png
  website/static/assets/images/blog/2024-03-05-Apache-Hudi-From-Zero-To-One-blog-9.png
Labels: docs, size:S

#7074 [HUDI-5101] Adding spark-structured streaming test support via spark-submit job
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/streaming/StructuredStreamingSinkUtil.java
  hudi-integ-test/src/main/scala/org/apache/hudi/integ/testsuite/streaming/StructuredStreamingSinkTestWriter.scala
Labels: priority:major, spark-streaming, test-coverage, size:M

#10220 [HUDI-7163] Fix not parsable text DateTimeParseException when compact
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
Labels: release-0.14.1, size:S

#10844 chore: remove repetitive words
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystPlansUtils.scala
  hudi-common/src/main/java/org/apache/hudi/common/bloom/InternalBloomFilter.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/sort/SortOperator.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  rfc/rfc-76/rfc-76.md
  scripts/pr_compliance.py
Labels: size:S

#10843 [DOCS][MINOR] Changed refs from OneTable to XTable and fixed an ambiguous wording
  website/docs/syncing_onetable.md
  website/docs/syncing_xtable.md
  website/sidebars.js
  website/versioned_docs/version-0.14.0/syncing_onetable.md
  website/versioned_docs/version-0.14.0/syncing_xtable.md
  website/versioned_docs/version-0.14.1/syncing_onetable.md
  website/versioned_docs/version-0.14.1/syncing_xtable.md
  website/versioned_sidebars/version-0.14.0-sidebars.json
  website/versioned_sidebars/version-0.14.1-sidebars.json
Labels: docs, size:L

#10847 [WEBSITE][MINOR] Add matomo for website analytics
  website/src/theme/Navbar/index.js
Labels: docs, size:XS

#10836 [HUDI-7489] Avoid collecting WriteStatus to driver in row writer code path
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
Labels: size:S

#10848 [MINOR] additional job contexts for ease of debugging
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:XS

#10853 [DOCS][MINOR] Update powered-by page
  website/src/pages/powered-by.md
Labels: docs, size:XS

#10862 [HUDI-7502][DOCS] Re-organize the content in "how to" section
  website/docs/concurrency_control.md
  website/docs/deployment.md
  website/docs/faq.md
  website/docs/faq_general.md
  website/docs/faq_reading_tables.md
  website/docs/faq_table_services.md
  website/docs/faq_writing_tables.md
  website/docs/flink-quick-start-guide.md
  website/docs/hoodie_streaming_ingestion.md
  website/docs/hudi_stack.md
  website/docs/ingestion_flink.md
  website/docs/ingestion_kafka_connect.md
  website/docs/overview.md
  website/docs/platform_services_post_commit_callback.md
  website/docs/precommit_validator.md
  website/docs/quick-start-guide.md
  website/docs/reading_tables_batch_reads.md
  website/docs/reading_tables_streaming_reads.md
  website/docs/sql_ddl.md
  website/docs/sql_dml.md
  website/docs/write_operations.md
  website/docs/writing_data.md
  website/docs/writing_tables_streaming_writes.md
  website/releases/release-1.0.0-beta1.md
  website/sidebars.js
  website/versioned_docs/version-0.14.1/faq.md
Labels: docs, size:XL

#10868 [MINOR][DOCS] Link to transforms page from hoodie streamer page
  website/docs/hoodie_streaming_ingestion.md
Labels: docs, size:XS

#10820 [HUDI-7478] Fix max delta commits guard check w/ MDT
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Labels: priority:critical, size:S

#10867 [MINOR] Fix and enable test TestHoodieDeltaStreamer.testJdbcSourceIncrementalFetchInContinuousMode
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:S

#10621 [HUDI-7382] Get partitions from active timeline instead of listing when building clustering plan
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/ClusteringPlanStrategy.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/clustering/plan/strategy/FlinkSizeBasedClusteringPlanStrategyRecently.java
Labels: size:M

#10871 [MINOR] rename KeyGenUtils#enableAutoGenerateRecordKeys
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/KeyGenUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/factory/HoodieAvroKeyGeneratorFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/factory/HoodieSparkKeyGeneratorFactory.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/SqlKeyGenerator.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:S

#10869 [HUDI-7506] Compute offsetRanges based on eventsPerPartition allocated in each range
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCheckpointUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Labels: size:M

#10460 [HUDI-7466] Add parallel listing of existing partitions in Glue Catalog sync
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/main/java/org/apache/hudi/config/GlueCatalogSyncClientConfig.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/ITTestGluePartitionPushdown.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
Labels: performance, meta-sync, size:L

#10870 [HUDI-7421] Build HoodieDeltaWriteStat using HoodieDeltaWriteStat#copy
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieDeltaWriteStat.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieDeltaWriteStat.java
Labels: code-refactor, size:S

#10840 [HUDI-7492] fix the issue of incorrect keygenerator specification when creating m…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: size:M

#10880 [MINOR] Add Hudi icon for idea
  .gitignore
  .idea/icon.png
Labels: size:XS

#10883 [HUDI-7514] Update Manifest file after the parquet writer closed in LSMTimelineWriter
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/LSMTimelineWriter.java
Labels: size:XS

#10888 [DOCS] Hardcode config names instead of params
  website/docs/basic_configurations.md
  website/docs/clustering.md
  website/docs/compaction.md
  website/docs/concurrency_control.md
  website/docs/configurations.md
  website/docs/deployment.md
  website/docs/disaster_recovery.md
  website/docs/faq_storage.md
  website/docs/faq_writing_tables.md
  website/docs/flink-quick-start-guide.md
  website/docs/precommit_validator.md
  website/docs/querying_data.md
  website/docs/quick-start-guide.md
  website/docs/reading_tables_streaming_reads.md
  website/docs/schema_evolution.md
  website/docs/syncing_metastore.md
  website/docs/troubleshooting.md
  website/docs/write_operations.md
  website/docs/writing_data.md
  website/docs/writing_tables_streaming_writes.md
Labels: docs, size:L

#10889 [HUDI-7516] Put jdbc-h2 creds into static variables for hudi-utilities tests
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestJdbcbasedSchemaProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJdbcSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/JdbcTestUtils.java
Labels: size:S

#10901 [MINOR] Remove redundant fileId from HoodieAppendHandle
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
Labels: size:XS

#10905 [MINOR] Update office hour
  website/community/office_hours.md
Labels: docs, size:XS

#10854 [DOCS] Add more users in the powered-by page
  website/src/pages/powered-by.md
Labels: docs, pr:wip, size:XS

#10911 [HUDI-7529] Resolve hotspots in stream read
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/partitioner/StreamReadAppendPartitioner.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/partitioner/StreamReadBucketIndexPartitioner.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/selector/StreamReadAppendKeySelector.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/selector/StreamReadBucketIndexKeySelector.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
Labels: size:M

#10910 [HUDI-7487] Fixed test with in-memory index by proper heap clearing
  hudi-common/src/test/java/org/apache/hudi/client/transaction/lock/TestInProcessLockProvider.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
Labels: size:M

#10912 [MINOR] Refactored `@Before*` and `@After*` in `HoodieDeltaStreamerTestBase`
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
Labels: size:M

#10908 [HUDI-7530] Refactoring of handleUpdateInternal in CommitActionExecutors and HoodieTables
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/BaseBootstrapMetadataHandler.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
Labels: size:M

#10857 [HUDI-7499] Support FirstValueAvroPayload for Hudi
  hudi-common/src/main/java/org/apache/hudi/common/model/FirstValueAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestFirstValueAvroPayload.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:M

#10919 [MINOR] Fix the checkstyle of /StreamReadAppendPartitioner
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/filedistribution/partitioner/StreamReadAppendPartitioner.java
Labels: size:XS

#10877 [HUDI-7513] Add jackson-module-scala to spark bundle
  pom.xml
Labels: size:XS

#10925 [MINOR] Restore the setMaxParallelism setting for HoodieTableSource.produceDataStream
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
Labels: size:XS

#10923 [HUDI-7531] Consider pending clustering when scheduling a new clustering plan
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/PreferWriterConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RestorePlanActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/IncrementalQueryAnalyzer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: table-service, release-0.15.0, size:M

#10913 [HUDI-7518] Fix HoodieMetadataPayload merging logic around repeated deletes
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataPayload.java
Labels: metadata, release-1.0.0, release-0.15.0, size:M

#10858 [HUDI-7500] fix gaps with deduce schema and null schema
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSyncUnitTests.java
Labels: size:M

#10928 [HUDI-7551] Avoid loading all partitions in CleanPlanner when MDT is enabled
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestPriorityBasedFileSystemView.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
Labels: release-0.15.0, size:M

#8884 [HUDI-6317] Streaming read should skip compaction and clustering instants to avoid duplicates
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
Labels: flink, table-service, streaming, release-1.0.0, size:S

#10936 [MINOR] When M3 metrics reporter type is used HoodieMetricsConfig should create default values for HoodieMetricsM3Config
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java
Labels: size:XS

#10941 [HUDI-6884] hudi-cli should generate correct HoodieTimeGeneratorConfig
  hudi-cli/src/main/java/org/apache/hudi/cli/HoodieCLI.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestMetadataCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestBootstrapCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestHDFSParquetImportCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestRepairsCommand.java
Labels: size:S

#10866 [HUDI-7187] Fix integ test props to honor new streamer properties
  hudi-utilities/src/test/java/org/apache/hudi/utilities/checkpointing/TestKafkaConnectHdfsProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/config/SourceTestConfig.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHiveSchemaProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestJdbcbasedSchemaProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestCsvDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJdbcSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSourcePostProcessor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestParquetDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlFileBasedSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestSqlSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestAbstractDebeziumSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelectorCommon.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractBaseTestSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/DistributedTestDataSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlFileBasedTransformer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlQueryBasedTransformer.java
  hudi-utilities/src/test/resources/streamer-config/dfs-source.properties
  hudi-utilities/src/test/resources/streamer-config/invalid_hive_sync_uber_config.properties
  hudi-utilities/src/test/resources/streamer-config/kafka-source.properties
  hudi-utilities/src/test/resources/streamer-config/short_trip_uber_config.properties
  hudi-utilities/src/test/resources/streamer-config/sql-transformer.properties
  hudi-utilities/src/test/resources/streamer-config/uber_config.properties
Labels: configs, test-stability, size:L
