Repository apache/hudi, pull requests merged in 2024-04, with the labels that each got.

#10874 [HUDI-7510] Loosen the compaction scheduling and rollback check for MDT
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/TestHoodieMetadataBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java
Labels: metadata, release-1.0.0, size:L

#10938 [HUDI-6538] Refactor methods in TimelineDiffHelper class
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineDiffHelper.java
Labels: code-refactor, size:S

#10952 [HUDI-6331][DOCS] Update user doc of partial insert in MERGE INTO command
  website/docs/sql_dml.md
Labels: docs, size:XS

#10953 [MINOR] Upgrade mockito to 3.12.4
  pom.xml
Labels: dependencies, size:XS

#10951 [HUDI-7564] Fix HiveSyncConfig inconsistency
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
Labels: size:XS

#10955 [HUDI-7569] [RLI] Fix wrong result generated by query
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Labels: size:S

#10778 [HUDI-7486] Classify schema exceptions when converting from avro to spark row representation
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/ExceptionWrappingIterator.scala
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieAvroSchemaException.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieRecordCreationException.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/HoodieStreamerConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/RowSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestCsvDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestParquetDFSSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractDFSSourceTestBase.java
Labels: spark-sql, size:L

#10959 [HUDI-7564] Revert hive sync inconsistency and add docs for it
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfigHolder.java
Labels: size:XS

#10939 [HUDI-7556] Fixing MDT validator and adding tests
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:M

#10960 [HUDI-7571] Add api to get exception details in HoodieMetadataTableValidator with ignoreFailed mode
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:S

#10963 [MINOR] Removed FSUtils.makeBaseFileName without fileExtension param
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestFileSystemViewCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/functional/CLIFunctionalTestHarness.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/HoodieTestCommitGenerator.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestFlinkSizeBasedClusteringPlanStrategy.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/table/action/commit/TestJavaCopyOnWriteActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/strategy/TestSparkBuildClusteringGroupsForPartition.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieWriteStat.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFSViewWithClustering.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestIncrementalFSViewSync.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestCluster.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotCopier.java
Labels: size:M

#10943 [MINOR] Handle cases of malformed records when converting to json
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/ErrorEvent.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieStreamerUtils.java
Labels: size:S

#10948 [MINOR] use Temurin jdk
  .github/workflows/bot.yml
  .github/workflows/release_candidate_validation.yml
Labels: size:S

#10967 [MINOR] Removed code duplicates in HoodieClients
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
Labels: size:M

#10949 [HUDI-6854] Change default payload type to HOODIE_AVRO_DEFAULT
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/RecordPayloadType.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBasicSchemaEvolution.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
Labels: size:S

#10328 [HUDI-7230] stream read supports skipping insert overwrite instant
  hudi-common/src/main/java/org/apache/hudi/common/table/read/IncrementalQueryAnalyzer.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
Labels: size:M

#10971 [DOCS] Update blogs
  website/blog/2024-03-10-navigating-the-future-the-evolutionary-journey-of-upstoxs-data-platform.mdx
  website/blog/2024-03-14-Modern-Datalakes-with-Hudi--MinIO--and-HMS.mdx
  website/blog/2024-03-22-data-lake-cost-optimisation-strategies.mdx
  website/blog/2024-03-23-options-on-kafka-sink-to-open-table-formats-apache-iceberg-and-apache-hudi.mdx
  website/blog/2024-03-30-record-level-indexing-apache-hudi-delivers-70-faster-point.mdx
  website/blog/2024-04-03-hands-on-guide-reading-data-from-hudi-tables-joining-delta.mdx
  website/static/assets/images/blog/2024-03-10-navigating-the-future-the-evolutionary-journey-of-upstoxs-data-platform.png
  website/static/assets/images/blog/2024-03-14-Modern-Datalakes-with-Hudi--MinIO--and-HMS.jpg
  website/static/assets/images/blog/2024-03-22-data-lake-cost-optimisation-strategies.png
  website/static/assets/images/blog/2024-03-23-options-on-kafka-sink-to-open-table-formats-apache-iceberg-and-apache-hudi.png
  website/static/assets/images/blog/2024-03-30-record-level-indexing-apache-hudi-delivers-70-faster-point.png
  website/static/assets/images/blog/2024-04-03-hands-on-guide-reading-data-from-hudi-tables-joining-delta.png
Labels: docs, size:M

#10977 [HUDI-6330][DOCS] Update user doc to show how to use consistent bucket index for Flink engine
  website/docs/sql_dml.md
  website/releases/release-0.14.0.md
Labels: docs, size:S

#10981 [DOCS] Updates slack link across site
  website/blog/2021-12-16-lakehouse-concurrency-control-are-we-too-optimistic.md
  website/blog/2022-01-06-apache-hudi-2021-a-year-in-review.md
  website/blog/2022-01-14-change-data-capture-with-debezium-and-apache-hudi.md
  website/blog/2022-12-29-Apache-Hudi-2022-A-Year-In-Review.md
  website/blog/2023-12-28-apache-hudi-2023-a-year-in-review.md
  website/community/get-involved.md
  website/docs/overview.md
  website/docusaurus.config.js
  website/i18n/cn/docusaurus-plugin-content-pages/get-involved.md
  website/i18n/cn/docusaurus-theme-classic/footer.json
  website/sidebars.js
  website/sidebarsCommunity.js
  website/sidebarsContribute.js
  website/src/components/JoinCommunity/index.js
  website/src/pages/powered-by.md
  website/versioned_docs/version-0.10.0/overview.md
  website/versioned_docs/version-0.10.1/overview.md
  website/versioned_docs/version-0.11.0/overview.md
  website/versioned_docs/version-0.11.1/overview.md
  website/versioned_docs/version-0.12.0/overview.md
  website/versioned_docs/version-0.12.1/overview.md
  website/versioned_docs/version-0.12.2/overview.md
  website/versioned_docs/version-0.12.3/overview.md
  website/versioned_docs/version-0.13.0/overview.md
  website/versioned_docs/version-0.13.1/overview.md
  website/versioned_docs/version-0.14.0/overview.md
  website/versioned_docs/version-0.14.1/overview.md
  website/versioned_sidebars/version-0.10.0-sidebars.json
  website/versioned_sidebars/version-0.10.1-sidebars.json
  website/versioned_sidebars/version-0.11.0-sidebars.json
  website/versioned_sidebars/version-0.11.1-sidebars.json
  website/versioned_sidebars/version-0.12.0-sidebars.json
  website/versioned_sidebars/version-0.12.1-sidebars.json
  website/versioned_sidebars/version-0.12.2-sidebars.json
  website/versioned_sidebars/version-0.12.3-sidebars.json
  website/versioned_sidebars/version-0.13.0-sidebars.json
  website/versioned_sidebars/version-0.13.1-sidebars.json
  website/versioned_sidebars/version-0.14.0-sidebars.json
  website/versioned_sidebars/version-0.14.1-sidebars.json
  website/versioned_sidebars/version-0.9.0-sidebars.json
Labels: docs, size:M

#10974 [HUDI-7572] Avoid to schedule empty compaction plan without log files
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestInlineCompaction.java
Labels: table-service, size:S

#10860 [HUDI-7480] Fix functional index and avoid multiple initializations
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/TableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestPriorityBasedFileSystemView.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
Labels: index, release-1.0.0, size:M

#10809 [MINOR] Optimize print write error msg in StreamWriteOperatorCoordinator#doCommit
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
Labels: size:S

#10986 [HUDI-7556] Fixing false positive validation with MDT validator
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:M

#10984 [HUDI-7583] Read log block header only for the schema and instant time
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:S

#10989 [MINOR] Fix BUG: HoodieLogFormatWriter: unable to close output stream for log…
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
Labels: size:XS

#10945 [HUDI-7552] Remove the suffix for MDT table service instants
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: metadata, release-1.0.0, size:M

#10993 [HUDI-7600] Shutdown ExecutorService when HiveMetastoreBasedLockProvider is closed
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
Labels: size:XS

#10635 [HUDI-7391] HoodieMetadataMetrics should use Metrics instance for metrics registry
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/metrics/HoodieLockMetrics.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/cloudwatch/CloudWatchMetricsReporter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieConsoleMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieGraphiteMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieJmxMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestMetricsReporterFactory.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/cloudwatch/TestCloudWatchMetricsReporter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/datadog/TestDatadogMetricsReporter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/m3/TestM3Metrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/prometheus/TestPrometheusReporter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/prometheus/TestPushGateWayReporter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsCloudWatchConfig.java
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsDatadogConfig.java
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsGraphiteConfig.java
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsJmxConfig.java
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsM3Config.java
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsPrometheusConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMetrics.java
  hudi-common/src/main/java/org/apache/hudi/metrics/ConsoleMetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/HoodieGauge.java
  hudi-common/src/main/java/org/apache/hudi/metrics/InMemoryMetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/JmxMetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/JmxReporterServer.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricUtils.java
  hudi-common/src/main/java/org/apache/hudi/metrics/Metrics.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricsGraphiteReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java
  hudi-common/src/main/java/org/apache/hudi/metrics/custom/CustomizableMetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogHttpClient.java
  hudi-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogMetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/datadog/DatadogReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/m3/M3MetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/m3/M3ScopeReporterAdaptor.java
  hudi-common/src/main/java/org/apache/hudi/metrics/prometheus/PrometheusReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/prometheus/PushGatewayMetricsReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/prometheus/PushGatewayReporter.java
  hudi-common/src/main/java/org/apache/hudi/metrics/userdefined/AbstractUserDefinedMetricsReporter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerMetrics.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionMetrics.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerMetrics.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:L

#10970 [HUDI-6441] Passing custom Headers with Hudi Callback URL
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/callback/client/http/HoodieWriteCommitHttpCallbackClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteCommitCallbackConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/callback/client/http/TestCallbackHttpClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/callback/http/TestCallbackHttpClient.java
Labels: size:L

#10999 [HUDI-7605] allow merger strategy to be set in spark sql writer
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Labels: size:S

#10479 [HUDI-7290] Don't assume ReplaceCommits are always Clustering
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/WriteMarkers.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanSourceFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ClusteringUtil.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
Labels: priority:critical, table-service, size:M

#10994 [HUDI-7601] Add heartbeat mechanism to refresh lock
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/LockConfiguration.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/Heartbeat.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
Labels: size:S

#10954 [HUDI-7565] Create spark file readers to read a single file instead of an entire partition
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReader.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReaderBase.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/TestSparkParquetReaderFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkParquetReader.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/util/JavaConversions.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark24ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_0Adapter.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_1Adapter.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_2Adapter.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_3Adapter.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_4Adapter.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_5Adapter.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark35ParquetReader.scala
Labels: reader-core, release-1.0.0, size:XL

#10990 [HUDI-7599] add bootstrap mor legacy reader back to default source
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestNewHoodieParquetFileFormat.java
Labels: spark, release-1.0.0, size:S

#10615 [HUDI-7378] Fix Spark SQL DML with custom key generator
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/factory/HoodieSparkKeyGeneratorFactory.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithCustomKeyGenerator.scala
Labels: size:L

#11013 [HUDI-7616] Avoid multiple cleaner plans and deprecate hoodie.clean.allow.multiple
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
Labels: table-service, release-1.0.0, release-0.15.0, size:XS

#11000 [HUDI-7606] Unpersist RDDs after table services, mainly compaction and clustering
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkReleaseResources.java
Labels: size:M

#11012 [HUDI-7615] Mark a few write configs with the correct sinceVersion
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorOptions.java
Labels: size:XS

#11015 [HUDI-7584] Always read log block lazily and remove readBlockLazily argument
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergedReadHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieCDCLogRecordIterator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReverseReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/LogReaderUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-examples/hudi-examples-flink/src/test/java/org/apache/hudi/examples/quickstart/TestQuickstartData.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadSnapshotReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeCompactedRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/RealtimeUnmergedRecordReader.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/reader/DFSHoodieDatasetInputReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowHoodieLogFileRecordsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:L

#10851 [HUDI-7493] Consistent naming of Cleaner configuration parameters
  docker/demo/config/test-suite/multi-writer-1.properties
  docker/demo/config/test-suite/multi-writer-2.properties
  docker/demo/config/test-suite/multi-writer-local-1.properties
  docker/demo/config/test-suite/multi-writer-local-2.properties
  docker/demo/config/test-suite/multi-writer-local-3.properties
  docker/demo/config/test-suite/multi-writer-local-4.properties
  docker/demo/config/test-suite/test-aggressive-clean-archival-inline-compact.properties
  docker/demo/config/test-suite/test-aggressive-clean-archival.properties
  docker/demo/config/test-suite/test-clustering-aggressive-clean-archival-inline-compact.properties
  docker/demo/config/test-suite/test-clustering-aggressive-clean-archival.properties
  docker/demo/config/test-suite/test-clustering-metadata-aggressive-clean-archival-inline-compact.properties
  docker/demo/config/test-suite/test-clustering-metadata-aggressive-clean-archival.properties
  docker/demo/config/test-suite/test-metadata-aggressive-clean-archival-inline-compact.properties
  docker/demo/config/test-suite/test-metadata-aggressive-clean-archival.properties
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestCleansCommand.java
  hudi-cli/src/test/resources/clean.properties
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleaningTriggerStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCleaningPolicy.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/configuration/TestOptionsResolver.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSourceStorage.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestIncrementalReadWithFullTableScan.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSourceDAGExecution.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTableDropPartition.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCleanProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCommitsProcedure.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: table-service, configs, size:L

#10856 [DOCS] [HUDI-7493] Consistent naming of Cleaner configuration parameters
  website/docs/basic_configurations.md
  website/docs/configurations.md
Labels: docs, size:XL

#11022 [HUDI-7619] Removed code duplicates in HoodieTableMetadataUtil
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: size:S

#11025 [HUDI-3907] Claim RFC-77 for secondary idnex design
  rfc/README.md
Labels: size:XS

#10962 [HUDI-6762] Removed usages of MetadataRecordsGenerationParams
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataRecordsGenerationParams.java
Labels: size:L

#10956 [HUDI-7566] Add schema evolution to spark file readers
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark24ParquetReader.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30ParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31ParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32PlusParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark35ParquetReader.scala
Labels: spark, release-1.0.0, size:L

#10992 [HUDI-7577] Avoid MDT compaction instant time conflicts
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
Labels: metadata, release-1.0.0, size:S

#11027 [MINOR] Remove redundant lines in StreamSync and TestStreamSyncUnitTests
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSyncUnitTests.java
Labels: size:S

#11021 [HUDI-7582] Fix functional index lookup
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/functional/TestHoodieSparkFunctionalIndex.java
  hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieFunctionalIndex.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
Labels: size:M

#11037 [MINOR] Rename location to path in `makeQualified`
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
Labels: size:S

#11028 [HUDI-7578] Avoid unnecessary rewriting to improve performance
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandleWithChangeLog.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandleWithChangeLog.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
Labels: priority:critical, performance-regression, release-0.15.0, size:S

#11038 [HUDI-7625] Avoid unnecessary rewrite for metadata table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
Labels: performance, metadata, performance-regression, release-0.15.0, size:XS

#11039 [HUDI-7626] propagate UserGroupInformation from the main thread to the new thread of timeline service threadpool
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
Labels: size:M

#11042 [HUDI-4228] Clean up literal usage in Hudi CLI argument check
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/ArchiveExecutorUtils.java
Labels: size:M

#11045 [HUDI-7633] Use try with resources for AutoCloseable
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/ExportCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/TableCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/LogReaderUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/util/SerializationUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-examples/hudi-examples-java/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java
  hudi-examples/hudi-examples-spark/src/main/java/org/apache/hudi/examples/spark/HoodieWriteClientExample.java
  hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactionAdminTool.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SchedulerConfGenerator.java
Labels: size:L

#11046 [MINOR] Remove redundant TestStringUtils in hudi-common module
  hudi-common/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
Labels: size:M

#11049 [HUDI-7636] Make StoragePath Serializable
  hudi-io/src/main/java/org/apache/hudi/storage/StoragePath.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestStoragePath.java
Labels: size:S

#11048 [HUDI-7635] Add default block size and openSeekable APIs to HoodieStorage
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
Labels: size:M

#11050 [HUDI-7637] Make StoragePathInfo Comparable
  hudi-io/src/main/java/org/apache/hudi/storage/StoragePathInfo.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestStoragePathInfo.java
Labels: size:S

#11052 [HUDI-7640] Uses UUID as temporary file suffix for HoodieStorage.createImmutableFileInPath
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
Labels: size:S

#11018 [HUDI-7618] Add ability to ignore checkpoints in delta streamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSyncUnitTests.java
Labels: size:S

#11056 [HUDI-7643] Fix test by using the right StreamSync constructor
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSyncUnitTests.java
Labels: size:XS

#10886 [HUDI-7515] Fix partition metadata write failure
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowDataCreateHandle.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodiePartitionMetadata.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestTablePathUtils.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableAddPartitionCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairAddpartitionmetaProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairMigratePartitionMetaProcedure.scala
Labels: size:M

#11057 [MINOR] Added configurations of Hudi table, file-based SQL source, Hudi error table, and timestamp key generator to configuration listing
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieErrorTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
  hudi-common/src/main/java/org/apache/hudi/common/config/TimestampKeyGeneratorConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/SqlFileBasedSourceConfig.java
Labels: size:S

#11058 [DOCS] [MINOR] Added configurations of Hudi table, file-based SQL source, Hudi error table, and timestamp key generator to configuration listing
  website/docs/basic_configurations.md
  website/docs/configurations.md
Labels: docs, size:M

#11059 [HUDI-7631] Clean up usage of CachingPath outside hudi-common module
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkPartitionUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowCreateHandle.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/HoodieTablePreCommitFileSystemView.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SparkSampleWritesUtils.java
Labels: size:M

#11032 [HUDI-7623] Refactoring of RemoteHoodieTableFileSystemView and RequestHandler
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
Labels: size:L

#11060 [HUDI-7655] Minor fix to rli validation with MDT validator
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: release-0.15.0, size:XS

#11068 [MINOR] Reuse MetadataPartitionType enum to get all partition paths
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
Labels: size:S

#11005 [HUDI-7608] Fix Flink table creation configuration not taking effect when writing…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieHiveCatalog.java
Labels: size:S

#11062 [MINOR] Fix incorrect catch of ClassCastException using HoodieSparkKeyGeneratorFactory
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/ExecutionStrategyUtil.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkHoodieIndexFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/keygen/factory/HoodieSparkKeyGeneratorFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/bootstrap/SparkFullBootstrapDataProviderBase.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/TestCustomKeyGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/keygen/factory/TestHoodieSparkKeyGeneratorFactory.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithCustomKeyGenerator.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:M

#11074 [HUDI-7653] Refactor HoodieFileIndex for more flexibility
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
Labels: size:L

#11076 [MINOR] Fixed naming of methods in HoodieMetadataConfig
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
Labels: size:S

#11066 [HUDI-7647] READ_UTC_TIMEZONE doesn't affect log files for MOR tables
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/ColumnStatsIndices.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/AvroToRowDataConverters.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: schema-and-data-types, flink-sql, size:S

#9085 [HUDI-6386] Enable testArchivalWithMultiWriters back as they are passing
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
Labels: table-service, bug-fix, size:S

#11063 [MINOR] fix LoggerName for JDBCExecutor
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/ddl/JDBCExecutor.java
Labels: size:XS

#11082 [HUDI-7632] Remove FileSystem usage in HoodieLogFormatWriter
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
Labels: size:S

#11072 [HUDI-7650] Remove FileSystem argument in TestHelpers methods
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/HoodieOfflineJobTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieClusteringJob.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/TestHoodieCompactorJob.java
Labels: size:M

#11086 [MINOR] Remove unused util methods in LogReaderUtils
  hudi-common/src/main/java/org/apache/hudi/common/table/log/LogReaderUtils.java
Labels: size:S

#11087 [HUDI-5180][HUDI-3939] Fix links and clarify JIRA self-service
  website/community/get-involved.md
  website/contribute/how-to-contribute.md
Labels: docs, size:XS

#11084 [HUDI-7660] Fix excessive object creation in RowDataKeyGen
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
Labels: performance, code-refactor, size:S

#10336 [HUDI-7235] Fix checkpoint bug for S3/GCS Incremental Source
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/GcsEventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestIncrSourceHelper.java
Labels: size:S

#11067 [HUDI-7648] Refactor MetadataPartitionType so as to enahance reuse
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
Labels: size:M

#11065 [HUDI-7645] Optimize BQ sync tool for MDT
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/BigQuerySyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
Labels: size:S

#11091 [HUDI-7666] Fix serializable implementation of StorageConfiguration class
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HadoopStorageConfiguration.java
  hudi-io/src/main/java/org/apache/hudi/storage/StorageConfiguration.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/BaseTestStorageConfiguration.java
Labels: size:S

#11093 [MINOR] Make KafkaSource abstraction public and more flexible
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/ProtoKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
Labels: size:S

#11080 [HUDI-7658] Add time to meta sync failure log
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:S

#10875 [HUDI-7511] Fixing offset range calculation for kafka
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Labels: size:S

#11097 [HUDI-7672] Fix the Hive server scratch dir for tests in hudi-utilities
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Labels: size:XS

#10976 [HUDI-7575] avoid repeated fetching of pending replace instants
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
Labels: size:S

#11103 [HUDI-7676] Fix serialization in Spark DAG in HoodieBackedTableMetadataWriter
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Labels: size:XS

#11089 [HUDI-7664] Remove Hadoop dependency from hudi-io module
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-io/pom.xml
  hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/DedupeSparkJob.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieRepairTool.java
Labels: size:S

#10806 [MINOR] Streamer test setup performance
  hudi-common/src/test/java/org/apache/hudi/common/testutils/RawTripTestPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Labels: size:S

#11096 [HUDI-7670] Return StorageConfiguration from getConf() and add unwrapConf() in HoodieStorage
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/DirectWriteMarkers.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestDFSPropertiesConfiguration.java
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriterBase.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieROTablePathFilter.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDataSourceHelpers.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/DedupeSparkJob.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
Labels: size:S

#11102 [HUDI-7668] Add and rename APIs in StorageConfiguration
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HadoopStorageConfiguration.java
  hudi-io/src/main/java/org/apache/hudi/storage/StorageConfiguration.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/BaseTestStorageConfiguration.java
Labels: size:S

#11101 [HUDI-7675]Don't set default value for primary key when get schema from hms
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HiveSchemaUtils.java
Labels: size:XS

#11100 [HUDI-7674] Fix Hudi CLI Command "metadata validate-files" to use file listing to validate
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
Labels: size:S

#11109 [MINOR] Fix build on master
  hudi-integ-test/src/main/java/org/apache/hudi/integ/testsuite/HoodieDeltaStreamerWrapper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
Labels: size:XS

#11108 [HUDI-7681] Remove Hadoop Path usage in a few classes in hudi-common module
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanMetadataV1MigrationHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanMetadataV2MigrationHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanPlanV1MigrationHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/clean/CleanPlanV2MigrationHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/compaction/CompactionV1MigrationHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/compaction/CompactionV2MigrationHandler.java
  hudi-common/src/main/java/org/apache/hudi/metrics/Metrics.java
Labels: size:S

#11112 [DOCS] Fix wrong default value of metadata.enabled option for Flink
  website/docs/metadata.md
  website/versioned_docs/version-0.14.0/metadata.md
  website/versioned_docs/version-0.14.1/metadata.md
Labels: docs, size:XS

#11114 [HUDI-7683] Make HoodieMetadataMetrics log level debug ro reduce noise
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMetrics.java
Labels: size:XS

#11113 [DOCS] Fix minor description errors after merging #11112
  website/docs/metadata.md
  website/versioned_docs/version-0.14.0/metadata.md
  website/versioned_docs/version-0.14.1/metadata.md
Labels: docs, size:XS

#11110 [HUDI-7682] Remove the files copy in Azure CI tests report
  azure-pipelines-20230430.yml
  scripts/ci/move_surefire_reports.sh
Labels: size:S

#11115 [MINOR] Remove the redundant log in HFileBootstrapIndex
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
Labels: code-refactor, size:XS

#11116 [HUDI-7684] Sort the records for Flink metadata table bulk_insert
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestSQL.java
Labels: metadata, flink-sql, size:S

#11127 [DOCS] Add blogs to site
  website/blog/2024-02-06-Combine-Transactional-Integrity-and-Data-Lake-Operations-with-YugabyteDB-and-Apache-Hudi.mdx
  website/blog/2024-02-23-Enabling-near-real-time-data-analytics-on-the-data-lake.mdx
  website/blog/2024-02-27-empowering-data-driven-excellence-how-the-bluestone-data-platform-embraced-data-mesh-for-success.mdx
  website/blog/2024-03-16-Open-Table-Formats-part-1-Apache-Hudi-Hadoop-Upserts-Deletes-and-Incrementals.mdx
  website/blog/2024-04-21-build-real-time-streaming-pipeline-with-kinesis-apache-flink-and-apache-hudi.mdx
  website/blog/2024-04-24-understanding-apache-hudi-consistency-model-part-1.mdx
  website/blog/2024-04-24-understanding-apache-hudi-consistency-model-part-2.mdx
  website/blog/2024-04-24-understanding-apache-hudi-consistency-model-part-3.mdx
  website/static/assets/images/blog/2024-02-06-Combine-Transactional-Integrity-and-Data-Lake-Operations-with-YugabyteDB-and-Apache-Hudi.png
  website/static/assets/images/blog/2024-02-23-Enabling-near-real-time-data-analytics-on-the-data-lake.jpg
  website/static/assets/images/blog/2024-02-27-empowering-data-driven-excellence-how-the-bluestone-data-platform-embraced-data-mesh-for-success.png
  website/static/assets/images/blog/2024-03-16-Open-Table-Formats-part-1-Apache-Hudi-Hadoop-Upserts-Deletes-and-Incrementals.jpg
  website/static/assets/images/blog/2024-04-21-build-real-time-streaming-pipeline-with-kinesis-apache-flink-and-apache-hudi.png
  website/static/assets/images/blog/2024-04-24-understanding-apache-hudi-consistency-model-part-1.png
  website/static/assets/images/blog/2024-04-24-understanding-apache-hudi-consistency-model-part-2.png
  website/static/assets/images/blog/2024-04-24-understanding-apache-hudi-consistency-model-part-3.png
Labels: docs, size:M
