Repository apache/hudi, pull requests merged in 2024-06, with the labels that each got.

#11043 [HUDI-7007] Add bloom_filters index support on read side
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BloomFiltersIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBloomFiltersIndexSupport.scala
Labels: index, size:L, release-1.0.0-beta2

#11368 [HUDI-7816] Provide SourceProfileSupplier option into the SnapshotLoadQuerySplitter
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SnapshotLoadQuerySplitter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSnapshotQuerySplitterImpl.java
Labels: size:S

#11384 [MINOR] Fix LoggerName for BaseHoodieTableServiceClient
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
Labels: size:XS

#11382 [MINOR] Avoid logging full commit metadata at info level
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
Labels: size:XS

#11379 [HUDI-7816] Provide SourceProfileSupplier option into the SnapshotLoadQuerySplitter (branch-0.x)
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/SnapshotLoadQuerySplitter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSnapshotQuerySplitterImpl.java
Labels: size:S

#11375 [HUDI-7824] Fixing incr cleaner with savepoint removal
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
Labels: size:M

#11387 [MINOR] Correct order of test services start in `UtilitiesTestBase`
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/UtilitiesTestBase.java
Labels: size:S

#11389 [HUDI-7782] Task not serializable due to DynamoDBBasedLockProvider and HiveMetastoreBasedLockProvider in clean action
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/transaction/lock/HiveMetastoreBasedLockProvider.java
Labels: size:S

#11394 [HUDI-7828] Support Flink 1.18.1
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/AbstractColumnReader.java
  pom.xml
Labels: size:XS

#11393 [HUDI-7828][branch-0.x] Support Flink 1.18.1
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/table/format/cow/vector/reader/AbstractColumnReader.java
  pom.xml
Labels: size:XS

#11407 [MINOR] Add logs whenever fallback to fs listing even with MDT enabled
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
Labels: size:XS

#11411 [MINOR] Remove calcite dependency
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Labels: size:XS

#10957 [HUDI-7567] Add schema evolution to the filegroup reader
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieInternalRowUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReader.scala
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderState.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/action/InternalSchemaMerger.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/convert/AvroInternalSchemaConverter.java
  hudi-common/src/test/java/org/apache/hudi/avro/AvroSchemaTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
  hudi-common/src/test/java/org/apache/hudi/internal/schema/action/TestMergeSchema.java
  hudi-common/src/test/java/org/apache/hudi/internal/schema/convert/TestAvroInternalSchemaConverter.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestHarness.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReaderBase.scala
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestHoodieSchemaUtils.java
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/parquet/TestHoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/TestSparkParquetReaderFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestAvroSchemaResolutionSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestSpark35RecordPositionMetadataColumn.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/util/TestSparkInternalSchemaConverter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
Labels: schema-evolution, size:XL, release-1.0.0-beta2

#11413 [HUDI-7840] Add position merging to the new file group reader
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedSchemaHandler.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/parquet/TestSparkFileFormatInternalRowReaderContext.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestFiltersInFileGroupReader.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestSpark35RecordPositionMetadataColumn.scala
Labels: size:L, release-1.0.0-beta2

#11406 [HUDI-7834] Create placeholder table versions and introduce new hoodie table property to track initial table version
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/RepairsCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToSixDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToSevenUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RepairOverwriteHoodiePropsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
Labels: size:M, release-1.0.0-beta2

#11412 [MINOR][branch-0.x] Remove calcite dependency
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestParquetColumnProjection.scala
Labels: size:XS

#11416 [HUDI-7844] Fix HoodieSparkSqlTestBase to throw error upon test failure
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
Labels: release-1.0.0, size:S, release-1.0.0-beta2

#11420 [HUDI-7846] Bump apache-rat-plugin to 0.16.1 to eliminate thread-safe warning in maven parallel build
  pom.xml
Labels: size:XS

#11418 [HUDI-7845] Call show_fsview_latest procedure support path_regex
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowFileSystemViewProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestFsViewProcedure.scala
Labels: size:M

#11414 [HUDI-7390] fix: HoodieStreamer no longer works without --props being supplied
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
Labels: size:XS

#10422 [HUDI-6787] Implement the HoodieFileGroupReader API for Hive
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestPartitionTTLManagement.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileGroupReaderBasedRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveRecord.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveRecordMerger.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/RecordReaderValueIterator.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieCombineRealtimeRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieParquetRealtimeInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieArrayWritableAvroUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/ObjectInspectorCache.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/hive/TestHoodieCombineHiveInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieMergeOnReadSnapshotReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/utils/TestHoodieArrayWritableAvroUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieStreamerUtils.java
Labels: release-1.0.0, size:XL, release-1.0.0-beta2

#9894 [HUDI-6798] Add record merging mode and implement event-time ordering in the new file group reader
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestTableSchemaEvolution.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/RecordMergeMode.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestCustomMerger.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestEventTimeMerging.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
Labels: release-1.0.0, size:L, release-1.0.0-beta2

#11422 [HUDI-7851] Fix java doc of DeltaWriteProfile
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/profile/DeltaWriteProfile.java
Labels: size:XS

#11424 [HUDI-7852] Constrain the comparison of different types of ordering values to limited cases
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
Labels: release-1.0.0, size:M, release-1.0.0-beta2

#11428 [HUDI-7786] Fix roaring bitmap dependency in hudi-integ-test-bundle
  packaging/hudi-integ-test-bundle/pom.xml
Labels: size:XS, release-1.0.0-beta2

#11404 [HUDI-7853] Fix missing serDe properties post migration from hiveSync to glueSync
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: size:S

#11381 [HUDI-7826] Make column nullable when setNullForMissingColumns is true
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/AvroSchemaTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/internal/schema/utils/TestAvroSchemaEvolutionUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestHoodieSchemaUtils.java
Labels: size:S

#11432 [DOCS] Update show_fsview_latest para
  website/docs/procedures.md
Labels: docs, size:S

#11433 [MINOR] Update release guide
  release/release_guide.md
Labels: size:XS

#11370 [HUDI-7819] Fix OptionsResolver#allowCommitOnEmptyBatch default value bug
  hudi-examples/hudi-examples-flink/src/main/java/org/apache/hudi/examples/quickstart/HoodieFlinkQuickstart.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: priority:minor, flink, configs, size:S

#11442 [MINOR] Fix README for Slack link update and Linkedin badge
  README.md
Labels: size:XS

#11427 [HUDI-7854] Bump AWS SDK v2 version to 2.25.69
  pom.xml
Labels: size:XS

#11426 [HUDI-7854] Bump AWS SDK v2 version to 2.25.69
  pom.xml
Labels: size:XS

#11441 [HUDI-7869] Ensure properties are copied when modifying schema
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
Labels: size:S

#11449 [HUDI-7871] remove tableconfig from filegroup reader params
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestHarness.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileGroupReaderBasedRecordReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: size:S

#11443 [HUDI-7671] Make Hudi timeline backward compatible
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
Labels: version-compatibility, size:S

#11451 [HUDI-7872] Recreate Glue table on certain types of exceptions
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AwsGlueCatalogSyncTool.java
  hudi-aws/src/main/java/org/apache/hudi/config/GlueCatalogSyncClientConfig.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/MockAwsGlueCatalogSyncTool.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAwsGlueSyncTool.java
  hudi-aws/src/test/java/org/apache/hudi/aws/testutils/GlueTestUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-common/src/test/resources/complex-schema-evolved.avsc
  hudi-common/src/test/resources/complex-schema-evolved.data
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncConfig.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncClient.java
Labels: meta-sync, size:XL

#11456 [HUDI-7879] Optimize the redundant creation of HoodieTable in DataSourceInternalWriterHelper and the unnecessary parameters in createTable within BaseHoodieWriteClient.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
Labels: size:S

#11458 [HUDI-7880] Support extraMetadata in Spark SQL Insert Into
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCLIUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieSqlCommonUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:S

#11462 [HUDI-7891] Fix HoodieActiveTimeline#deleteCompletedRollback missing check for Action type
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Labels: size:XS

#11439 [HUDI-7847] Infer record merge mode during table upgrade
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
Labels: size:S

#11444 [HUDI-7838] Remove the option hoodie.schema.cache.enable and always do the cache
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/SchemaEvolutionContext.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
Labels: size:S

#11455 [HUDI-7876] use properties to store log spill map configs for fg reader
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileGroupReaderTestUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileGroupReaderBasedRecordReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
Labels: size:M

#11450 [HUDI-7874] Fix Hudi being able to read 2-level structure
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroParquetReader.java
  hudi-hadoop-common/src/main/java/org/apache/parquet/avro/HoodieAvroReadSupport.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestParquetReaderCompatibility.scala
Labels: size:L

#11461 [HUDI-7874] Ensure Parquet can interoperate different level structures
  hudi-hadoop-common/src/main/java/org/apache/parquet/avro/HoodieAvroReadSupport.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestParquetReaderCompatibility.scala
Labels: size:L

#11488 [MINOR] Disable new HFile reader by default
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
Labels: size:XS

#11470 [HUDI-7906] improve the parallelism deduce in rdd write
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieGlobalSimpleIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/simple/HoodieSimpleIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieDeleteHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieWriteHelper.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/commit/TestWriterHelperBase.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaPairRDD.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaRDD.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/data/TestHoodieJavaRDD.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestSparkWriteHelper.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListPairData.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodiePairData.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: performance, priority:critical, usability, size:M, resource-and-concurrency

#11423 [HUDI-7849] Reduce time spent on running testFiltersInFileFormat
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestFiltersInFileGroupReader.java
Labels: size:XS

#11460 [HUDI-7881] Verify table base path as well for syncing table in bigquery metastore
  hudi-gcp/src/main/java/org/apache/hudi/gcp/bigquery/HoodieBigQuerySyncClient.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestBigQuerySyncTool.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/bigquery/TestHoodieBigQuerySyncClient.java
  hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
Labels: size:S

#11479 [HUDI-6508] Support compilation on Java 11
  .github/workflows/bot.yml
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-examples/hudi-examples-common/pom.xml
  hudi-examples/hudi-examples-java/pom.xml
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
Labels: size:M

#11376 [HUDI-5956] fix spark DAG ui when write
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/hudi/SparkAdapter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/adapter/Spark2Adapter.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
Labels: size:S

#11474 [HUDI-7909] Add Comment to the FieldSchema returned by Aws Glue Client
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/testutils/GlueTestUtil.java
Labels: size:M

#6781 [HUDI-4123] Enchancing deltastreamer sql source tests
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: priority:minor, hudistreamer, test-coverage, size:S

#10641 [HUDI-7395] Fix computation for metrics in HoodieMetadataMetrics
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataMetrics.java
Labels: metrics, size:S

#6845 [HUDI-4945] Add a test case for batch clean.
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: priority:minor, flink, table-service, size:S

#6695 [MINOR] Adding tests for streaming read mor with compaction
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
Labels: priority:minor, table-service, spark-streaming, test-coverage, size:S

#11503 [DOCS] Update Blogs
  website/blog/2024-04-25-apache-hudi-vs-apache-iceberg-a-comprehensive-comparison.mdx
  website/blog/2024-05-02-how-query-apache-hudi-tables-python-using-daft-spark-free.mdx
  website/blog/2024-05-07-learn-how-read-hudi-data-aws-glue-ray-using-daft-spark.mdx
  website/blog/2024-05-10-building-analytical-apps-on-the-lakehouse-using-apache-hudi-daft-streamlit.mdx
  website/blog/2024-05-19-apache-hudi-on-aws-glue.mdx
  website/blog/2024-05-22-use-aws-data-exchange-to-seamlessly-share-apache-hudi-datasets.mdx
  website/blog/2024-05-27-apache-hudi-vs-delta-lake-choosing-the-right-tool-for-your-data-lake-on-aws.mdx
  website/blog/2024-06-07-apache-hudi-a-deep-dive-with-python-code-examples.mdx
  website/blog/2024-06-18-how-to-use-apache-hudi-with-databricks.mdx
  website/src/pages/talks.md
  website/static/assets/images/blog/2024-04-25-apache-hudi-vs-apache-iceberg-a-comprehensive-comparison.png
  website/static/assets/images/blog/2024-05-02-how-query-apache-hudi-tables-python-using-daft-spark-free.png
  website/static/assets/images/blog/2024-05-07-learn-how-read-hudi-data-aws-glue-ray-using-daft-spark.png
  website/static/assets/images/blog/2024-05-10-building-analytical-apps-on-the-lakehouse-using-apache-hudi-daft-streamlit.png
  website/static/assets/images/blog/2024-05-19-apache-hudi-on-aws-glue.png
  website/static/assets/images/blog/2024-05-22-use-aws-data-exchange-to-seamlessly-share-apache-hudi-datasets.png
  website/static/assets/images/blog/2024-05-27-apache-hudi-vs-delta-lake-choosing-the-right-tool-for-your-data-lake-on-aws.png
  website/static/assets/images/blog/2024-06-07-apache-hudi-a-deep-dive-with-python-code-examples.png
  website/static/assets/images/blog/2024-06-18-how-to-use-apache-hudi-with-databricks.jpeg
Labels: docs, size:M

#11500 [DOCS][MINOR] Update team and syncs pages
  website/community/syncs.md
  website/community/team.md
  website/static/assets/images/upcoming-community-calls.png
Labels: docs, size:M

#11491 [DOCS] Update Roadmap page
  website/src/pages/roadmap.md
Labels: docs, size:S

#11504 [DOCS] Update video guides
  website/static/assets/images/video_blogs/2024-05-20-deltastreamer-with-incremental-etl-and-broadcast-joins-for-faster-etl.png
  website/static/assets/images/video_blogs/2024-05-22-hudi-delta-streamer-implementing-slowly-changing-dimension-and-query-that-using-trino.png
  website/static/assets/images/video_blogs/2024-05-22-hudi-streamer-implementing-slowly-changing-dimension-type-2-and-query-real-time-trino.png
  website/static/assets/images/video_blogs/2024-05-23-build-hudi-date-dimension-in-minutes-with-spark-sql-minio-and-query-with-trino.png
  website/static/assets/images/video_blogs/2024-05-25-learn-how-to-ingest-data-from-pulsar-topic-into-hudi-with-deltastreamer.png
  website/static/assets/images/video_blogs/2024-06-05-multiple-spark-writers-to-hudi-tables.png
  website/static/assets/images/video_blogs/2024-06-12-hudi-cleaning-process-hoodie.keep.min.commits-and-hoodie.keep.max.commits-explained.png
  website/static/assets/images/video_blogs/2024-06-15-how-we-utilized-hudis-time-travel-query-to-investigate-bid-and-spend.png
  website/static/assets/images/video_blogs/2024-06-16-hudi-with-spark-sql-for-beginners-insert-updates-delete-incremental-query-stored-procedures.png
  website/static/assets/images/video_blogs/2024-06-18-learn-how-to-ingest-xml-files-with-aws-glue-into-hudi-datalakes.png
  website/static/assets/images/video_blogs/2024-06-21-Four-Different-Ways-to-fetch-Apache-Hudi-Commit-time-in-Python-and-PySpark.png
  website/videoBlog/2024-05-20-deltastreamer-with-incremental-etl-and-broadcast-joins-for-faster-etl.mdx
  website/videoBlog/2024-05-22-hudi-delta-streamer-implementing-slowly-changing-dimension-and-query-that-using-trino.mdx
  website/videoBlog/2024-05-22-hudi-streamer-implementing-slowly-changing-dimension-type-2-and-query-real-time-trino.mdx
  website/videoBlog/2024-05-23-build-hudi-date-dimension-in-minutes-with-spark-sql-minio-and-query-with-trino.mdx
  website/videoBlog/2024-05-25-learn-how-to-ingest-data-from-pulsar-topic-into-hudi-with-deltastreamer.mdx
  website/videoBlog/2024-06-05-multiple-spark-writers-to-hudi-tables.mdx
  website/videoBlog/2024-06-12-hudi-cleaning-process-hoodie.keep.min.commits-and-hoodie.keep.max.commits-explained.mdx
  website/videoBlog/2024-06-15-how-we-utilized-hudis-time-travel-query-to-investigate-bid-and-spend.mdx
  website/videoBlog/2024-06-16-hudi-with-spark-sql-for-beginners-insert-updates-delete-incremental-query-stored-procedures.mdx
  website/videoBlog/2024-06-18-learn-how-to-ingest-xml-files-with-aws-glue-into-hudi-datalakes.mdx
  website/videoBlog/2024-06-21-Four-Different-Ways-to-fetch-Apache-Hudi-Commit-time-in-Python-and-PySpark.mdx
Labels: docs, size:M

#11505 [MINOR] Reduce logging volume
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
Labels: size:S

#11499 [MINOR] Removed useless checks from SqlBasedTransformers
  hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/SqlFileBasedTransformer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/SqlQueryBasedTransformer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/transform/TestSqlQueryBasedTransformer.java
Labels: size:S

#10652 [HUDI-7927] Lazy init secondary view in FS view
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewManager.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/PriorityBasedFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/table/view/TestPriorityBasedFileSystemView.java
Labels: size:M

#11511 [MINOR] `@TempDir` fails to cleanup temporary directory
  pom.xml
Labels: size:XS

#11495 [HUDI-7922] Add Hudi CLI bundle for Scala 2.13
  .github/workflows/bot.yml
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/ArchivedCommitsCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/JavaScalaConverters.scala
  scripts/release/deploy_staging_jars.sh
  scripts/release/validate_staged_bundles.sh
Labels: size:S

#11513 [HUDI-6508] Support compilation on Java 11
  .github/workflows/bot.yml
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestCopyOnWriteActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-examples/hudi-examples-common/pom.xml
  hudi-examples/hudi-examples-java/pom.xml
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
Labels: size:M

#11515 [HUDI-7882] Picking RFC-78 for bridge release
  rfc/README.md
Labels: size:XS

#11506 [HUDI-7838][DOCS] Remove the option hoodie.schema.cache.enable and always do the cache
  website/docs/configurations.md
Labels: docs, size:XS

#11507 [DOCS] Add missing parallelism into snapshot_exporter.md
  website/versioned_docs/version-0.13.0/snapshot_exporter.md
  website/versioned_docs/version-0.13.1/snapshot_exporter.md
  website/versioned_docs/version-0.14.0/snapshot_exporter.md
  website/versioned_docs/version-0.14.1/snapshot_exporter.md
  website/versioned_docs/version-0.15.0/snapshot_exporter.md
Labels: docs, size:S

#11501 [HUDI-7709] ClassCastException while reading the data using `TimestampBasedKeyGenerator`
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala
Labels: size:M

#11467 [HUDI-7877] Add record position to record index metadata payload
  hudi-common/src/main/avro/HoodieMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
Labels: size:S

#11526 [DOCS] Add Ecosystem Page
  website/src/pages/ecosystem.md
Labels: docs, size:S

#11528 [DOCS] Update Ecosystem page
  website/docusaurus.config.js
Labels: docs, size:XS

#11498 [HUDI-7924] Capture Latency and Failure Metrics For Hive Table recreation
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/metrics/HoodieMetaSyncMetrics.java
  hudi-sync/hudi-sync-common/src/test/java/org/apache/hudi/sync/common/metrics/TestHoodieMetaSyncMetrics.java
Labels: size:M

#11533 [MINOR] doap: don't nest multiple versions in a release
  doap_HUDI.rdf
Labels: size:S

#11487 [HUDI-7914] Use internal schema without metadata fields for delete-partitions OP
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTableDropPartition.scala
Labels: size:S

#11473 [HUDI-7908] HoodieFileGroupReader fails if preCombine and partition fields are the same
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:S

#11497 [HUDI-7921] Closing fsview in HoodieTableFileIndex
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/SyncableFileSystemView.java
Labels: size:S

#11472 [HUDI-7903] Fix storage partition stats index to skip data
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
Labels: index, size:L, release-1.0.0-beta2
