Repository apache/hudi, pull requests merged in 2024-11, with the labels that each got.

#12192 [HUDI-8455] Logic for partition column values parse is localized in `HoodieSparkUtils`
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkPartitionUtils.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/keygen/constant/KeyGeneratorType.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieTableFileIndex.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCDCFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
Labels: size:S

#12202 [HUDI-8430] Remove redundant configs in TestInsertTable
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:M

#12199 [MINOR] Fix typo in payload class config docs in Hudi Streamer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
Labels: size:XS

#12153 [HUDI-8326] Add some more functional index tests
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
Labels: size:M

#12173 [HUDI-8450] Optimize the design of EmbeddedTimelineServerHelper#createEmbeddedTimelineService
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineServerHelper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:S

#12140 [HUDI-8399] Upgrade protobuf version to 3.25.5 to fix CVE-2024-7254
  dependencies/hudi-kafka-connect-bundle.txt
  pom.xml
Labels: size:XS

#12165 [HUDI-4818] Update partition column type to avoid type conversion failure
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParsePartitionUtil.scala
Labels: size:XS

#12212 [HUDI-8484] Instant heartbeats memory leak
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/heartbeat/TestHoodieHeartbeatClient.java
Labels: priority:critical, resource-leak, size:S

#12218 Revert "[HUDI-4818] Update the data type to string to avoid type convertion failure (#12165)"
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParsePartitionUtil.scala
Labels: size:XS

#12166 [HUDI-8433] Fix not update issuedOffset when stream read empty commits
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/StreamReadMonitoringFunction.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestStreamReadMonitoringFunction.java
Labels: size:S

#12146 [HUDI-8410] Fix a flaky test for partition stats
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
Labels: size:S

#12222 [HUDI-8495] Add drop_partition procedure
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/BaseProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/DropPartitionProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestDropPartitionProcedure.scala
Labels: size:L

#12214 [HUDI-8459] Fix secondary index record merging
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-common/src/main/avro/HoodieMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMetadataMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexKeyUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieMetadataPayload.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:XL

#12157 [HUDI-8428] Encode pruned partitions while fetching functional index
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
Labels: size:M

#12243 [MINOR] fixed table type option in ITTestHoodieDataSource
  hudi-examples/hudi-examples-flink/src/main/java/org/apache/hudi/examples/quickstart/HoodieFlinkQuickstart.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: size:XS

#12174 [HUDI-8452] Init partition stats based on latest file slices only
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:M

#12258 [SITE][MINOR] Add Event banner for upcoming community sync Amazon
  website/src/components/EventFeature/index.js
Labels: docs, size:XS

#12224 [HUDI-8395] Fix metaClient handling when running upgrade or downgrade
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/CommonClientUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestMultipleTableVersionWriting.scala
Labels: size:S

#12246 [MINOR] Update Avro URL in README
  README.md
Labels: size:XS

#12263 [HUDI-8519] Fix update with multiple secondary indexes
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
Labels: size:M

#12255 [HUDI-8513] Fix equals in HoodieRecordGlobalLocation
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordGlobalLocation.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieRecordGlobalLocation.java
Labels: size:S

#12238 [HUDI-8504] Fix missing database config when building Hudi configs in Spark
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestProvidesHoodieConfig.scala
Labels: size:S

#12206 [HUDI-8210] Support writing table version 6 log format from 1.x
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/CommonClientUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/DummyTaskContextSupplier.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroParquetWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/utils/TestLegacyArchivedMetaEntryReader.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestCommonClientUtils.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkWriteableTestTable.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/common/TestHoodieJavaEngineContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieLogFile.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlockVersion.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/CompletionTimeQueryViewV1.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileSliceTestUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormatAppendFailure.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/model/TestHoodieFileGroup.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieLogWriterBuilder.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
Labels: size:XL

#12286 [HUDI-8547] Disable flakey tests
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
Labels: size:XS

#12219 [HUDI-8488] feat: introduce SLF4j metrics reporter
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestMetricsReporterFactory.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestSlf4jMetrics.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporterType.java
  hudi-common/src/main/java/org/apache/hudi/metrics/Slf4jMetricsReporter.java
Labels: size:M

#12266 [HUDI-8520] DROP INDEX & SHOW INDEX should work with index name instead of index partition name
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Index.scala
Labels: size:L

#12247 [HUDI-8337] Fixing failure handling with HoodieMetadataTableValidator
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:L

#12280 [HUDI-8530] Error out secondary index update for write operations such as insert overwrite where it is not supported
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/HoodieWriterClientTestHarness.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
Labels: size:M

#12311 [HUDI-8549] Fixing flaky tests TestSecondaryIndexPruning.testSecondaryIndexWithClusteringAndCleaning
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
Labels: size:XS

#12306 [HUDI-8464] Minor cleanup of time generation APIs and locking
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/TestInlineCompaction.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkCopyOnWriteTableArchiveWithReplace.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieTimeGeneratorConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/SkewAdjustingTimeGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGeneratorBase.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGenerators.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestWaitBasedTimeGenerator.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
Labels: size:M

#12241 [HUDI-8508] Fix timeline service port assignment bug
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TestTimelineService.java
Labels: size:M

#12304 [HUDI-8554] Use COMMIT_TIME_ORDERING
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/BootstrapCommand.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/OverwriteWithLatestSparkRecordMerger.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/config/RecordMergeMode.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestOverwriteWithLatestMerger.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/OverwriteWithLatestHiveRecordMerger.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBasicSchemaEvolution.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
Labels: size:M

#12309 [HUDI-8541] Change to relative paths for the index defs json
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
Labels: size:S

#12312 [HUDI-8416] Fix the bugs for multi base file format feature
  hudi-common/src/main/java/org/apache/hudi/common/table/view/AbstractTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/FileFormatUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/HoodieMultipleBaseFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestHoodieMultipleBaseFileFormat.scala
Labels: size:M

#12290 [HUDI-8533] Bloom functional Index creation without function fails
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieFunctionalIndex.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/FunctionalIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestSecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
Labels: size:L

#12239 fix: ui updates
  website/blog/2021-12-16-lakehouse-concurrency-control-are-we-too-optimistic.mdx
  website/blog/2022-01-06-apache-hudi-2021-a-year-in-review.mdx
  website/blog/2022-01-14-change-data-capture-with-debezium-and-apache-hudi.mdx
  website/blog/2022-12-29-Apache-Hudi-2022-A-Year-In-Review.mdx
  website/blog/2023-12-28-apache-hudi-2023-a-year-in-review.mdx
  website/community/get-involved.mdx
  website/constants.js
  website/docs/overview.mdx
  website/docusaurus.config.js
  website/i18n/cn/docusaurus-plugin-content-pages/get-involved.mdx
  website/sidebars.js
  website/sidebarsCommunity.js
  website/sidebarsContribute.js
  website/src/components/JoinCommunity/index.js
  website/src/components/SlackCommunity.js
  website/src/components/WhyHudi/Icons/data_stream.svg
  website/src/components/WhyHudi/Icons/derived_tables.svg
  website/src/components/WhyHudi/Icons/open_source.svg
  website/src/components/WhyHudi/Icons/trusted_platform.svg
  website/src/css/custom.css
  website/src/pages/powered-by.mdx
  website/versioned_docs/version-0.10.0/overview.mdx
  website/versioned_docs/version-0.10.1/overview.mdx
  website/versioned_docs/version-0.11.0/overview.mdx
  website/versioned_docs/version-0.11.1/overview.mdx
  website/versioned_docs/version-0.12.0/overview.mdx
  website/versioned_docs/version-0.12.1/overview.mdx
  website/versioned_docs/version-0.12.2/overview.mdx
  website/versioned_docs/version-0.12.3/overview.mdx
  website/versioned_docs/version-0.13.0/overview.mdx
  website/versioned_docs/version-0.13.1/overview.mdx
  website/versioned_docs/version-0.14.0/overview.mdx
  website/versioned_docs/version-0.14.1/overview.mdx
  website/versioned_docs/version-0.15.0/overview.mdx
Labels: docs, size:XL

#12283 [HUDI-8427] Fix delete in file group reader and re-enable test in TestHoodieSparkMergeOnReadTableInsertUpdateDelete
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/utils/TestHoodieArrayWritableAvroUtils.java
Labels: size:S

#12319 [HUDI-8559] Avoid adding the conf file twice
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
Labels: size:XS

#12328 [DOCS] Add JD to powered-by page
  website/src/pages/powered-by.mdx
Labels: docs, size:XS

#12325 [HUDI-8573] Fix performance degradation in RowDataKeyGen
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
Labels: size:XS

#12316 [HUDI-8565]: Fix RetryHelper sleep with negative time
  hudi-common/src/test/java/org/apache/hudi/common/util/TestRetryHelper.java
  hudi-io/src/main/java/org/apache/hudi/common/util/RetryHelper.java
Labels: size:S

#12308 [HUDI-8534] Ensure index creation is idempotent in face of failures
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkFunctionalIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieFunctionalIndex.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
Labels: size:M

#12329 fix: font size for anchor links in docs and blogs for markdown
  website/src/css/custom.css
Labels: docs, size:XS

#12334 [DOCS] Adding blog for automated small file handling
  website/blog/2024-11-19-automated-small-file-handling.md
  website/static/assets/images/blog/2024-11-19-automated-small-file-handling-benchmarks.png
  website/static/assets/images/blog/2024-11-19-automated-small-file-handling-process.png
Labels: docs, size:M

#12307 [HUDI-8548] fail create meta client if table does not exist and proper configs not set
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
Labels: size:XS

#12161 [HUDI-8192] Add tests of custom merger in Spark structured streaming
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkDeleteRecordMerger.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStructuredStreaming.scala
Labels: size:M

#12297 [HUDI-8521] Use commit time merge in preCombine for OverwriteWithLatestAvroPayload
  hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteNonDefaultsWithLatestAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/AbstractDebeziumAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestOverwriteWithLatestAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieRecordTestPayload.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSourceDefaults.scala
Labels: size:S

#12287 [HUDI-8295] Validate hudi-utilities-bundle on Spark 3.5 only
  packaging/bundle-validation/validate.sh
Labels: size:XS

#12335 [HUDI-8571] Fix the upgrade for OverwriteWithLatestPayload
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: size:S

#12337 [HUDI-8545] Handle unsupported payloads with Secondary Index creation
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:M

#12336 [HUDI-8432] Fix data skipping with RLI if record key is composite
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestRecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Labels: size:L

#12348 [MINOR] Change README
  README.md
  doap_HUDI.rdf
Labels: size:S

#12303 [HUDI-8560] Revert HUDI-8036
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/SparkParsePartitionUtil.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieIncrementalFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithCustomKeyGenerator.scala
Labels: size:L

#12321 [HUDI-8564] Removing WriteStatus references in Hoodie Metadata writer flow
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/BaseActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/WriteStatBasedIndexingCatchupTask.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaTableServiceClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestConsistentBucketIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestSparkNonBlockingConcurrencyControl.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieCleanerTestBase.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieWriteStat.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseFileRecordParsingUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieWriteStat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringCommitSink.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/internal/DataSourceInternalWriterHelper.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkSortAndSizeClustering.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/offlinejob/HoodieOfflineJobTestBase.java
Labels: size:XL

#12361 [DOCS] Updating new use-cases and home page text
  website/docs/cleaning.md
  website/docs/file_layouts.md
  website/docs/file_sizing.md
  website/docs/metadata_indexing.md
  website/docs/overview.mdx
  website/docs/rollbacks.md
  website/docs/use_cases.md
  website/docs/write_operations.md
  website/docusaurus.config.js
  website/sidebars.js
  website/src/components/DataLakes/index.js
  website/src/components/HomepageFeatures/index.js
  website/src/components/WhyHudi/index.js
  website/src/pages/roadmap.md
  website/versioned_docs/version-0.14.1/file_layouts.md
  website/versioned_docs/version-0.14.1/file_sizing.md
  website/versioned_docs/version-0.14.1/use_cases.md
  website/versioned_docs/version-0.14.1/write_operations.md
  website/versioned_docs/version-0.15.0/file_layouts.md
  website/versioned_docs/version-0.15.0/file_sizing.md
  website/versioned_docs/version-0.15.0/use_cases.md
  website/versioned_docs/version-0.15.0/write_operations.md
Labels: docs, size:L

#12362 [MINOR][site] Updated blogs for October
  website/blog/2024-10-02-apache-hudi-spark-and-minio-hands-on-lab-in-docker.mdx
  website/blog/2024-10-07-iceberg-vs-delta-lake-vs-hudi-a-comparative-look-at-lakehouse-architectures.mdx
  website/blog/2024-10-07-mastering-slowly-changing-dimensions-with-apache-hudi-and-spark-sql.mdx
  website/blog/2024-10-14-streaming-dynamodb-data-into-a-hudi-table-aws-glue-in-action.mdx
  website/blog/2024-10-22-exploring-time-travel-queries-in-apache-hudi.mdx
  website/blog/2024-10-23-Using-Apache-Hudi-with-Apache-Flink.mdx
  website/blog/2024-10-23-mastering-open-table-formats-a-guide-to-apache-iceberg-hudi-and-delta-lake.mdx
  website/blog/2024-10-26-moving-large-tables-from-snowflake-to-s3-using-the-copy-into-command-and-hudi.mdx
  website/blog/2024-10-27-I-spent-5-hours-exploring-the-story-behind-Apache-Hudi.mdx
  website/static/assets/images/blog/2024-10-02-apache-hudi-spark-and-minio-hands-on-lab-in-docker.jpeg
  website/static/assets/images/blog/2024-10-07-mastering-slowly-changing-dimensions-with-apache-hudi-and-spark-sql.png
  website/static/assets/images/blog/2024-10-14-streaming-dynamodb-data-into-a-hudi-table-aws-glue-in-action.png
  website/static/assets/images/blog/2024-10-22-exploring-time-travel-queries-in-apache-hudi.jpeg
  website/static/assets/images/blog/2024-10-22-exploring-time-travel-queries-in-apache-hudi.webp
  website/static/assets/images/blog/2024-10-26-moving-large-tables-from-snowflake-to-s3-using-the-copy-into-command-and-hudi.png
  website/static/assets/images/blog/2024-10-27-I-spent-5-hours-exploring-the-story-behind-Apache-Hudi.jpeg
  website/static/assets/images/video_blogs/2024-10-06-learn-how-to-read-hudi-tables-on-s3-locally-in-your-pyspark-job.png
  website/static/assets/images/video_blogs/2024-10-22-practice-of-building-a-lakehouse-based-on-apache-hudi-at-kuaishou-inc.png
  website/videoBlog/2024-10-06-learn-how-to-read-hudi-tables-on-s3-locally-in-your-pyspark-job.mdx
  website/videoBlog/2024-10-22-practice-of-building-a-lakehouse-based-on-apache-hudi-at-kuaishou-inc.mdx
Labels: docs, size:M

#12367 [DOCS][site] add hudi-rs page and ecosystem links
  website/docs/overview.mdx
  website/docs/python-rust-quick-start-guide.md
  website/sidebars.js
  website/src/pages/ecosystem.md
  website/versioned_docs/version-0.15.0/overview.mdx
  website/versioned_docs/version-0.15.0/python-rust-quick-start-guide.md
  website/versioned_sidebars/version-0.15.0-sidebars.json
Labels: docs, size:M

#12327 [HUDI-7665] Support upgrade downgrade to or from table version 8
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/ActiveActionWithDetails.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v2/LSMTimelineWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v2/TimelineArchiverV2.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/CommonClientUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestEightToSevenDowngradeHandler.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestSevenToEightUpgradeHandler.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieReplaceCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/LSMTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ArchivedTimelineV1.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ArchivedTimelineLoaderV2.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ArchivedTimelineV2.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ArchivedInstantReadSchemas.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CollectionUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestMultipleTableVersionWriting.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/LSMTimelineReadBenchmark.scala
Labels: size:XL

#12349 [HUDI-8578] Standardize SI/FI terminology and syntax
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestEightToSevenDowngradeHandler.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkExpressionIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/functional/TestHoodieSparkExpressionIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/index/functional/HoodieExpressionIndex.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestIndexSyntax.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
  rfc/README.md
  rfc/rfc-63/rfc-63.md
Labels: size:XL

#12262 [HUDI-8529] Add truncate table procedure
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/TruncateTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestTruncateTableProcedure.scala
Labels: size:M

#12363 [HUDI-8598] Fix AND operator to not filter unsupported query types
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestRecordLevelIndexSupport.scala
Labels: size:S

#12310 [HUDI-8556] Add config for max number of colstats columns
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestDataSkippingWithMORColstats.java
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/column-stats-index-table-short-schema.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/cow-updated2-column-stats-index-table-short-schema.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/mor-updated2-column-stats-index-table-short-schema.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/updated-column-stats-index-table-short-schema.json
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:L

#12373 [DOCS] Redoing the hudi stack page and overview page
  site-image-source/hudi-stack-1-x.excalidraw
  site-image-source/hudi-stack-indexes.excalidraw
  site-image-source/hudi-timeline-actions.excalidraw
  site-image-source/hudi-timeline-truetime.excalidraw
  website/docs/hudi_stack.md
  website/docs/overview.mdx
  website/docs/python-rust-quick-start-guide.md
  website/docs/timeline.md
  website/src/pages/roadmap.md
  website/static/assets/images/hudi-stack-1-x.png
  website/static/assets/images/hudi-stack-indexes.png
  website/static/assets/images/hudi-timeline-actions.png
  website/static/assets/images/hudi-timeline-truetime.png
Labels: docs, size:XL

#12350 [HUDI-8586] Allow partition stats only for primitive types
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestFileIndex.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestIncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/stats/TestColumnStatsIndex.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieTableSource.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestHoodieTableValuedFunction.scala
Labels: size:M

#12351 [HUDI-8557] Enabling Metadata by default on reads
  .github/workflows/bot.yml
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:M

#12372 [HUDI-8604] Support index command with External table in Spark SQL
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_3Adapter.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_4Adapter.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/adapter/Spark3_5Adapter.scala
Labels: size:S

#12341 [HUDI-9555] Cleaning up nested field with col stats
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestExternalPathHandling.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/cow-table-nested.json
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Labels: size:S

#12369 [HUDI-6371] Indexing catchup tasks should handle failed commits based on heartbeat
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/AbstractIndexingCatchupTask.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/IndexingCatchupTaskFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RecordBasedIndexingCatchupTask.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/RunIndexActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/WriteStatBasedIndexingCatchupTask.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/index/TestIndexingCatchupTask.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: size:M

#12378 [HUDI-8612] Rename expression index config names
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
Labels: size:S

#12371 [HUDI-8603] Fixing lock provider for single writer use-cases
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
Labels: size:S

#12375 [HUDI-8610] Fix clustering/replacecommit action inference
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/ClusteringPlanActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineMetadataUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CommitMetadataSerDeV2.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
Labels: size:S

#12374 [HUDI-8588] Col stats pruning is ignoring to leverage stats from log files
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BucketIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
Labels: size:M

#12383 [MINOR][site] Updated blogs for September
  website/blog/2024-09-04-developer-guide-how-to-submit-hudi-pyspark-python-jobs-to-emr-serverless.mdx
  website/blog/2024-09-09-use-apache-hudi-tables-in-athena-for-spark.mdx
  website/blog/2024-09-11-comparing-apache-hudi-apache-iceberg-and-delta-lake.mdx
  website/blog/2024-09-14-Ubers-Big-Data-Revolution-From-MySQL-to-Hadoop-and-Beyond.mdx
  website/blog/2024-09-17-how-apache-hudi-transformed-yuno-s-data-lake.mdx
  website/blog/2024-09-22-hands-on-with-apache-hudi-and-spark.mdx
  website/blog/2024-09-24-hudi-iceberg-and-delta-lake-data-lake-table-formats-compared.mdx
  website/blog/2024-09-30-change-query-support-in-apache-hudi-0-15.mdx
  website/static/assets/images/blog/2024-09-04-developer-guide-how-to-submit-hudi-pyspark-python-jobs-to-emr-serverless.png
  website/static/assets/images/blog/2024-09-11-comparing-apache-hudi-apache-iceberg-and-delta-lake.jpeg
  website/static/assets/images/blog/2024-09-14-Ubers-Big-Data-Revolution-From-MySQL-to-Hadoop-and-Beyond.png
  website/static/assets/images/blog/2024-09-17-how-apache-hudi-transformed-yuno-s-data-lake.png
  website/static/assets/images/blog/2024-09-24-hudi-iceberg-and-delta-lake-data-lake-table-formats-compared.png
  website/static/assets/images/video_blogs/2024-09-01-how-to-consume-apache-hudi-tables-in-snowflake-iceberg-and-athena-hands-on-labs.png
  website/static/assets/images/video_blogs/2024-09-26-Create-Apache-Hudi-Table-Using-Glue-in-Catalog-By-Reading-Streaming-Data-From-AWS-Kinesis.png
  website/videoBlog/2024-09-01-how-to-consume-apache-hudi-tables-in-snowflake-iceberg-and-athena-hands-on-labs.mdx
  website/videoBlog/2024-09-26-Create-Apache-Hudi-Table-Using-Glue-in-Catalog-By-Reading-Streaming-Data-From-AWS-Kinesis.mdx
Labels: docs, size:M
