Repository apache/hudi, pull requests merged in 2024-02, with the labels that each got.

#10575 [HUDI-7347] Introduce SeekableDataInputStream for random access
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCDCDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCommandBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCorruptBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopSeekableDataInputStream.java
  hudi-io/src/main/java/org/apache/hudi/io/SeekableDataInputStream.java
Labels: release-1.0.0

#10602 [HUDI-7366] Fix HoodieLocation with encoded paths
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieLocation.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieLocation.java
Labels: release-1.0.0

#10607 [HUDI-7367] Add makeQualified APIs
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieLocation.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieLocation.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
Labels: release-1.0.0

#10636 [HUDI-7392] Fix connection leak causing lingering CLOSE_WAIT
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
Labels: resource-leak

#10599 [HUDI-7364] Move InLineFs classes to hudi-hadoop-common module
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/InLineFSUtilsTest.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystem.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemHFileInLiningBase.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemWithHBaseHFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemWithHFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInMemoryFileSystem.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestParquetInLining.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileSystemTestUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/inline/InLineFSUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/inline/InLineFileSystem.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/inline/InLineFsDataInputStream.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/inline/InMemoryFileSystem.java
Labels: release-1.0.0

#10586 [HUDI-7357] Introduce generic StorageConfiguration
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HadoopStorageConfiguration.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/storage/hadoop/TestHoodieHadoopStorage.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/storage/hadoop/TestStorageConfigurationHadoopStorageConfiguration.java
  hudi-io/src/main/java/org/apache/hudi/storage/StorageConfiguration.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/BaseTestStorageConfiguration.java
Labels: release-1.0.0

#10673 [HUDI-7410] Use SeekableDataInputStream as the input of native HFile reader
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemWithHFileReader.java
  hudi-io/src/main/java/org/apache/hudi/io/ByteArraySeekableDataInputStream.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileBlockReader.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileReaderImpl.java
  hudi-io/src/test/java/org/apache/hudi/io/hfile/TestHFileReader.java
Labels: release-1.0.0

#10680 [DOCS] Clarify release notes on duplicate handling in Spark SQL and r…
  website/docs/configurations.md
  website/releases/release-0.14.0.md
  website/versioned_docs/version-0.14.0/configurations.md
  website/versioned_docs/version-0.14.1/configurations.md
Labels: pr:wip

#10685 [HUDI-7415] Support OLAP engine query from origin table avoid empty result in default
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieSyncConfig.java
Labels: db-sync

#10703 [HUDI-7423] Support table type name incase-sensitive when create table in sparksql
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/HoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
Labels: spark

#10738 [HUDI-7275] Separate use of HoodieTimelineTimeZone.UTC and LOCAL in tests to prevent infinite loops
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriterUtc.scala
Labels: test-stability

#10757 [MINOR] Update HoodieMetadataPayload bloom index error message
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
Labels: size:XS

#10759 [DOCS][HUDI-7398] Add note for java clustering execution strategy
  website/docs/clustering.md
Labels: docs, size:XS

#10755 [MINOR] Fix code style for HiveAvroSerializer
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveAvroSerializer.java
Labels: size:S

#10758 [DOCS][HUDI-7444] Add missing features for `HoodieStreamer`
  website/docs/hoodie_streaming_ingestion.md
Labels: docs, size:L

#10756 [HUDI-7443] Fix decimal conversion with legacy bytes type
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveAvroSerializer.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieRealtimeRecordReaderUtils.java
Labels: size:S

#10658 [DOCS][MINOR] Docs clarification around read and write indexes
  website/docs/indexing.md
Labels: docs, size:S

#10744 [HUDI-7441] Move `getWritePartitionPaths` method to common module to …
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadTableInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelation.scala
Labels: size:S

#10683 initial commit to update doris docs
  website/docs/sql_queries.md
Labels: docs, size:S

#10666 updated hoodie.datasource.hive_sync.partition_extractor_class
  website/releases/release-0.12.0.md
Labels: docs, size:XS

#10656 [MINOR] Improve mdt validator and upsert partitioner logs
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:S

#10768 [HUDI-7450] Fix offset computation bug when allocedEvents > actualNumEvents
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCheckpointUtils.java
Labels: size:S

#10702 [HUDI-5292] Exclude the test resources from every module packaging
  hudi-aws/pom.xml
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-flink-client/pom.xml
  hudi-client/hudi-java-client/pom.xml
  hudi-client/hudi-spark-client/pom.xml
  hudi-examples/hudi-examples-flink/pom.xml
  hudi-kafka-connect/pom.xml
  hudi-timeline-service/pom.xml
  packaging/hudi-aws-bundle/pom.xml
  packaging/hudi-datahub-sync-bundle/pom.xml
  packaging/hudi-flink-bundle/pom.xml
  packaging/hudi-gcp-bundle/pom.xml
  packaging/hudi-hadoop-mr-bundle/pom.xml
  packaging/hudi-hive-sync-bundle/pom.xml
  packaging/hudi-kafka-connect-bundle/pom.xml
  packaging/hudi-presto-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-trino-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
Labels: code-refactor, size:S

#10764 [HUDI-7262] Validate checksum only if it exists
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
Labels: size:S

#10238 [MINOR] Allow removal of column stats from metadata table for externally created files
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: size:XS

#10775 [WEBSITE] Add scarf for website analytics
  website/src/theme/Navbar/index.js
Labels: docs, size:XS

#10717 [HUDI-7431] Add replication and block size to StoragePathInfo to be backwards compatible
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HadoopFSUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/hadoop/fs/TestHadoopFSUtils.java
  hudi-io/src/main/java/org/apache/hudi/storage/StoragePathInfo.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestStoragePathInfo.java
Labels: release-1.0.0, size:M

#10777 [HUDI-7452] Repartition row dataset in S3/GCS based on task size
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/CloudObjectsSelectorCommon.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestCloudObjectsSelectorCommon.java
  hudi-utilities/src/test/resources/data/partitioned/country=IND/state=TS/data.json
  hudi-utilities/src/test/resources/data/partitioned/country=US/state=TX/data.json
Labels: size:S

#10598 [HUDI-7385] Add config for custom write support for parquet row writer
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/HoodieSparkFileWriterFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieInternalRowFileWriterFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/storage/row/HoodieRowParquetWriteSupport.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/io/storage/row/TestHoodieInternalRowParquetWriter.java
Labels: size:S
