Repository apache/hudi, pull requests merged in 2024-07, with the labels that each got.

#11522 [HUDI-7914] Fix/replacecommit incorrect fields
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTableDropPartition.scala
Labels: size:S

#11544 [HUDI-7942] Fix SmallFileAssignState#totalUnassigned naming error
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssigner.java
Labels: size:XS

#11547 [HUDI-6441][DOCS] Passing custom Headers with Hudi Callback URL
  website/docs/platform_services_post_commit_callback.md
Labels: docs, size:XS

#11550 [MINOR] Fix NPE after a clustering plan is finished
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/ConsistentBucketAssignFunction.java
Labels: size:XS

#11549 [HUDI-7403][DOCS] Support Filter/Transformer to Hudi Exporter Utility
  website/docs/snapshot_exporter.md
Labels: docs, size:S

#11551 [HUDI-6854][DOCS] Change default payload type to HOODIE_AVRO_DEFAULT
  website/docs/basic_configurations.md
  website/docs/configurations.md
Labels: docs, size:M

#11529 [HUDI-7933] Sync table in Glue/HMS if table base path is updated
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
Labels: size:M

#11434 [HUDI-7841] RLI and secondary index should consider only pruned partitions for file skipping
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Labels: size:M

#11538 [HUDI-7941] add show_file_status & run_rollback_inflight_tableservice procedure
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunRollbackInflightTableServiceProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowFileStatusProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRunRollbackInflightTableServiceProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowFileStatusProcedure.scala
Labels: size:L

#11502 [HUDI-7926] dataskipping failure mode should be strict in query test
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/HoodieCDCRDD.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/SecondaryIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBloomFiltersIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestFunctionalIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDataSkippingQuery.scala
Labels: size:S

#11543 [MINOR] if sync mode is glue, fix the sync tool class
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: size:S

#11219 [HUDI-7758] Only consider files in Hudi partitions when initializing MDT
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
Labels: release-0.15.0, size:S

#11563 [HUDI-7951] Fix conflict caused by classes using avro in hudi-aws-bundle
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  packaging/hudi-aws-bundle/pom.xml
Labels: size:XS

#11556 [HUDI-7945] Fix partition pruning using PARTITION_STATS index in Spark
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/util/FileFormatUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestBaseFileUtils.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDataSkippingQuery.scala
Labels: size:M

#11575 [HUDI-7954] Fix data skipping with secondary index when there are no log files
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/SecondaryIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
Labels: size:S

#11574 [HUDI-7953] Improved the variable naming and formatting of HoodieActiveTimeline and HoodieIndex
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
Labels: size:S

#11568 [HUDI-7949] insert into hudi table with columns specified
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieCatalystPlansUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/HoodieSpark2CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/HoodieSpark3CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/HoodieSpark30CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/HoodieSpark31CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/HoodieSpark32CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/ResolveInsertionBase.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/HoodieSpark33CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/HoodieSpark34CatalystPlanUtils.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/HoodieSpark35CatalystPlanUtils.scala
Labels: size:L

#11584 [HUDI-7965] Clean up SchemaTestUtil code
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
Labels: size:XS

#11570 [HUDI-7929] create k8s example for flink hudi integration
  hudi-examples/hudi-examples-k8s/Dockerfile
  hudi-examples/hudi-examples-k8s/README.md
  hudi-examples/hudi-examples-k8s/config/hadoop/core-site.xml
  hudi-examples/hudi-examples-k8s/config/k8s/flink-deployment.yml
  hudi-examples/hudi-examples-k8s/config/k8s/minio-standalone.yaml
  hudi-examples/hudi-examples-k8s/pom.xml
  hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/HudiDataStreamWriter.java
  hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/utils/DataGenerator.java
  hudi-examples/pom.xml
Labels: size:L

#11471 [HUDI-7962] Add show create table command
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/ShowHoodieCreateTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
Labels: cli, table-maintenance, size:S

#11585 [HUDI-7966] Handle NPE from AvroSchemaUtils.createNewSchemaFromFieldsWithReference
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaUtils.java
Labels: size:S

#11586 [HUDI-7709] Revert ClassCastException while reading the data using TimestampBasedKeyGenerator
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala
Labels: size:M

#11490 [HUDI-7911] Enable cdc log for MOR table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
  hudi-common/src/main/java/org/apache/hudi/common/table/cdc/HoodieCDCExtractor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/IncrementalQueryAnalyzer.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/IncrementalInputSplits.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/mor/MergeOnReadInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCRelation.scala
Labels: size:L

#11591 [MINOR] Improve release docs and update some links
  packaging/bundle-validation/README.md
  packaging/bundle-validation/base/Dockerfile
  release/release_guide.md
Labels: size:S

#11603 [HUDI-7929] fix file name in k8s example
  hudi-examples/hudi-examples-k8s/config/k8s/flink-deployment.yaml
Labels: size:XS

#11592 [HUDI-7968] Claiming rfc for robust spark writes
  rfc/README.md
Labels: size:XS

#11578 [HUDI-7957] fix data skew when writing with bulk_insert + bucket_inde…
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/BucketPartitionUtils.scala
  hudi-common/src/main/java/org/apache/hudi/common/util/hash/BucketIndexUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java
Labels: performance, size:S

#11530 [DOCS] fix: update home page title
  website/src/pages/index.js
  website/src/theme/LayoutHead/index.js
  website/src/theme/LayoutHead/useTitleFormatter.js
Labels: docs, size:S

#11608 [HUDI-7977] Improve bucket index partitioner algorithm
  hudi-common/src/main/java/org/apache/hudi/common/util/hash/BucketIndexUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/util/hash/TestBucketIndexUtil.java
Labels: size:M

#11610 [HUDI-7978][DOCS] Add a note on field oldering in partitioned by clause of create sql
  website/docs/sql_ddl.md
  website/versioned_docs/version-0.11.0/quick-start-guide.md
  website/versioned_docs/version-0.11.1/quick-start-guide.md
  website/versioned_docs/version-0.12.0/quick-start-guide.md
  website/versioned_docs/version-0.12.1/quick-start-guide.md
  website/versioned_docs/version-0.12.2/quick-start-guide.md
  website/versioned_docs/version-0.12.3/quick-start-guide.md
  website/versioned_docs/version-0.13.0/quick-start-guide.md
  website/versioned_docs/version-0.13.1/quick-start-guide.md
  website/versioned_docs/version-0.14.0/sql_ddl.md
  website/versioned_docs/version-0.14.1/sql_ddl.md
  website/versioned_docs/version-0.15.0/sql_ddl.md
Labels: docs, size:S

#11617 [MINOR] Codestyle of license and package statement ordering
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/main/java/org/apache/hudi/metaserver/store/jdbc/BasicDao.java
Labels: size:XS

#11611 [HUDI-7979] Adjusting defaults with spillable map memory
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/SerializableConfiguration.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/FileSystemViewStorageConfig.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieException.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieIOException.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieIncompatibleSchemaException.java
Labels: size:M

#11615 [HUDI-7709] Pass partition paths as partition column values if `TimestampBasedKeyGenerator` is used
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkHoodieTableFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala
Labels: size:M

#11625 [DOCS] Add a hudi logo with high resolution
  website/static/assets/images/hudi_logo_transparent_1400x600.png
Labels: docs, size:XS

#11561 [HUDI-7950] Shade roaring bitmap dependency in root POM
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: size:S

#11627 [MINOR] Update DOAP with 1.0.0-beta2 Release
  doap_HUDI.rdf
Labels: size:XS

#11614 [HUDI-7980] Optimize the configuration content when performing clustering with row writer
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
Labels: size:XS

#11622 [DOCS] Add doc update for HUDI-7962
  website/docs/sql_ddl.md
Labels: docs, size:S

#11612 [HUDI-7976] Fix BUG introduced in HUDI-7955 due to usage of wrong class
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveAvroSerializer.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieHiveUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/shims/Hive2Shim.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/shims/Hive3Shim.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/shims/HiveShim.java
Labels: size:S

#11626 [HUDI-7938] Broadcast `SerializableConfiguration` to avoid NullPointerException in Kryo SerDe
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: size:S

#11569 [MINOR] remove repeated look up candidate
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodiePruneFileSourcePartitions.scala
Labels: size:S

#11531 [HUDI-7934] Fix RocksDBDAO prefixDelete to delete last entry properly
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDBDAO.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestRocksDBDAO.java
Labels: size:S

#11618 [DOCS] Release notes 1.0.0-beta2
  website/docs/metadata.md
  website/docs/sql_ddl.md
  website/docs/sql_dml.md
  website/releases/download.md
  website/releases/older-releases.md
  website/releases/release-0.10.0.md
  website/releases/release-0.10.1.md
  website/releases/release-0.11.0.md
  website/releases/release-0.11.1.md
  website/releases/release-0.12.0.md
  website/releases/release-0.12.1.md
  website/releases/release-0.12.2.md
  website/releases/release-0.12.3.md
  website/releases/release-0.13.0.md
  website/releases/release-0.13.1.md
  website/releases/release-1.0.0-beta2.md
Labels: docs, size:M

#11545 [HUDI-7859] Rename instant files to be consistent with 0.x naming format when downgrade
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstant.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
Labels: upgrade, size:M

#11631 [HUDI-7988] ListingBasedRollbackStrategy support log compact
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestMergeOnReadRollbackActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
Labels: size:S

#11641 [HOTFIX] Fix wrong skipClean description in HoodieClusteringJob.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
Labels: size:XS

#11645 [MINOR] Fixed checkstyle in k8s example code (HUDI-7929)
  hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/HudiDataStreamWriter.java
  hudi-examples/hudi-examples-k8s/src/main/java/org/apache/hudi/examples/k8s/quickstart/utils/DataGenerator.java
Labels: size:M

#11518 [HUDI-4822] Extract the baseFile and logFiles from HoodieDeltaWriteStat in the right way
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieCommitMetadata.java
Labels: size:S

#11644 [HUDI-7999] Disable CI for spark < 3.3
  .github/workflows/bot.yml
Labels: size:S

#11651 [DOCS] Add Event banner for next community sync
  website/src/components/EventFeature/index.js
  website/src/pages/index.js
Labels: docs, size:XS

#11440 [HUDI-7779] Guard archival on savepoint removal until cleaner is able to clean it up
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/HoodieTimelineArchiver.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/clean/CleanPlanner.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
Labels: size:L

#11643 [HUDI-7998] fix insert overwrite hudi table with static partition whe…
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:XS

#11654 [MINOR] Improve error logging in JSON Avro conversion
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/AvroConvertor.java
Labels: size:XS

#11642 [HUDI-7997] Hivesync to support promotion type correctly
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/util/HiveSchemaUtil.java
Labels: size:S

#11658 [MINOR] Update how RLI validation filters out new entries
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:S

#11656 [HUDI-7908] Hotfix: HoodieFileGroupReader fails if preCombine and partition fields are the same
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: size:S

#10841 [HUDI-7494]: multi writer sync partition to glue will missing some partitions
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
Labels: priority:critical, size:S

#11646 [HUDI-8001] Insert overwrite failed due to missing 'path' property when using Spark 3.5.1 and Hudi 1.0.0
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestCreateTable.scala
Labels: size:S

#11657 [HUDI-8007] ShowInvalidParquetProcedure support delete by parameter
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowInvalidParquetProcedure.scala
Labels: spark-sql, cli, size:S

#11604 [HUDI-6510] Support compilation on Java 17
  .github/workflows/bot.yml
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  pom.xml
Labels: size:S

#11373 [HUDI-7821] Handle case where older proto message is read with new schema
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/ProtoConversionUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestProtoConversionUtil.java
  hudi-utilities/src/test/resources/schema-provider/proto/evolved.proto
  hudi-utilities/src/test/resources/schema-provider/proto/sample_schema_defaults.avsc
  hudi-utilities/src/test/resources/schema-provider/proto/sample_schema_wrapped_and_timestamp_as_record.avsc
Labels: size:M

#11668 [HUDI-712] Revert back to overwrite=true in HoodieSnapshotExporter
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotExporter.java
Labels: size:XS

#11669 [MINOR] Fix SyntaxWarning in pr_compliance.py
  scripts/pr_compliance.py
Labels: size:XS

#11660 [HUDI-8008] Handle proto schema references in returned schema
  hudi-utilities/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/converter/JsonToAvroSchemaConverter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/converter/ProtoSchemaToAvroSchemaConverter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/converter/TestJsonToAvroSchemaConverter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/converter/TestProtoSchemaToAvroSchemaConverter.java
  pom.xml
Labels: size:L

#11659 [HUDI-8006] Fix glue sync async call to update table
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/sync/TestAWSGlueSyncClient.java
Labels: size:S

#11675 [Docs]update show_invalid_parquet parameter
  website/docs/procedures.md
Labels: docs, size:XS

#11665 [HUDI-8009] Optimize the code of HoodieTable#getPendingCommitTimeline
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
Labels: size:S

#11671 [HUDI-8011] allow schema.on.read with positional merging
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReader.scala
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/InternalSchema.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/SparkParquetReaderBase.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/TestSparkParquetReaderFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestSpark35RecordPositionMetadataColumn.scala
  hudi-spark-datasource/hudi-spark2/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark24ParquetReader.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.0.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark30ParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.1.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark31ParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.2.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark32PlusParquetSchemaEvolutionUtils.scala
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark33ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark34ParquetReader.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/Spark35ParquetReader.scala
Labels: size:L

#11596 [HUDI-7025] Consolidate index and functional index config groups
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigGroups.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java
Labels: size:S

#11650 [HUDI-7964] Error out if partition schema and table schema do not match in create table command
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSchemaUtils.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestCreateTable.scala
Labels: spark-sql, size:S

#11673 [DOCS] Fix typo in metadata.md
  website/docs/metadata.md
  website/versioned_docs/version-0.14.0/metadata.md
  website/versioned_docs/version-0.14.1/metadata.md
  website/versioned_docs/version-0.15.0/metadata.md
Labels: docs, size:XS

#11548 [HUDI-7943] Resolve version conflict of fasterxml on spark3.2
  hudi-common/src/main/java/org/apache/hudi/common/util/JsonUtils.java
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/adapter/BaseSpark3Adapter.scala
  pom.xml
Labels: size:XS

#11682 [DOCS][MINOR] Remove events banner
  website/src/pages/index.js
Labels: docs, size:XS

#11624 [DOCS] Add new Blog on Lakehouse
  website/blog/2024-07-11-what-is-a-data-lakehouse.md
  website/static/assets/images/blog/dlh_1200.png
  website/static/assets/images/blog/dlh_new.png
  website/static/assets/images/blog/lkh_blog_hudi_stck.png
Labels: docs, size:M

#11582 [HUDI-7963] Minor enhancement to RLI flow with MDT
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
Labels: size:XS

#11683 [MINOR] Add build scripts for new bundle validation images
  packaging/bundle-validation/base/build_flink1146hive313spark331.sh
  packaging/bundle-validation/base/build_flink1153hive313spark334.sh
  packaging/bundle-validation/base/build_flink1162hive313spark343.sh
  packaging/bundle-validation/base/build_flink1170hive313spark351.sh
  packaging/bundle-validation/base/build_flink1180hive313spark351scala213.sh
Labels: size:M

#11265 [HUDI-7774] Add Avro Logical type support for Merciful Java convertor
  hudi-common/src/main/java/org/apache/hudi/avro/AvroLogicalTypeEnum.java
  hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-common/src/test/resources/date-type-invalid.avsc
  hudi-common/src/test/resources/date-type.avsc
  hudi-common/src/test/resources/decimal-logical-type-fixed-type.avsc
  hudi-common/src/test/resources/decimal-logical-type-invalid.avsc
  hudi-common/src/test/resources/decimal-logical-type.avsc
  hudi-common/src/test/resources/duration-logical-type-invalid.avsc
  hudi-common/src/test/resources/duration-logical-type.avsc
  hudi-common/src/test/resources/local-timestamp-logical-type.avsc
  hudi-common/src/test/resources/local-timestamp-micros-logical-type.avsc
  hudi-common/src/test/resources/local-timestamp-millis-logical-type.avsc
  hudi-common/src/test/resources/time-logical-type.avsc
  hudi-common/src/test/resources/timestamp-logical-type2.avsc
  hudi-common/src/test/resources/uuid-logical-type.avsc
Labels: size:XL

#11653 [HUDI-8002] Add back Flink 1.15 and 1.14 bundle validation
  .github/workflows/bot.yml
  packaging/bundle-validation/ci_run.sh
Labels: size:S

#11667 [HUDI-8005] Add a new DynamoDB based lock provider with auto-generated partition key
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedImplicitPartitionKeyLockProvider.java
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProvider.java
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedLockProviderBase.java
  hudi-aws/src/main/java/org/apache/hudi/config/DynamoDbBasedLockConfig.java
  hudi-aws/src/test/java/org/apache/hudi/aws/transaction/integ/ITTestDynamoDBBasedLockProvider.java
  hudi-common/src/main/java/org/apache/hudi/common/util/hash/HashID.java
  hudi-common/src/test/java/org/apache/hudi/common/util/hash/TestHashID.java
  hudi-common/src/test/resources/hash/magic_input.txt
  hudi-common/src/test/resources/hash/xxhash_BITS_128_for_magic_input.txt
  hudi-common/src/test/resources/hash/xxhash_BITS_32_for_magic_input.txt
  hudi-common/src/test/resources/hash/xxhash_BITS_64_for_magic_input.txt
  hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
  scripts/release/validate_source_copyright.sh
Labels: size:L

#11678 [HUDI-7993] Apply record index if _hoodie_record_key meta field in filter
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestRecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/TestSecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
Labels: size:M

#11686 [HUDI-6191] Improve passing the debezium checkpoint values to start job from offset
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/KafkaSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Labels: size:M

#11690 [HUDI-6191][DOCS] Improve passing the debezium checkpoint values to start job from offset
  website/docs/configurations.md
  website/docs/hoodie_streaming_ingestion.md
Labels: docs, size:XS

#11698 [HUDI-8030] Fix for add missing table configurations to payloadProps (fixes #11685)
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
Labels: size:XS

#11664 [HUDI-4625] Clean up KafkaOffsetGen: introduce retrying KafkaConsumer
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/KafkaSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieRetryingKafkaConsumer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Labels: size:M

#11699 [HUDI-7948] Claiming RFC-80 for Column families
  rfc/README.md
Labels: size:XS

#11670 [HUDI-6453] Cascade Glue schema changes to partitions
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/hive/SchemaDifference.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/HoodieMetaSyncOperations.java
Labels: size:S

#11693 [HUDI-8029] Enforce s3 base path format for partition key calculation
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedImplicitPartitionKeyLockProvider.java
  hudi-aws/src/test/java/org/apache/hudi/aws/transaction/integ/ITTestDynamoDBBasedLockProvider.java
  hudi-aws/src/test/java/org/apache/hudi/aws/utils/TestS3Utils.java
Labels: size:S

#11700 [MINOR]: Support MOR table type for HoodieJavaWriteClientExample
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-examples/hudi-examples-java/src/main/java/org/apache/hudi/examples/java/HoodieJavaWriteClientExample.java
Labels: size:S

#11707 [BLOG] Data Lake CDC Blog
  website/blog/2024-07-30-data-lake-cdc.md
  website/static/assets/images/blog/data-lake-cdc/database-cdc.png
  website/static/assets/images/blog/data-lake-cdc/hudi-cdc.jpg
  website/static/assets/images/blog/data-lake-cdc/log-based-cdc.png
  website/static/assets/images/blog/data-lake-cdc/trigger-based-cdc.png
  website/static/assets/images/blog/data-lake-cdc/ts-based-cdc.png
Labels: docs, size:M
