Repository apache/hudi, pull requests merged in 2024-01, with the labels that each got.

#10281 [HUDI-7198]Create nested node path if does not exist for zookeeper.
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedLockProvider.java
Labels: priority:critical, release-0.14.1

#10261 [HUDI-5973] Fixing refreshing of schemas in HoodieStreamer continuous mode
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/FilebasedSchemaProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
Labels: priority:critical, release-0.14.1

#10467 [HUDI-7284] stream sync doesn't differentiate replace commits
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: hudistreamer, clustering, release-0.14.2

#10345 [MINOR] Avoid resource leaks
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/Metrics.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/TestHoodieMetadataBase.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/LazyFileIterable.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/SerDeHelper.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieBootstrapRecordIterator.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieHFileInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
Labels: priority:critical, release-0.14.1

#10490 [HUDI-7293]Incremental read of insert table using rebalance strategy
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSource.java
Labels: flink, incremental-etl

#10506 [MINOR] fix eager rollback mdt ut
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
Labels: test-coverage

#10491 [HUDI-7294] TVF to query hudi metadata
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestHoodieTableValuedFunction.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/catalyst/plans/logcal/HoodieMetadataTableValuedFunction.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark32PlusAnalysis.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/TableValuedFunctions.scala
Labels: release-1.0.0

#10493 [HUDI-7291] Pushing Down Partition Pruning Conditions to Column Stats Earlier During Data Skipping
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
Labels: performance, spark, data-skipping

#10492 [HUDI-7296] Reduce CI Time by Minimizing Duplicate Code Coverage in Tests
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapRead.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionQuick.java
Labels: release-1.0.0

#10241 [HUDI-7170] Implement HFile reader independent of HBase
  hudi-common/pom.xml
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieHFileReaderWriter.java
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieReaderWriterUtils.java
  hudi-io/README.md
  hudi-io/hfile_format.md
  hudi-io/pom.xml
  hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
  hudi-io/src/main/java/org/apache/hudi/common/util/Option.java
  hudi-io/src/main/java/org/apache/hudi/common/util/io/ByteBufferBackedInputStream.java
  hudi-io/src/main/java/org/apache/hudi/exception/HoodieException.java
  hudi-io/src/main/java/org/apache/hudi/exception/HoodieIOException.java
  hudi-io/src/main/java/org/apache/hudi/io/compress/CompressionCodec.java
  hudi-io/src/main/java/org/apache/hudi/io/compress/HoodieDecompressor.java
  hudi-io/src/main/java/org/apache/hudi/io/compress/HoodieDecompressorFactory.java
  hudi-io/src/main/java/org/apache/hudi/io/compress/airlift/HoodieAirliftGzipDecompressor.java
  hudi-io/src/main/java/org/apache/hudi/io/compress/builtin/HoodieNoneDecompressor.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/BlockIndexEntry.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/DataSize.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileBlockReader.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileBlockType.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileContext.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileCursor.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileDataBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileFileInfoBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileInfo.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileMetaBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileReader.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileReaderImpl.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileRootIndexBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileTrailer.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileUtils.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/Key.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/KeyValue.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/UTF8StringKey.java
  hudi-io/src/main/java/org/apache/hudi/io/util/IOUtils.java
  hudi-io/src/main/protobuf/HFile.proto
  hudi-io/src/test/java/org/apache/hudi/io/compress/TestHoodieDecompressor.java
  hudi-io/src/test/java/org/apache/hudi/io/hfile/TestHFileReader.java
  hudi-io/src/test/java/org/apache/hudi/io/util/TestIOUtils.java
  hudi-io/src/test/resources/hfile/hudi_0_10_hbase_1_2_3_bootstrap_index_partitions.hfile
  hudi-io/src/test/resources/hfile/hudi_0_10_hbase_1_2_3_complex.hfile
  hudi-io/src/test/resources/hfile/hudi_0_10_hbase_1_2_3_simple.hfile
  hudi-io/src/test/resources/hfile/hudi_0_11_hbase_2_4_9_bootstrap_index_partitions.hfile
  hudi-io/src/test/resources/hfile/hudi_0_11_hbase_2_4_9_complex.hfile
  hudi-io/src/test/resources/hfile/hudi_0_11_hbase_2_4_9_simple.hfile
  hudi-io/src/test/resources/hfile/hudi_0_9_hbase_1_2_3_bootstrap_index_partitions.hfile
  hudi-io/src/test/resources/hfile/hudi_0_9_hbase_1_2_3_complex.hfile
  hudi-io/src/test/resources/hfile/hudi_0_9_hbase_1_2_3_simple.hfile
  hudi-io/src/test/resources/hfile/hudi_1_0_hbase_2_4_9_16KB_GZ_20000.hfile
  hudi-io/src/test/resources/hfile/hudi_1_0_hbase_2_4_9_16KB_GZ_200_20_non_unique.hfile
  hudi-io/src/test/resources/hfile/hudi_1_0_hbase_2_4_9_16KB_NONE_5000.hfile
  hudi-io/src/test/resources/hfile/hudi_1_0_hbase_2_4_9_512KB_GZ_20000.hfile
  hudi-io/src/test/resources/hfile/hudi_1_0_hbase_2_4_9_64KB_NONE_5000.hfile
  hudi-io/src/test/resources/hfile/hudi_1_0_hbase_2_4_9_no_entry.hfile
  packaging/hudi-metaserver-server-bundle/pom.xml
  pom.xml
Labels: reader-core, release-1.0.0

#10518 [HUDI-7305] Fix cast exception for byte/short/float partitioned field
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/execution/datasources/Spark3ParsePartitionUtil.scala
Labels: schema-and-data-types, spark

#10501 [HUDI-7284] Fix cluster stream sync check
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieDefaultTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestClusteringUtils.java
Labels: table-service, release-0.14.2

#10532 [HUDI-7277] fix `hoodie.bulkinsert.shuffle.parallelism` not activated…
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieDatasetBulkInsertHelper.java
Labels: spark

#10517 [HUDI-7303] Fix date field type unexpectedly convert to Long when usi…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/ExpressionPredicates.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ExpressionUtils.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/util/TestExpressionUtils.java
Labels: schema-and-data-types, flink

#10342 [HUDI-7237] Hudi Streamer: Handle edge case with null schema, minor cleanups
  hudi-common/src/main/java/org/apache/hudi/internal/schema/utils/AvroSchemaEvolutionUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaProviderWithPostProcessor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/InputBatch.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestSourceFormatAdapter.java
Labels: priority:critical, release-0.14.1

#10540 [HUDI-7316] Update AbstractHoodieLogRecordReader (and implementation) to accept already-constructed HoodieTableMetaClient and update Spark engine callers to pass meta client directly
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergedReadHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/HoodieLogCompactionPlanGenerator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnMergeOnReadStorage.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieUnMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
Labels: performance, metadata

#10531 [HUDI-7311] Add implicit literal type conversion before filter push down
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/ExpressionPredicates.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ImplicitTypeConverter.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/source/TestExpressionPredicates.java
Labels: schema-and-data-types, flink-sql

#10340 [HUDI-7228] Fix eager closure of log reader input streams with log record reader
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCDCDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCommandBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCorruptBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
Labels: priority:critical, release-0.14.1

#10549 [HUDI-7323] Use a schema supplier instead of a static value
  hudi-utilities/src/main/java/org/apache/hudi/utilities/UtilHelpers.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/ChainedTransformer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/transform/ErrorTableAwareChainedTransformer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestChainedTransformer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestErrorTableAwareChainedTransformer.java
Labels: schema-and-data-types, hudistreamer

#8743 [HUDI-6230] Handle aws glue partition index
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/main/java/org/apache/hudi/config/GlueCatalogSyncClientConfig.java
Labels: release-1.0.0

#10523 [HUDI-7308] LockManager::unlock should not call updateLockHeldTimerMetrics if lockDurationTimer has not been started
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/LockManager.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/InProcessLockProviderWithRuntimeError.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestTransactionManager.java
Labels: metrics, stability

#10344 [HUDI-7238] Bug fixes and optimization of ExternalSpillableMap
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/SpillableMapBasedFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/DiskMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestExternalSpillableMap.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadSnapshotReader.java
Labels: priority:critical, release-0.14.2

#10572 [HUDI-7351] Hive-sync partition pushdown does not work with glue
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
Labels: aws-support

#10567 [HUDI-7336] Introduce new HoodieStorage abstraction
  hudi-hadoop-common/pom.xml
  hudi-hadoop-common/src/main/java/org/apache/hudi/storage/hadoop/HoodieHadoopStorage.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/hadoop/storage/TestHoodieHadoopStorage.java
  hudi-io/src/main/java/org/apache/hudi/ApiMaturityLevel.java
  hudi-io/src/main/java/org/apache/hudi/PublicAPIClass.java
  hudi-io/src/main/java/org/apache/hudi/PublicAPIMethod.java
  hudi-io/src/main/java/org/apache/hudi/io/util/IOUtils.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieFileStatus.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieLocation.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieLocationFilter.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieFileStatus.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieLocation.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieLocationFilter.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
Labels: release-1.0.0

#10568 [HUDI-7342] Use BaseFileUtils to hide format-specific logic in HoodiePartitionMetadata
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/util/BaseFileUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/OrcUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ParquetUtils.java
Labels: release-1.0.0

#10574 [HUDI-7346] Remove usage of org.apache.hadoop.hbase.util.Bytes
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/hbase/SparkHoodieHBaseIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/hbase/TestSparkHoodieHBaseIndex.java
  hudi-common/src/main/java/org/apache/hudi/avro/GenericAvroSerializer.java
  hudi-common/src/main/java/org/apache/hudi/common/bootstrap/index/HFileBootstrapIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieConsistentHashingMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieReplaceCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/PostgresDebeziumAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFileReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/LSMTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/util/Base64CodecUtil.java
  hudi-common/src/main/java/org/apache/hudi/common/util/hash/HashID.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/io/FileBasedInternalSchemaStorageManager.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieAvroHFileReaderImplBase.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemHFileInLiningBase.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/inline/TestInLineFileSystemWithHBaseHFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/model/debezium/TestPostgresDebeziumAvroPayload.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/InputSplitUtils.java
  hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileFileInfoBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileUtils.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/Key.java
  hudi-io/src/main/java/org/apache/hudi/io/util/IOUtils.java
  hudi-io/src/test/java/org/apache/hudi/io/util/TestIOUtils.java
  hudi-platform-service/hudi-metaserver/hudi-metaserver-server/src/test/java/org/apache/hudi/metaserver/store/TestRelationalDBBasedStore.java
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/HDFSParquetImporterUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestProtoConversionUtil.java
Labels: release-1.0.0

#10570 [HUDI-7343] Replace Path.SEPARATOR with HoodieLocation.SEPARATOR
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/ExportCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestTableCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestBootstrapCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestHDFSParquetImportCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestMarkersCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestSavepointsCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestTableCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HeartbeatUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/heartbeat/HoodieHeartbeatClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/FileSystemBasedLockProvider.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieFunctionalIndexClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/utils/TestLegacyArchivedMetaEntryReader.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/conflict/detection/DirectMarkerBasedDetectionStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/inline/InLineFSUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/heartbeat/HoodieHeartbeatUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/metadata/AbstractHoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestHoodieWrapperFileSystem.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/meta/CkpMetadata.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/FileIndex.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/TableOptionProperties.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FilePathUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ClientIds.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ViewStorageProperties.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestInputPathHandler.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ExportInstantsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestBootstrapProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestHdfsParquetImportProcedure.scala
  hudi-spark-datasource/hudi-spark3.2plus-common/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark32PlusAnalysis.scala
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestService.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerBasedEarlyConflictDetectionRunnable.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SparkSampleWritesUtils.java
Labels: release-1.0.0

#10571 [HUDI-7345] Remove usage of org.apache.hadoop.util.VersionUtil
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-io/src/main/java/org/apache/hudi/common/util/ComparableVersion.java
  hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
Labels: release-1.0.0

#10573 [HUDI-7344] Use Java {Input/Output}Stream instead of FSData{Input/Output}Stream when possible
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/CompactionCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUpgradeDowngradeCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestHDFSParquetImportCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/testutils/HoodieTestCommitMetadataGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/FileSystemBasedLockProvider.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/HoodieTestCommitGenerator.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieFunctionalIndexConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieActiveTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/InternalSchemaCache.java
  hudi-common/src/main/java/org/apache/hudi/common/util/MarkerUtils.java
  hudi-common/src/main/java/org/apache/hudi/internal/schema/io/FileBasedInternalSchemaStorageManager.java
  hudi-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/TableOptionProperties.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/ViewStorageProperties.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/hadoop/fs/HoodieWrapperFileSystem.java
  hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestCluster.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/ManifestFileWriter.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/marker/MarkerDirState.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactionAdminTool.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/perf/TimelineServerPerf.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/FilebasedSchemaProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JdbcSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHDFSParquetImporter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestSanitizationUtils.java
Labels: release-1.0.0
