Repository apache/hudi, pull requests merged in 2025-07, with the labels that each got.

#13518 [HUDI-9567] BaseHoodieLogRecordReader should skip checking inflight i…
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
Labels: size:S

#13531 [DOC]: New Community Blog from Uber Eng
  website/blog/2025-06-30-uber-hudi.md
  website/static/assets/images/blog/fig4_uber.png
  website/static/assets/images/blog/fig5_uber.png
  website/static/assets/images/blog/fig6_uber.png
  website/static/assets/images/blog/fig7_uber.png
  website/static/assets/images/blog/figure2_uber.png
  website/static/assets/images/blog/figure3_uber.png
  website/static/assets/images/blog/uber1200x600.jpg
Labels: docs, size:M

#13507 [MINOR] Add logs for hoodie property file changes
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
Labels: size:S

#13538 [DOC ]Fix: Corrected error in the Uber blog
  website/blog/2025-06-30-uber-hudi.md
Labels: docs, size:XS

#13541 [DOC]: Update COW image for "Table & Query Types" page
  website/docs/table_types.md
  website/static/assets/images/COW_fix.png
Labels: docs, size:XS

#13547 Added blogs from 06/27-07/11
  content/assets/images/blog/20205-07-10-building-a-rag-based-ai-recommender.jpg
  content/assets/images/blog/2025-07-02-Lakehouse-Architecture-apache-hudi-and-apache-iceberg.png
  content/assets/images/blog/2025-07-03-why-uber-built-hudi-the-strategic-decision-behind-a-custom-table-format.jpg
  website/blog/2025-07-02-Lakehouse-Architecture-apache-hudi-and-apache-iceberg.mdx
  website/blog/2025-07-03-why-uber-built-hudi-the-strategic-decision-behind-a-custom-table-format.mdx
  website/blog/2025-07-07-how-stifel-built-a-modern-data-platform-using-aws-glue-and-an-event-driven-domain-architecture.mdx
  website/blog/2025-07-10-building-a-rag-based-ai-recommender.mdx
Labels: docs, size:S

#13546 [MINOR] Use scala-test throughout TestExpressionIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala
Labels: size:S

#13498 [HUDI-8401][RFC-97] Add partial update support with merge mode to assist with migration from payload to merge mode
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/TestBaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroReaderContextTypeConverter.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/ReaderContextTypeConverter.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/PartialUpdateMode.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecordMergerFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PartialUpdateStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/SortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroReaderContext.java
  hudi-common/src/test/java/org/apache/hudi/common/engine/TestReaderContextTypeConverter.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestPartialUpdateStrategy.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestSortedKeyBasedFileGroupRecordBuffer.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestFlinkRowDataReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveReaderContextTypeConverter.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHiveHoodieReaderContext.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHiveReaderContextTypeConverter.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPayloadDeprecationFlow.scala
Labels: size:XL

#13351 [HUDI-9451] Avoid broadcasting unnecessary `FileSlice` when reading
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionDirectoryConverter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestPartitionDirectoryConverter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
Labels: performance, spark-sql, reader-core, size:M

#13532 [HUDI-9424] Add unit tests for merging logic in `KeyBasedFileGroupRecordBuffer`
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecordMergerFactory.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestKeyBasedFileGroupRecordBuffer.java
Labels: size:L

#13413 [HUDI-9512] Avoid creating empty files when there is content to write
  hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
Labels: size:S

#13564 [MINOR] Fix test failures
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestKeyBasedFileGroupRecordBuffer.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
Labels: size:XS

#13562 [HUDI-8401] Fix the description of MERGE_PROPERTIES config
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
Labels: size:XS

#13543 [HUDI-9570] Using coordinator state to persist and recommit write metadata
  hudi-examples/hudi-examples-flink/pom.xml
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/EventBuffers.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnRead.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestData.java
Labels: size:M

#13557 [HUDI-9593] support custom partitioner in append mode
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/GroupedInsertPartitioner.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/partitioner/TestGroupedInsertPartitioner.java
Labels: size:M

#13508 [HUDI-9174] remove use of log scanner from cli
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HoodieLogFileCommand.java
Labels: size:S

#13549 [HUDI-9576] Test schema evolution in fg reader
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderOnJavaTestBase.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnJava.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/hadoop/TestHoodieFileGroupReaderOnHive.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/ArrayWritableTestUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/TestHoodieFileGroupReaderOnFlink.java
  hudi-hadoop-mr/src/main/java/org/apache/hadoop/hive/serde2/avro/HiveTypeUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/ObjectInspectorCache.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
Labels: size:XL

#13579 [MINOR] NullPointerException when reading action state of old archived timelines
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ArchivedTimelineV1.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestArchivedTimelineV1.java
  hudi-hadoop-common/src/test/resources/archived_timeline/.hoodie/archived/.commits_.archive.1_1-0-1
  hudi-hadoop-common/src/test/resources/archived_timeline/.hoodie/hoodie.properties
Labels: size:S

#13444 [HUDI-9526] Use HoodieFileGroupReader throughout the CDC flow
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/CompactionExecutionHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/LogCompactionExecutionHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/RunCompactionActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/HoodieLogCompactionPlanGenerator.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkMergeOnReadTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/compact/HoodieFlinkMergeOnReadTableCompactor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaMergeOnReadTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkMergeOnReadTable.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BaseFileUpdateCallback.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/SortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/UpdateProcessor.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestSortedKeyBasedFileGroupRecordBuffer.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactOperator.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/HoodieCDCTestBase.scala
Labels: size:XL

#13581 [MINOR] TableChanges class throw schema evolution exception
  hudi-common/src/main/java/org/apache/hudi/internal/schema/action/TableChanges.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolutionBySQL.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
Labels: size:S

#13533 [HUDI-8401] Upgrade current table version to 9
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToNineUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/NineToEightDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/util/CommonClientUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/TestCommonClientUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableVersion.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/compact/ITTestHoodieFlinkCompactor.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/others/TestMergeModeCommitTimeOrdering.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/others/TestMergeModeEventTimeOrdering.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestRepairsProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestUpgradeOrDowngradeProcedure.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:M

#13544 [HUDI-9592] Read metadata table through file group reader for spark datasource
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDMetadataWriteClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieMergeOnReadRDDV2.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/Iterators.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelationV2.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadSnapshotRelation.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark3.3.x/src/main/scala/org/apache/spark/sql/execution/datasources/HoodieSpark33PartitionedFileUtils.scala
  hudi-spark-datasource/hudi-spark3.4.x/src/main/scala/org/apache/spark/sql/execution/datasources/HoodieSpark34PartitionedFileUtils.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/execution/datasources/HoodieSpark35PartitionedFileUtils.scala
Labels: size:XL

#13589 [DOC]: NEW Merge-on-Read Internals Blog
  website/blog/2025-07-21-mor-comparison.md
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor-1200x600.jpg
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig1.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig2.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig3.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig4.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig5.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig6.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig7.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig8.png
  website/static/assets/images/blog/2025-07-21-mor-comparison/mor_fig9.png
Labels: docs, size:M

#13495 [HUDI-9558] Make merge handle configurable
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAbstractMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieConcatHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieSortedMergeHandleWithChangeLog.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/IOUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseMergeHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieMergeHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/TestHoodieMergeHandleFactory.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandleWithChangeLog.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/HoodieFlinkCopyOnWriteTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/HoodieJavaCopyOnWriteTable.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/SparkReaderContextFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestUpdateSchemaEvolution.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieDefaultMergeHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/io/TestMergeHandle.java
Labels: size:XL

#13556 [HUDI-8635] Fix stats for total records written and num inserts in FileGroupReader based compaction
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleFactory.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/SortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/UpdateProcessor.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestSortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/RawTripTestPayload.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
Labels: size:L

#13527 [HUDI-6920] Refactor HoodieHadoopFsRelationFactory
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCDCFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: size:M

#13593 [HUDI-9621] Fix divergence between file index and incremental file index
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieIncrementalFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionDirectoryConverter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestPartitionDirectoryConverter.scala
Labels: size:M

#13605 [HUDI-9543] SI should support null value
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/SecondaryIndexStreamingTracker.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/TestSecondaryIndexStreamingTracker.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/TestSecondaryIndexStreamingTrackerFileSlice.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexKeyUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexRecordGenerationUtils.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestSecondaryIndexKeyUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
Labels: size:XL

#13610 [HUDI-9617] Clean redundant adapters for supporting multiple Flink ve…
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/sort/SortOperatorGen.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/v2/HoodieSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/v2/utils/PipelinesV2.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/DataModificationInfos.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreWriteTopology.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/adapter/OperatorCoordinatorAdapter.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/adapter/SortCodeGeneratorAdapter.java
  hudi-flink-datasource/hudi-flink1.17.x/src/main/java/org/apache/hudi/adapter/SupportsPreWriteTopologyAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/flink/streaming/api/connector/sink2/SupportsPreWriteTopology.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/OperatorCoordinatorAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/SortCodeGeneratorAdapter.java
  hudi-flink-datasource/hudi-flink1.18.x/src/main/java/org/apache/hudi/adapter/SupportsPreWriteTopologyAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/OperatorCoordinatorAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/SortCodeGeneratorAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/SupportsPreWriteTopologyAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelDeleteAdapter.java
  hudi-flink-datasource/hudi-flink1.19.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelUpdateAdapter.java
  hudi-flink-datasource/hudi-flink1.20.x/src/main/java/org/apache/hudi/adapter/OperatorCoordinatorAdapter.java
  hudi-flink-datasource/hudi-flink1.20.x/src/main/java/org/apache/hudi/adapter/SortCodeGeneratorAdapter.java
  hudi-flink-datasource/hudi-flink1.20.x/src/main/java/org/apache/hudi/adapter/SupportsPreWriteTopologyAdapter.java
  hudi-flink-datasource/hudi-flink1.20.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelDeleteAdapter.java
  hudi-flink-datasource/hudi-flink1.20.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelUpdateAdapter.java
  hudi-flink-datasource/hudi-flink2.0.x/src/main/java/org/apache/hudi/adapter/OperatorCoordinatorAdapter.java
  hudi-flink-datasource/hudi-flink2.0.x/src/main/java/org/apache/hudi/adapter/SortCodeGeneratorAdapter.java
  hudi-flink-datasource/hudi-flink2.0.x/src/main/java/org/apache/hudi/adapter/SupportsPreWriteTopologyAdapter.java
  hudi-flink-datasource/hudi-flink2.0.x/src/main/java/org/apache/hudi/adapter/SupportsRowLevelDeleteAdapter.java
Labels: size:L

#13618 [MINOR] fix broken test
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
Labels: size:S

#13619 [MINOR] Upgrade junit and mockito
  pom.xml
Labels: size:XS

#13595 [HUDI-9566] Ban schema evolution on columns with SI
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/TestHoodieTableSchemaEvolution.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieIndex.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/others/TestTimeTravelTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala
Labels: size:L

#13602 [HUDI-9578] Metadata Table reuse functionality with FileGroupReader
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/InputSplit.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/ParquetRowIndexBasedSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/ReaderParameters.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/UpdateProcessor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/DefaultFileGroupRecordBufferLoader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/FileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/FileGroupRecordBufferLoader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/HoodieFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/KeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/LogScanningRecordBufferLoader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/PositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/ReusableFileGroupRecordBufferLoader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/ReusableKeyBasedRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/SortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/UnmergedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupReaderSchemaHandler.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestRecord.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestReusableKeyBasedRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestSortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/SchemaTestUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/parquet/TestSparkFileFormatInternalRowReaderContext.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
Labels: size:XL

#13626 [MINOR] fix flaky test
  hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListDataPairData.java
Labels: size:XS

#13616 [HUDI-9640] Replace merge_properties with a list properties with a given prefix
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PartialUpdateStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestPartialUpdateStrategy.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestConfigUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPayloadDeprecationFlow.scala
Labels: size:L

#13613 [HUDI-9637] Address follow up feedback from PartialUpdateMode support
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/TestBaseSparkInternalRowReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/PartialUpdateMode.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecordMergerFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PartialUpdateStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/util/AvroJavaTypeConverter.java
  hudi-common/src/main/java/org/apache/hudi/common/util/DefaultJavaTypeConverter.java
  hudi-common/src/main/java/org/apache/hudi/common/util/JavaTypeConverter.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestAvroJavaTypeConverter.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroReaderContext.java
  hudi-common/src/test/java/org/apache/hudi/common/engine/TestDefaultJavaTypeConverter.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/SchemaHandlerTestBase.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestFlinkRowDataReaderContext.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestCustomRecordMerger.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HiveJavaTypeConverter.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHiveHoodieReaderContext.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHiveJavaTypeConverter.java
Labels: size:L

#13631 [HUDI-9650] Add tests for BufferedRecordMerger
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PartialUpdateStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/util/OrderingValues.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBufferedRecordMerger.java
Labels: size:XL

#13622 [HUDI-9505] Bug fix for getSecondaryIndexRecords API
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieDataUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListDataPairData.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieDataUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:L

#13637 [MINOR] Removed unused imports in ContinuousFileSource (hudi-examples)
  hudi-examples/hudi-examples-flink/src/main/java/org/apache/hudi/examples/quickstart/source/ContinuousFileSource.java
Labels: size:XS

#13567 [HUDI-9626] Prefetch HFiles for metadata table if size is below a configured threshold
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HFileReaderFactory.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHFileReaderFactory.java
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieNativeAvroHFileReader.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroFileReaderFactory.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/io/hadoop/TestHoodieHFileReaderWriter.java
Labels: size:L

#13065 [HUDI-9246] Confine protobuf shading to the hudi-io package
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-spark-client/pom.xml
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
  hudi-common/pom.xml
  hudi-hadoop-common/pom.xml
  hudi-io/pom.xml
  hudi-spark-datasource/hudi-spark/pom.xml
  hudi-sync/hudi-hive-sync/pom.xml
  hudi-utilities/pom.xml
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
  pom.xml
Labels: size:S

#13297 [HUDI-9402] Supporting Docker demo for Mac chips with ARM architecture
  docker/compose/docker-compose_hadoop284_hive233_spark353_arm64.yml
  docker/setup_demo.sh
Labels: size:M

#13629 [HUDI-9632] Index lookup path rdd unpersist support v2
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaPairRDD.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieJavaRDD.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/data/HoodieSparkRDDUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTableRecordIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/data/TestHoodieJavaPairRDD.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/data/TestHoodieJavaRDD.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieSparkClientTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkRDDValidationUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListPairData.java
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodiePairData.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieDataCleanupManager.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieBackedTableMetadataDataCleanup.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieDataCleanupManager.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataRecordIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:XL

#13563 [HUDI-9628] Add bloom filtering to prune keys prior to lookup in Metadata HFiles
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieStorageConfig.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieNativeAvroHFileReader.java
  hudi-common/src/test/java/org/apache/hudi/common/config/TestHoodieStorageConfig.java
  hudi-common/src/test/java/org/apache/hudi/io/storage/TestHoodieNativeAvroHFileReader.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroFileReaderFactory.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/io/hadoop/TestHoodieHFileReaderWriter.java
Labels: size:L

#13647 [HUDI-9656] Rename index lookup components
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTableRecordIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/NoOpTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BloomFilterIndexRawKey.java
  hudi-common/src/main/java/org/apache/hudi/metadata/ColumnStatsIndexPrefixRawKey.java
  hudi-common/src/main/java/org/apache/hudi/metadata/ColumnStatsIndexRawKey.java
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/FilesIndexRawKey.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/RawKey.java
  hudi-common/src/main/java/org/apache/hudi/metadata/RecordIndexRawKey.java
  hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexKeyUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexPrefixRawKey.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieBackedTableMetadataDataCleanup.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestSecondaryIndexKeyUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/source/stats/FileStatsIndex.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ColumnStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMetadataRecordIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/testHoodieBackedTableMetadataIndexLookup.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:XL

#13517 [HUDI-9560] Add support event_time metadata
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCreateHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteMergeHandle.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/TestHoodieWriteHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkRecord.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieEmptyRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestConfigUtils.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveRecord.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieHiveRecord.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestHoodieActiveTimeline.scala
Labels: size:L

#13655 [MINOR] Fix a few minor issues for java file group reader
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
Labels: size:S

#13645 [HUDI-9661] Fix `Hoodie#getOrderingValue()` to avoid extracting order…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/CommitTimeFlinkRecordMerger.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/EventTimeFlinkRecordMerger.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkRecord.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/PartialUpdateFlinkRecordMerger.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/DefaultSparkRecordMerger.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/common/model/HoodieSparkRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieEmptyRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecordMergerFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieAvroRecordTestMerger.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileSliceTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestHoodieRecordUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FlinkRowDataReaderContext.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestCustomRecordMerger.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/DefaultHiveRecordMerger.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieHiveRecord.java
Labels: size:M

#13603 [HUDI-9630] Support Partitioned RLI in the Metadata Table
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/BucketizedMetadataTableFileGroupIndexParser.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/DefaultMetadataTableFileGroupIndexParser.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/MetadataIndexGenerator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/MetadataTableFileGroupIndexParser.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkHoodieIndexFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTablePartitionedRecordIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTableRecordIndex.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriterTableVersionSix.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieMetadataBulkInsertPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkHoodieMetadataBulkInsertPartitioner.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/NoOpTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/util/PartitionPathEncodeUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseFileRecordParsingUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/EmptyHoodieRecordPayloadWithPartition.java
  hudi-common/src/main/java/org/apache/hudi/metadata/FileSystemBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataPayload.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestHoodieBackedTableMetadataDataCleanup.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionedRecordLevelIndex.scala
Labels: size:XL

#13609 [HUDI-4449] Claim of RFC-98, Spark Datasource V2 Read
  rfc/README.md
  rfc/rfc-98/initial_integration_with_Spark.jpg
  rfc/rfc-98/rfc-98.md
Labels: size:S
