Repository apache/hudi, pull requests merged in 2025-10, with the labels that each got.

#13987 perf: Lazy deserialization of Avro indexed record
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/io/TestHoodieWriteHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkRecord.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRecordContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroRecordContext.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/model/BaseAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/SerializableIndexedRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/PostgresDebeziumAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/BufferedRecords.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/SortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/StreamingFileGroupRecordBufferLoader.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestUpdateProcessor.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/BaseTestFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestSortedKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/buffer/TestStreamingKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieCreateRecordUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/bootstrap/SparkFullBootstrapDataProviderBase.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodieMergeHandleWithSparkMerger.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/io/TestMergeHandle.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/SparkDatasetMixin.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/model/TestHoodieRecordSerialization.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/CreateHandleBenchmark.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractBaseTestSource.java
Labels: size:L, release-1.1.0

#14026 fix: Fixing condition to calculate enforceCoalesceWithRepartition for table services with streaming writes to mdt
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
Labels: size:S, release-1.1.0

#14024 fix: Upgrade Jackson version for Spark4 to match the provided version
  packaging/hudi-hadoop-mr-bundle/pom.xml
  pom.xml
Labels: size:XS

#14029 fix: Flaky NPE during downgrade from Eight to Seven table version
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
Labels: size:S

#14017 fix: CDC Query Issue with and without sorting
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/cdc/TestCDCDataFrameSuite.scala
Labels: size:S

#14001 test: Add lowering order and higher ordering values to payloads
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPayloadDeprecationFlow.scala
Labels: size:L, release-1.1.0

#14030 test: intial impl of payload fixtures
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/upgrade/TestUpgradeDowngrade.java
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/generate-fixtures.sh
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-awsdms.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-default.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-eventtime.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-mysql.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-overwrite.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-overwritenondefaults.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-partial.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/payload-tables/hudi-v6-table-payload-postgres.zip
  hudi-spark-datasource/hudi-spark/src/test/resources/upgrade-downgrade-fixtures/scala-templates/generate-fixture-payload.scala
Labels: size:L

#14040 docs(blog): add Hudi PuppyGraph blog
  website/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph.mdx
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-10-PuppyGraph-Query-3.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-11-PuppyGraph-Query-4.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-2-PuppyGraph_Supported_Data_Sources.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-3-Architecture-with-Graph-Database-vs-with-PuppyGraph.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-4-Sample-Architecture-of-PuppyGraph-Hudi.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-5-PuppyGraph-Login-Page.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-6-Schema-Page-in-PuppyGraph-UI.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-7-Loaded-Schema-in-PuppyGraph-UI.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-8-PuppyGraph-Query-1.png
  website/static/assets/images/blog/2025-10-02-Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/fig-9-PuppyGraph-Query-2.png
Labels: docs, size:M

#14033 perf: Avoid materializing into intermediate list in metadata table path
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieListData.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/test/java/org/apache/hudi/common/data/TestHoodieListData.java
Labels: size:S

#14046 fix: INSERT INTO should preserve duplication with hoodie.spark.sql.insert.into.operation=insert
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/insert/TestInsertTable.scala
Labels: size:S

#14042 fix: tracking partition names correctly during secondary index
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
Labels: size:S

#14045 fix: Fixing secondary record generation for MDT
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexRecordGenerationUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
Labels: size:M, release-1.1.0

#14048 fix: Fix record generation to avoid file system based listing for expression index
  azure-pipelines-20230430.yml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/utils/SparkMetadataWriterUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/view/TestHoodieTableFileSystemView.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala
Labels: size:M, release-1.1.0

#14023 feat: add new Hudi demo app `hudi-notebooks`
  hudi-notebooks/.dockerignore
  hudi-notebooks/.gitignore
  hudi-notebooks/Dockerfile.hive
  hudi-notebooks/Dockerfile.spark
  hudi-notebooks/README.md
  hudi-notebooks/build.sh
  hudi-notebooks/conf/hive/metastore-site.xml
  hudi-notebooks/conf/spark/hudi-defaults.conf
  hudi-notebooks/conf/spark/spark-defaults.conf
  hudi-notebooks/docker-compose.yml
  hudi-notebooks/entrypoint.sh
  hudi-notebooks/notebooks/01-crud-operations.ipynb
  hudi-notebooks/notebooks/02-query-types.ipynb
  hudi-notebooks/notebooks/03-scd-type2_and_type4.ipynb
  hudi-notebooks/notebooks/04-schema-evolution.ipynb
  hudi-notebooks/notebooks/05-mastering-sql-procedures.ipynb
  hudi-notebooks/notebooks/images/Hudi_SQL_Procedures.png
  hudi-notebooks/notebooks/images/Spark_Hudi.png
  hudi-notebooks/notebooks/utils.py
  hudi-notebooks/run_spark_hudi.sh
  scripts/release/create_source_directory.sh
Labels: size:XL

#14004 docs: Updating Docker Demo Guide for latest Hudi Version
  website/docs/docker_demo.md
Labels: docs, size:L
