Repository apache/hudi, pull requests merged in 2025-02, with the labels that each got.

#12752 [HUDI-8949] Relaxing checkpoint validation for HoodieStreamerSources
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieIncrSourceE2E.java
Labels: size:S

#12488 [HUDI-8767] Add bundle validation for release artifacts in Maven central
  .github/workflows/maven_artifact_validation.yml
  packaging/bundle-validation/README.md
  packaging/bundle-validation/ci_run.sh
  release/release_guide.md
Labels: size:M

#12763 [site] Update latest blogs and video guides
  website/blog/2024-12-03-apache-iceberg-vs-apache-hudi.mdx
  website/blog/2024-12-04-use-open-table-format-libraries-on-aws-glue-5-0-for-apache-spark.mdx
  website/blog/2024-12-28-how-lakehouse-handles-concurrent-read-and-writes.mdx
  website/blog/2024-12-31-indexing-in-apache-hudi.mdx
  website/blog/2024-12-31-the-architects-guide-to-open-table-formats-and-object-storage.mdx
  website/blog/2025-01-05-how-use-new-hudi-streamer-100-emr-serverless-750-hands-on.mdx
  website/blog/2025-01-08-the-future-of-data-lakehouses-a-fireside.mdx
  website/blog/2025-01-09-apache-iceberg-vs-delta-lake-vs-apache-hudi.mdx
  website/blog/2025-01-18-apache-hudi-1-0-now-generally-available.mdx
  website/blog/2025-01-28-concurrency-control.md
  website/blog/2025-01-30-an-intro-to-hudi-with-minio.mdx
  website/src/pages/talks.md
  website/static/assets/images/blog/2024-12-03-apache-iceberg-vs-apache-hudi.jpeg
  website/static/assets/images/blog/2024-12-04-use-open-table-format-libraries-on-aws-glue-5-0-for-apache-spark.png
  website/static/assets/images/blog/2024-12-28-how-lakehouse-handles-concurrent-read-and-writes.jpeg
  website/static/assets/images/blog/2024-12-31-indexing-in-apache-hudi.jpeg
  website/static/assets/images/blog/2024-12-31-the-architects-guide-to-open-table-formats-and-object-storage.jpg
  website/static/assets/images/blog/2025-01-05-how-use-new-hudi-streamer-100-emr-serverless-750-hands-on.png
  website/static/assets/images/blog/2025-01-08-the-future-of-data-lakehouses-a-fireside.jpg
  website/static/assets/images/blog/2025-01-09-apache-iceberg-vs-delta-lake-vs-apache-hudi.jpeg
  website/static/assets/images/blog/2025-01-18-apache-hudi-1-0-now-generally-available.jpeg
  website/static/assets/images/blog/2025-01-30-an-intro-to-hudi-with-minio.jpeg
  website/static/assets/images/video_blogs/2024-12-25-learn-about-secondary-indexes-in-apache-hudi-1-0-0.png
  website/static/assets/images/video_blogs/2025-01-04-learn-about-apache-hudi-1-0-0-expression-index-hands-on-labs.png
  website/static/assets/images/video_blogs/2025-01-26-create-your-first-apache-hudi-table-in-5-simple-steps.png
  website/videoBlog/2024-12-25-learn-about-secondary-indexes-in-apache-hudi-1-0-0.mdx
  website/videoBlog/2025-01-04-learn-about-apache-hudi-1-0-0-expression-index-hands-on-labs.mdx
  website/videoBlog/2025-01-26-create-your-first-apache-hudi-table-in-5-simple-steps.mdx
Labels: docs, size:M

#12754 [HUDI-8950] Explicitly set base path in sync config
  hudi-sync/hudi-sync-common/src/main/java/org/apache/hudi/sync/common/util/SyncUtilHelpers.java
Labels: size:XS

#12764 [MINOR] Refactored `BucketIdentifier`
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieSimpleBucketIndex.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/index/bucket/TestBucketIdentifier.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bucket/TestHoodieSimpleBucketIndex.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/BucketIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBucketIndexSupport.scala
Labels: size:M

#12766 [HUDI-8278] Add log message about different primary keys for HoodieTableFactory
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableFactory.java
Labels: size:XS

#12769 [HUDI-8951] Disabled flaky `TestHoodieDeltaStreamer::testHoodieIndexerExecutionAfterClustering`
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:XS

#12767 [MINOR] Fix code issues reported by code review tool
  hudi-spark-datasource/hudi-spark3.5.x/src/test/java/org/apache/hudi/internal/HoodieBulkInsertInternalWriterTestBase.java
  hudi-spark-datasource/hudi-spark3.5.x/src/test/java/org/apache/hudi/spark3/internal/TestHoodieBulkInsertDataInternalWriter.java
  hudi-spark-datasource/hudi-spark3.5.x/src/test/java/org/apache/hudi/spark3/internal/TestHoodieDataSourceInternalBatchWrite.java
Labels: size:S

#12788 [DOCS] Update python/rust page and links
  website/docs/python-rust-quick-start-guide.md
  website/src/pages/ecosystem.md
  website/versioned_docs/version-0.15.0/python-rust-quick-start-guide.md
  website/versioned_docs/version-1.0.0/python-rust-quick-start-guide.md
Labels: docs, size:L

#12271 [MINOR] Move field ordering lookup outside of loop for proto conversion
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/ProtoConversionUtil.java
Labels: size:XS

#12791 [HUDI-8966] Claim RFC-88 for New Schema/DataType/Expression Abstractions
  rfc/README.md
Labels: size:XS

#12785 [HUDI-8958] Enable record index validation by default
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
Labels: size:XS

#12810 [MINOR] Fix compilation issue
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java
Labels: size:XS

#12805 [HUDI-8989] Fixing Compaction scheduling for tbl v6
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/CompactionTestBase.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestAsyncCompaction.java
Labels: size:S

#11924 [HUDI-8190] Implement efficient streaming reads for HoodieDataBlocks
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieAvroDataBlock.java
Labels: size:L

#12816 [MINOR] Updating doap for release 1.0.1
  doap_HUDI.rdf
Labels: size:XS

#12806 [HUDI-8990][RFC-89] Claim RFC-89: Dynamic Partition Level Bucket Index
  rfc/README.md
Labels: size:XS

#12819 [HUDI-8569] Fix Insert overwrite / update MOR with global index does not work
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestGlobalIndex.scala
Labels: size:S

#12792 [HUDI-8967] Add a config to fail job if duplicate data files detected during reconcileAgainstMarkers
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieDuplicateDataFileDetectedException.java
Labels: size:S

#12790 [HUDI-8965] Add a test to ensure that hive sync tool throws exception upon sync failure
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
Labels: size:S

#12775 [HUDI-8959] HoodieMetadataTableValidator can skip validation if data table is not found
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:S

#12822 [HUDI-8998] Improve handling of zero scale decimals in MercifulJsonConverter
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/DecimalLogicalTypeProcessor.java
  hudi-common/src/test/java/org/apache/hudi/avro/MercifulJsonConverterTestBase.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
  hudi-common/src/test/resources/decimal-logical-type-zero-scale.avsc
Labels: size:M

#12715 [HUDI-8922] Avoid rescheduling pending rollbacks
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/TestHoodieTable.java
Labels: size:L

#12830 [SITE] Add developer sync call page
  website/contribute/developer-setup.md
  website/contribute/developer-sync-call.md
  website/contribute/report-security-issues.md
  website/contribute/rfc-process.md
  website/docusaurus.config.js
Labels: docs, size:S

#12831 [MINOR] Fix flaky TestHoodieAvroDataBlock
  hudi-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieAvroDataBlock.java
Labels: size:XS

#12797 [HUDI-8971] Fixing metadata metrics to honor metrics prefix
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/config/metrics/HoodieMetricsConfig.java
Labels: size:XS

#12814 [HUDI-8992] Initial changes to allow us to use streams instead of byte arrays
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/FileSystemViewCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v2/LSMTimelineWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIndexUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieArchivedTimeline.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/TestCleanPlanner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieIndex.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestAverageRecordSizeUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodiePartitionMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/BaseHoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/dto/TimelineDTO.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ActiveTimelineV1.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ArchivedTimelineV1.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/BaseTimelineV1.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/TimelineV1Factory.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ArchivedTimelineV2.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/BaseTimelineV2.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/TimelineV2Factory.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/fs/TestHoodieWrapperFileSystem.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestHoodieActiveTimeline.java
  hudi-io/src/main/java/org/apache/hudi/common/util/FileIOUtils.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieInstantWriter.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
  hudi-io/src/test/java/org/apache/hudi/io/storage/TestHoodieStorageBase.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowColumnStatsOverlapProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowFileSystemViewProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowMetadataTableColumnStatsProcedure.scala
Labels: size:L

#12834 [HUDI-9009] Fix potential race condition when listing files by leveraging exception type
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
Labels: size:XS

#12458 [HUDI-8701] prevent lock metrics failure from failing process
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/metrics/HoodieLockMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestHoodieLockMetrics.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestHoodieTimer.java
  hudi-io/src/main/java/org/apache/hudi/common/util/HoodieTimer.java
Labels: size:M

#12268 [MINOR] Register more classes with Kryo
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieCommonKryoRegistrar.java
Labels: size:XS

#12802 [HUDI-8972] Fixing heart beats for failed writes in HoodieStreamer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:M

#12765 [MINOR] Fix skew in clustering operator
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanEvent.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringPlanOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
Labels: size:S

#12840 [MINOR] Rebalance Azure CI jobs (2025-02-13)
  azure-pipelines-20230430.yml
Labels: size:S

#12803 [HUDI-8985] Fix avg record size estimator to avoid parsing all commit metadata of active timeline
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/estimator/AverageRecordSizeEstimator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/estimator/RecordSizeEstimator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/estimator/RecordSizeEstimatorFactory.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/estimator/TestAverageRecordSizeEstimator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/estimator/TestRecordSizeEstimatorFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/AverageRecordSizeUtils.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/UpsertPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestAverageRecordSizeUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/DefaultInstantComparator.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
Labels: size:XL

#12842 [HUDI-7596] Enable Jacoco code coverage report across multiple modules
  azure-pipelines-20230430.yml
  pom.xml
  scripts/jacoco/README.md
  scripts/jacoco/download_jacoco.sh
  scripts/jacoco/generate_jacoco_coverage_report.sh
  scripts/jacoco/merge_jacoco_exec_files.sh
  scripts/jacoco/merge_jacoco_job_files.sh
Labels: size:L

#12787 [HUDI-8962] Adding more logs during indexing
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bloom/HoodieBloomIndex.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/FlinkTaskContextSupplier.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/JavaTaskContextSupplier.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/HoodieJavaClientTestHarness.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkTaskContextSupplier.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/LocalTaskContextSupplier.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/TaskContextSupplier.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestColStatsRecordWithMetadataRecord.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
Labels: size:S

#12491 [HUDI-8769] Limit instantsToArchive to avoid expensive locks blocking ingestion and table services
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestHoodieTimelineArchiver.java
Labels: size:M

#12844 [MINOR] Rebalance Azure CI jobs (2025-02-14)
  azure-pipelines-20230430.yml
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestDropTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestRepairTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestShowPartitions.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestTruncateTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/TestCDCForSparkSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/TestCompactionTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/TestDataSkippingQuery.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/TestQueryMergeOnReadOptimizedTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestExpressionIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestGlobalIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestIndexSyntax.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala
Labels: size:L

#12847 [HUDI-9039] Run do init table transaction only when required
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
Labels: size:XS

#12789 [HUDI-7624] Fixing source read and index tagging duration
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseWriteHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/HoodieDeleteHelper.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
Labels: size:S

#12681 [HUDI-8882] Support Compaction/Rollback/Clean Timeline Instant Metrics in HoodieMetrics
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
Labels: size:M

#11844 [HUDI-8126] Persist sourceRdd to optimise writeStatus DAG
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieErrorTableConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/callback/SourceCommitCallback.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/BaseTestKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/testutils/sources/AbstractCloudObjectsSourceTestBase.java
Labels: size:L

#12664 [HUDI-8883] Add ability to configure HoodieCompactionPlanGenerator using reflection
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCompactionConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/compact/TestScheduleCompactionActionExecutor.java
Labels: size:M

#12855 [DOCS] Update Hudi Roadmap page
  website/src/pages/roadmap.md
Labels: docs, size:S

#12850 [HUDI-9045] Spillable Map operational improvements
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieCDCLogger.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieFileSystemViews.java
  hudi-common/src/main/java/org/apache/hudi/common/serialization/HoodieFileGroupSerializer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/view/SpillableMapBasedFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-common/src/test/java/org/apache/hudi/common/table/log/TestLogFileIterator.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/FormatUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/format/cdc/CdcInputFormat.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/collection/TestExternalSpillableMap.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieMergeOnReadSnapshotReader.java
  hudi-kafka-connect/src/main/java/org/apache/hudi/connect/writers/BufferedConnectWriter.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
Labels: size:M

#12164 [HUDI-8442] Reduce timeline loads while rolling back failed writes
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metadata/TestHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestSavepointRestoreCopyOnWrite.java
  hudi-common/src/main/java/org/apache/hudi/common/util/CleanerUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestCleanerUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestSavepointRestoreMergeOnRead.java
Labels: size:L

#12836 [HUDI-9016] Fix the HoodieCompactor schedule parameter alias name
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieCompactor.java
Labels: size:XS

#12804 [HUDI-8988] Implement retry logic for all HTTP calls to timeline server including remote file system view and markers
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/marker/TimelineServerBasedWriteMarkers.java
  hudi-client/hudi-spark-client/pom.xml
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestWriteMarkersBase.java
  hudi-common/pom.xml
  hudi-common/src/main/java/org/apache/hudi/common/table/view/RemoteHoodieTableFileSystemView.java
  hudi-common/src/main/java/org/apache/hudi/timeline/TimelineServiceClient.java
  hudi-common/src/main/java/org/apache/hudi/timeline/TimelineServiceClientBase.java
  hudi-common/src/test/java/org/apache/hudi/timeline/TestTimelineServiceClient.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TimelineServiceTestHarness.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
  pom.xml
Labels: size:L

#12858 [HUDI-9059] Fix ordering of getInstantTimes in CompletionTimeQueryViewV2
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CompletionTimeQueryViewV2.java
Labels: size:S

#12860 [HUDI-9060] Remove validations for clustering metadata
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/TestBaseHoodieTableServiceClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkTableServiceClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaTableServiceClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDTableServiceClient.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkClusteringCornerCases.java
Labels: size:M

#12052 [HUDI-8126] Support proto messages for spark kryo serializer excluding DynamicMessages
  hudi-client/hudi-spark-client/pom.xml
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/HoodieSparkKryoRegistrar.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/ProtoKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestProtoKafkaSource.java
  packaging/hudi-integ-test-bundle/pom.xml
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
  pom.xml
Labels: size:S

#12647 [HUDI-8868] Use external spillable map for cachedAllInputFileSlices in BaseHoodieTableFileIndex
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieCommonConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/serialization/HoodieFileSliceSerializer.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/serialization/TestHoodieFileSliceSerializer.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestConfigUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/bootstrap/index/TestBaseHoodieTableFileIndex.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: size:L

#12813 [HUDI-8126] Use union to parallelize data and error table writes
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieErrorTableConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieErrorTableConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerErrorTableWriteFlow.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionExtensive.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
Labels: size:L

#12231 [HUDI-8501] Improve SizeAwareDataInputStream to implement idempotent
  hudi-common/src/main/java/org/apache/hudi/common/fs/SizeAwareDataInputStream.java
  hudi-common/src/test/java/org/apache/hudi/common/fs/TestSizeAwareDataInputStream.java
Labels: size:M

#12111 [HUDI-8378] Fix Avro schema deserializer failing with schema evolution
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/AvroKafkaSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/DebeziumSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaSourceUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaSourceUtil.java
  hudi-utilities/src/test/resources/schema/evolved-test-with-default-value.avsc
Labels: size:M

#12762 [HUDI-8955] Resolve Kafka beginning offsets with retention to prevent OffsetOutOfRange exception
  hudi-common/src/main/java/org/apache/hudi/common/util/LogicalClock.java
  hudi-common/src/main/java/org/apache/hudi/common/util/SystemClock.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestSystemClock.java
  hudi-tests-common/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/config/KafkaSourceConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/KafkaOffsetGen.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestKafkaOffsetGen.java
Labels: size:L

#12872 [MINOR] Add StorageSchemes for Aliyun Apsara File Storage for HDFS
  hudi-io/src/main/java/org/apache/hudi/storage/StorageSchemes.java
Labels: size:XS

#12876 [HUDI-9070] Fix Hudi cli bundle script to use HUDI_CONF_DIR environment variable
  packaging/hudi-cli-bundle/hudi-cli-with-bundle.sh
Labels: size:XS

#12696 [HUDI-8901] Fix Timeline Server to process requests from multiple storage lakes
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/embedded/EmbeddedTimelineService.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/embedded/TestEmbeddedTimelineService.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/marker/TestTimelineServerBasedWriteMarkers.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestRemoteFileSystemViewWithMetadataTable.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/RequestHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/TimelineService.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/BaseFileHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/FileSliceHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/Handler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/InstantStateHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/MarkerHandler.java
  hudi-timeline-service/src/main/java/org/apache/hudi/timeline/service/handlers/TimelineHandler.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/MockHoodieHadoopStorage.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TestRequestHandler.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TestTimelineService.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/TimelineServiceTestHarness.java
  hudi-timeline-service/src/test/java/org/apache/hudi/timeline/service/functional/TestRemoteHoodieTableFileSystemView.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/perf/TimelineServerPerf.java
Labels: size:L

#12796 [HUDI-8920] [RFC-84] Optimize SerDe of stream records for Flink write (excluding bulk insert and append mode)
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/ConsistentBucketIdentifier.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkInternalRow.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkInternalRowSerializer.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkInternalRowTypeInfo.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/BootstrapOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bootstrap/batch/BatchBootstrapOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/ConsistentBucketAssignFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/ConsistentBucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketAssignFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunctionWithRateLimit.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/transform/RowDataToHoodieFunctions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/PayloadCreation.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/HoodieFlinkStreamer.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestConsistentBucketStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/ConsistentBucketStreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
Labels: size:XL

#12849 [hudi-9041] Send act commit event when reuse current instant
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BulkInsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockSubtaskGateway.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink1.14.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.15.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.16.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.17.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.19.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.20.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
Labels: size:L

#12864 [HUDI-9061] JSON to AVRO schema converter
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-kafka-connect/pom.xml
  hudi-utilities/pom.xml
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/converter/JsonToAvroSchemaConverter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/converter/JsonToAvroSchemaConverterConfig.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/JsonKafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/converter/TestJsonToAvroSchemaConverter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
  hudi-utilities/src/test/resources/schema-provider/json/array-with-item-type-union/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/array-with-item-type-union/input.json
  hudi-utilities/src/test/resources/schema-provider/json/complex-json-union-types/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/complex-json-union-types/input.json
  hudi-utilities/src/test/resources/schema-provider/json/not-null-default-value-schema/expected_no_stripping_quotes.json
  hudi-utilities/src/test/resources/schema-provider/json/not-null-default-value-schema/expected_stripping_quotes.json
  hudi-utilities/src/test/resources/schema-provider/json/not-null-default-value-schema/input.json
  hudi-utilities/src/test/resources/schema-provider/json/schema-repeating-names/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/schema-repeating-names/input.json
  packaging/hudi-utilities-bundle/pom.xml
  pom.xml
Labels: size:XL

#12877 [HUDI-9071] MDT validator can configure if log truncation applies
  hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:M

#12848 [HUDI-9040] Set the correct table path when renaming tables
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/AlterHoodieTableRenameCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
Labels: size:XS

#12883 [HUDI-9077][DOCS] Update MERGE INTO docs
  website/docs/sql_dml.md
  website/versioned_docs/version-1.0.1/sql_dml.md
Labels: docs, size:S

#12729 [HUDI-8934] Claim of RFC-87. Avro elimination for Flink writer
  rfc/README.md
  rfc/rfc-87/rfc-87.md
Labels: rfc, size:S

#12758 [HUDI-8954] Reconstruct writer schema while clustering by spark row writer
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkConsistentBucketClusteringExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSingleFileSortExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkSortAndSizeExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBulkInsertOverwriteCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/HoodieStreamerDatasetBulkInsertCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: size:S

#12879 [HUDI-9072] Support decimal in JsonKafkaSource
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/MercifulJsonConverterTestBase.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/FilebasedSchemaProvider.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/SourceFormatAdapter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestFilebasedSchemaProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/converter/TestJsonToAvroSchemaConverter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
  hudi-utilities/src/test/resources/schema-provider/json/kafka-decimal-simple/expected.json
  hudi-utilities/src/test/resources/schema-provider/json/kafka-decimal-simple/input.json
  hudi-utilities/src/test/resources/streamer-config/source_uber_encoded_decimal.avsc
  hudi-utilities/src/test/resources/streamer-config/source_uber_encoded_decimal.json
Labels: size:L

#12829 [HUDI-8992] Fix serde issues in commit metadata
  hudi-common/src/main/avro/HoodieCommitMetadata.avsc
  hudi-common/src/main/avro/HoodieReplaceCommitMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieReplaceCommitMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CommitMetadataSerDeV2.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieCommitMetadata.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/versioning/BaseTestCommitMetadataSerDe.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/versioning/v1/TestCommitMetadataSerDeV1.java
  hudi-common/src/test/java/org/apache/hudi/common/table/timeline/versioning/v2/TestCommitMetadataSerDeV2.java
Labels: size:L

#12881 [HUDI-7946][RFC-90] Claim RFC-90
  rfc/README.md
Labels: size:XS

#12741 [HUDI-8940] Fix Bloom Index Partitioner to distribute keys uniformly across partitions
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestHoodieBloomIndex.java
Labels: size:M

#12435 [HUDI-8577] Use config default for query type in default source in Spark
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
Labels: size:XS

#11629 [HUDI-7985] Add more test cases around timestamp and decimal formats in Json Avro converter
  hudi-common/src/test/java/org/apache/hudi/avro/MercifulJsonConverterTestBase.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestMercifulJsonConverter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestMercifulJsonToRowConverter.java
Labels: size:L

#12723 [DOCS] Typo fix in hudi_stack.md
  website/docs/hudi_stack.md
  website/versioned_docs/version-1.0.0/hudi_stack.md
  website/versioned_docs/version-1.0.1/hudi_stack.md
Labels: docs, size:XS

#12865 [DOCS] Fix minor website typos
  website/docs/quick-start-guide.md
  website/docs/write_operations.md
  website/versioned_docs/version-1.0.1/quick-start-guide.md
  website/versioned_docs/version-1.0.1/write_operations.md
Labels: docs, size:S

#12697 [HUDI-8799] Design of RFC-84, Optimized SerDe of `DataStream` in Flink operators
  rfc/rfc-84/datastream_hoodietablesink.png
  rfc/rfc-84/rfc-84.md
Labels: rfc, size:L

#12869 [HUDI-9065] Adding new filters to ArchivedTimelineV1
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/table/timeline/TestArchivedTimelineV2.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieArchivedTimeline.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ArchivedTimelineLoaderV1.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/ArchivedTimelineV1.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestArchivedTimelineV1.java
Labels: size:L

#12798 [HUDI-8486] Enforce data type match for required columns in Spark SQL MERGE INTO
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestTableColumnTypeMismatch.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestAlterTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoLogOnlyTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTableWithNonRecordKeyField.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeCommitTimeOrdering.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
Labels: size:XL

#12886 [HUDI-9041] Send commit ack event when reusing current instant
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BucketStreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/InsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockSubtaskGateway.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/StreamWriteFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/TestWriteBase.java
  hudi-flink-datasource/hudi-flink1.14.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.15.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.16.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.17.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
  hudi-flink-datasource/hudi-flink1.18.x/src/test/java/org/apache/hudi/adapter/ExecutionAttemptUtil.java
Labels: size:M

#12800 [HUDI-8486] Add column mismatch test coverage
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestTableColumnTypeMismatch.scala
Labels: size:S

#12892 [SITE] Update blogs
  website/blog/2025-02-23-curious-engineering-facts-lakehouse-apache-hudi-daft-positional-argument.mdx
  website/blog/2025-02-24-building-a-lakehouse-architecture-on-aws-with-terraform.mdx
  website/blog/2025-02-25-curious-engineering-facts-trace-agents-hudi-daft-1.mdx
  website/static/assets/images/blog/2025-02-23-curious-engineering-facts-lakehouse-apache-hudi-daft-positional-argument.jpeg
  website/static/assets/images/blog/2025-02-24-building-a-lakehouse-architecture-on-aws-with-terraform.jpeg
  website/static/assets/images/blog/2025-02-25-curious-engineering-facts-trace-agents-hudi-daft-1.jpeg
Labels: docs, size:S

#12890 [HUDI-9086] Disabling failing test to unblock master
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieDataSourceHelper.scala
Labels: size:S
