Repository apache/hudi, pull requests merged in 2025-01, with the labels that each got.

#12559 [HUDI-8802] Avoid unnecessary conversion between HoodieIndexAvroRecord and HoodieAvroRecord in HoodieFileSliceReader
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieFileSliceReader.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
Labels: size:S

#12560 [HUDI-8803] Fix ArrayIndexOutOfBoundsException while vectorized read with schema evolution
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestVectorizedReadWithSchemaEvolution.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/spark/sql/execution/datasources/parquet/Spark3HoodieVectorizedParquetRecordReader.java
Labels: size:M

#12544 [HUDI-8795] Skip checking recordKey config for table version <=1
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
Labels: size:S

#12531 [HUDI-8787] Improve compaction performance by reducing unnecessary disk access
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/BitCaskDiskMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/DiskMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/FilterIterator.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/KeyFilteringIterable.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDBDAO.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/RocksDbDiskMap.java
  hudi-common/src/test/java/org/apache/hudi/common/util/collection/TestFilterIterator.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/collection/TestBitCaskDiskMap.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/util/collection/TestRocksDbDiskMap.java
Labels: size:M

#12514 [HUDI-8780][RFC-83] Incremental Table Service
  rfc/rfc-83/rfc-83.md
  rfc/rfc-83/timeline.png
Labels: size:M

#12557 [HUDI-8791] Test secondary index on auto keygen tables
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
Labels: size:S

#12466 [HUDI-8647] Support Clustering Timeline Instant Metrics in HoodieMetrics
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/metrics/TestHoodieMetrics.java
Labels: size:S

#12505 [DOCS] Added reference blogs to hudi docs
  website/docs/azure_hoodie.md
  website/docs/cleaning.md
  website/docs/cli.md
  website/docs/clustering.md
  website/docs/compaction.md
  website/docs/concepts.md
  website/docs/concurrency_control.md
  website/docs/indexes.md
  website/docs/key_generation.md
  website/docs/markers.md
  website/docs/metadata.md
  website/docs/performance.md
  website/docs/precommit_validator.md
  website/docs/record_merger.md
  website/docs/timeline.md
  website/docs/writing_tables_streaming_writes.md
Labels: docs, size:S

#12562 [HUDI-8804] clean and archival should also be in try-catch block
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/plan/generators/BaseHoodieCompactionPlanGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/HoodieWriterClientTestHarness.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: size:M

#12358 [HUDI-8596] Fix Hudi Spark SQL cancelling issue
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/common/TestHoodieSparkEngineContext.java
Labels: size:S

#12529 [HUDI-8232] Adding Index defn for Col stats to track the list of columns indexed
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieTableServiceClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/CompactionAdminClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieColumnStatsIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/functional/BaseHoodieIndexClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaTableServiceClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/HoodieJavaWriteClient.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/table/action/commit/BaseJavaCommitActionExecutor.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/TestHoodieMetadataBase.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/HoodieSparkIndexClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/bootstrap/SparkBootstrapCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/HoodieUnsafeUtils.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieSparkIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieIndexDefinition.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/cow-updated3-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/cow-updated4-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/mor-updated3-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/mor-updated4-column-stats-index-table.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/update5-input-table-json/part-00000-7e680484-e7e1-48b6-8289-1a7c483b530b-c000.json
  hudi-spark-datasource/hudi-spark/src/test/resources/index/colstats/update6-input-table-json/part-00000-7e680484-e7e1-48b6-8289-1a7c483b530b-c000.json
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
Labels: size:L

#12451 [HUDI-8678] feat: improve consistent-bucket resizing performance by reducing unnecessary record collecting
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/ConsistentHashingBucketInsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SparkConsistentBucketClusteringExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/ConsistentBucketIndexBulkInsertPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDConsistentBucketBulkInsertPartitioner.java
Labels: size:M

#12578 [HUDI-8829] reduce bytes copy during writing avro records to log file
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
Labels: size:S

#12570 [MINOR] Fix bad log info in table services
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
Labels: size:XS

#12519 [HUDI-8783] Add tests for decimal data type
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestDecimalTypeDataWorkflow.scala
Labels: size:M

#12550 [HUDI-8799] Claim of RFC-84, Optimized SerDe of `DataStream` in Flink operators
  rfc/README.md
  rfc/rfc-84/rfc-84.md
Labels: size:S

#12518 [HUDI-8782] BulkInsertWriterHelper parallel close
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/BulkInsertWriterHelper.java
Labels: size:S

#12590 [MINOR] Avoid wrong way to get the latest completed instant
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieTimeline.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV1.scala
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
  hudi-sync/hudi-hive-sync/src/main/java/org/apache/hudi/hive/HoodieHiveSyncClient.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
Labels: size:S

#12575 [HUDI-8663] Look up in col stats based on indexed cols
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestDataSkippingUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
Labels: size:L

#12525 [HUDI-8518] Fix RLI and Secondary index with custom payload or merge mode
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/common/HoodieFlinkEngineContext.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/common/HoodieJavaEngineContext.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/metadata/JavaHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieEngineContext.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieLocalEngineContext.java
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseFileRecordParsingUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/SecondaryIndexRecordGenerationUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
Labels: size:XL

#12603 [HUDI-8847] Bump Spark 35 version to 3.5.4
  pom.xml
Labels: size:XS

#12605 [HUDI-8746] Improve a test in TestHoodieMultipleBaseFileFormat
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestHoodieMultipleBaseFileFormat.scala
Labels: size:S

#12606 [HUDI-8173] Default value of hoodie.avro.schema.validate silently getting updated if not passed explicitly
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
Labels: size:XS

#12611 [HUDI-8762] Fix a typo in TestIncrementalQueryWithArchivedInstants
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/TestIncrementalQueryWithArchivedInstants.scala
Labels: size:XS

#12596 [HUDI-8766] Enabling cols stats by default with writer
  azure-pipelines-20230430.yml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/testutils/TestHoodieMetadataBase.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestClientRollback.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestCleaner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/rollback/TestCopyOnWriteRollbackActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestCleanPlanExecutor.java
  hudi-common/src/main/avro/HoodieMetadata.avsc
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieColumnRangeMetadata.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteCopyOnWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestWriteMergeOnReadWithCompact.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieDeleteBlock.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestMetadataTableSupport.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestColStatsRecordWithMetadataRecord.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestBasicSchemaEvolution.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestDataSourceForBootstrap.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexWithSQL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestSecondaryIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestBootstrapProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCommitsProcedure.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: size:L

#12607 [HUDI-8849] Reenable TestExpressionIndex
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
Labels: size:S

#12609 [HUDI-7081] Enable fg reader for tests with enum typed data
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: size:XS

#12537 [HUDI-8800] Introduce SingleSparkConsistentBucketClusteringExecutionStrategy to improve performance
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieClusteringConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/cluster/strategy/ClusteringExecutionStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-client/hudi-java-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/JavaExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobConsistentHashingExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/SingleSparkJobExecutionStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/model/ClusteringGroupInfo.java
  hudi-common/src/main/java/org/apache/hudi/common/util/ClusteringUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestSparkConsistentBucketClustering.java
Labels: size:L

#12624 [HUDI-8849] Reenable TestExpressionIndex
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/ExpressionIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SparkBaseIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/command/index/TestExpressionIndex.scala
Labels: size:S

#12569 [HUDI-8811] Handle Kafka source configuration-related failures with specific exception handling
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/KafkaSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestAvroKafkaSource.java
Labels: size:S

#12625 [HUDI-8859] Support filter by instants in ShowInvalidParquetProcedure
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowInvalidParquetProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestShowInvalidParquetProcedure.scala
Labels: size:S

#12626 [HUDI-8860] Avoid calling values() on ExternalSpillableMap
  hudi-common/src/test/java/org/apache/hudi/common/table/log/TestLogFileIterator.java
Labels: size:M

#12584 [HUDI-8824] MIT should error out for some assignment clause patterns
  hudi-common/src/main/java/org/apache/hudi/common/util/ConfigUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieBaseRelation.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTableWithNonRecordKeyField.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
Labels: size:L

#12602 [HUDI-8664] Fix TestSparkSqlCoreFlow to be based on completion time
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/HoodieDataSourceHelpers.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlCoreFlow.scala
Labels: size:M

#12583 [HUDI-8828] Test coverage of MIT partial insert and update
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
Labels: size:S

#12587 [HUDI-8823] Ban update from updating primary key and partition key
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/UpdateHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestUpdateTable.scala
Labels: size:M

#12635 [HUDI-8629] Update Spark DML docs on schema evolution
  website/docs/sql_dml.md
  website/versioned_docs/version-1.0.0/sql_dml.md
Labels: docs, size:S

#12632 [HUDI-8862] Fix inconsistent instant when sync hive in StreamWriteOperatorCoordinator
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
Labels: size:XS

#12631 [MINOR] Fix incorrect parameter usage when selecting partition for TTL
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/ttl/strategy/PartitionTTLStrategy.java
Labels: size:XS

#12588 [HUDI-8758] Enforce insert deduplicate policy for spark SQL
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/ValidateDuplicateKeyPayload.scala
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestInsertDedupPolicy.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
Labels: size:L

#12613 [HUDI-8624] Enable fullscan by default for incremental queries
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:XS

#12639 [HUDI-8842] Support skipping compaction and cluster for spark increme…
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelationV2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestStreamingSource.scala
Labels: size:M

#12598 [HUDI-8841] Fix schema validating exception during flink async cluste…
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/clustering/ClusteringOperator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/cluster/ITTestHoodieFlinkClustering.java
Labels: size:M

#12629 [DOCS] Fix broken link in concurrency control page
  website/docs/concurrency_control.md
Labels: docs, size:XS

#12640 [HUDI-8865] Fix error message of unresolved columns in MERGE INTO on Spark 3.5
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/HoodieSpark35CatalystPlanUtils.scala
Labels: size:S

#12643 [HUDI-8621] Revert single file slice optimisation for getRecordsByKeys in MDT table
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java
Labels: size:S

#12581 [HUDI-8831] Hudi parser should passthrough unsupport procedure to delegate
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/parser/HoodieSqlCommonAstBuilder.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallCommandParser.scala
Labels: size:S

#12614 [HUDI-8855] Add bucket properties for spark bucket index query pruning
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
Labels: size:S

#12649 [HUDI-8806] Fix "No value present in Option" in show_clustering procedure
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/ShowClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: size:S

#12641 [HUDI-8629] Improve test coverage around different field names in MERGE INTO statements
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestPartialUpdateForMergeInto.scala
Labels: size:L

#12650 [MINOR] Fixed run of `javadoc:aggregate`
  README.md
  pom.xml
Labels: size:S

#12627 [HUDI-8866] Unified the file naming rules in NBCC mode
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/BucketIdentifier.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestSparkNonBlockingConcurrencyControl.java
Labels: size:M

#12658 [HUDI-8693] Renable TestHoodieDeltaStreamer.testDeletePartitions
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:S

#12654 [HUDI-8696] Remove TestHoodieMultiTableDeltaStreamer#testInvalidIngestionProps
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieMultiTableDeltaStreamer.java
Labels: size:S

#12638 [HUDI-8681] Unifying supported cols across col stats and partition stats index
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieColumnStatsIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
Labels: size:S

#12663 [HUDI-8297] Get rid of HoodieIdentifier
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/connector/catalog/HoodieIdentifier.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/catalog/HoodieCatalog.scala
Labels: size:S

#12644 [HUDI-6304] Handle cases when inflight compaction files are removed and job failed leaving pending rollback files
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/compact/CompactionPlanOperator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/CompactionUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestCompactionUtil.java
Labels: size:S

#12621 [HUDI-8315] update SqlKeyGenerator#convertPartitionPathToSqlType to handle default_partition_path
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/SqlKeyGenerator.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkSqlWithTimestampKeyGenerator.scala
Labels: size:S

#12672 [MINOR] Bump maven shade plugin version
  pom.xml
Labels: size:XS

#12670 [HUDI-7483] Disable flaky test dimension
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
Labels: size:XS

#12659 [HUDI-8880] Fix hive scan exception after new column is added
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieParquetInputFormat.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/avro/HoodieAvroParquetReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/avro/HoodieTimestampAwareParquetInputFormat.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHiveTableSchemaEvolution.java
Labels: size:S

#12676 [HUDI-8689] Enable TestSecondaryIndexPruning#testSecondaryIndexWithClusteringAndCleaning
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSecondaryIndexPruning.scala
Labels: size:XS

#12592 [HUDI-8839] CdcFileGroupIterator use spillable hashmap
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/cdc/CDCFileGroupIterator.scala
Labels: size:S

#12686 [HUDI-8694] Re-enable testLatestCheckpointCarryOverWithMultipleWriters
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerWithMultiWriter.java
Labels: size:S

#12675 [HUDI-7598] Remove duplicate methods in subclasses of HoodieSparkClientTestBase to enhance reusability
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/HoodieStatsIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/PartitionStatsIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
Labels: size:L

#12655 [HUDI-7656] Fix a flaky test for concurrent writes
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
Labels: size:S

#12680 [HUDI-8688] Revisit TestRecordLevelIndex#testRLIWithMDTCleaning
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
Labels: size:XS

#12620 [HUDI-8298] refactor SparkDatasetTestUtils#serializeRow
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/testutils/SparkDatasetTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/KeyGeneratorTestUtilities.java
Labels: size:S

#12694 [HUDI-8279] Throw HoodieJsonToAvroConversionException when converting from json to avro
  hudi-common/src/main/java/org/apache/hudi/avro/MercifulJsonConverter.java
  hudi-common/src/main/java/org/apache/hudi/avro/processors/JsonFieldProcessor.java
Labels: size:XS

#11992 [HUDI-8255][RFC-82] Hudi Issue and Sprint Management in Jira
  rfc/README.md
  rfc/rfc-85/images/1-create-subtask.png
  rfc/rfc-85/images/10-log-work-set-remaining-estimate.png
  rfc/rfc-85/images/11-story-screen-after-log-work.png
  rfc/rfc-85/images/12-sprint-1-burndown-chart.png
  rfc/rfc-85/images/13-sprint-1-burndown-details.png
  rfc/rfc-85/images/14-story-add-new-subtask.png
  rfc/rfc-85/images/15-sprint-2-burndown-chart.png
  rfc/rfc-85/images/16-sprint-2-burndown-details.png
  rfc/rfc-85/images/17-sprint-config-estimation.png
  rfc/rfc-85/images/2-create-subtask.png
  rfc/rfc-85/images/3-set-original-estimate.png
  rfc/rfc-85/images/4-story-screen.png
  rfc/rfc-85/images/5-subtask-screen.png
  rfc/rfc-85/images/6-move-issue-to-sprint-1.png
  rfc/rfc-85/images/7-sprint-1-board.png
  rfc/rfc-85/images/8-log-work.png
  rfc/rfc-85/images/9-log-work-timespent.png
  rfc/rfc-85/rfc-85.md
Labels: size:L

#12586 [HUDI-8634] Support schema on read in file group reader-based compaction and clustering in Spark
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieCompactionHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkCopyOnWriteTable.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/ddl/TestSpark3DDL.scala
Labels: size:M

#12703 [HUDI-8908] Claiming RFC-86 for DataFrame implementation of HUDI write path
  rfc/README.md
Labels: size:XS

#12617 [HUDI-8857] Log shortened list of files instead of all files in MDT validator to avoid huge log message
  hudi-io/src/main/java/org/apache/hudi/common/util/StringUtils.java
  hudi-io/src/test/java/org/apache/hudi/common/util/TestStringUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieMetadataTableValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:L

#12700 Revert "[HUDI-8621] Revert single file slice optimisation for getRecordsByKeys in MDT table (#12643)"
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestBootstrapReadBase.java
Labels: size:S

#12704 [HUDI-8910] Fix Unstable UT TestHoodieCompactionStrategy
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/compact/strategy/TestHoodieCompactionStrategy.java
Labels: size:XS

#12705 [MINOR] Rebalance Azure CI jobs (2025-01-24)
  azure-pipelines-20230430.yml
Labels: size:S

#12692 [HUDI-8898] Support INSERT SQL statement with a subset of columns in Spark 3.5
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
  hudi-spark-datasource/hudi-spark3.5.x/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieSpark35Analysis.scala
Labels: size:M

#12662 [HUDI-5769] Ensure partitions created by async indexer are not deleted by regular writers
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
Labels: size:M

#12653 [HUDI-8844] Support secondary and expression index creation through async indexer and write configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/HoodieIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/BaseHoodieIndexClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/HoodieSparkIndexClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/expression/ExpressionIndexSparkFunctions.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BaseSparkCommitActionExecutor.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestHoodieSparkIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieIndexingConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieIndexDefinition.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/index/expression/HoodieExpressionIndex.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/IndexCommands.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestMetadataUtilRLIandSIRecordGeneration.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieIndexer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieIndexer.java
  hudi-utilities/src/test/resources/streamer-config/indexer-expression-index.properties
  hudi-utilities/src/test/resources/streamer-config/indexer-secondary-index.properties
Labels: size:L

#12709 [HUDI-8805] Upgrade commons-io version to 2.14.0 to fix CVE-2024-47554
  dependencies/hudi-flink-bundle_2.11.txt
  dependencies/hudi-flink-bundle_2.12.txt
  dependencies/hudi-hadoop-mr-bundle.txt
  dependencies/hudi-hive-sync-bundle.txt
  dependencies/hudi-integ-test-bundle.txt
  dependencies/hudi-kafka-connect-bundle.txt
  dependencies/hudi-presto-bundle.txt
  dependencies/hudi-spark-bundle_2.11.txt
  dependencies/hudi-spark-bundle_2.12.txt
  dependencies/hudi-spark3-bundle_2.12.txt
  dependencies/hudi-timeline-server-bundle.txt
  dependencies/hudi-utilities-bundle_2.11.txt
  dependencies/hudi-utilities-bundle_2.12.txt
  pom.xml
Labels: size:S

#12646 [HUDI-8628] Table Service writer config hard wired to table schema
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
Labels: size:L

#12701 [MINOR] Removed `RecordLevelIndexSupport::fetchQueryWithAttribute`, which duplicates `filterQueryWithRecordKey`
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
Labels: size:S

#12572 [MINOR] fix up of HUDI-8804
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/utils/HoodieWriterClientTestHarness.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/functional/TestHoodieJavaClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
Labels: size:S

#12691 [HUDI-8897] Add a Scala retry API for running test multiple times
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/hudi/ScalaTestUtils.scala
Labels: size:S

#12452 [HUDI-8682] Simplify precombine and ordering field value handling in the file group reader
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/EventTimeAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieBaseFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieKeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieUnmergedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieTestReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/utils/TestHoodieArrayWritableAvroUtils.java
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/parquet/TestSparkFileFormatInternalRowReaderContext.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/resources/sql-statements.sql
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
Labels: size:L

#12615 [HUDI-8817] fix backward compatibility issue
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/util/SparkConfigUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestWriteTableVersionConfig.scala
Labels: size:M

#12717 [DOC] Changes to Hive Metastore-based distributed locking in the Concurrency control doc.
  website/docs/concurrency_control.md
Labels: docs, size:S

#12713 [HUDI-8851] Fix delete record generation in Prepped DELETE operation in Spark
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDeleteFromTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala
Labels: size:M

#12719 [HUDI-8926] Fix precombine field value to be in the same type in TestMergeModeEventTimeOrdering
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala
Labels: size:S

#12683 [HUDI-8004] avoid unnecessary record rewrite during merging with base file
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaUtils.java
Labels: size:S

#12555 [DOCS] Updated details indexing configurations on indexing page
  website/docs/indexes.md
  website/versioned_docs/version-1.0.0/indexes.md
Labels: docs, size:M

#12600 [HUDI-8413] Change the default merge mode to COMMIT_TIME_ORDERING
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/DefaultSparkRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/config/ConfigProperty.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/streamer/FlinkStreamerConfig.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestCustomMerger.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestEventTimeMerging.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/read/TestOverwriteWithLatestMerger.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/DefaultHiveRecordMerger.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DataSourceOptions.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieOptionConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestSqlConf.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/processor/maxwell/MaxwellJsonKafkaSourcePostProcessor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BootstrapExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:L

#12678 [HUDI-8616] DataHub meta sync improvements (#12456)
  hudi-sync/hudi-datahub-sync/pom.xml
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubResponseLogger.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncClient.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubSyncTool.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubTableProperties.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/DataHubSyncConfig.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/config/HoodieDataHubDatasetIdentifier.java
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/util/SchemaFieldsUtil.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubSyncClient.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestDataHubSyncConfig.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/config/TestHoodieDataHubDatasetIdentifier.java
  packaging/hudi-datahub-sync-bundle/pom.xml
Labels: size:XL

#12688 [HUDI-8726] s3/gcs incremental source should stick to checkpoint v1
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieClientTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/CheckpointUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/checkpoint/TestCheckpointUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV1.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/streaming/HoodieStreamSourceV2.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/IncrSourceHelper.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamerCheckpointUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/CheckpointValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/DummyOperationExecutor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/MockGcsEventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/MockS3EventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/S3EventsHoodieIncrSourceHarness.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestGcsEventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestS3EventsHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestS3GcsEventsHoodieIncrSourceE2ECkpVersion.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamerCheckpointUtils.java
Labels: size:XL

#12708 [HUDI-8726] Test hollow commit handling for table version 8
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestUpgradeDowngradeCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestMarkersCommand.java
  hudi-cli/src/test/java/org/apache/hudi/cli/testutils/HoodieTestCommitMetadataGenerator.java
  hudi-cli/src/test/java/org/apache/hudi/cli/testutils/HoodieTestReplaceCommitMetadataGenerator.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestConflictResolutionStrategyUtil.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/common/testutils/HoodieMetadataTestTable.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/TestBaseTableServicePlanActionExecutor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestClientRollback.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieClientOnCopyOnWriteStorage.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBootstrap.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/io/TestHoodieTimelineArchiver.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/TestConsistencyGuard.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/cluster/ClusteringTestUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/action/commit/TestUpsertPartitioner.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/HoodieCleanerTestBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/CompactionTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtilsBase.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtilsLegacy.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileSliceTestUtils.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bucket/ITTestBucketStreamWrite.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/model/TestHoodieFileGroup.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTimelineUtilsBackComp.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/metadata/TestHoodieTableMetadataUtil.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/hive/TestHoodieCombineHiveInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieMergeOnReadSnapshotReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/realtime/TestHoodieRealtimeRecordReader.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestOrcBootstrap.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestCallProcedure.scala
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/TestHiveSyncTool.java
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/helpers/TestDFSPathSelectorCommonMethods.java
Labels: size:XL

#12568 [HUDI-8808] Fix concurrent execution of appending rollback blocks in the same file group
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackHelper.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/RollbackUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/HoodieRollbackTestBase.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/TestBaseRollbackHelper.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/TestMarkerBasedRollbackStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/action/rollback/TestRollbackUtils.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/table/functional/TestMarkerBasedRollbackStrategy.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
Labels: size:XL, release-1.0.1

#12726 [HUDI-8468] use payload to do merging inside the expression payload
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieRecordUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala
Labels: size:M

#12718 [HUDI-8917] Checkpoint reset handling
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
  hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/Checkpoint.java
  hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/CheckpointUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/HoodieIncrSourceCheckpointValUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/checkpoint/UnresolvedStreamerCheckpointBasedOnCfg.java
  hudi-common/src/test/java/org/apache/hudi/common/table/checkpoint/TestCheckpointUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/table/checkpoint/TestHoodieIncrSourceCheckpointValUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/Source.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamerCheckpointUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/CheckpointValidator.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/DummyOperationExecutor.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/MockGeneralHoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieIncrSourceE2E.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieIncrSourceE2EAutoUpgrade.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestStreamerCheckpointUtils.java
Labels: size:XL

#12727 [HUDI-8895] Ignoring PSI lookup for filters w/ nulls
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/DataSkippingUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
Labels: size:M

#12730 [HUDI-8930] Removing default lock provider
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLockConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:S

#12594 [HUDI-8654] Add base file instant time of record positions to the log block header
  hudi-cli/src/test/java/org/apache/hudi/cli/commands/TestHoodieLogFileCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieMetadataWriteUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/utils/TestLegacyArchivedMetaEntryReader.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/HoodieWriteableTestTable.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/testutils/HoodieFlinkWriteableTestTable.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieAvroDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieCDCDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieDeleteBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieHFileDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieParquetDataBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodiePositionBasedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieFileSliceTestUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/util/TestSerializationUtils.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormatAppendFailure.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/log/block/TestHoodieDeleteBlock.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/testutils/InputFormatTestUtil.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestHoodiePositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableInsertUpdateDelete.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSourceStorage.scala
  hudi-sync/hudi-hive-sync/src/test/java/org/apache/hudi/hive/testutils/HiveTestUtil.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/TestHoodieMetadataTableValidator.java
Labels: size:L, release-1.0.1

#12737 [HUDI-8930] Fixing concurrency handling during upgrade
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/config/TestHoodieWriteConfig.java
  hudi-common/src/main/java/org/apache/hudi/client/transaction/lock/NoopLockProvider.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieTimeGeneratorConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimeGenerators.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/client/transaction/lock/TestNoopLockProvider.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/timeline/TestWaitBasedTimeGenerator.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: size:L

#12725 [HUDI-8850] Fix record merge mode related issues and improve test coverage in Spark SQL
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/HoodieSparkSqlTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable2.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeCommitTimeOrdering.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeEventTimeOrdering.scala
Labels: size:L, release-1.0.1

#12724 [DOCS] New blog Concurrency Control
  website/blog/2025-01-28-concurrency-control.md
  website/static/assets/images/blog/concurrency_control/2PL.png
  website/static/assets/images/blog/concurrency_control/MVCC.png
  website/static/assets/images/blog/concurrency_control/OCC.png
  website/static/assets/images/blog/concurrency_control/concur_blog.png
  website/static/assets/images/blog/concurrency_control/concurrency_blog_thumb.jpg
Labels: docs, size:M

#12706 [MINOR] Fix bloom index shuffle setup
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/BucketizedBloomCheckPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/bloom/SparkHoodieBloomIndexHelper.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/index/bloom/TestBucketizedBloomCheckPartitioner.java
Labels: size:S

#12744 [HUDI-8943] Partition stats should skip queries with null or complex expressions
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndexWithSql.scala
Labels: size:M

#12740 [MINOR] Fix typo and remove hardcoded classnames
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngradeUtils.java
  hudi-common/src/main/java/org/apache/hudi/client/transaction/lock/NoopLockProvider.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: size:S

#12731 [HUDI-8785] Missed set of `POPULATE_META_FIELDS` parameter during table initialization by Flink
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/StreamerUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: size:S

#12743 [HUDI-8942] Validate merge mode based on payload class and merger strategy only for table versions 8 or higher
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableConfig.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/util/SparkConfigUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamer.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
Labels: size:M

#12711 [HUDI-8607] Test concurrent indexing with multi writer scenarios
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/JavaTestUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/HoodieDeltaStreamerTestBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:M

#12748 [HUDI-8948] Use filtered query filters in Partition Stats Index pruning
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/PartitionStatsIndexSupport.scala
Labels: size:XS

#12746 [HUDI-8947] Fixing log file naming with MOR table writes using table version 6
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAppendHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergeHandleWithChangeLog.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/testutils/providers/HoodieMetaClientProvider.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandleWithChangeLog.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandleWithChangeLog.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/FunctionalTestHarness.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/table/log/HoodieLogFormatWriter.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/TestHoodieMergeOnReadTable.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeModeCommitTimeOrdering.scala
Labels: size:L
