Repository apache/hudi, pull requests merged in 2025-09, with the labels that each got.

#13817 [HUDI-9779] Use HoodieAvroIndexedRecord for records of error table
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BaseErrorTableWriter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamerSchemaEvolutionBase.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestJsonKafkaSource.java
Labels: size:S

#13787 [HUDI-9767] Upstream Trino Changes
  hudi-trino-plugin/pom.xml
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiConfig.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiConnectorFactory.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiErrorCode.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiModule.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiSessionProperties.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiSplit.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiSplitManager.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiSplitSource.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiTableHandle.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/HudiUtil.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/cache/HudiCacheKeyProvider.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/partition/HiveHudiPartitionInfo.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/partition/HudiPartitionInfoLoader.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/query/HudiDirectoryLister.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/query/HudiSnapshotDirectoryLister.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/query/index/HudiColumnStatsIndexSupport.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/query/index/HudiPartitionStatsIndexSupport.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/query/index/HudiRecordLevelIndexSupport.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/query/index/HudiSecondaryIndexSupport.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/query/index/IndexSupportFactory.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/split/HudiBackgroundSplitLoader.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/split/HudiSplitFactory.java
  hudi-trino-plugin/src/main/java/io/trino/plugin/hudi/util/HudiAvroSerializer.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/HudiQueryRunner.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/HudiUtilTest.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/SessionBuilder.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/TestHudiAlluxioCacheFileOperations.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/TestHudiAlluxioCachingSmokeTest.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/TestHudiConfig.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/TestHudiMemoryCacheFileOperations.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/TestHudiNoCacheFileOperations.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/TestHudiSmokeTest.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/split/TestHudiSplitFactory.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java
  hudi-trino-plugin/src/test/java/io/trino/plugin/hudi/util/FileOperationUtils.java
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_cow_pt_table_with_field_names_in_caps.md
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_cow_pt_table_with_field_names_in_caps.zip
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_cow_table_with_field_names_in_caps.md
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_cow_table_with_field_names_in_caps.zip
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_cow_table_with_multi_keys_and_field_names_in_caps.md
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_cow_table_with_multi_keys_and_field_names_in_caps.zip
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_mor_table_with_field_names_in_caps.md
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_mor_table_with_field_names_in_caps.zip
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_non_extractable_partition_path.md
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_non_extractable_partition_path.zip
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_non_part_mor.md
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_non_part_mor.zip
Labels: size:XL

#13818 [MINOR] Remove unnecessary hudi_v6_composite_key.zip
  hudi-trino-plugin/src/test/resources/hudi-testing-data/hudi_v6_composite_key.zip
Labels: size:XS

#13761 [HUDI-9703] Support Regex Config in RunClusteringProcedure
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/RunClusteringProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/procedure/TestClusteringProcedure.scala
Labels: size:S

#13806 [HUDI-9762] Avoid file renaming during multiple mini-batches flink wr…
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/WriteStatus.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieAbstractMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/HoodieFlinkWriteClient.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkCreateHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkFileGroupReaderBasedIncrementalMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkFileGroupReaderBasedMergeAndReplaceHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkFileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkIncrementalConcatHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkIncrementalMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkIncrementalMergeHandleWithChangeLog.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeAndReplaceHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkWriteHandleFactory.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/MergeHandleUtils.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/WriteStatMerger.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/WriteStatusMerger.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/util/TestWriteStatusMerger.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/StreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/event/WriteMetadataEvent.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/TestStreamWriteOperatorCoordinator.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/MockCoordinatorExecutor.java
Labels: size:XL

#13833 [MINOR] Updating RFC status and making it easier to read
  rfc/README.md
Labels: size:M

#13837 [HUDI-9784] Adding mysql binlog validation for debezium
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/debezium/MysqlDebeziumSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/debezium/TestMysqlDebeziumSource.java
Labels: size:S

#13838 [HUDI-9785] Fix data loss problem for incremental query on table with…
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieCommitMetadata.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/format/TestInputFormat.java
Labels: size:S

#13852 [HUDI-9794] Convert the avro into file bytes in LegacyArchivedMetaEntryReader to keep forward compatibility
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: version-compatibility, version-upgrade, size:M

#13854 Revert "[HUDI-9794] Convert the avro into file bytes in LegacyArchivedMetaEntryReader to keep forward compatibility"
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/timeline/versioning/v1/TimelineArchiverV1.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: size:M

#13844 [HUDI-9790] Add record validation in HoodieStreamerUtils createHoodieRecords for error table writing
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerUtils.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/streamer/TestHoodieStreamerUtils.java
Labels: size:M, release-1.1.0

#13825 [MINOR] add getter method for metadataConfig
  hudi-common/src/main/java/org/apache/hudi/BaseHoodieTableFileIndex.java
  hudi-common/src/test/java/org/apache/hudi/BaseHoodieTableFileIndexTest.java
Labels: size:S

#13836 [HUDI-9782] Add audit logging scaffolding to storage based LP
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/S3StorageLockClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/transaction/lock/TestS3StorageLockClient.java
  hudi-aws/src/test/java/org/apache/hudi/aws/transaction/lock/TestS3StorageLockClientAuditOperations.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/StorageBasedLockProvider.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/StorageLockClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/audit/AuditOperationState.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/audit/AuditService.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/audit/AuditServiceFactory.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/TestStorageBasedLockProvider.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/lock/audit/TestAuditServiceFactory.java
  hudi-gcp/src/main/java/org/apache/hudi/gcp/transaction/lock/GCSStorageLockClient.java
  hudi-gcp/src/test/java/org/apache/hudi/gcp/transaction/lock/TestGCSStorageLockClientAuditOperations.java
Labels: size:XL

#13862 [HUDI-9794] Convert the avro into file bytes in LegacyArchivedMetaEntryReader to keep forward compatibility
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/LegacyArchivedMetaEntryReader.java
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroUtils.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/MetadataConversionUtils.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: size:M

#13855 [HUDI-9786] Handle getProgress for log files only splits in Record Reader
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HoodieFileGroupReaderBasedRecordReader.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHiveHoodieReaderContext.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieFileGroupReaderBasedRecordReader.java
Labels: size:M

#13874 [HUDI-9794] File Avro Bytes Flakiness fix with graceful handling
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: size:M

#13857 [Website][Minor] - Blog links redirect should open new tab
  website/src/theme/BlogPostItem/BlogPostBox.js
Labels: docs, size:XS

#13903 [MINOR] Enable HFile block cache by default
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
Labels: size:XS

#13905 (docs) Removed FAQ from Docs starting from 1.0.0
  website/sidebars.js
  website/versioned_sidebars/version-1.0.0-sidebars.json
  website/versioned_sidebars/version-1.0.1-sidebars.json
  website/versioned_sidebars/version-1.0.2-sidebars.json
Labels: docs, size:S

#13907 chore: update issue templates post JIRA migration
  .github/ISSUE_TEMPLATE/SUPPORT_REQUEST.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/hudi_bug.yml
  .github/ISSUE_TEMPLATE/hudi_community_support.yml
  .github/ISSUE_TEMPLATE/hudi_feature.yml
  .github/ISSUE_TEMPLATE/hudi_improvement.yml
Labels: size:L

#13921 docs: Update contribution guide with changes due to JIRA to GH issues migration
  website/community/get-involved.mdx
  website/contribute/developer-setup.md
  website/contribute/how-to-contribute.md
  website/docs/performance.md
Labels: docs, size:L

#13926 fix: make sure blog links redirect opens a new tab
  website/src/theme/BlogPostItem/BlogPostBox.js
Labels: docs, size:S

#13583 [HUDI-9611] Metadata writer tries to initialize invalid partitions
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieWriteHandle.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
  hudi-common/src/main/java/org/apache/hudi/metadata/MetadataPartitionType.java
  hudi-common/src/test/java/org/apache/hudi/metadata/TestMetadataPartitionType.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/feature/index/TestSecondaryIndex.scala
Labels: size:S, release-1.1.0

#13860 perf(spark): Write handle perf fix for prepending meta fields
  hudi-common/src/main/java/org/apache/hudi/avro/JoinedGenericRecord.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieAvroIndexedRecord.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestHoodieAvroUtils.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/io/TestMergeHandle.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/execution/benchmark/CreateHandleBenchmark.scala
Labels: size:L

#13934 [MINOR] Incremental and Time Travel Query Testing
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
Labels: size:L, release-1.1.0

#13796 [HUDI-9778] Remove HoodieRecord wrapper from MDT reads
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/index/SparkMetadataTableRecordIndex.java
  hudi-common/src/main/java/org/apache/hudi/common/util/HoodieDataUtils.java
  hudi-common/src/main/java/org/apache/hudi/metadata/BaseTableMetadata.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadata.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/RecordLevelIndexSupport.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/SecondaryIndexSupport.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestHoodieDataUtils.scala
Labels: size:M, release-1.1.0

#13944 docs(cli): fix wget output flag (-O) in S3 instructions and “fired up via” wording
  website/versioned_docs/version-1.0.2/cli.md
Labels: docs, size:XS

#13946 perf: Increase HFile prefetch threshold
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieMetadataConfig.java
Labels: size:XS

#13797 [HUDI-9777] Avoid redundant file length fetch in HoodieNativeHFileReader
  hudi-common/src/main/java/org/apache/hudi/avro/HoodieAvroReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HFileReaderFactory.java
  hudi-common/src/main/java/org/apache/hudi/io/storage/HoodieFileReaderFactory.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/io/hadoop/HoodieAvroFileReaderFactory.java
Labels: size:M, release-1.1.0

#13943 fix: Issue when reading a Hudi table with nested partition fields - resulting to failure
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieSparkUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestNestedPartitionPathSchema.scala
Labels: size:M, release-1.1.0

#12960 [HUDI-8934] [RFC-87] Avro elimination in Flink writer
  rfc/rfc-87/rfc-87.md
Labels: rfc, size:L, release-1.1.0

#13971 refactor: Adapt delete handling with DeleteContext for HoodieFlinkRecord
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/client/model/HoodieFlinkRecord.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/format/FlinkRecordContext.java
Labels: size:S

#13985 chore: Updated Ask AI lookup
  website/docusaurus.config.js
Labels: docs, size:S

#13986 docs: Change some noisy WARN logs to INFO/DEBUG
  README.md
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/index/ScheduleIndexActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/block/HoodieLogBlock.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/buffer/PositionBasedFileGroupRecordBuffer.java
  hudi-hadoop-common/src/main/java/org/apache/hudi/common/config/DFSPropertiesConfiguration.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
Labels: size:S

#13984 feat: Do not spill for file group reader during Flink COW writing
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkFileGroupReaderBasedMergeHandle.java
Labels: size:S

#13977 fix: Fix the buffer overflow issue for hfile writer
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileDataBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileFileInfoBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileLeafIndexBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileMetaBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileMetaIndexBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileRootIndexBlock.java
  hudi-io/src/main/java/org/apache/hudi/io/hfile/HFileWriterImpl.java
  hudi-io/src/test/java/org/apache/hudi/io/hfile/TestHFileWriter.java
Labels: size:L, release-1.1.0

#13981 fix: Merge Into Command updates cause runtime issues
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark3-common/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
  hudi-spark-datasource/hudi-spark4-common/src/main/scala/org/apache/spark/sql/hudi/command/MergeIntoHoodieTableCommand.scala
Labels: size:M

#14002 chore: Remove validation of issue link on fix PRs
  scripts/pr_compliance.py
Labels: size:S

#13998 fix: Converting ordering value with timestamp millis type properly fo…
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/util/OrderingValueEngineTypeConverter.java
  hudi-client/hudi-flink-client/src/test/java/org/apache/hudi/util/TestOrderingValueEngineTypeConverter.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/AvroConversionUtils.scala
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRecordContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/BaseSparkInternalRowReaderContext.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/OrderingValueEngineTypeConverter.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaUtils.java
Labels: size:M

#13999 fix: Update AMD64 Docker demo images to use latest Hudi version
  docker/build_docker_images.sh
  docker/compose/docker-compose_hadoop334_hive313_spark353_amd64.yml
  docker/hoodie/hadoop/sparkadhoc/Dockerfile
  docker/hoodie/hadoop/sparkadhoc/adhoc.sh
  docker/setup_demo.sh
  docker/stop_demo.sh
Labels: size:L

#14000 perf: Lazily convert payload records to byte array format
  hudi-aws/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/AWSDmsAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/BaseAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/DefaultHoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/EventTimeAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/HoodieRecordPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteNonDefaultsWithLatestAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/OverwriteWithLatestAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/PartialUpdateAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/model/debezium/AbstractDebeziumAvroPayload.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestPartialUpdateAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/model/debezium/TestPostgresDebeziumAvroPayload.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestUpdateProcessor.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/reader/HoodieRecordTestPayload.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/DataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/payload/ExpressionPayload.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/model/TestHoodieRecordSerialization.scala
Labels: size:M, release-1.1.0

#14010 refactor: Set merge memory for flink COW write path properly
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/FileGroupReaderBasedMergeHandle.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/io/FlinkFileGroupReaderBasedMergeHandle.java
Labels: size:S, release-1.1.0

#14019 perf: Remove the eager loading of CompletionTimeQueryView
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/timeline/TestCompletionTimeQueryView.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/TimelineFactory.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v1/TimelineV1Factory.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/CompletionTimeQueryViewV2.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/TimelineV2Factory.java
  hudi-common/src/test/java/org/apache/hudi/tableformat/TestTimelineFactory.java
Labels: size:S
