Repository apache/hudi, pull requests merged in 2025-03, with the labels that each got.

#12897 [HUDI-9093] Fix the HoodieClusteringJob duplicate parameter alias
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieClusteringJob.java
Labels: size:XS

#12904 [DOCS] Added blog for record mergers in hudi
  content/assets/images/blog/2025-03-03-record-mergers-in-apache-hudi.png
  website/blog/2025-03-03-record-mergers-in-hudi.mdx
Labels: docs, size:M

#12911 [HUDI-9079] Log the exception message properly to handle the "default" partition
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToFiveUpgradeHandler.java
Labels: size:S

#12912 [DOCS] Fix image location for record merger blog
  website/static/assets/images/blog/2025-03-03-record-mergers-in-apache-hudi.png
Labels: docs, size:XS

#12915 [HUDI-8826] Extend MIT partial update test
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestMergeIntoTable.scala
Labels: size:S

#12914 [HUDI-8745] Add tests for record index and secondary index with insert dups policy
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestInsertDedupPolicy.scala
Labels: size:S

#12874 [HUDI-9067] Fixing num spark tasks for clean action
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/common/HoodieSparkEngineContext.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/common/TestHoodieSparkEngineContext.java
Labels: size:S

#12882 [HUDI-5387] Add bundle validation for hudi-cli-bundle
  packaging/bundle-validation/ci_run.sh
  packaging/bundle-validation/cli/commands.txt
  packaging/bundle-validation/validate.sh
Labels: size:S

#12781 [HUDI-8219] Add concurrent schema evolution conflict detection
  .gitignore
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/ConcurrentSchemaEvolutionTableSchemaGetter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SchemaConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/SimpleSchemaConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/utils/TransactionUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/HoodieTable.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestConcurrentSchemaEvolutionTableSchemaGetter.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/client/transaction/TestSimpleSchemaConflictResolutionStrategy.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/TestBaseHoodieTable.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/TestHoodieTable.java
  hudi-common/src/main/java/org/apache/hudi/avro/AvroSchemaComparatorForSchemaEvolution.java
  hudi-common/src/main/java/org/apache/hudi/common/table/TableSchemaResolver.java
  hudi-common/src/main/java/org/apache/hudi/exception/HoodieSchemaEvolutionConflictException.java
  hudi-common/src/test/java/org/apache/hudi/avro/TestAvroSchemaComparatorForSchemaEvolution.java
  hudi-common/src/test/java/org/apache/hudi/common/model/TestHoodieReplaceCommitMetadata.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/FileCreateUtils.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestDataGenerator.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-common/src/test/resources/avro-schema-evo/schema-allshapes-A.txt
  hudi-common/src/test/resources/avro-schema-evo/schema-allshapes-B.txt
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestTableSchemaResolver.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieCommonTestHarness.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
Labels: size:XL

#12888 [HUDI-9030] Compatibility fixes for table version 6 with 1.0
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/ScheduleCompactionActionExecutor.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/ListingBasedRollbackStrategy.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/MarkerBasedRollbackStrategy.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/AbstractHoodieLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordScanner.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestStreamerUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieReaderConfig.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/AbstractRealtimeRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/realtime/HoodieCombineRealtimeRecordReader.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/IncrementalRelationV1.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/MergeOnReadIncrementalRelationV1.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/helpers/QueryRunner.java
Labels: size:L

#12917 [MINOR] Fix generating file id with wrong bucket index
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkBucketIndexPartitioner.java
Labels: size:XS

#12916 [HUDI-9115] Deprecate Hudi CLI script
  hudi-cli/hudi-cli.sh
  hudi-integ-test/src/test/java/org/apache/hudi/integ/ITTestHoodieDemo.java
  hudi-integ-test/src/test/java/org/apache/hudi/integ/command/ITTestHoodieSyncCommand.java
Labels: size:S

#12921 [MINOR] Add retries and logs to merging Jacoco execution data files
  scripts/jacoco/merge_jacoco_exec_files.sh
Labels: size:S

#12913 [HUDI-9057] Fixing ClassNotFound issue w/ ProtoBufSchemaProvider
  hudi-utilities/pom.xml
  packaging/hudi-utilities-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
  pom.xml
Labels: size:S

#12909 [HUDI-9086] Re-enable flaky tests and fixing spark context not shutting down
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestDataSourceUtils.java
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hive/TestHiveClientUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieDataSourceHelper.scala
Labels: size:S

#12924 [HUDI-9123][RFC-91] Claim RFC-91 for storage-based lock provider using conditional writes
  rfc/README.md
Labels: size:XS

#12695 [HUDI-8697] Revisit TestHDFSParquetImporter and TestHoodieSnapshotCopier
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/HDFSParquetImportCommand.java
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/SparkMain.java
  hudi-cli/src/test/java/org/apache/hudi/cli/integ/ITTestHDFSParquetImportCommand.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HDFSParquetImporter.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/HoodieSnapshotCopier.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHDFSParquetImporter.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/functional/TestHoodieSnapshotCopier.java
Labels: size:XL

#12928 [Docs]Update invalid link to doris hudi catalog
  website/docs/sql_queries.md
  website/versioned_docs/version-0.10.0/query_engine_setup.md
  website/versioned_docs/version-0.12.2/query_engine_setup.md
  website/versioned_docs/version-0.12.3/query_engine_setup.md
  website/versioned_docs/version-0.13.0/query_engine_setup.md
  website/versioned_docs/version-0.13.1/querying_data.md
  website/versioned_docs/version-0.14.0/sql_queries.md
  website/versioned_docs/version-0.14.1/sql_queries.md
  website/versioned_docs/version-0.15.0/sql_queries.md
  website/versioned_docs/version-1.0.0/sql_queries.md
  website/versioned_docs/version-1.0.1/sql_queries.md
Labels: docs, size:S

#12942 [MINOR] Skip merging Jacoco execution data file from Azure Job 1 FT
  azure-pipelines-20230430.yml
Labels: size:XS

#12947 [Fix](opt)fix the error words in hudi_stack.md
  website/versioned_docs/version-1.0.1/hudi_stack.md
Labels: docs, size:XS

#12943 [MINOR] Fix cleaner config compatibility with older releases
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieCleanConfig.java
Labels: size:S

#12925 [HUDI-9125] Pass compaction/merge related props to HoodieBaseFileGroupRecordBuffer
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodiePayloadConfig.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/io/HoodieSparkFileGroupReaderBasedMergeHandle.java
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/ExternalSpillableMap.java
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/testutils/SparkDatasetTestUtils.java
Labels: size:S

#12923 [HUDI-9116] Update Hudi CLI public documentation
  website/docs/cli.md
  website/versioned_docs/version-1.0.0/cli.md
  website/versioned_docs/version-1.0.1/cli.md
Labels: docs, size:S

#12929 [HUDI-9132] Avoid empty string row key for delete and update operations
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestDeleteTable.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestUpdateTable.scala
Labels: size:M

#12873 [HUDI-9068] Fix cloudwatch metrics
  hudi-aws/src/main/java/org/apache/hudi/aws/cloudwatch/CloudWatchReporter.java
  hudi-aws/src/test/java/org/apache/hudi/aws/cloudwatch/TestCloudWatchReporter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-java-client/src/test/java/org/apache/hudi/client/TestJavaHoodieBackedMetadata.java
Labels: size:S

#12885 [HUDI-9141] Handle the case that dbName is empty in HoodieFileIndex
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/catalyst/catalog/HoodieCatalogTable.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestHoodieFileIndex.scala
Labels: size:S

#12937 [MINOR] Remove storage instance variable from HoodieIngestionMetrics
  hudi-utilities/src/main/java/org/apache/hudi/utilities/ingestion/HoodieIngestionMetrics.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/HoodieStreamerMetrics.java
Labels: size:S

#12884 [HUDI-8990][RFC-89] Partition Level Bucket Index
  rfc/rfc-89/archive.jpg
  rfc/rfc-89/dry-run.jpg
  rfc/rfc-89/rescale.jpg
  rfc/rfc-89/rfc-89.md
  rfc/rfc-89/workflow.jpg
Labels: size:L

#12959 [HUDI-7803] Fix bundle validation on Flink 1.18
  .github/workflows/bot.yml
  packaging/bundle-validation/validate.sh
Labels: size:XS

#12965 [HUDI-9020] Remove hadoop deps from hudi-common
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieReaderConfig.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
Labels: size:S

#12956 [HUDI-9166] Static cleanup method that doesn't hold references to DiskMap instances
  hudi-common/src/main/java/org/apache/hudi/common/util/collection/DiskMap.java
Labels: size:S

#12961 [HUDI-9166] Introduce schema pruning for delete-record
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/DeleteHoodieTableCommand.scala
Labels: size:S

#12968 [HUDI-8990][RFC-89] Correcting ambiguity in DDL expression
  rfc/rfc-89/rfc-89.md
Labels: size:XS

#12976 [HUDI-9173] Fix issue with inflight compaction and global index lookup
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/io/HoodieMergedReadHandle.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableCompaction.java
Labels: size:S, release-1.0.2

#12981 [HUDI-9186] Remove tableState from HoodieFileGroupReaderBasedParquetFileFormat constructor
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieHadoopFsRelationFactory.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/HoodieFileGroupReaderBasedParquetFileFormat.scala
Labels: size:S

#12969 [HUDI-9168] Refactor hudi-client-common to not import hudi-aws
  hudi-aws/pom.xml
  hudi-aws/src/main/java/org/apache/hudi/aws/metrics/cloudwatch/CloudWatchMetricsReporter.java
  hudi-aws/src/main/java/org/apache/hudi/aws/metrics/cloudwatch/CloudWatchReporter.java
  hudi-aws/src/main/java/org/apache/hudi/aws/sync/AWSGlueCatalogSyncClient.java
  hudi-aws/src/main/java/org/apache/hudi/aws/transaction/lock/DynamoDBBasedImplicitPartitionKeyLockProvider.java
  hudi-aws/src/main/java/org/apache/hudi/aws/utils/S3Utils.java
  hudi-aws/src/test/java/org/apache/hudi/aws/metrics/cloudwatch/TestCloudWatchMetricsReporter.java
  hudi-aws/src/test/java/org/apache/hudi/aws/metrics/cloudwatch/TestCloudWatchReporter.java
  hudi-aws/src/test/java/org/apache/hudi/aws/utils/TestS3Utils.java
  hudi-client/hudi-client-common/pom.xml
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/ZookeeperBasedImplicitBasePathLockProvider.java
  hudi-common/src/main/java/org/apache/hudi/common/fs/FSUtils.java
  hudi-common/src/main/java/org/apache/hudi/metrics/MetricsReporterFactory.java
  hudi-common/src/test/java/org/apache/hudi/metrics/TestMetricsReporterFactory.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/fs/TestFSUtils.java
Labels: size:M, release-1.0.2

#12953 [HUDI-8345] Delete partition stats index for a partition that is deleted
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestTable.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Labels: size:S, release-1.0.2

#12668 [HUDI-7375] Enable testLogReaderWithDifferentVersionsOfDeleteBlocks
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/functional/TestHoodieLogFormat.java
Labels: size:XS

#12977 [HUDI-9175] Remove the unnecessary MDT metadata check for col_stats index config update
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/BaseHoodieWriteClient.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/HoodieColumnStatsIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/commit/BaseCommitActionExecutor.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/table/action/commit/BaseFlinkCommitActionExecutor.java
  hudi-common/src/main/java/org/apache/hudi/common/model/ActionType.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/util/FlinkWriteClients.java
Labels: size:S, release-1.0.2

#12926 [HUDI-9127] Fixing completion time generation to honor timezone from table config
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/TestSparkRDDWriteClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/HoodieInstantTimeGenerator.java
  hudi-common/src/main/java/org/apache/hudi/common/table/timeline/versioning/v2/ActiveTimelineV2.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
Labels: size:S, release-1.0.2

#12980 [DOCS] Weekly round of blog additions
  website/blog/2025-03-13-hudi-on-dbr.mdx
  website/blog/2025-03-13-lightning-fast-analytics.mdx
  website/static/assets/images/blog/hudi-aws-dbr.png
  website/static/assets/images/blog/lightning-fast-analytics.jpeg
  website/static/assets/images/video_blogs/2025-03-14-hudi-mdt-schema.png
  website/videoBlog/2025-03-14-metadata-and-schema-of-hudi-table.mdx
Labels: docs, size:S

#12970 [HUDI-9170] Fixing schema projection with file group reader
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestHoodieDatasetBulkInsertHelper.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/testutils/DataSourceTestUtils.java
  hudi-spark-datasource/hudi-spark/src/test/resources/exampleEvolvedSchema.txt
  hudi-spark-datasource/hudi-spark/src/test/resources/exampleSchema.txt
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestCOWDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestMORDataSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSparkDataSource.scala
Labels: size:L, release-1.0.2

#12987 [HUDI-9083] Fixing flakiness with multi writer test
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/TestHoodieClientMultiWriter.java
Labels: size:XS, release-1.0.2

#12994 [HUDI-9196] Disable flaky tests on Flink
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
Labels: size:XS

#13003 [DOCS] Fix image path for recent blog
  website/blog/2025-03-13-hudi-on-dbr.mdx
Labels: docs, size:XS

#12948 [HUDI-9013] Add backwards compatible MDT writer support and reader support with tbl v6
  hudi-cli/src/main/java/org/apache/hudi/cli/commands/MetadataCommand.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriterTableVersionSix.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metrics/HoodieMetrics.java
  hudi-client/hudi-flink-client/src/main/java/org/apache/hudi/metadata/FlinkHoodieBackedTableMetadataWriter.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/SparkRDDWriteClient.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkHoodieBackedTableMetadataWriterTableVersionSix.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/metadata/SparkMetadataWriterFactory.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/HoodieSparkTable.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedTableMetadata.java
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/client/functional/TestHoodieMetadataBase.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/testutils/HoodieTestUtils.java
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/CreateMetadataTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/InitMetadataTableProcedure.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/functional/TestHoodieSparkMergeOnReadTableRollback.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/RecordLevelIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestRecordLevelIndexTableVersionSix.scala
Labels: size:L, release-1.0.2

#12991 [HUDI-9120] Fix merge mode inference for table version 6 in file group reader
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReaderSchemaHandler.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/common/TestSqlConf.scala
Labels: size:S, release-1.0.2

#12935 [HUDI-9120] Enable File Group reader by default for table version 6
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/compact/HoodieCompactor.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/client/clustering/run/strategy/MultipleSparkJobExecutionStrategy.java
  hudi-common/src/main/java/org/apache/hudi/common/config/HoodieReaderConfig.java
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieReaderConfig.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/utils/HoodieInputFormatUtils.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/DefaultSource.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/TestHoodieSparkSqlWriter.scala
Labels: size:M, release-1.0.2

#13014 [HUDI-9207] Spark Insert Overwrite Support Row Writer
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/HoodieDatasetBulkInsertHelper.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: size:S

#12843 [HUDI-9022] Handle records with custom delete markers in FG reader
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/SparkFileFormatInternalRowReaderContext.scala
  hudi-client/hudi-spark-client/src/test/java/org/apache/hudi/testutils/SparkClientFunctionalTestHarness.java
  hudi-common/src/main/java/org/apache/hudi/common/engine/HoodieReaderContext.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/log/HoodieMergedLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupReaderSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/KeyBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedSchemaHandler.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/UnmergedFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestFileGroupRecordBuffer.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderBase.java
  hudi-common/src/test/java/org/apache/hudi/common/table/read/TestHoodieFileGroupRecordBuffer.java
  hudi-hadoop-mr/src/main/java/org/apache/hudi/hadoop/HiveHoodieReaderContext.java
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/execution/datasources/parquet/TestSparkFileFormatInternalRowReaderContext.scala
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/TestPositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/common/table/read/TestHoodieFileGroupReaderOnSpark.scala
Labels: size:XL, release-1.0.2

#13025 [HUDI-9215] Set partitionColumnsWithKeyGenerator based on table version
  hudi-client/hudi-spark-client/src/main/scala/org/apache/hudi/util/SparkKeyGenUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/java/org/apache/hudi/cli/BootstrapExecutorUtils.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/BootstrapExecutor.java
  hudi-utilities/src/main/java/org/apache/hudi/utilities/streamer/StreamSync.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/deltastreamer/TestHoodieDeltaStreamer.java
Labels: size:S

#13018 [HUDI-9211] Fix bug with config in DataHubSyncTool
  hudi-sync/hudi-datahub-sync/pom.xml
  hudi-sync/hudi-datahub-sync/src/main/java/org/apache/hudi/sync/datahub/DataHubTableProperties.java
  hudi-sync/hudi-datahub-sync/src/test/java/org/apache/hudi/sync/datahub/TestDataHubTableProperties.java
Labels: size:S, release-1.0.2

#12927 [HUDI-9123][RFC-91] Add RFC for storage based lock provider using conditional writes.
  rfc/rfc-91/dfs-locking-diagram.png
  rfc/rfc-91/rfc-91.md
Labels: size:M

#13026 [HUDI-9216] Fallback to spark.catalog.currentDatabase if tableConfig.databaseName is null or empty
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieFileIndex.scala
  hudi-spark-datasource/hudi-spark-common/src/test/scala/org/apache/spark/sql/hudi/TestHoodieFileIndex.scala
Labels: size:S

#13029 [HUDI-9220] Cannot find write operation type if run inline log compaction
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
Labels: size:XS

#13031 [MINOR] Improve CI to parallelize tests more and reduce completion time
  .github/workflows/bot.yml
  azure-pipelines-20230430.yml
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/HoodieSparkFunctionalTestSuiteA.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/HoodieSparkFunctionalTestSuiteB.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/functional/TestNewHoodieParquetFileFormat.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/ColumnStatIndexTestBase.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestPartitionStatsIndex.scala
  pom.xml
Labels: size:L

#13032 [MINOR] Fix flaky test testCreateNewInstantTimes
  hudi-hadoop-common/src/test/java/org/apache/hudi/common/table/TestHoodieTableMetaClient.java
Labels: size:XS, release-1.0.2

#13033 [HUDI-9216] Ignore validation of empty databaseName in HoodieTableMetaClient
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieHFileInputFormat.java
  hudi-hadoop-mr/src/test/java/org/apache/hudi/hadoop/TestHoodieParquetInputFormat.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark-common/src/test/java/org/apache/hudi/TestHoodieWriterUtils.java
Labels: size:S, release-1.0.2

#13023 [MINOR]Follow up HUDI-8803, optimize vectorized reader by cache 'batchIdxField'
  hudi-spark-datasource/hudi-spark3-common/src/main/java/org/apache/spark/sql/execution/datasources/parquet/Spark3HoodieVectorizedParquetRecordReader.java
Labels: size:XS

#13039 [MINOR] Use ConfigUtils to handle defaults for all Zookeeper lock provider configs
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/client/transaction/lock/BaseZookeeperBasedLockProvider.java
Labels: size:S

#13027 [HUDI-9205] Refactor Flink tests to avoid sleeping for data results
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/ITTestDataStreamWrite.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestSchemaEvolution.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/FlinkMiniCluster.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/factory/CollectSinkTableFactory.java
  hudi-io/src/main/java/org/apache/hudi/storage/HoodieStorage.java
  packaging/bundle-validation/flink/insert.sql
  packaging/bundle-validation/validate.sh
Labels: size:L

#13041 [HUDI-9227] Fix bulk insert overwrite after a failed insert
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTable.scala
Labels: spark-sql, stability, size:S

#13035 [HUDI-9221] Fix tests in TestHoodieBackedMetadata after new default indexes enabled
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/client/functional/TestHoodieBackedMetadata.java
Labels: size:S

#13045 [HUDI-9233] Handle empty table edge case for col stats initialization
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/metadata/HoodieBackedTableMetadataWriter.java
  hudi-common/src/main/java/org/apache/hudi/metadata/HoodieTableMetadataUtil.java
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestColumnStatsIndex.scala
Labels: size:S, release-1.0.2

#12962 [HUDI-9167] Remove redundant classes in hudi-utilities-slim-bundle
  packaging/hudi-spark-bundle/pom.xml
  packaging/hudi-utilities-slim-bundle/pom.xml
Labels: size:S, release-1.0.2

#13037 [HUDI-9042] Support `TimestampType.DATE_STRING` by `RowDataKeyGen`
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/keygen/TimestampBasedAvroKeyGenerator.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bulk/RowDataKeyGen.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/bulk/TestRowDataKeyGen.java
  rfc/README.md
Labels: size:S

#13048 [HUDI-9238] Fix bug with HudiIncrSource when source is table version 6
  hudi-utilities/src/main/java/org/apache/hudi/utilities/sources/HoodieIncrSource.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/sources/TestHoodieIncrSource.java
Labels: size:M

#13050 [HUDI-9239]Fix the bug of Spark Cache not releasing cleanly
  hudi-common/src/main/java/org/apache/hudi/common/data/HoodieData.java
Labels: size:XS

#13030 [HUDI-9133] Fallback to legacy schema fetching in case of IllegalAccessError from schema registry client
  hudi-utilities/src/main/java/org/apache/hudi/utilities/schema/SchemaRegistryProvider.java
  hudi-utilities/src/test/java/org/apache/hudi/utilities/schema/TestSchemaRegistryProvider.java
Labels: size:S, release-1.0.2

#13053 [HUDI-9240] Bump spark 35 version to 3.5.5
  pom.xml
Labels: size:XS

#13044 [HUDI-9231]Show complete DAG for one single query in spark web ui while inserting into hudi table
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/analysis/HoodieAnalysis.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableAsSelectCommand.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/InsertIntoHoodieTableCommand.scala
Labels: size:S

#13046 [HUDI-8409] Fixing merge mode config during upgrade and downgrade from version 7 to 8 and back
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/DowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/EightToSevenDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FiveToFourDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/FourToThreeDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/OneToZeroDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToEightUpgradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SevenToSixDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/SixToFiveDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/ThreeToTwoDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/TwoToOneDowngradeHandler.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/upgrade/UpgradeDowngrade.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestEightToSevenDowngradeHandler.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/table/upgrade/TestSevenToEightUpgradeHandler.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieWriterUtils.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/hudi/functional/TestSevenToEightUpgrade.scala
Labels: size:L, release-1.0.2

#13047 [HUDI-8635] Support numWrites metric for compaction
  hudi-common/src/main/java/org/apache/hudi/common/table/log/BaseHoodieLogRecordReader.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/FileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/HoodieFileGroupRecordBuffer.java
  hudi-common/src/main/java/org/apache/hudi/common/table/read/PositionBasedFileGroupRecordBuffer.java
  hudi-spark-datasource/hudi-spark/src/test/java/org/apache/hudi/table/action/compact/TestHoodieCompactor.java
Labels: size:S

#13017 [HUDI-8990] Partition Level Bucket Index
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieIndexConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieLayoutConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/config/HoodieWriteConfig.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/HoodieSimpleBucketIndex.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/partition/NumBucketsFunction.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/partition/PartitionBucketIndexCalculator.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/partition/PartitionBucketIndexRule.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/partition/PartitionBucketIndexUtils.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/partition/RegexRuleEngine.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/index/bucket/partition/RuleEngine.java
  hudi-client/hudi-client-common/src/main/java/org/apache/hudi/table/action/rollback/BaseRollbackActionExecutor.java
  hudi-client/hudi-client-common/src/test/java/org/apache/hudi/index/bucket/TestPartitionBucketIndexCalculator.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/BucketIndexBulkInsertPartitionerWithRows.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/execution/bulkinsert/RDDSimpleBucketBulkInsertPartitioner.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/BucketBulkInsertDataInternalWriterHelper.java
  hudi-client/hudi-spark-client/src/main/java/org/apache/hudi/table/action/commit/SparkPartitionBucketIndexPartitioner.java
  hudi-client/hudi-spark-client/src/main/scala/org/apache/spark/sql/BucketPartitionUtils.scala
  hudi-common/src/main/java/org/apache/hudi/common/model/PartitionBucketIndexHashingConfig.java
  hudi-common/src/main/java/org/apache/hudi/common/model/WriteOperationType.java
  hudi-common/src/main/java/org/apache/hudi/common/table/HoodieTableMetaClient.java
  hudi-common/src/main/java/org/apache/hudi/common/util/hash/BucketIndexUtil.java
  hudi-common/src/test/java/org/apache/hudi/common/util/hash/TestBucketIndexUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/FlinkOptions.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsInference.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/configuration/OptionsResolver.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketBulkInsertWriterHelper.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/BucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/bucket/RowDataBucketStreamWriteFunction.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/partitioner/BucketIndexPartitioner.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/sink/utils/Pipelines.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/HoodieTableSink.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieCatalogUtil.java
  hudi-flink-datasource/hudi-flink/src/main/java/org/apache/hudi/table/catalog/HoodieHiveCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/sink/utils/BulkInsertFunctionWrapper.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/ITTestHoodieDataSource.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/table/catalog/TestHoodieCatalog.java
  hudi-flink-datasource/hudi-flink/src/test/java/org/apache/hudi/utils/TestConfigurations.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/BaseDatasetBulkInsertCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/java/org/apache/hudi/commit/DatasetBucketRescaleCommitActionExecutor.java
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/hudi/HoodieSparkSqlWriter.scala
  hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/ProvidesHoodieConfig.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/HoodieProcedures.scala
  hudi-spark-datasource/hudi-spark/src/main/scala/org/apache/spark/sql/hudi/command/procedures/PartitionBucketIndexManager.scala
  hudi-spark-datasource/hudi-spark/src/test/scala/org/apache/spark/sql/hudi/dml/TestInsertTableWithPartitionBucketIndex.scala
Labels: size:XL

#13062 [BLOG] Add New Community Blog for Amazon
  website/blog/2025-03-31-amazon-hudi.md
  website/static/assets/images/blog/amz-1200x600.jpg
  website/static/assets/images/blog/fig1_amz.png
  website/static/assets/images/blog/fig2_amz.png
  website/static/assets/images/blog/fig3_amz.png
  website/static/assets/images/blog/fig4_amz.png
  website/static/assets/images/blog/fig5_amz.png
  website/static/assets/images/blog/fig6_amz.png
Labels: docs, size:M

#13063 Fix Image path for the Amazon Blog
  website/blog/2025-03-31-amazon-hudi.md
Labels: docs, size:XS
